In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

#var_name=os.path.basename(parentdir)

#var_name

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [3]:
df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

In [4]:
df_WEBH2021.columns = df_WEBH2021.iloc[0]
df_WEBH2021.replace(to_replace='..', value=0,inplace=True)
df_WEBH2021

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
0,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1.971000e+03,1.972000e+03,1.973000e+03,1.974000e+03,...,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2017,2018,2019,2020 Provisional
1,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1.368252e+03,1.648414e+03,1.685224e+03,1.640362e+03,...,9.782067e+03,1.027236e+04,1.107478e+04,1.195079e+04,1.250100e+04,1.222355e+04,12264.16248,12034.6322,12596.41582,12331.64135
2,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.755636e+00,3.635428e+00,2.577490e+00,5.287409e+00,6.978797e+00,6.829994e+00,7.916741,12.735731,17.037944,19.629498
3,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-5.414240e+02,-6.147180e+02,-7.389394e+02,-7.453829e+02,...,-7.720392e+03,-8.171019e+03,-9.101059e+03,-1.016689e+04,-1.063445e+04,-1.055251e+04,-10248.0298,-10333.3662,-10629.0366,-10541.275
4,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),8.842975e+02,9.232502e+02,9.455419e+02,9.283231e+02,...,2.013814e+03,1.968849e+03,1.831204e+03,1.736614e+03,1.797036e+03,1.863051e+03,1872.030679,1797.650326,1744.105366,1648.774748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.788729e+07,1.825346e+07,1.883300e+07,1.928119e+07,1.943470e+07,1.995069e+07,20589646.76,21366327.3,21641349.85,21619592.25
6157,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3.905413e+06,4.241816e+06,4.606277e+06,4.552613e+06,...,1.512668e+07,1.545191e+07,1.578194e+07,1.604617e+07,1.609427e+07,1.633914e+07,16687929.51,17081705.24,17007627.45,0
6158,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),1.110870e+05,1.524750e+05,2.031960e+05,2.727110e+05,...,2.582639e+06,2.460286e+06,2.479105e+06,2.535405e+06,2.570071e+06,2.608402e+06,2636117.238,2709100.699,2789694.402,2678855.226
6159,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1.240596e+06,1.304209e+06,1.321598e+06,1.460175e+06,...,4.410657e+06,4.729751e+06,5.060522e+06,5.302669e+06,5.511269e+06,5.891551e+06,6250190.754,6679673.151,7014495.554,0
6160,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5.257164e+06,5.698587e+06,6.131143e+06,6.287520e+06,...,2.221337e+07,2.273654e+07,2.342006e+07,2.398489e+07,2.427486e+07,2.494774e+07,25688502.59,26595243.41,26935958.13,0

In [5]:
np.unique(df_WEBH2021['Flow'].values)

array(['Commercial and public services (PJ)', 'Electricity output (GWh)',
       'Electricity, CHP and heat plants (PJ)', 'Exports (PJ)', 'Flow',
       'Imports (PJ)', 'Industry (PJ)',
       'Oil refineries, transformation (PJ)',
       'Other final consumption (PJ)', 'Production (PJ)',
       'Residential (PJ)', 'Total energy supply (PJ)',
       'Total final consumption (PJ)', 'Transport (PJ)'], dtype=object)

In [6]:
sector1='Commercial and public services (PJ)'
sector2='Residential (PJ)'
df_sector1=df_WEBH2021[df_WEBH2021['Flow']=='Commercial and public services (PJ)']

df_sector2=df_WEBH2021[df_WEBH2021['Flow']=='Residential (PJ)']

df_total1=df_sector1[df_sector1['Product']=='Total']
df_total2=df_sector2[df_sector2['Product']=='Total']

In [7]:
df_sector=df_WEBH2021[df_WEBH2021['Flow']=='Commercial and public services (PJ)']
df_sector.head()

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
11,Australia,"Coal, peat and oil shale",Commercial and public services (PJ),01. Australia,"01. Coal, peat and oil shale",11. Commercial and public services (PJ),2.599999,3.900,3.937652,10.945811,...,0.504798,0.306901,0.148698,0.278200,0.289500,0.324096,0.525498,0.137,0.034202,0
23,Australia,"Crude, NGL and feedstocks",Commercial and public services (PJ),01. Australia,"02. Crude, NGL and feedstocks",11. Commercial and public services (PJ),0.000000,0.000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
35,Australia,Oil products,Commercial and public services (PJ),01. Australia,03. Oil products,11. Commercial and public services (PJ),5.111999,4.899,4.686001,28.217701,...,27.966555,30.106421,31.185702,32.250041,32.663806,33.093623,34.238403,35.573381,29.091226,0
47,Australia,Natural gas,Commercial and public services (PJ),01. Australia,04. Natural gas,11. Commercial and public services (PJ),3.768300,5.652,6.406202,5.102101,...,45.665101,45.626398,45.482402,49.212899,50.802300,52.524901,53.8713,54.533698,53.764202,0
59,Australia,Nuclear,Commercial and public services (PJ),01. Australia,05. Nuclear,11. Commercial and public services (PJ),0.000000,0.000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0

In [8]:
df_total1.head()

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
107,Australia,Total,Commercial and public services (PJ),01. Australia,11. Total,11. Commercial and public services (PJ),38.685496,42.790201,47.231856,81.678816,...,296.321256,297.161312,305.924205,312.095146,327.745208,331.154218,338.15852,343.932084,340.600237,0
215,Austria,Total,Commercial and public services (PJ),02. Austria,11. Total,11. Commercial and public services (PJ),15.381725,19.067198,20.759620,21.695947,...,103.543608,102.987727,101.832518,96.390306,99.097658,96.707435,103.791513,101.592731,104.088148,0
323,Belgium,Total,Commercial and public services (PJ),03. Belgium,11. Total,11. Commercial and public services (PJ),38.036404,43.108000,44.549403,30.695403,...,181.661722,189.780296,201.853160,174.959263,190.173139,191.616966,191.821642,192.029483,190.136727,0
431,Canada,Total,Commercial and public services (PJ),04. Canada,11. Total,11. Commercial and public services (PJ),695.727598,788.937033,707.226866,752.371092,...,992.381399,955.015997,985.731199,1036.537297,1017.174598,1015.810204,1092.383201,1169.699697,1192.683098,0
539,Chile,Total,Commercial and public services (PJ),05. Chile,11. Total,11. Commercial and public services (PJ),3.928500,4.350600,4.498202,4.924803,...,66.379696,59.917701,64.082198,65.449062,67.269282,75.252731,83.550537,79.917236,78.956491,0

In [9]:
df_prop=pd.read_excel('../row_data/frac_scoe_heat_energy_proportion.xlsx')
df_prop

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_coal,0.90
1,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_sol...,0.10
2,Oil products,frac_scoe_heat_energy_commercial_municipal_diesel,0.25
3,Oil products,frac_scoe_heat_energy_commercial_municipal_gas...,0.40
4,Oil products,frac_scoe_heat_energy_commercial_municipal_ker...,0.10
5,Oil products,frac_scoe_heat_energy_commercial_municipal_gas...,0.25
6,Electricity,frac_scoe_heat_energy_commercial_municipal_ele...,1.00
7,Renewables and waste,frac_scoe_heat_energy_commercial_municipal_ele...,0.00
8,Nuclear,frac_scoe_heat_energy_commercial_municipal_ele...,0.00
9,Natural gas,frac_scoe_heat_energy_commercial_municipal_nat...,1.00
10,Heat,frac_scoe_heat_energy_commercial_municipal_nat...,1.00

In [10]:
df_prop[df_prop['SISEPUEDE_var']=='frac_scoe_heat_energy_commercial_municipal_coal']

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_coal,0.9

In [11]:
years=range(2000,2020)
countries_WEBH=df_total1['Country'].values
df_total1_fake=pd.DataFrame(columns=years)
df_total1_fake['Country']=countries_WEBH
df_total1_fake.replace(np.nan,0)

df_total2_fake=pd.DataFrame(columns=years)
df_total2_fake['Country']=countries_WEBH
df_total2_fake.replace(np.nan,0)
df_total2_fake.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Country
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Australia
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Austria
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Belgium
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile

In [12]:
for c in countries_WEBH:
    for y in years:
        #print(y,c)
        T=[]
        for fuel,p in zip(df_prop['WEBH2021_var'].values,df_prop['Proportion'].values):
            fu=df_WEBH2021.loc[(df_WEBH2021['Product']==fuel) &
                            (df_WEBH2021['Country']==c) &
                               (df_WEBH2021['Flow']==sector1),[y]][y].values[0]
            T.append(fu*p)
        Tsum=sum(T)
        df_total1_fake.loc[(df_total1_fake['Country']==c),[y]]=Tsum
df_total1_fake

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Country
0,210.613486,209.945118,234.963718,254.095016,259.770194,260.06801,263.543791,277.30355,280.797979,289.696013,...,295.367256,295.535318,303.613204,309.657139,325.409208,328.334219,337.1864,342.71208,339.537229,Australia
1,102.039115,118.28791,115.650331,127.930299,125.711479,119.450128,123.418897,107.001181,116.945166,103.868245,...,98.033788,98.166468,96.980289,91.658765,94.068311,92.412481,97.691375,95.018162,97.326206,Austria
2,145.490396,152.676996,158.5093,167.230999,171.0002,172.322797,179.3791,162.364598,195.3196,189.789097,...,180.794661,188.144421,199.250021,172.234581,186.945439,188.302938,188.39797,188.748246,186.72119,Belgium
3,962.143622,948.280516,1045.038401,1080.574201,1076.324604,971.556402,919.292201,952.474098,968.730701,967.1864,...,991.9804,954.377999,985.093202,1035.899299,1016.536597,1015.172203,1091.745199,1169.0617,1192.045101,Canada
4,26.050718,26.922728,29.230433,34.076826,38.944475,38.858804,40.686933,43.495409,47.411566,48.377364,...,66.339695,59.9157,63.987199,62.192067,66.159885,74.218805,82.663601,78.821467,77.966648,Chile
5,49.683751,37.531539,46.886642,49.227503,43.411903,44.231139,48.093491,49.176436,49.711953,54.023767,...,63.701417,70.401787,61.692812,64.400282,63.836755,64.798379,73.896827,69.266461,78.233134,Colombia
6,123.853796,133.588265,125.772439,141.435229,143.660567,128.829264,127.118315,121.322047,129.401109,122.020803,...,127.519834,123.526334,121.927462,118.34164,120.238402,125.081085,128.895549,126.488093,128.981722,Czech Republic
7,74.603697,77.457701,77.802601,80.293002,81.1626,81.075402,82.2248,81.521702,82.126,81.703401,...,79.647502,80.980801,80.1947,75.170163,77.580491,78.468926,80.550356,79.910471,78.537602,Denmark
8,11.714407,11.890952,11.897604,13.642386,14.898154,15.575181,15.599142,15.861692,17.22012,16.893081,...,16.028096,17.246689,16.992697,18.726409,19.012401,20.237982,19.077874,20.048174,19.009315,Estonia
9,94.631389,102.689522,105.553566,106.074177,106.560428,106.487289,108.899417,108.883951,108.631952,117.355924,...,116.25596,122.556931,117.954679,117.186556,111.196652,117.288295,118.2884,122.963301,120.303402,Finland
10,763.837108,786.716698,744.355199,828.3955,851.763258,860.804531,835.714512,868.579025,876.409111,930.871475,...,858.077681,918.1153,942.964155,865.667277,899.136498,899.87103,911.91704,895.966177,878.223566,France
11,1076.801828,1142.49879,1130.678315,1432.518276,1398.078852,1364.327215,1473.259495,1256.268285,1379.7776,1329.943618,...,1210.660066,1258.403398,1316.810837,1207.054386,1268.062128,1249.814379,1255.799443,1127.700797,1047.200415,Germany
12,54.767799,61.466302,64.4257,69.556301,74.229799,80.902001,86.573001,89.120698,92.628998,89.505498,...,77.095999,79.4027,74.545304,70.2303,76.385403,83.5896,80.751364,75.173169,76.162217,Greece
13,121.035456,128.685631,118.769279,123.396702,143.314231,142.343521,129.027283,112.936058,110.273555,116.862062,...,122.921622,93.528699,92.657401,86.2948,89.861715,89.28078,87.771033,85.524199,83.67512,Hungary
14,8.958601,9.151202,9.368199,9.2964,9.779197,10.030597,10.2512,12.352898,12.769773,12.515367,...,12.902679,13.48979,13.591755,14.330064,15.422936,16.659252,16.075742,18.905181,20.599533,Iceland
15,48.757409,50.008986,51.524205,54.969322,54.593339,58.705082,62.204464,63.229045,66.575994,61.296247,...,61.667281,63.67221,64.526865,60.71308,65.674195,66.592565,66.232316,70.160247,71.855708,Ireland
16,42.3324,35.6796,49.968001,42.944401,45.0288,47.0988,49.625998,53.157602,55.695602,56.250001,...,61.441202,65.347202,63.910799,57.4308,68.276806,69.300479,69.543577,69.48734,71.121607,Israel
17,477.313203,496.0735,494.499172,547.329265,557.917799,624.161299,645.581399,629.298402,706.086801,701.568105,...,654.1026,660.534597,656.300402,605.939495,636.465902,637.8745,648.264869,682.269356,652.083558,Italy
18,2182.605937,2225.125579,2285.550284,2263.20872,2329.277621,2352.945071,2378.58742,2394.929166,2327.634047,2156.873454,...,2125.035557,2037.183597,2145.083479,2115.524923,2049.324464,2000.509391,2043.853899,2049.306929,1983.199221,Japan
19,713.831401,700.475199,704.9048,718.920306,736.911601,793.223998,732.9386,753.320403,758.248199,783.929097,...,813.461402,814.571796,822.8934,789.390899,814.050602,867.704398,853.206569,858.887035,838.758818,Korea
20,16.501736,17.264345,18.691981,19.805662,20.482818,20.518334,21.986658,23.218984,22.319684,20.777828,...,20.405898,22.140853,21.135841,21.861318,21.06611,21.456115,21.824068,21.815355,21.351303,Latvia
21,17.699157,18.054135,18.802601,20.280403,21.369193,22.200093,24.125531,25.115968,23.973872,23.45128,...,23.003627,24.05894,23.26004,22.91364,22.465758,23.554782,25.050767,25.672306,24.672863,Lithuania
22,15.195777,15.379515,14.541979,16.444298,15.51909,15.354306,15.376567,15.394286,16.152792,15.701815,...,14.729945,16.567034,17.143455,15.05047,16.576077,16.682698,19.02847,20.00054,22.201365,Luxembourg
23,141.932302,145.702599,149.0083,120.5247,142.015,141.518898,148.648398,145.98,146.967499,145.535199,...,149.2094,152.405298,160.593201,160.303399,163.494804,162.396799,160.947601,178.226436,175.095723,Mexico
24,256.585199,270.960401,268.674002,280.781202,300.105198,284.728798,290.1491,278.897402,290.689294,298.527796,...,283.721596,294.337809,295.172997,258.840637,273.401142,274.35142,277.984918,275.968848,272.756714,Netherlands
25,36.718965,36.560528,37.148208,39.488976,43.060572,44.149333,44.513936,45.292853,44.619159,44.004566,...,44.436459,47.208272,46.706132,48.003412,48.842539,48.825507,49.347999,47.78922,49.765377,New Zealand
26,87.812599,105.164499,109.690099,94.318501,94.821395,94.545597,92.9857,101.328695,102.080602,116.155401,...,108.925903,113.461099,114.999401,108.006398,108.972599,118.006398,115.818297,123.39692,122.883359,Norway
27,198.465076,218.511751,248.212499,257.45396,274.029983,273.606919,305.750808,290.350548,326.707555,326.922577,...,342.184673,340.10967,327.283119,315.99273,317.561152,343.848645,324.701793,320.213556,315.153549,Poland
28,58.010203,77.399504,80.319902,76.831598,77.754704,91.183003,84.868797,84.6225,80.713197,84.625699,...,76.040398,73.771303,72.107498,76.758903,79.553517,76.841014,76.525133,79.077084,77.437185,Portugal
29,92.083998,70.541936,64.725768,54.199072,59.913518,73.200621,78.335288,78.238958,80.514605,80.31986,...,66.206714,59.648728,71.080225,50.360995,53.090387,54.035887,58.279054,53.571848,49.12259,Slovak Republic
30,21.9027,29.874602,29.707699,20.957295,22.567501,19.736299,18.312,15.414102,20.705501,20.476994,...,21.529597,18.436599,19.043702,17.355601,18.618201,20.204002,19.62259,19.024945,18.341814,Slovenia
31,276.313183,289.163,295.945,290.912199,316.507301,343.901399,367.409301,362.865995,383.21,389.331001,...,423.254803,417.904998,399.108004,363.219298,428.864801,451.1918,444.556501,442.620997,417.563602,Spain
32,183.5962,198.736699,198.768799,199.174998,188.117199,169.071152,171.393545,174.317883,172.057501,166.555614,...,159.407721,166.486436,163.667752,163.021921,165.411722,172.193555,163.353252,167.495718,164.763668,Sweden
33,129.70685,136.055274,130.871756,136.835916,136.176922,140.538856,136.493976,128.480273,134.652851,131.975405,...,124.607253,131.529746,136.702148,119.319739,125.652198,128.620728,126.41595,121.072568,121.293225,Switzerland
34,104.360939,115.358,126.59898,158.228496,182.4186,206.951841,252.451442,279.530701,426.666141,409.917601,...,414.624607,460.762703,444.300093,461.444775,510.256838,519.461003,567.027213,524.368096,583.833091,Turkey
35,702.186001,728.900004,669.200917,657.989374,684.843233,696.480778,662.167646,648.658496,707.556656,656.176268,...,633.425464,674.49008,686.61502,642.207244,661.05788,712.416108,703.238232,714.15167,706.357988,United Kingdom
36,8022.6383,8043.544809,8149.578693,8241.191806,8308.067327,8289.483755,8161.049344,8467.354133,8557.760765,8493.656146,...,8454.596288,8063.67275,8490.83184,8681.609286,8536.202978,8591.934758,8519.550207,8936.265053,8901.779092,United States
37,17652.774703,17972.324333,18215.835376,18830.533288,19150.108654,19200.166513,19188.037497,19317.658024,19919.743502,19654.640073,...,19393.345041,19092.094058,19730.721125,19464.312691,19614.733488,19821.532907,19925.081454,20297.149746,20085.913819,OECD Total
38,337.056994,322.979696,334.958792,337.79241,348.614358,366.93294,374.246949,390.988124,401.878928,407.682407,...,447.583105,471.437469,491.889062,519.983792,518.362131,512.118109,515.26436,524.942073,543.397005,Brazil
39,964.975113,1029.118346,1066.81394,1213.205854,1494.544638,1571.45723,1710.648149,1873.231491,1872.196016,2009.154299,...,2497.860421,2717.543806,2875.276196,2910.05416,3092.753936,3194.639887,3304.418452,3323.593397,3424.945551,People's Republic of China
40,188.408546,193.660413,214.991062,231.222164,221.118423,247.956971,274.104897,314.934948,353.085693,386.761063,...,474.632554,530.7514,541.714858,574.213955,628.568019,684.728561,731.791224,772.374454,829.110191,India
41,111.972499,116.527302,118.211401,122.239998,139.544997,144.9809,144.919601,151.348102,156.406505,165.814199,...,184.188301,208.215702,220.7333,226.898702,221.909,234.295802,240.378645,240.171826,247.036808,Indonesia
42,8.469599,9.8674,10.196499,10.878399,12.571503,13.513701,14.6071,15.499002,18.813302,19.218798,...,21.310201,22.610901,23.042602,23.841398,23.920779,24.419879,26.337241,26.569805,28.120056,Morocco
43,40.074099,41.840099,46.379001,44.557701,46.433697,51.202002,55.6847,60.630901,63.020798,62.778303,...,67.668196,69.537,71.500399,72.437401,74.229799,75.791601,75.766853,78.783903,81.520831,Singapore
44,92.372665,108.275798,117.661192,132.964696,154.204269,166.953025,184.582116,210.188689,216.719122,210.771517,...,162.94089,189.433152,195.649955,195.902369,184.807584,205.818332,223.62442,224.85348,222.594387,South Africa
45,129.433871,134.097598,145.126081,151.386959,161.254317,160.264658,175.602192,187.109662,210.348207,206.21393,...,229.397703,252.354986,241.525493,179.554485,186.887498,195.047676,197.387523,203.616527,211.474226,Thailand
46,4865.5692,4930.349148,5062.572014,5419.143654,5930.737673,6752.904977,7153.780718,7990.845006,8364.126976,8362.953319,...,9260.926615,9768.577602,10224.462989,10331.005129,10679.053636,11072.664163,11430.309863,11689.444158,12087.250696,Non-OECD Total
47,244.718598,265.482041,294.147281,312.31049,350.36089,381.465226,427.192493,468.408005,498.748376,510.267029,...,480.094633,539.482209,579.590761,578.844707,562.870118,597.925855,613.721119,617.312795,629.135849,Africa
48,637.786666,633.0576,656.267954,663.838564,692.469598,714.049022,731.593029,870.25992,830.99297,848.951713,...,920.944551,969.611244,1016.065737,1036.982998,1064.066357,1041.852958,1055.697898,1074.52116,1064.884813,Non-OECD Americas
49,1928.591496,2044.953348,2142.135981,2331.091159,2669.221959,2807.589054,3012.196961,3288.168191,3347.675126,3562.524104,...,4244.052886,4578.131103,4781.334852,4826.380713,5093.9623,5329.431688,5560.782487,5699.282148,5918.059254,Non-OECD Asia (including China)
50,1532.103089,1437.932972,1398.932725,1494.677003,1557.426061,2144.395676,2215.267356,2544.770748,2827.915591,2549.216845,...,2611.216285,2537.094652,2665.434337,2608.722305,2580.843082,2685.365979,2794.695456,2780.929492,2965.926042,Non-OECD Europe and Eurasia
51,522.369351,548.923188,571.088074,617.226438,661.259164,705.405998,767.530879,819.23814,858.794913,891.993629,...,1004.61826,1144.258394,1182.037301,1280.074405,1377.31178,1418.087682,1405.412903,1517.398562,1509.244735,Middle East
52,17469.645641,17797.846184,18013.179819,18633.944798,18948.524768,18997.492446,18974.955685,19095.726627,19687.155552,19418.767466,...,19124.020932,18818.303186,19464.098983,19203.828922,19338.887045,19531.341094,19616.404275,19994.156689,19773.626924,IEA Total
53,19478.175052,19872.400836,20212.405468,21024.722107,21675.565343,21873.14271,22071.883345,22470.602954,23156.417109,23069.264393,...,23424.088242,23499.911226,24338.281695,24113.651968,24491.064988,24890.07339,25182.527763,25632.309727,25613.820229,IEA and Accession/Association countries
54,22518.343905,22902.673483,23278.407391,24249.676945,25080.846326,25953.071485,26341.818217,27308.503031,28283.870472,28017.593391,...,28654.271666,28860.671654,29955.184119,29795.31782,30293.787126,30894.197068,31355.391307,31986.593904,32173.164513,World

In [13]:
for c in countries_WEBH:
    for y in years:
        #print(y,c)
        T=[]
        for fuel,p in zip(df_prop['WEBH2021_var'].values,df_prop['Proportion'].values):
            fu=df_WEBH2021.loc[(df_WEBH2021['Product']==fuel) &
                            (df_WEBH2021['Country']==c) &
                               (df_WEBH2021['Flow']==sector2),[y]][y].values[0]
            T.append(fu*p)
        Tsum=sum(T)
        df_total2_fake.loc[(df_total2_fake['Country']==c),[y]]=Tsum
df_total2_fake

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Country
0,297.617079,303.07268,312.067576,320.918768,327.166889,326.145683,331.107087,341.345487,344.627189,359.219091,...,374.522712,372.809599,373.383903,367.762194,374.855408,379.184781,377.279222,377.362614,378.774173,Australia
1,203.599144,214.079914,207.441818,213.16627,209.755104,212.20437,205.696814,193.581906,197.31451,197.411028,...,194.633262,195.330444,203.002981,183.819867,194.047466,203.160827,204.947419,193.074902,197.724661,Austria
2,391.161721,407.080739,384.640236,405.240117,411.855139,409.590327,367.370854,333.207403,358.848229,339.065909,...,314.378836,329.981005,352.273203,292.002534,320.693573,318.882698,314.620172,311.553052,302.129754,Belgium
3,1215.51335,1172.271485,1211.753591,1263.874826,1241.523519,1258.227548,1213.444229,1322.429129,1324.272748,1295.653241,...,1325.851641,1263.463573,1321.0809,1363.16169,1313.900362,1259.803259,1302.979538,1353.490136,1345.228043,Canada
4,78.953896,84.002402,80.959498,75.563898,81.110001,81.630542,82.986898,88.364595,84.327503,87.971999,...,92.881303,94.791003,99.664199,96.843003,95.292703,110.203798,109.759608,114.80368,115.459162,Chile
5,97.823004,111.178247,110.92994,111.671301,117.759972,121.678624,135.456164,137.795869,137.816443,135.460263,...,138.806559,134.87067,133.302772,139.290444,139.658799,143.144825,144.979204,153.567951,156.30065,Colombia
6,227.578911,249.057061,235.552349,243.101447,237.182831,228.7889,231.460895,213.539406,214.414837,216.299642,...,220.043558,227.387842,230.595454,198.577106,205.988467,217.80033,220.359071,209.768963,201.621232,Czech Republic
7,156.183445,163.917403,158.875738,160.671398,158.731197,156.716404,153.375103,147.327898,147.406204,147.608247,...,147.847091,146.388921,146.595661,133.170925,139.413117,142.504454,140.66801,139.844688,138.818864,Denmark
8,24.924544,25.995933,25.463176,24.297834,24.520752,24.888922,24.78939,24.397664,23.599907,23.398819,...,23.899473,24.352623,23.442739,21.634979,20.769802,22.897852,23.118496,22.903274,23.992093,Estonia
9,148.571755,160.122843,162.418277,168.199,164.556865,163.701607,166.583804,166.246499,158.04269,165.613773,...,161.537592,172.371134,163.828563,161.21757,156.934147,168.899803,166.6982,164.120751,161.5618,Finland
10,1408.841503,1481.600496,1436.111701,1484.2484,1551.639803,1516.528896,1506.415501,1428.84664,1558.642959,1534.015611,...,1373.587081,1493.114602,1546.343999,1272.595855,1337.541287,1387.912552,1363.791853,1309.423777,1287.530334,France
11,2553.72216,2737.769785,2628.464432,2579.152707,2500.872372,2455.267083,2458.052247,2068.630096,2313.628904,2205.210252,...,2034.004707,2112.744728,2236.525226,1917.105918,1974.290757,2072.528965,2045.560899,1997.101427,2068.922803,Germany
12,154.137838,163.131637,171.526229,196.251996,191.837485,196.205941,195.704811,184.591273,183.015361,170.248234,...,188.60036,163.647044,115.694669,117.653212,141.609542,141.00344,140.254723,119.933214,129.292659,Greece
13,211.031865,226.089427,227.184958,251.765853,234.501881,251.792816,238.046505,209.884891,213.522207,206.528765,...,198.537055,183.528981,174.291468,160.148462,175.553922,185.316925,194.852437,186.168176,183.844783,Hungary
14,12.0354,12.135402,12.4608,12.359798,12.731201,12.992,13.360401,15.657493,16.264173,16.226199,...,16.453115,16.870497,16.388412,17.064643,17.304597,17.650356,16.810077,18.926178,18.50368,Iceland
15,110.307593,117.339244,116.816732,122.89136,127.358533,133.540372,134.209277,131.873084,144.052623,139.669174,...,128.685188,122.124355,119.35768,107.376247,112.937352,113.944231,113.469226,122.270621,116.425969,Ireland
16,76.4993,73.670397,74.720597,86.5244,87.792101,82.760501,89.377202,91.886201,87.574299,95.531497,...,98.991699,103.207798,56.3832,57.531602,68.958346,70.94348,73.247459,72.75731,78.939702,Israel
17,1101.166659,1154.0925,1112.358285,1175.829884,1221.059043,1255.739857,1159.631758,1079.506911,1083.664445,1113.340337,...,1158.535361,1155.326911,1150.200798,993.8261,1086.877399,1082.824803,1083.719987,1063.094814,1031.19839,Italy
18,2006.820459,1962.660157,2032.181527,1983.438015,2007.989766,2081.012862,2005.672837,2016.180868,1958.781451,1941.057785,...,1995.452204,2016.544466,1963.776785,1883.814222,1832.848582,1835.584652,1911.854712,1761.724032,1743.237489,Japan
19,625.270608,662.348557,733.295357,747.488688,720.445071,767.502622,783.355572,769.725755,784.744049,778.454914,...,840.418298,845.804223,843.25303,796.458196,791.165767,860.753406,886.226981,890.12516,852.908352,Korea
20,27.328131,29.878018,29.848501,30.911597,29.600802,30.746021,30.809719,30.624323,30.615724,30.594618,...,29.443269,29.808538,28.874019,28.085368,27.109208,29.027319,28.910507,29.098448,28.374802,Latvia
21,35.110572,36.789855,38.17608,39.000791,39.2105,39.791,41.62913,39.812771,40.963099,41.203886,...,40.760893,40.768622,38.814257,37.353281,36.366017,39.749789,41.249622,42.275342,40.299583,Lithuania
22,18.980464,20.442792,19.629703,20.361891,21.663052,21.353739,20.968558,20.439242,20.779377,20.957588,...,19.368844,19.735009,19.974201,18.610318,20.247423,20.783254,21.292901,19.744555,18.517358,Luxembourg
23,468.628595,467.640201,471.944302,486.946302,478.234605,471.840696,471.787301,478.121402,485.430299,475.747997,...,489.656798,494.363498,475.104499,484.140798,486.063398,486.3593,483.628103,495.9356,485.023154,Mexico
24,438.68,462.953497,451.594696,462.599302,446.411601,433.119503,436.773495,400.142503,443.658696,443.506003,...,411.132104,435.95289,458.574451,362.402244,380.38952,392.446922,383.164694,383.179537,367.949989,Netherlands
25,49.968487,51.792227,50.885367,53.106728,54.173441,53.093996,55.098204,54.025458,52.768556,55.820942,...,54.19005,54.675932,53.240375,53.869031,54.357631,53.879753,54.490821,55.040477,55.667337,New Zealand
26,136.033302,141.936895,138.182198,131.403099,130.064604,133.853001,133.117104,136.368003,135.256697,140.544102,...,139.087799,146.155703,149.497297,140.737297,146.586399,148.611194,150.191799,151.69888,150.661927,Norway
27,624.623756,682.257859,677.159006,682.701957,683.960572,713.21891,751.248179,707.640108,719.765968,732.457511,...,724.850585,750.968225,736.362393,685.524099,681.108101,712.553749,720.490079,695.612738,645.764772,Poland
28,68.693899,70.9192,76.165395,81.511704,84.448602,84.644301,84.5999,85.5902,81.169098,84.406503,...,84.936703,79.544502,76.168899,73.326301,72.276846,74.933169,73.78344,76.64555,76.58786,Portugal
29,108.27061,128.232134,124.702992,117.966653,110.344261,104.886458,95.649154,85.471847,87.721624,88.292231,...,86.758141,84.923356,88.052151,80.031645,82.003418,83.444151,86.583124,84.21942,84.895986,Slovak Republic
30,32.085052,31.839798,35.07655,38.735156,38.319247,36.066498,34.917799,30.296598,33.119602,32.2501,...,30.636582,29.028303,27.47523,23.98426,25.531002,26.004198,25.882605,25.123061,25.068381,Slovenia
31,417.250379,443.124117,456.960955,496.3802,527.419302,546.301954,564.405849,565.305148,557.9664,558.557103,...,543.012004,536.545002,508.62443,500.165398,507.4633,514.337595,488.090349,502.656498,490.200902,Spain
32,279.383598,290.695599,282.9349,284.464602,274.953198,292.884257,280.717358,269.221418,261.677583,273.280303,...,271.167225,285.183652,279.147195,262.05648,269.174132,279.397197,282.143687,279.310978,274.193779,Sweden
33,214.300341,223.787127,219.369814,229.234953,231.338954,236.85166,229.144351,209.804701,221.351452,218.019613,...,198.01497,213.43974,224.856519,189.691967,200.07588,206.124969,201.214912,190.372875,191.888388,Switzerland
34,423.018567,383.522971,399.583825,438.476869,467.621795,524.987998,548.570308,585.605522,591.019624,531.691517,...,642.352019,633.640176,624.161994,603.712762,648.076321,681.179502,753.264392,715.926195,761.624966,Turkey
35,1794.711105,1845.903,1812.956874,1863.279689,1900.521618,1840.12401,1792.077474,1727.782587,1746.553187,1693.095505,...,1537.494406,1659.812111,1665.516941,1431.861765,1484.426143,1513.047133,1465.623375,1524.177958,1509.159684,United Kingdom
36,10551.842814,10375.568795,10583.532703,10876.763699,10671.779998,10814.740402,10150.233302,10683.649101,10705.342801,10483.853805,...,10414.656899,9583.652402,10457.019,10711.657998,10239.760099,9946.397001,9887.946196,10815.011832,10737.160672,United States
37,26790.669906,27168.900395,27303.926683,27960.501156,27820.455675,28115.420288,27217.844538,27074.920001,27549.720516,27072.264114,...,26745.186385,26252.85808,27180.849492,25968.265783,25861.656236,25943.221639,25983.147906,26668.044667,26475.454131,OECD Total
38,573.811378,539.136342,526.350039,520.959572,535.062682,547.376421,557.263214,583.662064,607.093595,632.748999,...,681.273333,703.524186,736.276451,762.069776,759.731076,768.649592,776.514709,786.590047,802.506468,Brazil
39,3316.465961,3386.435737,3538.732919,3934.865418,4491.121707,4883.457708,5302.495052,5689.812491,5732.018969,5987.118017,...,6760.115818,7163.559309,7692.581463,8042.08982,8546.305794,9076.038863,9590.661791,9881.94453,9872.555356,People's Republic of China
40,1142.652186,1147.153959,1204.344601,1255.647387,1344.821576,1376.876876,1436.669358,1455.534928,1503.583629,1593.965458,...,1746.757968,1781.193205,1867.915657,2010.740903,2124.624488,2221.605222,2298.80723,2396.69903,2503.854676,India
41,515.479105,521.6336,506.4729,518.582001,536.426603,521.523802,494.047299,510.951198,488.2501,464.062103,...,482.904804,522.093001,563.199598,600.914498,624.010402,648.6317,677.174334,723.38392,732.833934,Indonesia
42,64.681501,65.7246,68.720402,71.2102,75.409397,79.7719,86.3277,93.816897,100.4781,102.721003,...,113.5522,121.6208,125.106696,131.557801,134.825301,140.653792,145.134354,148.015513,154.006632,Morocco
43,26.144602,26.8157,27.1155,27.5288,27.247699,25.415002,25.356797,25.4579,25.232399,26.512702,...,26.646704,27.241603,27.715904,28.280101,29.387999,30.701495,29.677022,29.455603,31.061564,Singapore
44,183.131578,230.164934,236.096394,262.979816,288.330346,302.279131,329.484543,374.320783,387.13448,373.214187,...,274.968291,329.105591,333.323206,333.539094,321.082803,334.532207,394.626729,395.255331,393.341821,South Africa
45,108.679309,117.245644,121.292618,128.904073,133.490968,147.611667,152.67216,161.583433,171.527925,182.851674,...,203.875895,232.474942,216.442174,213.33288,215.239536,228.500593,231.477701,234.902859,247.991483,Thailand
46,18803.169865,19185.096921,19295.005039,20121.180062,20981.083481,20823.506018,21836.983873,22425.224803,22822.853543,23139.141036,...,25011.344688,25214.777913,26018.401998,26977.717407,27702.799513,28805.120343,30098.561095,31669.526744,31746.016559,Non-OECD Total
47,1023.48429,1123.339571,1163.639137,1216.212349,1267.593843,1363.328111,1385.942521,1495.601612,1567.242244,1566.472798,...,1561.80931,1702.532071,1756.454877,1804.428873,1873.161408,1903.901982,2022.47503,2121.417224,2171.73705,Africa
48,1430.264655,1391.507716,1362.040063,1376.089444,1425.308275,1475.26637,1493.019885,1605.573072,1623.472818,1655.540336,...,1782.471506,1855.601688,1934.729818,1974.802333,1999.576408,2028.869149,1958.741446,1977.609478,1952.85671,Non-OECD Americas
49,5999.987236,6119.076805,6361.628939,6873.084629,7600.972337,8059.373631,8551.446697,9021.488509,9128.271027,9517.219292,...,10592.919253,11153.202757,11819.879725,12401.947569,13122.76403,13926.687873,14702.609996,15157.242221,15341.472053,Non-OECD Asia (including China)
50,8424.06867,8562.565825,8252.171654,8451.361747,8276.533479,7295.822995,7528.876495,7242.701408,7464.4379,7211.861114,...,7826.949566,7342.62794,7145.667905,7423.933885,7256.019753,7308.689028,7827.122623,8772.06726,8623.564679,Non-OECD Europe and Eurasia
51,1925.365014,1988.607004,2155.525246,2204.431893,2410.675545,2629.714912,2877.698276,3059.860199,3039.429554,3188.047497,...,3247.195053,3160.813456,3361.669671,3372.604748,3451.277915,3636.972313,3587.612005,3641.190559,3656.386064,Middle East
52,26430.834555,26789.406279,26921.754714,27565.734209,27413.931852,27709.755094,26789.307219,26640.482154,27119.039682,26633.025545,...,26297.212967,25803.51265,26779.947407,25568.113179,25451.43556,25506.49786,25542.308819,26211.492698,26012.508175,IEA Total
53,32650.266944,33129.357688,33455.666197,34599.171868,35171.715393,35919.928273,35523.072736,35893.481285,36485.040216,36356.387329,...,36958.748438,37057.963376,38670.67298,38021.656389,38546.918829,39319.853227,40055.618585,41191.143816,41141.659203,IEA and Accession/Association countries
54,45593.839764,46353.997323,46598.931717,48081.681216,48801.539152,48938.926307,49054.828414,49500.144804,50372.574062,50211.405142,...,51756.531079,51467.635999,53199.251487,52945.983193,53564.455751,54748.341978,56081.709005,58337.571407,58221.470695,World

In [14]:
sisepuede_vars=[var for var in np.unique(df_prop['SISEPUEDE_var'].values)]
sisepuede_vars.append('frac_scoe_heat_energy_commercial_municipal_hydrogen')
sisepuede_vars

['frac_scoe_heat_energy_commercial_municipal_coal',
 'frac_scoe_heat_energy_commercial_municipal_diesel',
 'frac_scoe_heat_energy_commercial_municipal_electricity',
 'frac_scoe_heat_energy_commercial_municipal_gas_petroleum_liquid',
 'frac_scoe_heat_energy_commercial_municipal_gasoline',
 'frac_scoe_heat_energy_commercial_municipal_kerosene',
 'frac_scoe_heat_energy_commercial_municipal_natural_gas',
 'frac_scoe_heat_energy_commercial_municipal_solid_biomass',
 'frac_scoe_heat_energy_commercial_municipal_hydrogen']

In [20]:
#### HISTORICAL ######
s1_frac=0.5
s2_frac=0.5

nation_in_df=np.unique(df_WEBH2021['Country'].values)

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
#years=range(2000,2020)

for s_var in sisepuede_vars:
    coun_year=[]
    df_historical_out=0
    for count in zip(countries,ISO3):
        for year in years:
            coun_year.append([count[0],count[1],year])
            
    df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_historical_out[s_var]=0

    df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    for country in countries:
        for year in years:
        
            if country in nation_in_df:

                dato_fuel=[]
                
                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):
                    
                    #Sector 1

                    Total1=df_total1_fake.loc[df_total1_fake['Country']==country,[year]][year].values[0]

                    df_fuel1=df_sector1[df_sector1['Product']==fuel]

                    f1=df_fuel1.loc[df_fuel1['Country']==country,[year]][year].values[0]
                    
                    #Sector 2
                    
                    Total2=df_total2_fake.loc[df_total2_fake['Country']==country,[year]][year].values[0]

                    df_fuel2=df_sector2[df_sector2['Product']==fuel]

                    f2=df_fuel2.loc[df_fuel2['Country']==country,[year]][year].values[0]
                    
                    f = s1_frac*f1 + s2_frac*f2
                    
                    Total = s1_frac*Total1 + s2_frac*Total2 

                    dato_fuel.append(p*f/Total)
                    
                    

                    #print(dato_fuel)


                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                            (df_historical_out['Year']== year), s_var]=sum(dato_fuel)
            
            else:
                
                dato_fuel=[]
                
                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):
                    
                    #Sector 1

                    Total1=df_total1_fake.loc[df_total1_fake['Country']=='World',[year]][year].values[0]

                    df_fuel1=df_sector1[df_sector1['Product']==fuel]

                    f1=df_fuel1.loc[df_fuel1['Country']=='World',[year]][year].values[0]
                    
                    #Sector 2
                    
                    Total2=df_total2_fake.loc[df_total2_fake['Country']=='World',[year]][year].values[0]

                    df_fuel2=df_sector2[df_sector2['Product']==fuel]

                    f2=df_fuel2.loc[df_fuel2['Country']=='World',[year]][year].values[0]
                    
                    f = s1_frac*f1 + s2_frac*f2
                    
                    Total = s1_frac*Total1 + s2_frac*Total2 
                    
                    dato_fuel.append(p*f/Total)
                    
                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                                (df_historical_out['Year']== year), s_var] = sum(dato_fuel)
                
    
    df_historical_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')

In [21]:
#### Projected ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years2=range(max(years)+1,2051)

for s_var in sisepuede_vars:
    coun_year=[]
    for count in zip(countries,ISO3):
        for year in years2:
            coun_year.append([count[0],count[1],year])
            
    df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_projected_out[s_var]=0

    #df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    df_historical=pd.read_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')
    
    for count,year in zip(df_projected_out['Nation'].values,df_projected_out['Year'].values):
        
        df_dato=df_historical[(df_historical['Nation']==count) & 
                                   (df_historical['Year']==max(years))]
        dato=df_dato[s_var].values[0]
        
        df_projected_out.loc[(df_projected_out['Nation'] == count) & 
                            (df_projected_out['Year']== year), s_var] = dato
    
    
    df_projected_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/projected/{s_var}.csv')