In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_cement'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [3]:
IPPU_folder = 'prodinit_ippu_cement_tonne'
IPPU_var = 'prodinit_ippu_cement_tonne'
df_ippu_hist = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & (df_ippu_hist['year']==y),][IPPU_var].values[0]
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & (df_ippu_proj['year']==y)][IPPU_var].values[0]
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_cement_tonne
0          SYC  2010                1.289554e+05
1          SYC  2011                1.128187e+05
2          SYC  2012                8.281698e+05
3          SYC  2013                1.090451e+06
4          SYC  2014                1.095272e+06
...        ...   ...                         ...
7826       BRB  2046                3.818867e+07
7827       BRB  2047                4.283295e+07
7828       BRB  2048                4.804203e+07
7829       BRB  2049                5.388462e+07
7830       BRB  2050                6.043774e+07

[7831 rows x 3 columns]

In [4]:
#df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

df_eei

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Manufacturing [ISIC 10-18; 20-32],Oil and oil products (PJ) ...,117.58,91.59,88.38,111.41,122.11,129.29,133.41,...,161.91,179.86,155.11,155.37,118.72,106.86,97.51,101.08,100.39,97.74
1,Australia,Manufacturing [ISIC 10-18; 20-32],Gas (PJ) ...,314.61,339.39,338.58,343.29,352.22,325.43,322.22,...,330.12,325.92,339.72,346.59,334.74,322.67,309.67,311.85,298.23,303.55
2,Australia,Manufacturing [ISIC 10-18; 20-32],Coal and coal products (PJ) ...,231.33,201.89,178.75,209.41,223.34,226.59,225.07,...,230.37,191.49,184.76,177.97,170.35,197.53,208.32,205.26,196.51,190.24
3,Australia,Manufacturing [ISIC 10-18; 20-32],Biofuels and waste (PJ) ...,96.47,94.43,99.89,101.47,104.3,109.06,110.25,...,104.6,104.29,112.36,105.27,115.61,115.49,124.1,112.09,103.36,98.69
4,Australia,Manufacturing [ISIC 10-18; 20-32],Heat (PJ) ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,Uzbekistan,Construction [ISIC 41-43],Biofuels and waste (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9756,Uzbekistan,Construction [ISIC 41-43],Heat (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9757,Uzbekistan,Construction [ISIC 41-43],Electricity (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0.51,0.42,0.28,0.46,..,..,..
9758,Uzbekistan,Construction [ISIC 41-43],Other sources (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0.01,0,..,..,..
9759,Uzbekistan,Construction [ISIC 41-43],Total final energy use (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,6.85,6.54,6.23,9.44,..,..,..

In [5]:
set(df_eei['PRODUCT/FLOW'].values)

{'Biofuels and waste (PJ)    ',
 'Biofuels and waste (PJ)     ',
 'Biofuels and waste (PJ)         ',
 'Biofuels and waste (PJ)          ',
 'Biofuels and waste (PJ)            ',
 'Biofuels and waste (PJ)             ',
 'Biofuels and waste (PJ)              ',
 'Biofuels and waste (PJ)               ',
 'Biofuels and waste (PJ)                ',
 'Biofuels and waste (PJ)                 ',
 'Biofuels and waste (PJ)                  ',
 'Biofuels and waste (PJ)                   ',
 'Biofuels and waste (PJ)                    ',
 'Biofuels and waste (PJ)                     ',
 'Biofuels and waste (PJ)                      ',
 'Biofuels and waste (PJ)                       ',
 'Biofuels and waste (PJ)                        ',
 'Biofuels and waste (PJ)                         ',
 'Biofuels and waste (PJ)                          ',
 'Biofuels and waste (PJ)                           ',
 'Biofuels and waste (PJ)                            ',
 'Biofuels and waste (PJ)                             ',
 'Biofuels and waste (PJ)                              ',
 'Biofuels and waste (PJ)                               ',
 'Biofuels and waste (PJ)                                ',
 'Biofuels and waste (PJ)                                 ',
 'Biofuels and waste (PJ)                                  ',
 'Biofuels and waste (PJ)                                   ',
 'Biofuels and waste (PJ)                                    ',
 'Biofuels and waste (PJ)                                     ',
 'Biofuels and waste (PJ)                                      ',
 'Biofuels and waste (PJ)                                       ',
 'Biofuels and waste (PJ)                                        ',
 'Biofuels and waste (PJ)                                         ',
 'Biofuels and waste (PJ)                                          ',
 'Biofuels and waste (PJ)                                           ',
 'Biofuels and waste (PJ)                                            ',
 'Biofuels and waste (PJ)                                             ',
 'Biofuels and waste (PJ)                                              ',
 'Biofuels and waste (PJ)                                               ',
 'Biofuels and waste (PJ)                                                ',
 'Biofuels and waste (PJ)                                                 ',
 'Biofuels and waste (PJ)                                                  ',
 'Biofuels and waste (PJ)                                                   ',
 'Biofuels and waste (PJ)                                                    ',
 'Biofuels and waste (PJ)                                                     ',
 'Biofuels and waste (PJ)                                                      ',
 'Biofuels and waste (PJ)                                                       ',
 'Coal and coal products (PJ)',
 'Coal and coal products (PJ) ',
 'Coal and coal products (PJ)     ',
 'Coal and coal products (PJ)      ',
 'Coal and coal products (PJ)        ',
 'Coal and coal products (PJ)         ',
 'Coal and coal products (PJ)          ',
 'Coal and coal products (PJ)           ',
 'Coal and coal products (PJ)            ',
 'Coal and coal products (PJ)             ',
 'Coal and coal products (PJ)              ',
 'Coal and coal products (PJ)               ',
 'Coal and coal products (PJ)                ',
 'Coal and coal products (PJ)                 ',
 'Coal and coal products (PJ)                  ',
 'Coal and coal products (PJ)                   ',
 'Coal and coal products (PJ)                    ',
 'Coal and coal products (PJ)                     ',
 'Coal and coal products (PJ)                      ',
 'Coal and coal products (PJ)                       ',
 'Coal and coal products (PJ)                        ',
 'Coal and coal products (PJ)                         ',
 'Coal and coal products (PJ)                          ',
 'Coal and coal products (PJ)                           ',
 'Coal and coal products (PJ)                            ',
 'Coal and coal products (PJ)                             ',
 'Coal and coal products (PJ)                              ',
 'Coal and coal products (PJ)                               ',
 'Coal and coal products (PJ)                                ',
 'Coal and coal products (PJ)                                 ',
 'Coal and coal products (PJ)                                  ',
 'Coal and coal products (PJ)                                   ',
 'Coal and coal products (PJ)                                    ',
 'Coal and coal products (PJ)                                     ',
 'Coal and coal products (PJ)                                      ',
 'Coal and coal products (PJ)                                       ',
 'Coal and coal products (PJ)                                        ',
 'Coal and coal products (PJ)                                         ',
 'Coal and coal products (PJ)                                          ',
 'Coal and coal products (PJ)                                           ',
 'Coal and coal products (PJ)                                            ',
 'Coal and coal products (PJ)                                             ',
 'Coal and coal products (PJ)                                              ',
 'Coal and coal products (PJ)                                               ',
 'Coal and coal products (PJ)                                                ',
 'Coal and coal products (PJ)                                                 ',
 'Coal and coal products (PJ)                                                  ',
 'Coal and coal products (PJ)                                                   ',
 'Electricity (PJ)           ',
 'Electricity (PJ)            ',
 'Electricity (PJ)                ',
 'Electricity (PJ)                 ',
 'Electricity (PJ)                   ',
 'Electricity (PJ)                    ',
 'Electricity (PJ)                     ',
 'Electricity (PJ)                      ',
 'Electricity (PJ)                       ',
 'Electricity (PJ)                        ',
 'Electricity (PJ)                         ',
 'Electricity (PJ)                          ',
 'Electricity (PJ)                           ',
 'Electricity (PJ)                            ',
 'Electricity (PJ)                             ',
 'Electricity (PJ)                              ',
 'Electricity (PJ)                               ',
 'Electricity (PJ)                                ',
 'Electricity (PJ)                                 ',
 'Electricity (PJ)                                  ',
 'Electricity (PJ)                                   ',
 'Electricity (PJ)                                    ',
 'Electricity (PJ)                                     ',
 'Electricity (PJ)                                      ',
 'Electricity (PJ)                                       ',
 'Electricity (PJ)                                        ',
 'Electricity (PJ)                                         ',
 'Electricity (PJ)                                          ',
 'Electricity (PJ)                                           ',
 'Electricity (PJ)                                            ',
 'Electricity (PJ)                                             ',
 'Electricity (PJ)                                              ',
 'Electricity (PJ)                                               ',
 'Electricity (PJ)                                                ',
 'Electricity (PJ)                                                 ',
 'Electricity (PJ)                                                  ',
 'Electricity (PJ)                                                   ',
 'Electricity (PJ)                                                    ',
 'Electricity (PJ)                                                     ',
 'Electricity (PJ)                                                      ',
 'Electricity (PJ)                                                       ',
 'Electricity (PJ)                                                        ',
 'Electricity (PJ)                                                         ',
 'Electricity (PJ)                                                          ',
 'Electricity (PJ)                                                           ',
 'Electricity (PJ)                                                            ',
 'Electricity (PJ)                                                             ',
 'Electricity (PJ)                                                              ',
 'Gas (PJ)                   ',
 'Gas (PJ)                    ',
 'Gas (PJ)                        ',
 'Gas (PJ)                         ',
 'Gas (PJ)                           ',
 'Gas (PJ)                            ',
 'Gas (PJ)                             ',
 'Gas (PJ)                              ',
 'Gas (PJ)                               ',
 'Gas (PJ)                                ',
 'Gas (PJ)                                 ',
 'Gas (PJ)                                  ',
 'Gas (PJ)                                   ',
 'Gas (PJ)                                    ',
 'Gas (PJ)                                     ',
 'Gas (PJ)                                      ',
 'Gas (PJ)                                       ',
 'Gas (PJ)                                        ',
 'Gas (PJ)                                         ',
 'Gas (PJ)                                          ',
 'Gas (PJ)                                           ',
 'Gas (PJ)                                            ',
 'Gas (PJ)                                             ',
 'Gas (PJ)                                              ',
 'Gas (PJ)                                               ',
 'Gas (PJ)                                                ',
 'Gas (PJ)                                                 ',
 'Gas (PJ)                                                  ',
 'Gas (PJ)                                                   ',
 'Gas (PJ)                                                    ',
 'Gas (PJ)                                                     ',
 'Gas (PJ)                                                      ',
 'Gas (PJ)                                                       ',
 'Gas (PJ)                                                        ',
 'Gas (PJ)                                                         ',
 'Gas (PJ)                                                          ',
 'Gas (PJ)                                                           ',
 'Gas (PJ)                                                            ',
 'Gas (PJ)                                                             ',
 'Gas (PJ)                                                              ',
 'Gas (PJ)                                                               ',
 'Gas (PJ)                                                                ',
 'Gas (PJ)                                                                 ',
 'Gas (PJ)                                                                  ',
 'Gas (PJ)                                                                   ',
 'Gas (PJ)                                                                    ',
 'Gas (PJ)                                                                     ',
 'Gas (PJ)                                                                      ',
 'Heat (PJ)                  ',
 'Heat (PJ)                   ',
 'Heat (PJ)                       ',
 'Heat (PJ)                        ',
 'Heat (PJ)                          ',
 'Heat (PJ)                           ',
 'Heat (PJ)                            ',
 'Heat (PJ)                             ',
 'Heat (PJ)                              ',
 'Heat (PJ)                               ',
 'Heat (PJ)                                ',
 'Heat (PJ)                                 ',
 'Heat (PJ)                                  ',
 'Heat (PJ)                                   ',
 'Heat (PJ)                                    ',
 'Heat (PJ)                                     ',
 'Heat (PJ)                                      ',
 'Heat (PJ)                                       ',
 'Heat (PJ)                                        ',
 'Heat (PJ)                                         ',
 'Heat (PJ)                                          ',
 'Heat (PJ)                                           ',
 'Heat (PJ)                                            ',
 'Heat (PJ)                                             ',
 'Heat (PJ)                                              ',
 'Heat (PJ)                                               ',
 'Heat (PJ)                                                ',
 'Heat (PJ)                                                 ',
 'Heat (PJ)                                                  ',
 'Heat (PJ)                                                   ',
 'Heat (PJ)                                                    ',
 'Heat (PJ)                                                     ',
 'Heat (PJ)                                                      ',
 'Heat (PJ)                                                       ',
 'Heat (PJ)                                                        ',
 'Heat (PJ)                                                         ',
 'Heat (PJ)                                                          ',
 'Heat (PJ)                                                           ',
 'Heat (PJ)                                                            ',
 'Heat (PJ)                                                             ',
 'Heat (PJ)                                                              ',
 'Heat (PJ)                                                               ',
 'Heat (PJ)                                                                ',
 'Heat (PJ)                                                                 ',
 'Heat (PJ)                                                                  ',
 'Heat (PJ)                                                                   ',
 'Heat (PJ)                                                                    ',
 'Heat (PJ)                                                                     ',
 'Oil and oil products (PJ)  ',
 'Oil and oil products (PJ)   ',
 'Oil and oil products (PJ)       ',
 'Oil and oil products (PJ)        ',
 'Oil and oil products (PJ)          ',
 'Oil and oil products (PJ)           ',
 'Oil and oil products (PJ)            ',
 'Oil and oil products (PJ)             ',
 'Oil and oil products (PJ)              ',
 'Oil and oil products (PJ)               ',
 'Oil and oil products (PJ)                ',
 'Oil and oil products (PJ)                 ',
 'Oil and oil products (PJ)                  ',
 'Oil and oil products (PJ)                   ',
 'Oil and oil products (PJ)                    ',
 'Oil and oil products (PJ)                     ',
 'Oil and oil products (PJ)                      ',
 'Oil and oil products (PJ)                       ',
 'Oil and oil products (PJ)                        ',
 'Oil and oil products (PJ)                         ',
 'Oil and oil products (PJ)                          ',
 'Oil and oil products (PJ)                           ',
 'Oil and oil products (PJ)                            ',
 'Oil and oil products (PJ)                             ',
 'Oil and oil products (PJ)                              ',
 'Oil and oil products (PJ)                               ',
 'Oil and oil products (PJ)                                ',
 'Oil and oil products (PJ)                                 ',
 'Oil and oil products (PJ)                                  ',
 'Oil and oil products (PJ)                                   ',
 'Oil and oil products (PJ)                                    ',
 'Oil and oil products (PJ)                                     ',
 'Oil and oil products (PJ)                                      ',
 'Oil and oil products (PJ)                                       ',
 'Oil and oil products (PJ)                                        ',
 'Oil and oil products (PJ)                                         ',
 'Oil and oil products (PJ)                                          ',
 'Oil and oil products (PJ)                                           ',
 'Oil and oil products (PJ)                                            ',
 'Oil and oil products (PJ)                                             ',
 'Oil and oil products (PJ)                                              ',
 'Oil and oil products (PJ)                                               ',
 'Oil and oil products (PJ)                                                ',
 'Oil and oil products (PJ)                                                 ',
 'Oil and oil products (PJ)                                                  ',
 'Oil and oil products (PJ)                                                   ',
 'Oil and oil products (PJ)                                                    ',
 'Oil and oil products (PJ)                                                     ',
 'Other sources (PJ)         ',
 'Other sources (PJ)          ',
 'Other sources (PJ)              ',
 'Other sources (PJ)               ',
 'Other sources (PJ)                 ',
 'Other sources (PJ)                  ',
 'Other sources (PJ)                   ',
 'Other sources (PJ)                    ',
 'Other sources (PJ)                     ',
 'Other sources (PJ)                      ',
 'Other sources (PJ)                       ',
 'Other sources (PJ)                        ',
 'Other sources (PJ)                         ',
 'Other sources (PJ)                          ',
 'Other sources (PJ)                           ',
 'Other sources (PJ)                            ',
 'Other sources (PJ)                             ',
 'Other sources (PJ)                              ',
 'Other sources (PJ)                               ',
 'Other sources (PJ)                                ',
 'Other sources (PJ)                                 ',
 'Other sources (PJ)                                  ',
 'Other sources (PJ)                                   ',
 'Other sources (PJ)                                    ',
 'Other sources (PJ)                                     ',
 'Other sources (PJ)                                      ',
 'Other sources (PJ)                                       ',
 'Other sources (PJ)                                        ',
 'Other sources (PJ)                                         ',
 'Other sources (PJ)                                          ',
 'Other sources (PJ)                                           ',
 'Other sources (PJ)                                            ',
 'Other sources (PJ)                                             ',
 'Other sources (PJ)                                              ',
 'Other sources (PJ)                                               ',
 'Other sources (PJ)                                                ',
 'Other sources (PJ)                                                 ',
 'Other sources (PJ)                                                  ',
 'Other sources (PJ)                                                   ',
 'Other sources (PJ)                                                    ',
 'Other sources (PJ)                                                     ',
 'Other sources (PJ)                                                      ',
 'Other sources (PJ)                                                       ',
 'Other sources (PJ)                                                        ',
 'Other sources (PJ)                                                         ',
 'Other sources (PJ)                                                          ',
 'Other sources (PJ)                                                           ',
 'Other sources (PJ)                                                            ',
 'Total final energy use (PJ)',
 'Total final energy use (PJ) ',

In [6]:
#Cross Walk with IEA data:
industries_correspondence = {
  'electronics' : (0.5, 'Machinery [ISIC 25-28]'), #Electronics is ISIC 26 and 27, so let's say half of 25-28
  'plastic' : (0.5, 'Rubber and plastic [ISIC 22]'), # SEE BELOW
  'chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), #OK
  'cement' : (0.9, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'glass' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'other_product_manufacturing' : (1.0, 'Other manufacturing [ISIC 31-32]'), #OK
  'agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), #OK
  'textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), #SEE BELOW
  'rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), #+ AND 0.5  'Rubber and plastic [ISIC 22]'
  'metals' : (1.0, 'Basic metals [ISIC 24]'), #OK
  'lime_and_carbonite' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
  # REMOVE 'recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') #I propose we leave this out entirely, unless we are doing all recyclables
}

In [7]:
fraction = 0.9
df_enduse = df_eei.loc[df_eei['ENDUSE']=='Non-metallic minerals [ISIC 23]']
df_enduse = df_enduse[df_enduse['PRODUCT/FLOW'].str.startswith('Total final energy use (PJ)')]
mask = (df_enduse == '..').any(axis=1)
df_enduse = df_enduse.drop(index=df_enduse[mask].index)
df_enduse

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
63,Australia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,91.09,92.28,93.55,109.16,109.54,104.98,101.67,...,112.01,103.23,95.47,91.25,91.19,91.58,85.52,86.28,86.35,81.34
223,Austria,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,32.07,32.37,34.05,33.95,35.78,34.55,38.26,...,37.21,35.49,38.94,39,39.9,40.04,39.72,38.43,37.85,39.36
383,Belgium,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,61.91,57.75,56.02,63.55,60.39,62.17,64.93,...,60.44,56.88,58.21,58.43,57.68,58.43,53.38,56.33,56.62,53.01
543,Canada,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,115.89,108.55,114.47,116.3,121.84,122.42,121.55,...,112.19,103.34,105.01,95.99,91.46,98.52,103.97,99.74,97.61,84.33
703,Czech Republic,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,53.24,54.69,52.98,52.76,54.18,52.9,54.56,...,48.4,47.05,47.02,42.2,43.96,46.46,47.23,49.2,48.96,47.73
863,Denmark,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,25.73,25.42,24.14,25.38,26.8,26.15,27.65,...,19.13,19.74,18.49,18.51,18.53,20.99,22.86,23.94,23.6,23.75
1023,Estonia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,5.1,6.86,4.15,3.97,4.38,5.08,5.15,...,5.36,4.89,6.93,5.42,3.56,3.11,4,4.49,4.04,1.4
1183,Finland,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,16.29,16.79,17.14,17.34,18.34,17.84,18.58,...,14.43,13.2,12.85,12.19,11.98,12.76,13.52,12.9,12.36,11.71
1343,France,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,172.97,199.87,204.99,198.1,197.34,194.37,196.18,...,174.76,166.62,166.83,163.26,157.03,160.4,154.56,160.58,161.6,145.59
1503,Germany,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,325.28,294.87,278.89,285.03,291.74,281.29,287.85,...,281.08,270.2,273.46,275.28,273.95,283.36,284.41,287.2,280.53,278.97
1663,Greece,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,53.88,57.41,51.44,46.73,50.52,46.95,46.15,...,30.43,28.7,30.44,31.83,30.83,32.5,28.49,27.2,26.87,23.14
1823,Hungary,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,24.8,27.05,27.24,28.17,27.21,27.07,26.06,...,18.2,15.84,16.65,18.8,20.35,22.29,22.29,23.7,25.17,23.07
1983,Ireland,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,10.46,9.69,12.43,17.25,21.04,22.38,21.35,...,10.11,11.43,11.28,14.72,15.63,16.6,16.9,18.6,18.17,17.7
2143,Italy,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,338.7,319.21,321.78,354.33,369.03,372.34,341.35,...,244.58,225.92,208.68,187.85,208.11,193.51,175.56,179.99,177.39,176.66
2303,Japan,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,507.48,486.85,480.72,469.82,445.81,441.24,443.49,...,368.12,368.14,375.15,360.46,346.54,352.92,350.02,358.48,338.45,320.51
2463,Korea,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,231.69,235.24,244.89,262.62,247.23,222.88,240.41,...,254.48,232.03,235.14,237.84,237.73,232.66,218.12,218.22,214.3,205.83
2623,Lithuania,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,6.44,6.51,6.48,6.5,6.81,7.77,9.35,...,6.59,7.35,8.07,7.3,6.16,5.93,5.62,6.5,6.94,6.11
2783,Luxembourg,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,8.35,8.61,7.26,5.79,7,7.06,7.29,...,6.97,6.79,5.78,6.46,6.25,6.25,6.22,5.99,6.11,5.44
2991,Mexico,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,139.32,136.05,144.79,134.41,162.93,158.68,187.11,...,160.68,179.42,186.62,197.74,218.78,229.34,208.22,195.46,191.23,186.57
3103,Netherlands,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,36.27,35.6,31.45,31.43,31.6,32.01,32.04,...,27.56,25.54,23.76,23.9,24.52,25.08,24.78,26.41,22.25,21.4
3263,New Zealand,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,7.29,7.31,7.42,7.46,7.68,8.16,7.89,...,5.89,6.45,9.94,8.7,8.07,6.49,6.71,6.83,8.95,5.81
3423,Norway,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,12.12,11.86,11.61,11.37,10.71,11.04,11.93,...,14.88,14.81,15.24,13.62,13.71,13.67,14.65,15.07,15.01,13.92
3583,Poland,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,108.03,98.78,93.59,98.12,104.45,105.33,107.2,...,125.17,112.88,106.6,109.99,107.97,119.27,125.38,130.1,133.84,126.5
3743,Portugal,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,88.26,87.03,92.96,76.63,75.21,77.55,75.77,...,63.57,45.21,45.42,49.37,46.9,44.05,47.02,44.99,45.49,45.46
3903,Slovak Republic,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,29.99,23.25,20.96,20.13,17.14,20.87,19.32,...,16.68,14.29,16.2,17.73,18.2,19.24,19.46,17.14,18.47,18.75
4063,Spain,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,266.61,295.03,259.33,308.47,287.64,315.13,276.98,...,201.64,164.61,145.48,143.61,154.39,168.43,173.32,177.63,175,159.3
4223,Sweden,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,21.09,21.33,20.79,18.63,19.54,19.48,20.57,...,20.96,20.62,16.83,16.43,18.12,17.5,18.05,20.08,18.6,17.07
4383,Switzerland,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,20.94,21.17,17.08,17.94,18.58,18.09,20.71,...,20.57,19.16,18.68,20.52,18.28,18.9,19.01,18.3,17.67,17.55
4543,Republic of Türkiye,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,92.83,82.78,79.33,102.1,133.28,126.76,136.15,...,238.11,241.31,221.05,233.39,233.05,243.98,398.89,402.4,340.08,404.59
4703,United Kingdom,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,161.41,132.34,126.42,128.59,118.09,131.39,128.06,...,100.67,98.92,105.63,98.38,98.97,95.67,91.59,90.33,86.78,89.4
4863,United States,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,1055.3,1026.26,1005.9,1011.45,1057.84,1052,1081.38,...,700.56,719.43,741.37,749.21,691.59,678.11,621.49,764.25,781.18,714.2
5183,Brazil,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,268.2,265.83,259.46,247.27,246.2,264.35,278.91,...,394.72,403,419.37,419.83,378.81,340.99,332.63,326.84,330.77,325.39
5343,Morocco,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,3.02,6.53,6.88,7.29,39.52,41.51,43.96,...,59.78,62.72,64.07,56.02,57.72,55.76,58.88,60.23,60.98,52.81
5823,Chile,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,9.5,9.86,9.06,12.96,13.28,11.41,14.89,...,12.55,12.63,13.48,11.49,12.2,12.22,11.41,11.33,11.78,11.03
6143,Latvia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,2.71,2.88,3.68,4.34,4.1,4.95,4.9,...,6.53,6.72,6.07,6.56,5.63,4.6,5.47,7.13,6.8,7.41
6303,Albania,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,2.46,2.56,1.22,1.63,1.77,1.53,3.49,...,8.92,5.07,4,6.2,5.67,4.94,9.82,11.77,7.86,8.74
6463,Armenia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,0.23,0.22,0.28,0.36,0.57,0.59,0.76,...,0.59,0.56,0.5,4.2,3.15,2.68,3.51,3.97,3.39,4.63
7103,Bulgaria,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,21.17,21.25,23.12,23.32,24.83,25.71,28.21,...,21.32,20.33,21.14,21.77,22.36,23.42,23.93,23.94,23.47,23.48
7263,Croatia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,18.38,20.44,20.07,19.17,20.61,21.71,21.39,...,14.6,13.51,14.24,14.04,13.86,13.33,15.69,15.76,15.17,15.45
7423,Cyprus,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,9.47,8.67,8.9,9.38,10.1,8.96,8.72,...,5.08,4.36,5.5,6.85,6.15,6.21,6.59,6.39,6.16,7.06
8063,Kosovo,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,0.78,0.98,0.98,0.98,0.98,1,1.05,...,2.59,2.37,2.81,2.38,3.75,3.23,4.63,4.3,4.76,4.65
8543,Republic of Moldova,Non-metallic minerals [ISIC 23],Total final energy use (PJ),0.43,1.25,0.74,0.87,1.07,6.06,5.8,...,3.72,4.17,4.6,2.97,3.57,2.81,3.31,4.11,3.95,3.85
8703,Republic of North Macedonia,Non-metallic minerals [ISIC 23],Total final energy use (PJ),4.6,4.89,5.1,4.41,4.36,4.83,5.03,...,3.92,3.87,3.7,3.33,3.23,3.73,3.77,4.17,4.39,4.08
8863,Romania,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,48.68,52.31,57.24,35.49,48.7,45.89,44.2,...,28.75,37.12,33.06,35.46,39.36,41.83,42.5,47.14,45.61,50.22
9183,Slovenia,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,9.24,9.46,7.88,9.21,9.47,10.08,11.39,...,7.8,7.22,7.47,7.61,7.49,7.37,8.01,8.47,8.77,7.89

In [8]:
years_hist=range(2010,2021)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 87.88511111111112,
 2011: 90.49555555555557,
 2012: 88.06977777777777,
 2013: 88.16066666666666,
 2014: 87.73533333333333,
 2015: 86.1408888888889,
 2016: 86.24799999999999,
 2017: 87.358,
 2018: 91.16244444444445,
 2019: 89.14066666666668,
 2020: 86.50800000000001}

In [9]:
sub_continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in sub_continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in sub_continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year    meanEEI
0    Australia and New Zealand  2010  60.220000
1    Australia and New Zealand  2011  58.950000
2    Australia and New Zealand  2012  54.840000
3    Australia and New Zealand  2013  52.705000
4    Australia and New Zealand  2014  49.975000
..                         ...   ...        ...
237             Western Europe  2016  84.637143
238             Western Europe  2017  83.154286
239             Western Europe  2018  84.748571
240             Western Europe  2019  83.232857
241             Western Europe  2020  80.188571

[121 rows x 3 columns]

In [10]:
#### HISTORICAL ######
iso3 = sorted(set(df_ippu_all['iso_code3'].values))
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_cement
0,Aruba,ABW,2010,0
1,Aruba,ABW,2011,0
2,Aruba,ABW,2012,0
3,Aruba,ABW,2013,0
4,Aruba,ABW,2014,0
...,...,...,...,...
2096,Zimbabwe,ZWE,2016,0
2097,Zimbabwe,ZWE,2017,0
2098,Zimbabwe,ZWE,2018,0
2099,Zimbabwe,ZWE,2019,0
2100,Zimbabwe,ZWE,2020,0

In [11]:
for c,y in zip(df_historical_out['iso_code3'].values,df_historical_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato*fraction
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato*fraction
df_historical_out

San Marino 2020 prodinit_ippu_cement_tonne=0.0

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_cement
0,Aruba,ABW,2010,0.501724
1,Aruba,ABW,2011,0.403974
2,Aruba,ABW,2012,0.359275
3,Aruba,ABW,2013,0.620407
4,Aruba,ABW,2014,0.377582
...,...,...,...,...
2096,Zimbabwe,ZWE,2016,0.057803
2097,Zimbabwe,ZWE,2017,0.129744
2098,Zimbabwe,ZWE,2018,0.056283
2099,Zimbabwe,ZWE,2019,0.039352
2100,Zimbabwe,ZWE,2020,0.050188

In [12]:
#### Projected ######

years_proj=range(max(years_hist)+1,2051)

iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        coun_year.append([count,iso3,year,0])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out[var_name]=0
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_cement
0,Seychelles,SYC,2021,0
1,Seychelles,SYC,2022,0
2,Seychelles,SYC,2023,0
3,Seychelles,SYC,2024,0
4,Seychelles,SYC,2025,0
...,...,...,...,...
5725,Barbados,BRB,2046,0
5726,Barbados,BRB,2047,0
5727,Barbados,BRB,2048,0
5728,Barbados,BRB,2049,0
5729,Barbados,BRB,2050,0

In [13]:
y_hist_max = max(years_hist)
for c,y in zip(df_projected_out['iso_code3'].values,df_projected_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y_hist_max)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato*fraction
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y_hist_max), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y_hist_max]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato*fraction
df_projected_out

San Marino 2021 prodinit_ippu_cement_tonne=0.0
San Marino 2022 prodinit_ippu_cement_tonne=0.0
San Marino 2023 prodinit_ippu_cement_tonne=0.0
San Marino 2024 prodinit_ippu_cement_tonne=0.0
San Marino 2025 prodinit_ippu_cement_tonne=0.0
San Marino 2026 prodinit_ippu_cement_tonne=0.0
San Marino 2027 prodinit_ippu_cement_tonne=0.0
San Marino 2028 prodinit_ippu_cement_tonne=0.0
San Marino 2029 prodinit_ippu_cement_tonne=0.0
San Marino 2030 prodinit_ippu_cement_tonne=0.0
San Marino 2031 prodinit_ippu_cement_tonne=0.0
San Marino 2032 prodinit_ippu_cement_tonne=0.0
San Marino 2033 prodinit_ippu_cement_tonne=0.0
San Marino 2034 prodinit_ippu_cement_tonne=0.0
San Marino 2035 prodinit_ippu_cement_tonne=0.0
San Marino 2036 prodinit_ippu_cement_tonne=0.0
San Marino 2037 prodinit_ippu_cement_tonne=0.0
San Marino 2038 prodinit_ippu_cement_tonne=0.0
San Marino 2039 prodinit_ippu_cement_tonne=0.0
San Marino 2040 prodinit_ippu_cement_tonne=0.0
San Marino 2041 prodinit_ippu_cement_tonne=0.0
San Marino 2042 prodinit_ippu_cement_tonne=0.0
San Marino 2043 prodinit_ippu_cement_tonne=0.0
San Marino 2044 prodinit_ippu_cement_tonne=0.0
San Marino 2045 prodinit_ippu_cement_tonne=0.0
San Marino 2046 prodinit_ippu_cement_tonne=0.0
San Marino 2047 prodinit_ippu_cement_tonne=0.0
San Marino 2048 prodinit_ippu_cement_tonne=0.0
San Marino 2049 prodinit_ippu_cement_tonne=0.0
San Marino 2050 prodinit_ippu_cement_tonne=0.0

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_cement
0,Seychelles,SYC,2021,0.384022
1,Seychelles,SYC,2022,0.241850
2,Seychelles,SYC,2023,0.152312
3,Seychelles,SYC,2024,0.095923
4,Seychelles,SYC,2025,0.060410
...,...,...,...,...
5725,Barbados,BRB,2046,0.002039
5726,Barbados,BRB,2047,0.001818
5727,Barbados,BRB,2048,0.001621
5728,Barbados,BRB,2049,0.001445
5729,Barbados,BRB,2050,0.001288

In [14]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [15]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')

In [16]:
df_historical_out.loc[df_historical_out['Nation']=='Mexico']

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_cement
1232,Mexico,MEX,2010,0.005070
1233,Mexico,MEX,2011,0.004674
1234,Mexico,MEX,2012,0.004323
1235,Mexico,MEX,2013,0.004251
1236,Mexico,MEX,2014,0.005287
1237,Mexico,MEX,2015,0.006339
1238,Mexico,MEX,2016,0.007347
1239,Mexico,MEX,2017,0.006631
1240,Mexico,MEX,2018,0.005630
1241,Mexico,MEX,2019,0.005042
1242,Mexico,MEX,2020,0.005028

In [17]:
df_ippu_all.loc[df_ippu_all['iso_code3']=='MEX']

     iso_code3  Year  prodinit_ippu_cement_tonne
984        MEX  2010                2.718831e+07
985        MEX  2011                3.093772e+07
986        MEX  2012                3.734932e+07
987        MEX  2013                3.951391e+07
988        MEX  2014                3.366246e+07
989        MEX  2015                3.106025e+07
990        MEX  2016                2.809266e+07
991        MEX  2017                2.826169e+07
992        MEX  2018                3.124698e+07
993        MEX  2019                3.413140e+07
994        MEX  2020                3.339763e+07
995        MEX  2021                3.339763e+07
996        MEX  2022                3.428143e+07
997        MEX  2023                3.518862e+07
998        MEX  2024                3.611982e+07
999        MEX  2025                3.707565e+07
1000       MEX  2026                3.805679e+07
1001       MEX  2027                3.906388e+07
1002       MEX  2028                4.009763e+07
1003       MEX  2029                4.115873e+07
1004       MEX  2030                4.224792e+07
1005       MEX  2031                4.336592e+07
1006       MEX  2032                4.451351e+07
1007       MEX  2033                4.569147e+07
1008       MEX  2034                4.690061e+07
1009       MEX  2035                4.814174e+07
1010       MEX  2036                4.941571e+07
1011       MEX  2037                5.072340e+07
1012       MEX  2038                5.206569e+07
1013       MEX  2039                5.344350e+07
1014       MEX  2040                5.485778e+07
1015       MEX  2041                5.630948e+07
1016       MEX  2042                5.779960e+07
1017       MEX  2043                5.932915e+07
1018       MEX  2044                6.089917e+07
1019       MEX  2045                6.251075e+07
1020       MEX  2046                6.416497e+07
1021       MEX  2047                6.586296e+07
1022       MEX  2048                6.760589e+07
1023       MEX  2049                6.939495e+07
1024       MEX  2050                7.123135e+07

In [18]:
0.007347*2.809266e+07/0.9

229329.74779999998

In [19]:
df_enduse[df_enduse['COUNTRY']=='Mexico']

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2991,Mexico,Non-metallic minerals [ISIC 23],Total final energy use (PJ) ...,139.32,136.05,144.79,134.41,162.93,158.68,187.11,...,160.68,179.42,186.62,197.74,218.78,229.34,208.22,195.46,191.23,186.57