In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_plastic'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [3]:
IPPU_folder = 'prodinit_ippu_plastic_tonne'
IPPU_var = 'prodinit_ippu_plastic_tonne'
df_ippu_hist = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & (df_ippu_hist['year']==y),][IPPU_var].values[0]
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & (df_ippu_proj['year']==y)][IPPU_var].values[0]
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_plastic_tonne
0          SVK  2010                490714.404826
1          SVK  2011                540658.381662
2          SVK  2012                505985.354336
3          SVK  2013                516691.021961
4          SVK  2014                539387.622991
...        ...   ...                          ...
7826       BHR  2046                348513.292563
7827       BHR  2047                372569.064450
7828       BHR  2048                398285.261272
7829       BHR  2049                425776.492153
7830       BHR  2050                455165.276996

[7831 rows x 3 columns]

In [4]:
df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei

,COUNTRY,PRODUCT/FLOW,ENDUSE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Australia,Oil and oil products (PJ),"Manufacturing [ISIC 10-18, 20-32]",130.43,106.35,104.18,106.50,118.77,125.35,127.31,128.88,136.56,129.94,136.44,165.71,185.91,158.38,160.02,121.34,106.70
1,Australia,Oil and oil products (PJ),Food and tobacco [ISIC 10-12],5.89,6.00,2.38,2.66,2.75,2.76,2.90,2.99,2.90,5.52,5.04,5.84,6.37,5.89,5.96,5.18,5.04
2,Australia,Oil and oil products (PJ),Textiles and leather [ISIC 13-15],0.48,0.48,0.48,0.48,0.38,0.95,0.95,0.98,0.95,0.77,0.75,0.76,0.75,0.94,0.95,0.77,0.76
3,Australia,Oil and oil products (PJ),Wood and wood products [ISIC 16],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,Australia,Oil and oil products (PJ),Paper pulp and printing [ISIC 17-18],2.56,2.95,1.74,0.64,0.68,0.77,0.82,0.73,0.64,0.49,0.48,0.47,0.67,2.32,2.37,2.57,2.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12469,Ukraine,Steel production (10^6 t),Memo: Coke and refined petroleum products [ISI...,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
12470,Ukraine,Steel production (10^6 t),"Agriculture, forestry and fishing [ISIC 01-03]",x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
12471,Ukraine,Steel production (10^6 t),Mining [ISIC 05-09],x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
12472,Ukraine,Steel production (10^6 t),Construction [ISIC 41-43],x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
12473,Ukraine,Steel production (10^6 t),General activity data,31.77,33.11,34.05,36.93,38.74,38.64,40.89,42.83,37.28,29.86,33.43,35.33,32.98,32.77,27.17,22.97,24.22

In [5]:
#Cross Walk with IEA data:
industries_correspondence = {
                'electronics' : (1.0, 'Machinery [ISIC 25-28]'), 
                'plastic' : (1.0, 'Rubber and plastic [ISIC 22]'), 
                'chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), 
                'cement' : (1.0, 'Of which: cement'),
                'glass' : (1.0, 'Non-metallic minerals [ISIC 23]'), 
                'other_product_manufacturing' : (1.0, 'Other manufacturing [ISIC 31-32]'), 
                'agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), 
                'textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), 
                'rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), 
                'metals' : (1.0, 'Basic metals [ISIC 24]'),  
                'lime_and_carbonite' : (1.0, 'Non-ferrous metals [ISIC 2420+2432]'), 
                'paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
                'recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') 
                }

In [6]:
df_enduse = df_eei.loc[(df_eei['PRODUCT/FLOW']=='Total final energy (PJ)') & 
                       (df_eei['ENDUSE']=='Rubber and plastic [ISIC 22]')]
df_enduse

,COUNTRY,PRODUCT/FLOW,ENDUSE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
153,Australia,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
531,Austria,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
909,Belgium,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1287,Canada,Total final energy (PJ),Rubber and plastic [ISIC 22],14.78,15.41,14.78,14.91,15.26,14.43,13.46,13.73,12.98,11.47,12.38,12.50,11.80,11.00,11.54,10.76,10.68
1665,Czech Republic,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.36,14.19,11.80,12.07,12.47,11.87,12.75,12.83,13.30,13.23
2043,Denmark,Total final energy (PJ),Rubber and plastic [ISIC 22],4.58,4.57,4.48,4.89,4.94,4.76,4.58,4.12,3.40,3.12,3.25,3.06,2.60,2.67,2.76,2.89,0.00
2421,Finland,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2799,France,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3177,Germany,Total final energy (PJ),Rubber and plastic [ISIC 22],70.50,69.71,67.60,77.58,80.46,79.42,81.18,81.28,84.15,75.98,86.39,80.95,80.64,80.81,79.71,81.48,83.25
3555,Greece,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3933,Hungary,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.57,7.91,8.57,8.98
4311,Ireland,Total final energy (PJ),Rubber and plastic [ISIC 22],2.17,1.94,1.93,1.85,1.80,2.17,2.46,2.35,2.14,1.88,2.00,2.07,1.99,2.03,2.01,2.08,2.18
4689,Italy,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5067,Japan,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5445,Korea,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5823,Luxembourg,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6201,Mexico,Total final energy (PJ),Rubber and plastic [ISIC 22],8.88,8.69,7.81,6.78,7.04,8.23,8.29,7.93,7.79,7.49,8.49,9.19,8.63,9.58,10.02,10.72,11.25
6579,Netherlands,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6957,New Zealand,Total final energy (PJ),Rubber and plastic [ISIC 22],1.46,1.52,1.75,1.91,1.85,2.27,2.20,2.05,1.91,1.77,2.06,1.51,2.02,1.82,1.83,2.01,2.09
7335,Poland,Total final energy (PJ),Rubber and plastic [ISIC 22],10.34,10.66,10.90,12.12,13.15,13.09,13.46,13.93,14.52,13.44,15.21,16.86,15.16,18.96,18.82,18.85,20.98
7713,Portugal,Total final energy (PJ),Rubber and plastic [ISIC 22],1.10,1.06,1.06,1.13,1.23,1.15,1.22,1.29,0.85,1.20,1.42,1.38,1.38,1.51,1.47,1.51,1.48
8091,Slovak Republic,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8469,Spain,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8847,Sweden,Total final energy (PJ),Rubber and plastic [ISIC 22],6.97,6.39,6.27,6.47,6.20,6.00,6.23,6.11,5.73,5.30,5.98,5.73,5.36,5.01,4.68,4.68,4.54
9225,Switzerland,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
9603,Turkey,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,27.59
9981,United Kingdom,Total final energy (PJ),Rubber and plastic [ISIC 22],57.18,69.18,60.98,57.95,57.78,62.45,62.65,62.45,54.76,48.59,64.68,58.43,56.61,62.81,63.90,61.34,58.61
10359,United States,Total final energy (PJ),Rubber and plastic [ISIC 22],349.08,360.43,349.74,331.65,351.91,338.53,311.25,341.21,283.50,290.25,275.46,296.61,314.07,318.80,295.38,298.29,298.35
10737,Morocco,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11115,Armenia,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.16,0.18
11493,Belarus,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11871,Republic of Moldova,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.05
12249,Ukraine,Total final energy (PJ),Rubber and plastic [ISIC 22],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [7]:
years_hist=range(2010,2017)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 14.83,
 2011: 15.174545454545454,
 2012: 15.51909090909091,
 2013: 16.25212121212121,
 2014: 15.541212121212121,
 2015: 15.656969696969698,
 2016: 16.46787878787879}

In [8]:
sub_continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in sub_continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in sub_continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year     meanEEI
0    Australia and New Zealand  2010    1.030000
1    Australia and New Zealand  2011    0.755000
2    Australia and New Zealand  2012    1.010000
3    Australia and New Zealand  2013    0.910000
4    Australia and New Zealand  2014    0.915000
5    Australia and New Zealand  2015    1.005000
6    Australia and New Zealand  2016    1.045000
14             Central America  2010    8.490000
15             Central America  2011    9.190000
16             Central America  2012    8.630000
17             Central America  2013    9.580000
18             Central America  2014   10.020000
19             Central America  2015   10.720000
20             Central America  2016   11.250000
42              Eastern Europe  2010    5.456000
43              Eastern Europe  2011    5.866000
44              Eastern Europe  2012    5.406000
45              Eastern Europe  2013    8.056000
46              Eastern Europe  2014    7.912000
47              Eastern Europe  2015    8.144000
48              Eastern Europe  2016    8.638000
77            Northern America  2010  143.920000
78            Northern America  2011  154.555000
79            Northern America  2012  162.935000
80            Northern America  2013  164.900000
81            Northern America  2014  153.460000
82            Northern America  2015  154.525000
83            Northern America  2016  154.515000
84             Northern Europe  2010    2.807500
85             Northern Europe  2011    2.715000
86             Northern Europe  2012    2.487500
87             Northern Europe  2013    2.427500
88             Northern Europe  2014    2.362500
89             Northern Europe  2015    2.412500
90             Northern Europe  2016    1.680000
126            Southern Europe  2010    0.355000
127            Southern Europe  2011    0.345000
128            Southern Europe  2012    0.345000
129            Southern Europe  2013    0.377500
130            Southern Europe  2014    0.367500
131            Southern Europe  2015    0.377500
132            Southern Europe  2016    0.370000
145               Western Asia  2015    0.080000
146               Western Asia  2016   13.885000
147             Western Europe  2010   12.341429
148             Western Europe  2011   11.564286
149             Western Europe  2012   11.520000
150             Western Europe  2013   11.544286
151             Western Europe  2014   11.387143
152             Western Europe  2015   11.640000
153             Western Europe  2016   11.892857

In [9]:
#### HISTORICAL ######
iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Slovak Republic,SVK,2010,0
1,Slovak Republic,SVK,2011,0
2,Slovak Republic,SVK,2012,0
3,Slovak Republic,SVK,2013,0
4,Slovak Republic,SVK,2014,0
...,...,...,...,...
1332,Turkmenistan,TKM,2012,0
1333,Turkmenistan,TKM,2013,0
1334,Turkmenistan,TKM,2014,0
1335,Turkmenistan,TKM,2015,0
1336,Turkmenistan,TKM,2016,0

In [10]:
for c,y in zip(df_historical_out['iso_code3'].values,df_historical_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Slovak Republic,SVK,2010,0.000000
1,Slovak Republic,SVK,2011,0.000000
2,Slovak Republic,SVK,2012,0.000000
3,Slovak Republic,SVK,2013,0.000000
4,Slovak Republic,SVK,2014,0.000000
...,...,...,...,...
1332,Turkmenistan,TKM,2012,0.330579
1333,Turkmenistan,TKM,2013,0.227787
1334,Turkmenistan,TKM,2014,0.176671
1335,Turkmenistan,TKM,2015,0.212984
1336,Turkmenistan,TKM,2016,0.222431

In [11]:
#### Projected ######

years_proj=range(max(years_hist)+1,2051)

iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        coun_year.append([count,iso3,year,0])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out[var_name]=0
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Slovak Republic,SVK,2017,0
1,Slovak Republic,SVK,2018,0
2,Slovak Republic,SVK,2019,0
3,Slovak Republic,SVK,2020,0
4,Slovak Republic,SVK,2021,0
...,...,...,...,...
6489,Turkmenistan,TKM,2046,0
6490,Turkmenistan,TKM,2047,0
6491,Turkmenistan,TKM,2048,0
6492,Turkmenistan,TKM,2049,0
6493,Turkmenistan,TKM,2050,0

In [12]:
y_hist_max = max(years_hist)
for c,y in zip(df_projected_out['iso_code3'].values,df_projected_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y_hist_max)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y_hist_max), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y_hist_max]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Slovak Republic,SVK,2017,0.000000
1,Slovak Republic,SVK,2018,0.000000
2,Slovak Republic,SVK,2019,0.000000
3,Slovak Republic,SVK,2020,0.000000
4,Slovak Republic,SVK,2021,0.000000
...,...,...,...,...
6489,Turkmenistan,TKM,2046,0.028632
6490,Turkmenistan,TKM,2047,0.026325
6491,Turkmenistan,TKM,2048,0.024204
6492,Turkmenistan,TKM,2049,0.022254
6493,Turkmenistan,TKM,2050,0.020461

In [13]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [14]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')