In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_plastic'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent=df_country_continent.dropna(how='any')

In [3]:
#Socioeconomic varibles

#GDP
df_gdp_hist = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/historical/gdp_mmm_usd.csv')
df_gdp_proj = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/projected/gdp_mmm_usd.csv')

nation_gdp = sorted(set(df_gdp_proj['Nation'].values))

years_all = range(min(df_gdp_hist['Year'].values),max(df_gdp_proj['Year'].values)+1)
c_y_gdp = []
for c in nation_gdp:
    for y in years_all:
    
        try:
            gdp = df_gdp_hist.loc[(df_gdp_hist['Nation']==c) & (df_gdp_hist['Year']==y),]['gdp_mmm_usd'].values[0]
            
        except:
            gdp = df_gdp_proj.loc[(df_gdp_proj['Nation']==c) & (df_gdp_proj['Year']==y)]['gdp_mmm_usd'].values[0]
            
        c_y_gdp.append([c,y,gdp])

df_gdp_all = pd.DataFrame(c_y_gdp,columns=['Nation', 'Year', 'gdp_mmm_usd'])



#Rural population
df_popru_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/historical/population_gnrl_rural.csv')
df_popru_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/projected/population_gnrl_rural.csv')

#Urban population
df_popur_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/historical/population_gnrl_urban.csv')
df_popur_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/projected/population_gnrl_urban.csv')

nation_pop = sorted(set(df_popur_proj['Nation'].values))

years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop = []
for c in nation_pop:
    for y in years_all:
    
        try:
            pop_ur = df_popur_hist.loc[(df_popur_hist['Nation']==c) &
                                       (df_popur_hist['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_hist.loc[(df_popru_hist['Nation']==c) &
                                       (df_popru_hist['Year']==y),]['population_gnrl_rural'].values[0]
            
        except:
            pop_ur = df_popur_proj.loc[(df_popur_proj['Nation']==c) &
                                       (df_popur_proj['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_proj.loc[(df_popru_proj['Nation']==c) &
                                       (df_popru_proj['Year']==y),]['population_gnrl_rural'].values[0]
            
        c_y_pop.append([c,y,pop_ur,pop_ru])

df_pop_all = pd.DataFrame(c_y_pop,columns=['Nation', 'Year', 'population_gnrl_urban','population_gnrl_rural'])

#All Together
nation_pop_gdp = sorted(set(nation_pop).intersection(set(nation_gdp)))
years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop_gdp = []
for c in nation_pop_gdp:
    iso3 = df_gdp_hist.loc[df_gdp_hist['Nation']==c]['iso_code3'].values[0]
    for y in years_all:
        pop_ur = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_urban'].values[0]
        
        pop_ru = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_rural'].values[0]
        
        gdp = df_gdp_all.loc[(df_gdp_all['Nation']==c) & (df_gdp_all['Year']==y)]['gdp_mmm_usd'].values[0]
        
        c_y_pop_gdp.append([c,iso3,y,pop_ur,pop_ru,gdp])
df_pop_gdp_all = pd.DataFrame(c_y_pop_gdp,columns=['Nation','iso_code3', 'Year',
                                                   'population_gnrl_urban',
                                                   'population_gnrl_rural',
                                                   'gdp_mmm_usd'])
df_pop_gdp_all

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010
...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404

In [4]:
#IPPU data
ippu_correspondence = {
  'consumpinit_inen_energy_tj_per_tonne_production_electronics' : 'prodinit_ippu_electronics_tonne', 
  'consumpinit_inen_energy_tj_per_tonne_production_plastic' : 'prodinit_ippu_plastic_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_chemicals' : 'prodinit_ippu_chemicals_tonne', 
  'consumpinit_inen_energy_tj_per_tonne_production_cement' : 'prodinit_ippu_cement_tonne', 
  'consumpinit_inen_energy_tj_per_tonne_production_glass' : 'prodinit_ippu_glass_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_textiles' : 'prodinit_ippu_textiles_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_rubber_and_leather' : 'prodinit_ippu_rubber_and_leather_tonne', 
  'consumpinit_inen_energy_tj_per_tonne_production_metals' : 'prodinit_ippu_metals_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_lime_and_carbonite' : 'prodinit_ippu_lime_and_carbonite_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_paper' : 'prodinit_ippu_paper_tonne',
  'consumpinit_inen_energy_tj_per_tonne_production_recycled_wood' : 'prodinit_ippu_paper_tonne'
}
IPPU_var = ippu_correspondence[var_name]

df_ippu_hist = pd.read_csv(ggpdir+'/IPPU/'+IPPU_var+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(ggpdir+'/IPPU/'+IPPU_var+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & (df_ippu_hist['year']==y),][IPPU_var].values[0]
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & (df_ippu_proj['year']==y)][IPPU_var].values[0]
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_plastic_tonne
0          TLS  2010                 7.010074e+02
1          TLS  2011                 5.223627e+02
2          TLS  2012                 8.743854e+02
3          TLS  2013                 9.811595e+02
4          TLS  2014                 8.600855e+02
...        ...   ...                          ...
7826       VNM  2046                 1.750047e+07
7827       VNM  2047                 1.907294e+07
7828       VNM  2048                 2.078670e+07
7829       VNM  2049                 2.265445e+07
7830       VNM  2050                 2.469003e+07

[7831 rows x 3 columns]

In [5]:
#IEA DATA
df_IEA=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

#Cross Walk with IEA data:
industries_correspondence = {
  'consumpinit_inen_energy_tj_per_tonne_production_electronics' : (0.5, 'Machinery [ISIC 25-28]'), #Electronics is ISIC 26 and 27, so let's say half of 25-28
  'consumpinit_inen_energy_tj_per_tonne_production_plastic' : (0.5, 'Rubber and plastic [ISIC 22]'), # SEE BELOW
  'consumpinit_inen_energy_tj_per_tonne_production_chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), #OK
  'consumpinit_inen_energy_tj_per_tonne_production_cement' : (0.9, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'consumpinit_inen_energy_tj_per_tonne_production_glass' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'consumpinit_inen_energy_tj_per_mmm_gdp_other_product_manufacturing' : (0.7, 'Manufacturing [ISIC 10-18; 20-32]'), #OK
  'consumpinit_inen_energy_total_pj_agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), #OK
  'consumpinit_inen_energy_tj_per_tonne_production_textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), #SEE BELOW
  'consumpinit_inen_energy_tj_per_tonne_production_rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), #+ AND 0.5  'Rubber and plastic [ISIC 22]'
  'consumpinit_inen_energy_tj_per_tonne_production_metals' : (1.0, 'Basic metals [ISIC 24]'), #OK
  'consumpinit_inen_energy_tj_per_tonne_production_lime_and_carbonite' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'consumpinit_inen_energy_tj_per_tonne_production_paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
  'consumpinit_inen_energy_tj_per_tonne_production_recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') #I propose we leave this out entirely, unless we are doing all recyclables
}

(fraction,subsector) = industries_correspondence[var_name]

IEA_subsec=sorted(list(set(df_IEA['Subsector'].values)))

socioec_vars=['Nation', 'Year','population_gnrl_urban','population_gnrl_rural','gdp_mmm_usd']

columns = socioec_vars+IEA_subsec

def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

nation_pop_gdp_all=sorted(set(df_pop_gdp_all['Nation'].values))

df_enduse = df_IEA.loc[df_IEA['Subsector']==subsector]
df_enduse = df_enduse[df_enduse['Product'].str.startswith('Total final energy use (PJ)')]
#mask = (df_enduse == '..').any(axis=1)
#df_enduse = df_enduse.drop(index=df_enduse[mask].index)

nation_enduse = df_enduse['Country'].values
nation_pop_gdp_enduse = sorted(set(nation_pop_gdp_all).intersection(set(nation_enduse)))
years_all = range(min(df_pop_gdp_all['Year'].values),2020+1)
c_y_pop_gdp = []
for c in nation_pop_gdp_enduse:
    for y in years_all:
        pop_ur = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_urban'].values[0]
        
        pop_ru = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_rural'].values[0]
        
        gdp = df_gdp_all.loc[(df_gdp_all['Nation']==c) & (df_gdp_all['Year']==y)]['gdp_mmm_usd'].values[0]
        
        end_use = df_enduse.loc[(df_enduse['Country']==c)][str(y)].values[0]
        
        if is_number(end_use):
            end_use=float(end_use)
            
            c_y_pop_gdp.append([c,y,pop_ur,pop_ru,gdp,end_use])
        
df_pop_gdp_enduse = pd.DataFrame(c_y_pop_gdp,columns=['Nation', 'Year',
                                                   'population_gnrl_urban',
                                                   'population_gnrl_rural',
                                                   'gdp_mmm_usd',
                                                    subsector+' Total (PJ)'])
df_pop_gdp_enduse

,Nation,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,Rubber and plastic [ISIC 22] Total (PJ)
0,Armenia,2015,1.845589e+06,1.079970e+06,17.839562,0.16
1,Armenia,2016,1.852180e+06,1.083967e+06,18.562577,0.18
2,Armenia,2017,1.858250e+06,1.086539e+06,19.285593,0.17
3,Armenia,2018,1.863995e+06,1.087746e+06,20.008609,0.20
4,Armenia,2019,1.869846e+06,1.087882e+06,20.731625,0.15
...,...,...,...,...,...,...
177,United States,2020,2.740321e+08,5.746903e+07,16143.597760,257.62
178,Uzbekistan,2014,1.564029e+07,1.511741e+07,92.870937,0.06
179,Uzbekistan,2015,1.588419e+07,1.541471e+07,97.456825,0.12
180,Uzbekistan,2016,1.613096e+07,1.571694e+07,102.805785,0.12
181,Uzbekistan,2017,1.637244e+07,1.601616e+07,108.154744,0.13

In [6]:
#Linear regression

from sklearn.linear_model import Lasso 
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import normalize

X=df_pop_gdp_enduse[['population_gnrl_urban','population_gnrl_rural','gdp_mmm_usd']]
Y=df_pop_gdp_enduse[subsector+' Total (PJ)']

linear_model = LinearRegression()
linear_model.fit(X,Y)
print(linear_model.coef_)

[-5.37076104e-07  1.14780644e-06  2.42302417e-02]

In [8]:
years_hist=range(min(df_pop_gdp_enduse['Year'].values),max(df_pop_gdp_enduse['Year'].values)+1)

ISO3 = sorted(set(df_pop_gdp_all['iso_code3'].values).intersection(set(df_ippu_all['iso_code3'].values)))

coun_year_PJ=[]
coun_year_dato=[]

for iso3 in ISO3:
    count = df_gdp_hist.loc[df_gdp_hist['iso_code3']==iso3]['Nation'].values[0]
    for year in years_hist:
        
        tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==iso3)&
                                (df_ippu_all['Year']==year)][IPPU_var].values[0]

        
        if (count,year) in zip(df_pop_gdp_enduse['Nation'].values,df_pop_gdp_enduse['Year'].values):
            
            PJ=df_pop_gdp_enduse.loc[(df_pop_gdp_enduse['Nation'] ==count) & 
                        (df_pop_gdp_enduse['Year']== year), subsector+' Total (PJ)'].values[0]
        else:
            
            X_test = df_pop_gdp_all.loc[(df_pop_gdp_all['Nation'] == count) & 
                            (df_pop_gdp_all['Year']== year)][['population_gnrl_urban',
                                                              'population_gnrl_rural',
                                                              'gdp_mmm_usd']]
            PJ =linear_model.predict(X_test)[0]

            if PJ<0:
                PJ=0
                
        if tonne!=0:
            dato=fraction*PJ*1e3/tonne
        else: 
            dato=0
        
        coun_year_dato.append([count,iso3,year,dato])
        coun_year_PJ.append([count,iso3,year,PJ])

        

df_historical_out = pd.DataFrame(coun_year_dato, columns=['Nation','iso_code3', 'Year',var_name])
df_enduse_complete = pd.DataFrame(coun_year_PJ,columns=['Nation','iso_code3','Year',subsector+' Total (PJ)'])

years_proj=range(max(years_hist)+1,2051)
coun_year_dato=[]

for iso3 in ISO3:
    count = df_gdp_hist.loc[df_gdp_hist['iso_code3']==iso3]['Nation'].values[0]
    for year in years_proj:
        
        tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==iso3)&
                                (df_ippu_all['Year']==year)][IPPU_var].values[0]

        
        if (count,year) in zip(df_pop_gdp_enduse['Nation'].values,df_pop_gdp_enduse['Year'].values):
            
            PJ=df_pop_gdp_enduse.loc[(df_pop_gdp_enduse['Nation'] ==count) & 
                        (df_pop_gdp_enduse['Year']== year), subsector+' Total (PJ)'].values[0]
        else:
            
            X_test = df_pop_gdp_all.loc[(df_pop_gdp_all['Nation'] == count) & 
                            (df_pop_gdp_all['Year']== year)][['population_gnrl_urban',
                                                              'population_gnrl_rural',
                                                              'gdp_mmm_usd']]
            PJ =linear_model.predict(X_test)[0]

            if PJ<0:
                PJ=0
                
        if tonne!=0:
            dato=fraction*PJ*1e3/tonne
        else: 
            dato=0
        
        coun_year_dato.append([count,iso3,year,dato])
        
df_projected_out = pd.DataFrame(coun_year_dato, columns=['Nation','iso_code3', 'Year',var_name])

In [9]:
df_enduse_complete

        Nation iso_code3  Year  Rubber and plastic [ISIC 22] Total (PJ)
0        Aruba       ABW  2011                                 0.772725
1        Aruba       ABW  2012                                 0.777936
2        Aruba       ABW  2013                                 0.783154
3        Aruba       ABW  2014                                 0.788345
4        Aruba       ABW  2015                                 0.793487
...        ...       ...   ...                                      ...
1715  Zimbabwe       ZWE  2016                                 9.280418
1716  Zimbabwe       ZWE  2017                                 9.418758
1717  Zimbabwe       ZWE  2018                                 9.547514
1718  Zimbabwe       ZWE  2019                                 9.672000
1719  Zimbabwe       ZWE  2020                                 9.795245

[1720 rows x 4 columns]

In [10]:
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Aruba,ABW,2011,0.199499
1,Aruba,ABW,2012,0.213689
2,Aruba,ABW,2013,0.217485
3,Aruba,ABW,2014,0.185381
4,Aruba,ABW,2015,0.151642
...,...,...,...,...
1715,Zimbabwe,ZWE,2016,0.092919
1716,Zimbabwe,ZWE,2017,0.089533
1717,Zimbabwe,ZWE,2018,0.062189
1718,Zimbabwe,ZWE,2019,0.081963
1719,Zimbabwe,ZWE,2020,0.086906

In [11]:
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_plastic
0,Aruba,ABW,2021,0.156730
1,Aruba,ABW,2022,0.148646
2,Aruba,ABW,2023,0.140978
3,Aruba,ABW,2024,0.133706
4,Aruba,ABW,2025,0.126808
...,...,...,...,...
5155,Zimbabwe,ZWE,2046,0.003864
5156,Zimbabwe,ZWE,2047,0.003431
5157,Zimbabwe,ZWE,2048,0.003046
5158,Zimbabwe,ZWE,2049,0.002704
5159,Zimbabwe,ZWE,2050,0.002401

In [12]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')
df_enduse_complete.to_csv('../row_data/'+subsector+'_Total_PJ'+'.csv')
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')