In [49]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_chemicals'

In [50]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [51]:
IPPU_folder = 'prodinit_ippu_chemicals_tonne'
IPPU_var = 'prodinit_ippu_chemicals_tonne'
df_ippu_hist = pd.read_csv(ggpdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(ggpdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & (df_ippu_hist['year']==y),][IPPU_var].values[0]
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & (df_ippu_proj['year']==y)][IPPU_var].values[0]
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_chemicals_tonne
0          RWA  2010                   25021.862322
1          RWA  2011                   13167.859628
2          RWA  2012                   21698.704320
3          RWA  2013                   18421.445977
4          RWA  2014                    9230.061846
...        ...   ...                            ...
7826       ATG  2046                      74.639711
7827       ATG  2047                      70.273672
7828       ATG  2048                      66.163023
7829       ATG  2049                      62.292827
7830       ATG  2050                      58.649017

[7831 rows x 3 columns]

In [52]:
#df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

df_eei

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Manufacturing [ISIC 10-18; 20-32],Oil and oil products (PJ) ...,117.58,91.59,88.38,111.41,122.11,129.29,133.41,...,161.91,179.86,155.11,155.37,118.72,106.86,97.51,101.08,100.39,97.74
1,Australia,Manufacturing [ISIC 10-18; 20-32],Gas (PJ) ...,314.61,339.39,338.58,343.29,352.22,325.43,322.22,...,330.12,325.92,339.72,346.59,334.74,322.67,309.67,311.85,298.23,303.55
2,Australia,Manufacturing [ISIC 10-18; 20-32],Coal and coal products (PJ) ...,231.33,201.89,178.75,209.41,223.34,226.59,225.07,...,230.37,191.49,184.76,177.97,170.35,197.53,208.32,205.26,196.51,190.24
3,Australia,Manufacturing [ISIC 10-18; 20-32],Biofuels and waste (PJ) ...,96.47,94.43,99.89,101.47,104.3,109.06,110.25,...,104.6,104.29,112.36,105.27,115.61,115.49,124.1,112.09,103.36,98.69
4,Australia,Manufacturing [ISIC 10-18; 20-32],Heat (PJ) ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,Uzbekistan,Construction [ISIC 41-43],Biofuels and waste (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9756,Uzbekistan,Construction [ISIC 41-43],Heat (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9757,Uzbekistan,Construction [ISIC 41-43],Electricity (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0.51,0.42,0.28,0.46,..,..,..
9758,Uzbekistan,Construction [ISIC 41-43],Other sources (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0.01,0,..,..,..
9759,Uzbekistan,Construction [ISIC 41-43],Total final energy use (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,6.85,6.54,6.23,9.44,..,..,..

In [53]:
#Cross Walk with IEA data:
industries_correspondence = {
  'electronics' : (0.5, 'Machinery [ISIC 25-28]'), #Electronics is ISIC 26 and 27, so let's say half of 25-28
  'plastic' : (0.5, 'Rubber and plastic [ISIC 22]'), # SEE BELOW
  'chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), #OK
  'cement' : (0.9, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'glass' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'other_product_manufacturing' : (1.0, 'Other manufacturing [ISIC 31-32]'), #OK
  'agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), #OK
  'textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), #SEE BELOW
  'rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), #+ AND 0.5  'Rubber and plastic [ISIC 22]'
  'metals' : (1.0, 'Basic metals [ISIC 24]'), #OK
  'lime_and_carbonite' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
  # REMOVE 'recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') #I propose we leave this out entirely, unless we are doing all recyclables
}

In [54]:
df_enduse = df_eei.loc[df_eei['ENDUSE']=='Chemicals and chemical products [ISIC 20-21]']
df_enduse = df_enduse[df_enduse['PRODUCT/FLOW'].str.startswith('Total final energy use (PJ)')]
mask = (df_enduse == '..').any(axis=1)
df_enduse = df_enduse.drop(index=df_enduse[mask].index)
df_enduse

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
47,Australia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),161.55,150.38,151.25,161.44,174.34,171.65,170.96,...,200.69,208.39,205,219.93,203.98,189.09,181.21,182.63,172.77,176.85
207,Austria,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),34.11,33.64,33.63,36.02,36.35,37.64,36.22,...,42.08,43.07,41.59,41.72,41.67,45.1,45.84,44.2,45.43,44.82
367,Belgium,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),131.87,131.33,131.58,133.87,118.12,125.16,126.94,...,165.13,168.82,175.09,179.92,179.85,180.34,173.97,175.44,166.52,167.24
527,Canada,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),277.92,248.81,245.84,226.22,253.12,242.45,261.29,...,302.38,299.12,310.18,310.14,299.75,287.21,265.75,259.87,257.65,255.14
687,Czech Republic,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),66.24,53.44,53.29,64,77.92,77.96,73.43,...,44.74,45.18,43.38,40.52,38.7,36.22,43.81,43.63,43.09,44.06
847,Denmark,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),11.31,12.04,11.68,11.2,10.53,10.72,10.07,...,11.21,11.82,11.23,10.85,10.65,11.44,11.47,10.33,9.91,10.13
1007,Estonia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),3.71,3.66,2.6,4.03,4.32,4.59,4.59,...,1.71,1.96,3.12,1.28,1.77,1.59,1.52,1.4,1.45,1.35
1167,Finland,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),35.78,36.46,38.16,41.7,42.05,39.6,39.09,...,42.77,41.91,44.1,40.92,41.12,42.47,39.4,42.28,41.21,39.78
1327,France,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),244.87,265.26,229.01,233.74,212.86,236.57,205.76,...,303.4,300.25,306.21,288.72,270.7,274.66,255.24,270.4,276.78,267.98
1487,Germany,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),466.39,453.75,459.4,510.69,501.61,516.11,556.71,...,632.41,633.4,610.93,619.55,638.21,628.2,659.04,619.64,586.27,600.11
1647,Greece,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),11.29,10.51,10.73,8.8,10.17,11.23,11.26,...,7.28,4.21,4.66,6.77,9.3,6.45,5.07,5.44,3.72,3.84
1807,Hungary,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),34.69,33.87,32.08,27.27,21.07,24.55,26.08,...,35.12,34.86,44.32,44.01,46.26,45.82,48.83,48.35,47.73,48.96
1967,Ireland,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),11.32,11.74,11.06,10.7,9.91,10.95,9.37,...,9.08,9.09,8.73,8.89,9.49,9.84,9.89,10.37,10.48,10.1
2127,Italy,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ) ...,258.01,222.45,222.4,241.29,232.28,227.12,216.86,...,171.59,171.89,172.91,155.58,137.83,146.81,152.99,152.65,146.37,142.79
2287,Japan,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ) ...,1054.14,1026.69,1032.9,985.64,1000.55,1014.2,1027.53,...,922.97,871.14,931.16,902.46,882.55,814.43,814.03,790.65,787.21,747.69
2447,Korea,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ) ...,265.27,263.13,254.17,279.44,309.21,319.38,318.94,...,381.46,359.77,382.89,386.6,344.68,333.25,357.83,375.26,366.39,381.03
2607,Lithuania,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),6.74,6.11,7.08,7.82,8.47,12.2,12.98,...,16.4,17.29,15.15,16.64,14.98,14.2,17.51,17.23,17.47,14.14
2767,Luxembourg,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),1.63,1.57,1.59,2.51,2.65,2.87,2.47,...,2.48,2.49,2.85,2.45,2.1,2.12,1.84,1.16,1.25,1.11
2975,Mexico,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),290.93,244.99,205.4,180.83,185.33,182.03,186.74,...,186.69,190.1,203.83,186.9,157.31,158.92,156.68,161.12,138.34,146.53
3087,Netherlands,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),305.26,309.25,326.61,337.92,343.29,342.34,334.75,...,306.94,317.83,312.5,307.89,300.07,319.79,318.03,311.31,303.96,315.46
3247,New Zealand,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),34.21,32.02,35.07,18.94,18.25,8.23,9.36,...,14.5,18.41,22.56,33.12,28.47,32.6,30.14,26.22,29.22,27.72
3407,Norway,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),48.81,46.43,40.26,56.83,56.85,56.51,57.17,...,59.57,57.23,58.14,60.95,62.33,59.16,57.89,59.91,60.73,63.65
3567,Poland,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),143.31,133.3,127.71,120.73,121.56,115.35,119.93,...,114.1,112.57,116.72,111.81,106.26,107.17,115.75,122.33,129.35,129.66
3727,Portugal,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),16.21,22.72,21.88,22.88,22.33,19.07,18.67,...,22.78,19.67,19.32,14.45,14.51,14.73,15.25,17.83,18.29,17.18
3887,Slovak Republic,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),25.51,25.02,27.32,22.2,19.42,20.97,17.34,...,13.72,17.71,12.51,11.39,16.48,17.05,17,22.71,21.5,21.92
4047,Spain,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ) ...,156.94,153.06,167.91,168.48,185.28,195.86,187.33,...,162.74,173.11,171.14,166.63,140.71,142.41,144.08,149.72,150.5,144.89
4207,Sweden,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),31.35,31.88,32.43,38.1,38.34,36.2,33.99,...,22.78,22.75,22.41,24.35,25.13,23.19,22.26,20.97,21.03,21.76
4367,Switzerland,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),26.45,27.67,27.46,29.35,29.76,31.91,32.64,...,30.63,34.43,31.98,28.47,28.95,30.32,29.94,29.73,29.31,28.03
4527,Republic of Türkiye,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),59.26,54.67,61.45,69.87,96.02,100.92,95.81,...,93.62,98.37,85.93,90.83,123.39,122.88,121.86,120.14,122.26,145.83
4687,United Kingdom,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),291.12,290.21,291.2,272.57,236.1,220.83,211.24,...,156.73,151.31,149.68,135.42,134.06,136.29,139.69,141.68,139.08,139.42
4847,United States,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),4055.64,3820.66,3806.26,3556.88,3554.1,3300.11,2714.27,...,2573.81,2457.27,2410.07,2557.16,2950.35,3083.65,3103.81,3205.34,3251.63,3241.18
5167,Brazil,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),268.8,266.12,276.13,274.05,297.52,298.6,308.32,...,311.49,302.99,292.49,280.88,287.84,282.33,293.86,289.28,279.47,244.28
5327,Morocco,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),1.42,2.78,2.82,3.28,4.97,5.33,5.47,...,6.55,6.72,6.49,6.34,6.37,6.23,7.18,7.09,7.16,6.67
5807,Chile,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ) ...,2.46,2.71,2.72,3.58,3,2.86,2.68,...,6.6,6.2,6.38,3.03,2.77,5.33,3.2,4.82,6.06,4.5
6127,Latvia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.62,0.74,0.74,0.72,0.69,0.73,0.8,...,0.97,1.01,1.06,1.02,0.98,0.98,1.09,1.12,0.89,0.89
6287,Albania,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.57,0.69,0.99,0.98,0.86,0.7,1.42,...,0.61,0.7,0.76,0.74,0.63,0.55,0.65,0.64,0.58,0.6
6447,Armenia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.78,0.68,0.47,0.35,0.51,0.54,0.75,...,0.25,0.26,0.27,0.3,0.2,0.12,0.14,0.14,0.15,0.15
7087,Bulgaria,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),56.66,57.44,46.79,50.21,50.12,50.13,48.12,...,36.89,34.17,32.69,34.35,36.9,35.64,38.25,35.14,33.29,32.26
7247,Croatia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),10.74,10.23,8.38,9.52,12.16,9.44,10.72,...,8.01,5.47,5.49,5.52,5.89,5.88,6.53,6.03,6.32,6.81
7407,Cyprus,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.06,0.07,0.07,0.07,0.08,0.09,0.09,...,0.1,0.16,0.13,0.22,0.28,0.26,0.27,0.3,0.32,0.32
8047,Kosovo,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,0.06,0.06,0.06,0.06,0.05,0.06,0.05,0.05,0.05,0.06
8527,Republic of Moldova,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.06,0.12,0.07,0.08,0.15,0.16,0.19,...,0.17,0.15,0.19,0.22,0.21,0.21,0.24,0.25,0.35,0.44
8687,Republic of North Macedonia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),0.35,0.46,0.5,0.46,0.44,0.45,0.45,...,0.41,0.31,0.29,0.26,0.39,0.35,0.4,0.39,0.42,0.42
8847,Romania,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),89.66,109.51,121.51,130.49,99.78,95.31,87.77,...,93.45,81.99,68.86,69.07,59.3,52.31,55.61,59.51,61.59,59.85
9007,Serbia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),3.37,5.81,6.77,7.1,16.73,25.37,24.82,...,19.48,18.38,14.41,12.95,14.23,18.26,19.31,16.22,15.13,14.6
9167,Slovenia,Chemicals and chemical products [ISIC 20-21],Total final energy use (PJ),4.86,4.46,4.77,7.65,7.62,7.04,7.19,...,6.55,6.23,6.26,6.35,6.69,6.83,6.86,6.37,6.45,6.62

In [55]:
years_hist=range(2010,2021)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 165.70195652173913,
 2011: 163.9804347826087,
 2012: 160.00478260869565,
 2013: 160.13304347826087,
 2014: 161.4702173913044,
 2015: 167.0508695652174,
 2016: 168.1030434782609,
 2017: 169.37521739130435,
 2018: 171.02804347826088,
 2019: 169.89413043478262,
 2020: 169.10478260869567}

In [56]:
sub_continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in sub_continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in sub_continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year     meanEEI
0    Australia and New Zealand  2010  104.680000
1    Australia and New Zealand  2011  107.595000
2    Australia and New Zealand  2012  113.400000
3    Australia and New Zealand  2013  113.780000
4    Australia and New Zealand  2014  126.525000
..                         ...   ...         ...
237             Western Europe  2016  211.504286
238             Western Europe  2017  211.985714
239             Western Europe  2018  207.411429
240             Western Europe  2019  201.360000
241             Western Europe  2020  203.535714

[121 rows x 3 columns]

In [57]:
#### HISTORICAL ######
iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_chemicals
0,Rwanda,RWA,2010,0
1,Rwanda,RWA,2011,0
2,Rwanda,RWA,2012,0
3,Rwanda,RWA,2013,0
4,Rwanda,RWA,2014,0
...,...,...,...,...
2096,Antigua and Barbuda,ATG,2016,0
2097,Antigua and Barbuda,ATG,2017,0
2098,Antigua and Barbuda,ATG,2018,0
2099,Antigua and Barbuda,ATG,2019,0
2100,Antigua and Barbuda,ATG,2020,0

In [58]:
for c,y in zip(df_historical_out['iso_code3'].values,df_historical_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y)].values[0])*1e3

        dato=tj/tonne
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y]*1e3
            
        dato=tj/tonne
        
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_chemicals
0,Rwanda,RWA,2010,6.622287
1,Rwanda,RWA,2011,12.453082
2,Rwanda,RWA,2012,7.373933
3,Rwanda,RWA,2013,8.692751
4,Rwanda,RWA,2014,17.493948
...,...,...,...,...
2096,Antigua and Barbuda,ATG,2016,437.735115
2097,Antigua and Barbuda,ATG,2017,510.429099
2098,Antigua and Barbuda,ATG,2018,478.560289
2099,Antigua and Barbuda,ATG,2019,311.268689
2100,Antigua and Barbuda,ATG,2020,502.057392

In [59]:
#### Projected ######

years_proj=range(max(years_hist)+1,2051)

iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        coun_year.append([count,iso3,year,0])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out[var_name]=0
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_chemicals
0,Rwanda,RWA,2021,0
1,Rwanda,RWA,2022,0
2,Rwanda,RWA,2023,0
3,Rwanda,RWA,2024,0
4,Rwanda,RWA,2025,0
...,...,...,...,...
5725,Antigua and Barbuda,ATG,2046,0
5726,Antigua and Barbuda,ATG,2047,0
5727,Antigua and Barbuda,ATG,2048,0
5728,Antigua and Barbuda,ATG,2049,0
5729,Antigua and Barbuda,ATG,2050,0

In [60]:
y_hist_max = max(years_hist)
for c,y in zip(df_projected_out['iso_code3'].values,df_projected_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y_hist_max)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y_hist_max), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y_hist_max]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_chemicals
0,Rwanda,RWA,2021,13.196372
1,Rwanda,RWA,2022,13.137124
2,Rwanda,RWA,2023,13.078143
3,Rwanda,RWA,2024,13.019425
4,Rwanda,RWA,2025,12.960972
...,...,...,...,...
5725,Antigua and Barbuda,ATG,2046,2265.614123
5726,Antigua and Barbuda,ATG,2047,2406.374662
5727,Antigua and Barbuda,ATG,2048,2555.880524
5728,Antigua and Barbuda,ATG,2049,2714.675049
5729,Antigua and Barbuda,ATG,2050,2883.335333

In [61]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [62]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')

In [63]:
#Mexico
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Mexico')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='MEX')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Mexico')]['2015'].values[0]
print('Mexico')
print(hist_val*ippu_val/1000,iea_val)

#Brazil
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Brazil')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='BRA')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Brazil')]['2015'].values[0]

print('Brazil')
print(hist_val*ippu_val/1000,iea_val)

#Chile
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Chile')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='CHL')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Chile')]['2015'].values[0]

print('Chile')

print(hist_val*ippu_val/1000,iea_val)

Mexico
157.31 157.31
Brazil
287.84 287.84
Chile
2.77 2.77

In [64]:
df_historical_out.loc[(df_historical_out['Nation']=='Mexico')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

0.033462924289028265

In [66]:
df_ippu_all.loc[(df_ippu_all['iso_code3']=='MEX')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

4701023.69539707