In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

# var_name=os.path.basename(parentdir)

# var_name


# #scoe crowss walk 
# scoe_energy_demands = {
#    consumpinit_scoe_gj_per_hh_residential_elec_appliances : [all but (residential space heating +residential cooking+ clothes dryers)]
#    consumpinit_scoe_gj_per_hh_residential_heat_energy : [residential space heating +residential cooking+ clothes dryers]
#    consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances : (share of electric in residential [0-1.0])*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy  (1- share of electri in residential)*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances :  (share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy (1-share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]


#  frac_scoe_X_coal : [Coal and coal products (PJ)      ]
#  frac_scoe_X_diesel : [0.4*Oil and oil products (PJ)      ]
#  frac_scoe_X_electricity : [Electricity (PJ)      ]
#  frac_scoe_X_gas_petroleum_liquid:  [0.4*Oil and oil products (PJ)      ]
#  frac_scoe_X_gasoline :  [0.1*Oil and oil products (PJ)      ]
#  frac_scoe_X_hydrocarbon_gas_liquids :  [0.1*Oil and oil products (PJ)      ]
#  frac_scoe_X_hydrogen : 0
#  frac_scoe_X_kerosene:  [Other sources (PJ)        ]
#  frac_scoe_X_natural_gas : [Gas (PJ) + Heat (PJ)              ]
#  frac_scoe_X_solid_biomass : [Biofuels and waste (PJ)   ]
 
#  frac_scoe_heat_energy_other_se_coal  frac_scoe_heat_energy_other_se_diesel 
#     frac_scoe_heat_energy_other_se_electricity 
# frac_scoe_heat_energy_other_se_gas_petroleum_liquid
#     frac_scoe_heat_energy_other_se_gasoline 
#     frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids 
#     frac_scoe_heat_energy_other_se_hydrogen 	 frac_scoe_heat_energy_other_se_kerosene 	
#     frac_scoe_heat_energy_other_se_natural_gas 	 frac_scoe_heat_energy_other_se_solid_biomass 
#     frac_scoe_heat_energy_residential_coal 	 frac_scoe_heat_energy_residential_diesel 
#     frac_scoe_heat_energy_residential_electricity 	 frac_scoe_heat_energy_residential_gas_petroleum_liquid 
#     frac_scoe_heat_energy_residential_gasoline 	 frac_scoe_heat_energy_residential_hydrocarbon_gas_liquids 
# frac_scoe_heat_energy_residential_hydrogen 	 frac_scoe_heat_energy_residential_kerosene 
#     frac_scoe_heat_energy_residential_natural_gas 	 frac_scoe_heat_energy_residential_solid_biomass

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [3]:
#Socioeconomic varibles

# # #GDP
# df_gdp_hist = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/historical/gdp_mmm_usd.csv')
# df_gdp_proj = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/projected/gdp_mmm_usd.csv')

# df_gdp_hist = df_gdp_hist.sort_values(['Nation','Year'])

# df_gdp_proj = df_gdp_proj.sort_values(['Nation','Year'])

# df_gdp_all=pd.concat([df_gdp_hist,df_gdp_proj])

# df_gdp_all

# #Rural population
# df_popru_hist = pd.read_csv(ggpdir+
#         '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/historical/population_gnrl_rural.csv')
# df_popru_proj = pd.read_csv(ggpdir+
#         '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/projected/population_gnrl_rural.csv')

# df_popru_hist = df_popru_hist.sort_values(['Nation','Year'])

# df_popru_proj = df_popru_proj.sort_values(['Nation','Year'])

# df_popru_all=pd.concat([df_popru_hist,df_popru_proj])

# df_popru_all
# #Urban population
# df_popur_hist = pd.read_csv(ggpdir+
#         '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/historical/population_gnrl_urban.csv')
# df_popur_proj = pd.read_csv(ggpdir+
#         '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/projected/population_gnrl_urban.csv')

# df_popur_hist = df_popur_hist.sort_values(['Nation','Year'])

# df_popur_proj = df_popur_proj.sort_values(['Nation','Year'])

# df_popur_all=pd.concat([df_popur_hist,df_popur_proj])

# df_popur_all

# df_pop_ru_ur=df_popru_all.merge(df_popur_all,on=['Nation','Year','iso_code3'])

# df_pop_ru_ur

# df_pop_gdp_all=df_gdp_all.merge(df_pop_ru_ur,on=['Nation','Year','iso_code3'])

# df_pop_gdp_all

In [4]:
# No funciona:
# df_pop_gdp_all[df_pop_gdp_all['iso_code3']=='ABW']

In [5]:
#Socioeconomic varibles

#GDP
df_gdp_hist = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/historical/gdp_mmm_usd.csv')
df_gdp_proj = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/projected/gdp_mmm_usd.csv')

nation_gdp = sorted(set(df_gdp_proj['Nation'].values))

years_all = range(min(df_gdp_hist['Year'].values),max(df_gdp_proj['Year'].values)+1)
c_y_gdp = []
for c in nation_gdp:
    for y in years_all:
    
        try:
            gdp = df_gdp_hist.loc[(df_gdp_hist['Nation']==c) & (df_gdp_hist['Year']==y),]['gdp_mmm_usd'].values[0]
            
        except:
            gdp = df_gdp_proj.loc[(df_gdp_proj['Nation']==c) & (df_gdp_proj['Year']==y)]['gdp_mmm_usd'].values[0]
            
        c_y_gdp.append([c,y,gdp])

df_gdp_all = pd.DataFrame(c_y_gdp,columns=['Nation', 'Year', 'gdp_mmm_usd'])



#Rural population
df_popru_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/historical/population_gnrl_rural.csv')
df_popru_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/projected/population_gnrl_rural.csv')

#Urban population
df_popur_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/historical/population_gnrl_urban.csv')
df_popur_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/projected/population_gnrl_urban.csv')

nation_pop = sorted(set(df_popur_proj['Nation'].values))

years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop = []
for c in nation_pop:
    for y in years_all:
    
        try:
            pop_ur = df_popur_hist.loc[(df_popur_hist['Nation']==c) &
                                       (df_popur_hist['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_hist.loc[(df_popru_hist['Nation']==c) &
                                       (df_popru_hist['Year']==y),]['population_gnrl_rural'].values[0]
            
        except:
            pop_ur = df_popur_proj.loc[(df_popur_proj['Nation']==c) &
                                       (df_popur_proj['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_proj.loc[(df_popru_proj['Nation']==c) &
                                       (df_popru_proj['Year']==y),]['population_gnrl_rural'].values[0]
            
        c_y_pop.append([c,y,pop_ur,pop_ru])

df_pop_all = pd.DataFrame(c_y_pop,columns=['Nation', 'Year', 'population_gnrl_urban','population_gnrl_rural'])

#All Together
nation_pop_gdp = sorted(set(nation_pop).intersection(set(nation_gdp)))
years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop_gdp = []
for c in nation_pop_gdp:
    iso3 = df_gdp_hist.loc[df_gdp_hist['Nation']==c]['iso_code3'].values[0]
    for y in years_all:
        pop_ur = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_urban'].values[0]
        
        pop_ru = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_rural'].values[0]
        
        gdp = df_gdp_all.loc[(df_gdp_all['Nation']==c) & (df_gdp_all['Year']==y)]['gdp_mmm_usd'].values[0]
        
        c_y_pop_gdp.append([c,iso3,y,pop_ur,pop_ru,gdp])
df_pop_gdp_all = pd.DataFrame(c_y_pop_gdp,columns=['Nation','iso_code3', 'Year',
                                                   'population_gnrl_urban',
                                                   'population_gnrl_rural',
                                                   'gdp_mmm_usd'])
df_pop_gdp_all

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010
...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404

In [6]:
# Si funciona
# df_pop_gdp_all[df_pop_gdp_all['iso_code3']=='ABW']

In [7]:
mean_gdp=np.mean(df_pop_gdp_all['gdp_mmm_usd'].values)
df_pop_gdp_all['gdp_class']= df_pop_gdp_all['gdp_mmm_usd'].apply(lambda x: 1 if x >= mean_gdp else 2)
df_pop_gdp_all

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,gdp_class
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178,2
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386,2
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594,2
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802,2
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010,2
...,...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002,2
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852,2
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703,2
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553,2
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404,2

In [8]:
mypath='../row_data'
files_in_row_data = [f for f in os.listdir(mypath)]
files_in_row_data

['frac_scoe_heat_energy_proportion.xlsx',
 'IEA - Energy Efficiency Indicators database - Extended (December 2022).xlsb',
 '~$frac_scoe_heat_energy_proportion.xlsx',
 'WorldEnergyBalancesHighlights2021.xlsx',
 'Complete_IEA',
 'Countries_ISO3.csv']

In [9]:
mypath=grandparentdir
scoe_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_scoe_')])
scoe_vars

['frac_scoe_heat_energy_commercial_municipal_coal',
 'frac_scoe_heat_energy_commercial_municipal_diesel',
 'frac_scoe_heat_energy_commercial_municipal_electricity',
 'frac_scoe_heat_energy_commercial_municipal_gasoline',
 'frac_scoe_heat_energy_commercial_municipal_hydrocarbon_gas_liquids',
 'frac_scoe_heat_energy_commercial_municipal_hydrogen',
 'frac_scoe_heat_energy_commercial_municipal_kerosene',
 'frac_scoe_heat_energy_commercial_municipal_natural_gas',
 'frac_scoe_heat_energy_commercial_municipal_solid_biomass',
 'frac_scoe_heat_energy_other_se_coal',
 'frac_scoe_heat_energy_other_se_diesel',
 'frac_scoe_heat_energy_other_se_electricity',
 'frac_scoe_heat_energy_other_se_gasoline',
 'frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids',
 'frac_scoe_heat_energy_other_se_hydrogen',
 'frac_scoe_heat_energy_other_se_kerosene',
 'frac_scoe_heat_energy_other_se_natural_gas',
 'frac_scoe_heat_energy_other_se_solid_biomass',
 'frac_scoe_heat_energy_residential_coal',
 'frac_scoe_heat_energy_residential_diesel',
 'frac_scoe_heat_energy_residential_electricity',
 'frac_scoe_heat_energy_residential_gas_petroleum_liquid',
 'frac_scoe_heat_energy_residential_gasoline',
 'frac_scoe_heat_energy_residential_hydrocarbon_gas_liquids',
 'frac_scoe_heat_energy_residential_hydrogen',
 'frac_scoe_heat_energy_residential_kerosene',
 'frac_scoe_heat_energy_residential_natural_gas',
 'frac_scoe_heat_energy_residential_solid_biomass']

In [10]:
# df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

df_energy=pd.read_excel('../row_data/IEA - Energy Efficiency Indicators database - Extended (December 2022).xlsb',
                        engine='pyxlsb',sheet_name='Services - Energy',skiprows=[0])
df_energy=df_energy.replace('..',0)
# df_energy['End use'].unique()
df_energy

,Country,End use,Product,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Total Services,Oil and oil products (PJ) ...,19.38,18.15,19.57,18.34,20.16,20.17,23.21,...,27.97,30.11,31.19,32.25,32.66,29.83,30.91,30.72,26.98,27.23
1,Australia,Total Services,Gas (PJ) ...,45.00,38.97,39.51,39.60,39.93,40.17,38.88,...,45.63,45.63,45.54,49.26,50.85,52.20,53.10,53.73,53.46,51.57
2,Australia,Total Services,Coal and coal products (PJ) ...,1.14,3.80,3.61,3.68,2.49,2.87,2.16,...,0.95,0.86,0.87,1.05,0.19,0.29,0.48,0.51,0.58,0.79
3,Australia,Total Services,Biofuels and waste (PJ) ...,1.90,0.40,0.40,0.60,0.63,0.84,0.95,...,1.10,1.50,1.80,2.10,2.00,0.79,0.90,0.80,0.60,0.50
4,Australia,Total Services,Heat (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2851,Uruguay,"Arts, entertainment and recreation [ISIC 90-93]",Other sources (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2852,Uruguay,"Arts, entertainment and recreation [ISIC 90-93]",Total final energy use (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2853,Uruguay,Other services [ISIC 33; 45; 94-96],Electricity (PJ) ...,2.93,3.00,2.96,2.94,3.07,3.14,3.72,...,4.60,4.84,4.92,4.87,4.77,4.96,4.85,5.10,0.00,0.00
2854,Uruguay,Other services [ISIC 33; 45; 94-96],Other sources (PJ) ...,0.57,0.52,0.53,0.53,0.59,0.61,0.62,...,0.69,0.66,0.70,0.65,0.64,0.67,0.59,0.55,0.00,0.00
2855,Uruguay,Other services [ISIC 33; 45; 94-96],Total final energy use (PJ) ...,3.50,3.52,3.49,3.47,3.67,3.75,4.34,...,5.29,5.50,5.62,5.52,5.41,5.63,5.44,5.65,0.00,0.00

In [11]:
heat_enduse=['Residential space heating','Residential cooking','Clothes dryers']

# df_energy_heat=df_energy[df_energy['End use'].isin(heat_enduse)]

df_energy_building=df_energy[df_energy['End use']=='Other building energy use']

'Other building energy use'

# df_energy_heat['Product'].unique()

Products=['Oil and oil products (PJ)',
       'Gas (PJ)',
       'Coal and coal products (PJ)',
       'Biofuels and waste (PJ)',
       'Heat (PJ)',
       'Electricity (PJ)',
       'Other sources (PJ)',
       'Total final energy use (PJ)']
df_energy_building[df_energy_building['Country']=='Albania']

,Country,End use,Product,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2060,Albania,Other building energy use,Oil and oil products (PJ) ...,1.74,1.91,1.19,3.00,1.35,2.13,2.71,...,1.14,0.51,1.41,1.64,1.98,2.02,2.54,2.66,2.64,2.22
2061,Albania,Other building energy use,Gas (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2062,Albania,Other building energy use,Coal and coal products (PJ) ...,0.00,0.00,0.08,0.09,0.21,0.12,0.12,...,0.05,0.04,0.16,0.14,0.12,0.15,0.14,0.14,0.18,0.14
2063,Albania,Other building energy use,Biofuels and waste (PJ) ...,1.62,1.61,1.05,2.14,0.50,0.42,0.42,...,0.67,1.03,0.82,0.47,0.94,0.91,0.78,0.60,0.82,0.87
2064,Albania,Other building energy use,Heat (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2065,Albania,Other building energy use,Electricity (PJ) ...,2.25,1.97,2.01,4.06,6.03,5.87,2.64,...,4.67,4.76,5.32,4.94,4.94,4.15,5.24,5.38,5.66,4.82
2066,Albania,Other building energy use,Other sources (PJ) ...,0.00,0.00,0.04,0.03,0.02,0.05,0.05,...,0.25,0.25,0.26,0.28,0.23,0.23,0.21,0.21,0.22,0.19
2067,Albania,Other building energy use,Total final energy use (PJ) ...,5.61,5.49,4.36,9.32,8.10,8.59,5.94,...,6.84,6.58,7.96,7.47,8.20,7.47,8.91,8.98,9.53,8.24

In [12]:
nation_enduse = df_energy_building['Country'].values
nation_pop_gdp_all=df_pop_gdp_all['Nation'].unique()

nation_pop_gdp_enduse = sorted(set(nation_pop_gdp_all).intersection(set(nation_enduse)))
years_hist = range(2011,2019+1)

c_y = []
for c in nation_pop_gdp_enduse:
    for y in years_hist:
        c_y.append([c,y])

df_energy_products=pd.DataFrame(c_y,columns=['Nation','Year'])
      
for product in Products:
    
    df_energy_products[product]=0
    
    for c in nation_pop_gdp_enduse:
        for y in years_hist:
            prod_val=0
            try:
                prod_val+=df_energy_building[(df_energy_building['Product'].str.startswith(product))&
                          (df_energy_building['Country']==c)][y].values[0]
            # some End Use does not have all products specified, those are taken to be 0 by passing
            except:
                pass
            df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),product]=prod_val
    
df_energy_products

,Nation,Year,Oil and oil products (PJ),Gas (PJ),Coal and coal products (PJ),Biofuels and waste (PJ),Heat (PJ),Electricity (PJ),Other sources (PJ),Total final energy use (PJ)
0,Albania,2011,1.14,0.06,0.05,0.67,0.0,4.67,0.25,6.84
1,Albania,2012,0.51,0.00,0.04,1.03,0.0,4.76,0.25,6.58
2,Albania,2013,1.41,0.00,0.16,0.82,0.0,5.32,0.26,7.96
3,Albania,2014,1.64,0.00,0.14,0.47,0.0,4.94,0.28,7.47
4,Albania,2015,1.98,0.00,0.12,0.94,0.0,4.94,0.23,8.20
...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,2015,0.64,0.40,0.00,0.93,0.0,5.54,0.00,7.50
446,Uruguay,2016,0.72,0.40,0.00,0.93,0.0,5.81,0.00,7.86
447,Uruguay,2017,0.61,0.42,0.00,0.94,0.0,5.69,0.00,7.66
448,Uruguay,2018,0.62,0.45,0.00,0.94,0.0,6.05,0.00,8.06
449,Uruguay,2019,0.93,0.42,0.00,0.94,0.0,10.55,0.00,12.85

In [13]:
for c in df_energy_products['Nation'].unique():
    for y in df_energy_products['Year'].unique():
        for product in Products:
            prod_val=df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),'Total final energy use (PJ)'].values[0]
            if prod_val==0:
                val=np.mean(df_energy_products[df_energy_products['Nation']==c][product].values)
                
                df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),product]=val
df_energy_products

,Nation,Year,Oil and oil products (PJ),Gas (PJ),Coal and coal products (PJ),Biofuels and waste (PJ),Heat (PJ),Electricity (PJ),Other sources (PJ),Total final energy use (PJ)
0,Albania,2011,1.14,0.06,0.05,0.67,0.0,4.67,0.25,6.84
1,Albania,2012,0.51,0.00,0.04,1.03,0.0,4.76,0.25,6.58
2,Albania,2013,1.41,0.00,0.16,0.82,0.0,5.32,0.26,7.96
3,Albania,2014,1.64,0.00,0.14,0.47,0.0,4.94,0.28,7.47
4,Albania,2015,1.98,0.00,0.12,0.94,0.0,4.94,0.23,8.20
...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,2015,0.64,0.40,0.00,0.93,0.0,5.54,0.00,7.50
446,Uruguay,2016,0.72,0.40,0.00,0.93,0.0,5.81,0.00,7.86
447,Uruguay,2017,0.61,0.42,0.00,0.94,0.0,5.69,0.00,7.66
448,Uruguay,2018,0.62,0.45,0.00,0.94,0.0,6.05,0.00,8.06
449,Uruguay,2019,0.93,0.42,0.00,0.94,0.0,10.55,0.00,12.85

In [14]:
#Drop countries if all values are 0
# for c in df_energy_products['Nation'].unique():
#     val=0
#     for product in Products:
#         val+=np.mean(df_energy_products[df_energy_products['Nation']==c][product].values)
#     if val==0:
#         df_energy_products=df_energy_products.drop(df_energy_products[df_energy_products['Nation']==c].index)

df_energy_products['Nation'].unique()

array(['Albania', 'Argentina', 'Australia', 'Austria', 'Azerbaijan',
       'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Brazil',
       'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Georgia', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy',
       'Japan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Mexico',
       'Morocco', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Serbia', 'Slovak Republic', 'Slovenia',
       'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Ukraine',
       'United Kingdom', 'United States', 'Uruguay'], dtype=object)

In [15]:
# #  frac_scoe_X_coal : [Coal and coal products (PJ)      ]
# #  frac_scoe_X_diesel : [0.4*Oil and oil products (PJ)      ]
# #  frac_scoe_X_electricity : [Electricity (PJ)      ]
# #  frac_scoe_X_gas_petroleum_liquid:  [0.4*Oil and oil products (PJ)      ] Missing for this sisepuede variable
# #  frac_scoe_X_gasoline :  [0.1*Oil and oil products (PJ)      ]
# #  frac_scoe_X_hydrocarbon_gas_liquids :  [0.1*Oil and oil products (PJ)      ]
# #  frac_scoe_X_hydrogen : 0
# #  frac_scoe_X_kerosene:  [Other sources (PJ)        ]
# #  frac_scoe_X_natural_gas : [Gas (PJ) + Heat (PJ)              ]
# #  frac_scoe_X_solid_biomass : [Biofuels and waste (PJ)   ]

# #  frac_scoe_X_coal : [Coal and coal products (PJ)      ]
# #  frac_scoe_X_diesel : [0.6*Oil and oil products (PJ)      ]
# #  frac_scoe_X_electricity : [Electricity (PJ)      ]
# #  frac_scoe_X_gasoline :  [0.2*Oil and oil products (PJ)      ]
# #  frac_scoe_X_hydrocarbon_gas_liquids :  [0.2*Oil and oil products (PJ)      ]
# #  frac_scoe_X_hydrogen : 0
# #  frac_scoe_X_kerosene:  [Other sources (PJ)        ]
# #  frac_scoe_X_natural_gas : [Gas (PJ) + Heat (PJ)              ]
# #  frac_scoe_X_solid_biomass : [Biofuels and waste (PJ)   ]

# # 'frac_scoe_heat_energy_commercial_municipal_coal',
# # 'frac_scoe_heat_energy_commercial_municipal_diesel',
# # 'frac_scoe_heat_energy_commercial_municipal_electricity',
# # 'frac_scoe_heat_energy_commercial_municipal_gasoline',
# # 'frac_scoe_heat_energy_commercial_municipal_hydrocarbon_gas_liquids',
# # 'frac_scoe_heat_energy_commercial_municipal_hydrogen',
# # 'frac_scoe_heat_energy_commercial_municipal_kerosene',
# # 'frac_scoe_heat_energy_commercial_municipal_natural_gas',
# # 'frac_scoe_heat_energy_commercial_municipal_solid_biomass'

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_coal']=df_energy_products.apply(
# lambda row:
# row['Coal and coal products (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 , axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_diesel']=df_energy_products.apply(
# lambda row:
# 0.6*row['Oil and oil products (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_electricity']=df_energy_products.apply(
# lambda row:
# row['Electricity (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_gasoline']=df_energy_products.apply(
# lambda row:
# 0.2*row['Oil and oil products (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_hydrocarbon_gas_liquids']=df_energy_products.apply(
# lambda row:
# 0.2*row['Oil and oil products (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_hydrogen']=df_energy_products.apply(
# lambda row:
# 0*row['Oil and oil products (PJ)'] / 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_kerosene']=df_energy_products.apply(
# lambda row:
# row['Other sources (PJ)']/ 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_natural_gas']=df_energy_products.apply(
# lambda row:
# (row['Gas (PJ)']+row['Heat (PJ)'])/ 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# ) if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 ,axis=1)

# df_energy_products['frac_scoe_heat_energy_commercial_municipal_solid_biomass']=df_energy_products.apply(
# lambda row:
# row['Biofuels and waste (PJ)']/ 
# (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']) 

#     if (row['Coal and coal products (PJ)']+0.4*row['Oil and oil products (PJ)']+row['Electricity (PJ)']
# +0.4*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']+0.1*row['Oil and oil products (PJ)']
# +row['Other sources (PJ)']+row['Gas (PJ)']+row['Heat (PJ)']+row['Biofuels and waste (PJ)']
# )!=0 else 0 
# ,axis=1)

# df_energy_products

In [16]:
# Cross Walk with IEA Fuel products

# frac_scoe_X_coal : [Coal and coal products (PJ)      ]
#  frac_scoe_X_diesel : [0.6*Oil and oil products (PJ)      ]
#  frac_scoe_X_electricity : [Electricity (PJ)      ]
#  frac_scoe_X_gasoline :  [0.2*Oil and oil products (PJ)      ]
#  frac_scoe_X_hydrocarbon_gas_liquids :  [0.2*Oil and oil products (PJ)      ]
#  frac_scoe_X_hydrogen : 0
#  frac_scoe_X_kerosene:  [Other sources (PJ)        ]
#  frac_scoe_X_natural_gas : [Gas (PJ) + Heat (PJ)              ]
#  frac_scoe_X_solid_biomass : [Biofuels and waste (PJ)   ]

# 'frac_scoe_heat_energy_other_se_coal',
# 'frac_scoe_heat_energy_other_se_diesel',
# 'frac_scoe_heat_energy_other_se_electricity',
# 'frac_scoe_heat_energy_other_se_gasoline',
# 'frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids',
# 'frac_scoe_heat_energy_other_se_hydrogen',
# 'frac_scoe_heat_energy_other_se_kerosene',
# 'frac_scoe_heat_energy_other_se_natural_gas',
# 'frac_scoe_heat_energy_other_se_solid_biomass'

cross_walk_dict={'frac_scoe_heat_energy_other_se_coal':[(1,'Coal and coal products (PJ)')],
'frac_scoe_heat_energy_other_se_diesel': [(0.6,'Oil and oil products (PJ)')],
'frac_scoe_heat_energy_other_se_electricity':[(1,'Electricity (PJ)')],
'frac_scoe_heat_energy_other_se_gasoline':[(0.2,'Oil and oil products (PJ)')],
'frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids':[(0.2,'Oil and oil products (PJ)')],
'frac_scoe_heat_energy_other_se_hydrogen':[(0,'Oil and oil products (PJ)')],
'frac_scoe_heat_energy_other_se_kerosene':[(0.4,'Other sources (PJ)')],
'frac_scoe_heat_energy_other_se_natural_gas': [(1,'Gas (PJ)'),(1,'Heat (PJ)')],
'frac_scoe_heat_energy_other_se_solid_biomass':[(1,'Biofuels and waste (PJ)')]}

for c in df_energy_products['Nation'].unique():
    for y in df_energy_products['Year'].unique():
        
        total_energy=0
        
        for ssp_var in cross_walk_dict.keys():    
            for (frac,product) in cross_walk_dict[ssp_var]:
                
                total_energy+=frac*df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),product].values[0]
                
        df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),'Pseudo Total (PJ)']=total_energy
        
        for ssp_var in cross_walk_dict.keys():
            var_energy=0
            for (frac,product) in cross_walk_dict[ssp_var]:
                
                var_energy+=frac*df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),product].values[0]
            total_ener=df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),'Pseudo Total (PJ)'].values[0]
            if  total_ener!=0:   
                df_energy_products.loc[(df_energy_products['Nation']==c)&
                              (df_energy_products['Year']==y),ssp_var]=var_energy/total_ener
            else:
                df_energy_products.loc[(df_energy_products['Nation']==c)&
                              (df_energy_products['Year']==y),ssp_var]=0
df_energy_products

,Nation,Year,Oil and oil products (PJ),Gas (PJ),Coal and coal products (PJ),Biofuels and waste (PJ),Heat (PJ),Electricity (PJ),Other sources (PJ),Total final energy use (PJ),Pseudo Total (PJ),frac_scoe_heat_energy_other_se_coal,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass
0,Albania,2011,1.14,0.06,0.05,0.67,0.0,4.67,0.25,6.84,6.690,0.007474,0.102242,0.698057,0.034081,0.034081,0.0,0.014948,0.008969,0.100149
1,Albania,2012,0.51,0.00,0.04,1.03,0.0,4.76,0.25,6.58,6.440,0.006211,0.047516,0.739130,0.015839,0.015839,0.0,0.015528,0.000000,0.159938
2,Albania,2013,1.41,0.00,0.16,0.82,0.0,5.32,0.26,7.96,7.814,0.020476,0.108267,0.680829,0.036089,0.036089,0.0,0.013309,0.000000,0.104940
3,Albania,2014,1.64,0.00,0.14,0.47,0.0,4.94,0.28,7.47,7.302,0.019173,0.134758,0.676527,0.044919,0.044919,0.0,0.015338,0.000000,0.064366
4,Albania,2015,1.98,0.00,0.12,0.94,0.0,4.94,0.23,8.20,8.072,0.014866,0.147175,0.611992,0.049058,0.049058,0.0,0.011397,0.000000,0.116452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,2015,0.64,0.40,0.00,0.93,0.0,5.54,0.00,7.50,7.510,0.000000,0.051132,0.737683,0.017044,0.017044,0.0,0.000000,0.053262,0.123835
446,Uruguay,2016,0.72,0.40,0.00,0.93,0.0,5.81,0.00,7.86,7.860,0.000000,0.054962,0.739186,0.018321,0.018321,0.0,0.000000,0.050891,0.118321
447,Uruguay,2017,0.61,0.42,0.00,0.94,0.0,5.69,0.00,7.66,7.660,0.000000,0.047781,0.742820,0.015927,0.015927,0.0,0.000000,0.054830,0.122715
448,Uruguay,2018,0.62,0.45,0.00,0.94,0.0,6.05,0.00,8.06,8.060,0.000000,0.046154,0.750620,0.015385,0.015385,0.0,0.000000,0.055831,0.116625
449,Uruguay,2019,0.93,0.42,0.00,0.94,0.0,10.55,0.00,12.85,12.840,0.000000,0.043458,0.821651,0.014486,0.014486,0.0,0.000000,0.032710,0.073209

In [17]:
# select the columns with names starting with 'frac'
frac_cols = df_energy_products.filter(regex='^frac')

# calculate the sum of each row in the selected columns
frac_sum = frac_cols.sum(axis=1)
frac_sum

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
445    1.0
446    1.0
447    1.0
448    1.0
449    1.0
Length: 450, dtype: float64

In [18]:
df_energy_products_gdp_class=df_energy_products.merge(df_pop_gdp_all[['Nation','Year','gdp_mmm_usd','gdp_class']],on=['Nation','Year'])
df_energy_products_gdp_class

,Nation,Year,Oil and oil products (PJ),Gas (PJ),Coal and coal products (PJ),Biofuels and waste (PJ),Heat (PJ),Electricity (PJ),Other sources (PJ),Total final energy use (PJ),...,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass,gdp_mmm_usd,gdp_class
0,Albania,2011,1.14,0.06,0.05,0.67,0.0,4.67,0.25,6.84,...,0.102242,0.698057,0.034081,0.034081,0.0,0.014948,0.008969,0.100149,21.159910,2
1,Albania,2012,0.51,0.00,0.04,1.03,0.0,4.76,0.25,6.58,...,0.047516,0.739130,0.015839,0.015839,0.0,0.015528,0.000000,0.159938,21.865577,2
2,Albania,2013,1.41,0.00,0.16,0.82,0.0,5.32,0.26,7.96,...,0.108267,0.680829,0.036089,0.036089,0.0,0.013309,0.000000,0.104940,22.571244,2
3,Albania,2014,1.64,0.00,0.14,0.47,0.0,4.94,0.28,7.47,...,0.134758,0.676527,0.044919,0.044919,0.0,0.015338,0.000000,0.064366,23.276911,2
4,Albania,2015,1.98,0.00,0.12,0.94,0.0,4.94,0.23,8.20,...,0.147175,0.611992,0.049058,0.049058,0.0,0.011397,0.000000,0.116452,23.982578,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,2015,0.64,0.40,0.00,0.93,0.0,5.54,0.00,7.50,...,0.051132,0.737683,0.017044,0.017044,0.0,0.000000,0.053262,0.123835,51.626567,2
446,Uruguay,2016,0.72,0.40,0.00,0.93,0.0,5.81,0.00,7.86,...,0.054962,0.739186,0.018321,0.018321,0.0,0.000000,0.050891,0.118321,52.159029,2
447,Uruguay,2017,0.61,0.42,0.00,0.94,0.0,5.69,0.00,7.66,...,0.047781,0.742820,0.015927,0.015927,0.0,0.000000,0.054830,0.122715,52.691490,2
448,Uruguay,2018,0.62,0.45,0.00,0.94,0.0,6.05,0.00,8.06,...,0.046154,0.750620,0.015385,0.015385,0.0,0.000000,0.055831,0.116625,53.223952,2
449,Uruguay,2019,0.93,0.42,0.00,0.94,0.0,10.55,0.00,12.85,...,0.043458,0.821651,0.014486,0.014486,0.0,0.000000,0.032710,0.073209,53.756413,2

In [19]:
df_energy_products_gdp_class_1=df_energy_products_gdp_class[df_energy_products_gdp_class['gdp_class']==1]
df_energy_products_gdp_class_2=df_energy_products_gdp_class[df_energy_products_gdp_class['gdp_class']==2]

nation_gdp_class_1=df_pop_gdp_all[df_pop_gdp_all['gdp_class']==1]['Nation'].unique()
nation_gdp_class_2=df_pop_gdp_all[df_pop_gdp_all['gdp_class']==2]['Nation'].unique()


# frac_vars=[
# 'frac_scoe_heat_energy_commercial_municipal_coal',
# 'frac_scoe_heat_energy_commercial_municipal_diesel',
# 'frac_scoe_heat_energy_commercial_municipal_electricity',
# 'frac_scoe_heat_energy_commercial_municipal_gasoline',
# 'frac_scoe_heat_energy_commercial_municipal_hydrocarbon_gas_liquids',
# 'frac_scoe_heat_energy_commercial_municipal_hydrogen',
# 'frac_scoe_heat_energy_commercial_municipal_kerosene',
# 'frac_scoe_heat_energy_commercial_municipal_natural_gas',
# 'frac_scoe_heat_energy_commercial_municipal_solid_biomass']

frac_vars=cross_walk_dict.keys()


#Class 1

mean_frac_vect=[]
for frac_var in frac_vars:
    mean_frac_vect.append(np.mean(df_energy_products_gdp_class_1[frac_var].values))
    
class_1_mean_val_df=pd.DataFrame([mean_frac_vect],columns=frac_vars)

# define a custom function to normalize the row values
def normalize(row):
#     norm = np.linalg.norm(row)
    norm = np.sum(row)
    if norm == 0:
        return row
    else:
        return row / norm

# apply the custom function to each row of the DataFrame
class_1_mean_val_df = class_1_mean_val_df.apply(normalize, axis=1)

print( class_1_mean_val_df.apply(sum, axis=1))

class_1_mean_val_df['gpd_class']=1

class_1_mean_val_df

0    1.0
dtype: float64

,frac_scoe_heat_energy_other_se_coal,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass,gpd_class
0,0.007976,0.065392,0.66651,0.021797,0.021797,0.0,0.002752,0.189945,0.023829,1

In [20]:
#Class 2

mean_frac_vect=[]
for frac_var in frac_vars:
    mean_frac_vect.append(np.mean(df_energy_products_gdp_class_2[frac_var].values))
    
class_2_mean_val_df=pd.DataFrame([mean_frac_vect],columns=frac_vars)

# define a custom function to normalize the row values
def normalize(row):
#     norm = np.linalg.norm(row)
    norm = np.sum(row)
    if norm == 0:
        return row
    else:
        return row / norm

# apply the custom function to each row of the DataFrame
class_2_mean_val_df = class_1_mean_val_df.apply(normalize, axis=1)

print( class_2_mean_val_df.apply(sum, axis=1))

class_2_mean_val_df['gpd_class']=1

class_2_mean_val_df

0    1.0
dtype: float64

,frac_scoe_heat_energy_other_se_coal,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass,gpd_class
0,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915,1

In [21]:
nation_pop_gdp_all=df_pop_gdp_all['Nation'].unique()
df_pop_gdp_all_hist=df_pop_gdp_all[df_pop_gdp_all['Year']<2020].copy()
for c in nation_pop_gdp_all:
    for y in years_hist:
        for frac_var in frac_vars:
#              df_pop_gdp_all_copy[frac_var]=0
            if (c,y) in zip(df_energy_products['Nation'].values,
                            df_energy_products['Year'].values):
                
                val=df_energy_products.loc[(df_energy_products['Nation']==c)&
                                  (df_energy_products['Year']==y),frac_var].values[0]
                
                df_pop_gdp_all_hist.loc[(df_pop_gdp_all_hist['Nation']==c)&
                                  (df_pop_gdp_all_hist['Year']==y),frac_var]=val
            else:
                if c in nation_gdp_class_1:
                    df_pop_gdp_all_hist.loc[(df_pop_gdp_all_hist['Nation']==c)&
                                  (df_pop_gdp_all_hist['Year']==y),frac_var]=class_1_mean_val_df[frac_var].values[0]
                if c in nation_gdp_class_2:
                    df_pop_gdp_all_hist.loc[(df_pop_gdp_all_hist['Nation']==c)&
                                  (df_pop_gdp_all_hist['Year']==y),frac_var]=class_2_mean_val_df[frac_var].values[0]
df_pop_gdp_all_hist

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,gdp_class,frac_scoe_heat_energy_other_se_coal,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7244,Zimbabwe,ZWE,2015,4.473872e+06,9.340770e+06,6.769741,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7245,Zimbabwe,ZWE,2016,4.531238e+06,9.499100e+06,6.756399,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7246,Zimbabwe,ZWE,2017,4.589452e+06,9.647147e+06,6.743057,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7247,Zimbabwe,ZWE,2018,4.650597e+06,9.788215e+06,6.729715,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7248,Zimbabwe,ZWE,2019,4.717307e+06,9.928166e+06,6.716372,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915

In [22]:
nation_pop_gdp_all=df_pop_gdp_all['Nation'].unique()
df_pop_gdp_all_proj=df_pop_gdp_all[df_pop_gdp_all['Year']>=2020].copy()
for c in nation_pop_gdp_all:
    for y in range(min(years_hist),2051):
        for frac_var in frac_vars:
            
            val=df_pop_gdp_all_hist.loc[(df_pop_gdp_all_hist['Nation']==c)&
                                  (df_pop_gdp_all_hist['Year']==2019),frac_var].values[0]
            df_pop_gdp_all_proj.loc[(df_pop_gdp_all_proj['Nation']==c)&
                                  (df_pop_gdp_all_proj['Year']==y),frac_var]=val
df_pop_gdp_all_proj

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,gdp_class,frac_scoe_heat_energy_other_se_coal,frac_scoe_heat_energy_other_se_diesel,frac_scoe_heat_energy_other_se_electricity,frac_scoe_heat_energy_other_se_gasoline,frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids,frac_scoe_heat_energy_other_se_hydrogen,frac_scoe_heat_energy_other_se_kerosene,frac_scoe_heat_energy_other_se_natural_gas,frac_scoe_heat_energy_other_se_solid_biomass
9,Afghanistan,AFG,2020,1.013149e+07,2.879685e+07,50.050108,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
10,Afghanistan,AFG,2021,1.095378e+07,3.071641e+07,51.885013,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
11,Afghanistan,AFG,2022,1.134045e+07,3.139778e+07,53.719919,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
12,Afghanistan,AFG,2023,1.172712e+07,3.207916e+07,55.554825,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
13,Afghanistan,AFG,2024,1.211379e+07,3.276054e+07,57.389731,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404,2,0.003988,0.032696,0.333255,0.010899,0.010899,0.0,0.001376,0.094973,0.011915

In [23]:
for ssp_var in frac_vars:
    df_pop_gdp_all_hist[['Nation','iso_code3','Year',
    ssp_var]].to_csv(grandparentdir+'/'+ssp_var+
    '/input_to_sisepuede/historical/'+ssp_var+'.csv')

    df_pop_gdp_all_proj[['Nation','iso_code3','Year',
    ssp_var]].to_csv(grandparentdir+'/'+ssp_var+
    '/input_to_sisepuede/projected/'+ssp_var+'.csv')
    
    pd.concat([df_pop_gdp_all_hist,df_pop_gdp_all_proj]).loc[(pd.concat([df_pop_gdp_all_hist,df_pop_gdp_all_proj])['Nation']=='Brazil')&
                 (pd.concat([df_pop_gdp_all_hist,df_pop_gdp_all_proj])['Year']==2015)].to_csv(grandparentdir+'/'+ssp_var+
    '/row_data/'+ssp_var[0:33]+'_all_Bra_2015.csv')
    
    pd.concat([df_pop_gdp_all_hist,df_pop_gdp_all_proj]).to_csv(grandparentdir+'/'+ssp_var+
    '/row_data/'+ssp_var[0:33]+'_all.csv')
    
    df_energy_products_gdp_class.to_csv(grandparentdir+'/'+ssp_var+
    '/row_data/'+ssp_var[0:33]+'_historical.csv')

In [24]:
ssp_var[0:42]

'frac_scoe_heat_energy_other_se_solid_bioma'