In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_recycled_wood'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [3]:
IPPU_folder = 'prodinit_ippu_paper_tonne'
IPPU_var = 'prodinit_ippu_paper_tonne'
df_ippu_hist = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(grandparentdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & 
                                    (df_ippu_hist['year']==y),][IPPU_var].values[0]/1000
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & 
                                    (df_ippu_proj['year']==y)][IPPU_var].values[0]/1000
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_paper_tonne
0          FSM  2010                   0.550800
1          FSM  2011                   0.545147
2          FSM  2012                   0.655376
3          FSM  2013                   0.884041
4          FSM  2014                   0.323716
...        ...   ...                        ...
7826       CYP  2046                   7.980984
7827       CYP  2047                   7.378595
7828       CYP  2048                   6.821673
7829       CYP  2049                   6.306787
7830       CYP  2050                   5.830763

[7831 rows x 3 columns]

In [4]:
#df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

df_eei

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Manufacturing [ISIC 10-18; 20-32],Oil and oil products (PJ) ...,117.58,91.59,88.38,111.41,122.11,129.29,133.41,...,161.91,179.86,155.11,155.37,118.72,106.86,97.51,101.08,100.39,97.74
1,Australia,Manufacturing [ISIC 10-18; 20-32],Gas (PJ) ...,314.61,339.39,338.58,343.29,352.22,325.43,322.22,...,330.12,325.92,339.72,346.59,334.74,322.67,309.67,311.85,298.23,303.55
2,Australia,Manufacturing [ISIC 10-18; 20-32],Coal and coal products (PJ) ...,231.33,201.89,178.75,209.41,223.34,226.59,225.07,...,230.37,191.49,184.76,177.97,170.35,197.53,208.32,205.26,196.51,190.24
3,Australia,Manufacturing [ISIC 10-18; 20-32],Biofuels and waste (PJ) ...,96.47,94.43,99.89,101.47,104.3,109.06,110.25,...,104.6,104.29,112.36,105.27,115.61,115.49,124.1,112.09,103.36,98.69
4,Australia,Manufacturing [ISIC 10-18; 20-32],Heat (PJ) ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,Uzbekistan,Construction [ISIC 41-43],Biofuels and waste (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9756,Uzbekistan,Construction [ISIC 41-43],Heat (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9757,Uzbekistan,Construction [ISIC 41-43],Electricity (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0.51,0.42,0.28,0.46,..,..,..
9758,Uzbekistan,Construction [ISIC 41-43],Other sources (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0.01,0,..,..,..
9759,Uzbekistan,Construction [ISIC 41-43],Total final energy use (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,6.85,6.54,6.23,9.44,..,..,..

In [5]:
#Cross Walk with IEA data:
industries_correspondence = {
  'electronics' : (0.5, 'Machinery [ISIC 25-28]'), #Electronics is ISIC 26 and 27, so let's say half of 25-28
  'plastic' : (0.5, 'Rubber and plastic [ISIC 22]'), # SEE BELOW
  'chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), #OK
  'cement' : (0.9, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'glass' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'other_product_manufacturing' : (1.0, 'Other manufacturing [ISIC 31-32]'), #OK
  'agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), #OK
  'textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), #SEE BELOW
  'rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), #+ AND 0.5  'Rubber and plastic [ISIC 22]'
  'metals' : (1.0, 'Basic metals [ISIC 24]'), #OK
  'lime_and_carbonite' : (0.05, 'Non-metallic minerals [ISIC 23]'), #FIXED
  'paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
  # REMOVE 'recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') #I propose we leave this out entirely, unless we are doing all recyclables
}

In [6]:
fraction = 1.0
df_enduse = df_eei.loc[df_eei['ENDUSE']=='Wood and wood products [ISIC 16]']
df_enduse = df_enduse[df_enduse['PRODUCT/FLOW'].str.startswith('Total final energy use (PJ)')]
mask = (df_enduse == '..').any(axis=1)
df_enduse = df_enduse.drop(index=df_enduse[mask].index)
df_enduse

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
191,Austria,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,12.93,13.28,13.56,15.24,16.24,27.06,24.75,...,25.67,27.59,29.93,29.37,29.74,27.43,27.69,25.4,23.84,23.66
351,Belgium,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,6.95,7.62,7.3,8.51,5.73,5.65,5.9,...,9.03,9.34,9.44,9.5,10.05,10.1,9.69,10.28,9.52,9.7
511,Canada,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,55.22,44.16,48.59,41.8,44.15,45.87,46.04,...,56.64,57.42,52.25,53.41,54.13,52.39,56.6,54.86,54.27,54.4
671,Czech Republic,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,5.22,5.6,6.08,7.76,8.51,8.84,8.92,...,7.94,8.83,9.04,8.78,9.59,9.91,9.12,9.12,8.86,9.45
831,Denmark,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,5.36,5.02,4.03,3.61,3.62,3.63,3.85,...,3.51,2.8,2.44,2.15,2.46,3.09,3.5,3.72,3.57,3.61
991,Estonia,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,3.2,3.77,4.57,5.71,6.25,6.67,4.93,...,5.14,4.15,4.85,5.1,5.49,2.43,2.57,2.79,3.06,3.46
1151,Finland,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,19.1,20.03,22.04,22.46,23.17,24.91,25.28,...,24.2,23.35,22.74,21.39,20.46,21.65,24.4,24,22.64,22.63
1311,France,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,15.9,16.35,16.16,17.56,17.96,19.39,18.47,...,21.51,22.86,25.74,22.7,24.9,25.7,25.58,28.87,24.7,22.87
1471,Germany,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,36.09,36.96,38.32,46.76,58.43,68.13,58.1,...,88.14,90.92,85.36,93.92,92.19,93.63,94.33,93.68,87.9,88.71
1631,Greece,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.99,1.72,1.67,2,1.99,2.1,2.08,...,2.29,1.57,1.22,1.03,1.29,0.97,1.14,1.73,1.25,1.2
1791,Hungary,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,2.7,2.71,2.61,2.37,2.36,2.35,2.12,...,1.66,2.05,2.62,2.32,2.57,3.09,4.04,5.23,5.05,4.89
1951,Ireland,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,5.5,5.98,6.08,4.28,5.08,5.88,5.69,...,4.9,5.06,5.22,5.81,5.86,5.77,6.55,6.47,6.21,5.43
2111,Italy,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,19.48,20.27,20.29,20.22,21.08,21.12,22.56,...,19.92,18.08,16.9,17.33,19.13,19.61,20.31,20.69,20.27,20.16
2271,Japan,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,21.74,21.68,25.98,26.45,29.77,31.07,30.4,...,24.93,24.92,25.5,15.99,14.46,16.46,16.58,17.55,18.21,17.8
2431,Korea,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,8.99,8.39,9.46,9.51,10.41,10.93,10.76,...,10.15,10.18,10.74,15.25,16.75,15.29,13.59,13.77,10.94,10.02
2591,Lithuania,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.49,1.98,3.81,4.41,4.67,4.89,4.66,...,3.32,4.02,3.88,3.5,3.54,4.29,3.98,3.77,3.72,4.33
2751,Luxembourg,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,0.1,0.09,0.1,0.11,0.12,0.99,0.94,...,0.84,0.74,0.8,0.96,0.85,0.91,0.81,0.48,0.26,0.26
3071,Netherlands,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,3.56,2.46,2.55,2.42,2.29,2.52,2.53,...,2.75,2.65,2.26,2.8,2.92,3.08,1.97,2.48,2.37,2.61
3231,New Zealand,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,30.71,34.36,41.32,41.9,44.88,44.14,42.85,...,39.9,39.39,36.96,35.99,37.85,39.05,38.48,37.18,36.4,30.76
3391,Norway,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,10.81,6.62,6.57,6.42,6.66,6.42,6.43,...,6.95,6.77,6.32,6.1,6.63,6.34,6.17,6.61,7.07,7.41
3551,Poland,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,25.12,25.11,27.25,27.48,28.98,29.27,28.46,...,32.21,32.36,35.86,34.08,37.02,40.55,43.86,43.39,47.63,49.9
3711,Portugal,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,9.13,8.38,6.65,5.89,5.57,5.97,5.93,...,4.5,4.68,4.49,4.49,4.79,5.2,4.9,5.91,6.3,5.94
3871,Slovak Republic,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.34,1.81,1.65,2.57,2.21,2.06,2.24,...,2.66,2.56,1.69,1.79,2.36,1.69,1.99,2.34,2.11,1.96
4031,Spain,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,25.09,26.2,27.75,29.29,36.18,33.02,27.81,...,22.97,20.65,21.1,19.52,20.73,26.93,27.06,26.67,26.86,25.9
4191,Sweden,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,31.08,30.12,30.28,30.28,28.05,31.39,31.82,...,26.59,25.35,26.85,26.45,26.22,27.4,28.06,27.62,26.66,25.29
4511,Republic of Türkiye,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,2.4,2.2,2.26,2.44,2.94,3.56,3.73,...,8.77,7.06,12.61,14.23,14.76,16.63,18.42,22.6,23.05,25
4671,United Kingdom,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,15.91,12.92,11.89,16.66,13.34,15.16,16.6,...,13.12,13.15,13.17,14.17,14.32,15.3,15.15,15.59,15.49,14.16
4831,United States,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,449.6,426.38,352.13,369.03,372.56,378.57,427.02,...,339.78,285.46,304.07,334.19,320.26,395.49,467.53,491.8,424.53,401.85
6111,Latvia,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,3.48,4.28,3.75,3.85,4.92,5.7,6.86,...,13.43,14.44,15.03,17.63,18.82,18.61,19.46,20.34,20.43,20.98
6431,Armenia,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,0,0.01,0.01,0.04,0.03,0.03,0,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0,0
7071,Bulgaria,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.96,2.11,2.31,2.43,2.52,2.39,3.09,...,2.36,2.31,2.42,2.67,2.59,2.42,2.61,2.97,2.92,3.42
7231,Croatia,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.51,1.6,1.52,1.58,1.95,1.99,2.41,...,1.67,1.47,1.51,1.44,1.97,2.33,3.15,3.26,3.76,3.77
7391,Cyprus,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
8511,Republic of Moldova,Wood and wood products [ISIC 16],Total final energy use (PJ),0.06,0.04,0.04,0.05,0.08,0.09,0.04,...,0.29,0.3,0.2,0.22,0.05,0.06,0.04,0.04,0.03,0.04
8671,Republic of North Macedonia,Wood and wood products [ISIC 16],Total final energy use (PJ),0.2,0.09,0.28,0.12,0.11,0.09,0.05,...,0.03,0.02,0.04,0.02,0.03,0.03,0.03,0.04,0.03,0.04
8831,Romania,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,7.17,7.82,8.39,5.06,9.57,8.44,10.18,...,9.43,10.64,10.86,11.49,12.13,13.9,13.78,14.39,13.48,11.82
9151,Slovenia,Wood and wood products [ISIC 16],Total final energy use (PJ) ...,1.96,1.63,1.01,2.18,2.45,2.67,2.82,...,1.9,1.59,1.62,2.54,2.17,2.05,1.97,1.98,2.12,2.26

In [7]:
CircularEc_folder = 'frac_waso_recycled_wood'
df_frac_hist = pd.read_csv(grandparentdir+'/frac_recycled/'
                           +CircularEc_folder+'/input_to_sisepuede/historical/'
                           +CircularEc_folder+'.csv')

df_frac_proj = pd.read_csv(grandparentdir+'/frac_recycled/'
                           +CircularEc_folder+'/input_to_sisepuede/projected/'
                           +CircularEc_folder+'.csv')

iso3 = list(set(df_frac_hist['iso_code3'].values))

years_all = range(min(df_frac_hist['Year'].values),max(df_frac_proj['Year'].values)+1)
c_y_frac = []
for c in iso3:
    for y in years_all:
    
        try:
            frac = df_frac_hist.loc[(df_frac_hist['iso_code3']==c) & (df_frac_hist['Year']==y),][CircularEc_folder].values[0]
            
        except:
            frac = df_frac_proj.loc[(df_frac_proj['iso_code3']==c) & (df_frac_proj['Year']==y)][CircularEc_folder].values[0]
            
        c_y_frac.append([c,y,frac])

df_frac_all = pd.DataFrame(c_y_frac,columns=['iso_code3', 'Year', CircularEc_folder])
df_frac_all

     iso_code3  Year  frac_waso_recycled_wood
0          FSM  2010                 0.096899
1          FSM  2011                 0.096899
2          FSM  2012                 0.096899
3          FSM  2013                 0.096899
4          FSM  2014                 0.096899
...        ...   ...                      ...
8892       CYP  2046                 0.133100
8893       CYP  2047                 0.133100
8894       CYP  2048                 0.133100
8895       CYP  2049                 0.133100
8896       CYP  2050                 0.133100

[8897 rows x 3 columns]

In [8]:
years_hist=range(2010,2017)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 23.236486486486484,
 2011: 22.679459459459455,
 2012: 21.21,
 2013: 21.7772972972973,
 2014: 22.658378378378377,
 2015: 22.678648648648647,
 2016: 25.129999999999995}

In [9]:
sub_continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in sub_continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in sub_continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year     meanEEI
0    Australia and New Zealand  2010   39.820000
1    Australia and New Zealand  2011   39.900000
2    Australia and New Zealand  2012   39.390000
3    Australia and New Zealand  2013   36.960000
4    Australia and New Zealand  2014   35.990000
5    Australia and New Zealand  2015   37.850000
6    Australia and New Zealand  2016   39.050000
35                Eastern Asia  2010   26.870000
36                Eastern Asia  2011   24.930000
37                Eastern Asia  2012   24.920000
38                Eastern Asia  2013   25.500000
39                Eastern Asia  2014   15.990000
40                Eastern Asia  2015   14.460000
41                Eastern Asia  2016   16.460000
42              Eastern Europe  2010   11.180000
43              Eastern Europe  2011   10.720000
44              Eastern Europe  2012   11.238000
45              Eastern Europe  2013   12.160000
46              Eastern Europe  2014   11.868000
47              Eastern Europe  2015   12.780000
48              Eastern Europe  2016   13.974000
77            Northern America  2010  210.635000
78            Northern America  2011  198.210000
79            Northern America  2012  171.440000
80            Northern America  2013  178.160000
81            Northern America  2014  193.800000
82            Northern America  2015  187.195000
83            Northern America  2016  223.940000
84             Northern Europe  2010   10.931250
85             Northern Europe  2011   11.005000
86             Northern Europe  2012   10.742500
87             Northern Europe  2013   10.916250
88             Northern Europe  2014   11.016250
89             Northern Europe  2015   11.185000
90             Northern Europe  2016   11.197500
126            Southern Europe  2010    8.406667
127            Southern Europe  2011    8.875000
128            Southern Europe  2012    8.006667
129            Southern Europe  2013    7.806667
130            Southern Europe  2014    7.725000
131            Southern Europe  2015    8.346667
132            Southern Europe  2016    9.515000
140               Western Asia  2010    0.020000
141               Western Asia  2011    0.020000
142               Western Asia  2012    0.020000
143               Western Asia  2013    0.015000
144               Western Asia  2014    0.015000
145               Western Asia  2015    0.015000
146               Western Asia  2016    0.015000
147             Western Europe  2010   23.423333
148             Western Europe  2011   24.656667
149             Western Europe  2012   25.683333
150             Western Europe  2013   25.588333
151             Western Europe  2014   26.541667
152             Western Europe  2015   26.775000
153             Western Europe  2016   26.808333

In [10]:
#### HISTORICAL ######
iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_recycled_wood
0,"Micronesia, Fed. Sts.",FSM,2010,0
1,"Micronesia, Fed. Sts.",FSM,2011,0
2,"Micronesia, Fed. Sts.",FSM,2012,0
3,"Micronesia, Fed. Sts.",FSM,2013,0
4,"Micronesia, Fed. Sts.",FSM,2014,0
...,...,...,...,...
1332,Cyprus,CYP,2012,0
1333,Cyprus,CYP,2013,0
1334,Cyprus,CYP,2014,0
1335,Cyprus,CYP,2015,0
1336,Cyprus,CYP,2016,0

In [11]:
for c,y in zip(df_historical_out['iso_code3'].values,df_historical_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    frac = df_frac_all.loc[(df_frac_all['iso_code3']==c)&(df_frac_all['Year']==y)][CircularEc_folder].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y)].values[0])*1e3

        dato=frac*tj/tonne
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y]*1e3
            
        dato=frac*tj/tonne
        
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_recycled_wood
0,"Micronesia, Fed. Sts.",FSM,2010,4087.866622
1,"Micronesia, Fed. Sts.",FSM,2011,4031.247086
2,"Micronesia, Fed. Sts.",FSM,2012,3135.958183
3,"Micronesia, Fed. Sts.",FSM,2013,2386.996967
4,"Micronesia, Fed. Sts.",FSM,2014,6782.430863
...,...,...,...,...
1332,Cyprus,CYP,2012,0.029553
1333,Cyprus,CYP,2013,0.021957
1334,Cyprus,CYP,2014,0.029399
1335,Cyprus,CYP,2015,0.032825
1336,Cyprus,CYP,2016,0.036888

In [12]:
#### Projected ######

years_proj=range(max(years_hist)+1,2051)

iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        coun_year.append([count,iso3,year,0])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out[var_name]=0
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_recycled_wood
0,"Micronesia, Fed. Sts.",FSM,2017,0
1,"Micronesia, Fed. Sts.",FSM,2018,0
2,"Micronesia, Fed. Sts.",FSM,2019,0
3,"Micronesia, Fed. Sts.",FSM,2020,0
4,"Micronesia, Fed. Sts.",FSM,2021,0
...,...,...,...,...
6489,Cyprus,CYP,2046,0
6490,Cyprus,CYP,2047,0
6491,Cyprus,CYP,2048,0
6492,Cyprus,CYP,2049,0
6493,Cyprus,CYP,2050,0

In [13]:
y_hist_max = max(years_hist)
for c,y in zip(df_projected_out['iso_code3'].values,df_projected_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    frac = df_frac_all.loc[(df_frac_all['iso_code3']==c)&(df_frac_all['Year']==y)][CircularEc_folder].values[0]
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y_hist_max)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato*frac
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y_hist_max), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y_hist_max]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato*frac
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_recycled_wood
0,"Micronesia, Fed. Sts.",FSM,2017,4362.605892
1,"Micronesia, Fed. Sts.",FSM,2018,4645.558774
2,"Micronesia, Fed. Sts.",FSM,2019,3656.987054
3,"Micronesia, Fed. Sts.",FSM,2020,2573.177984
4,"Micronesia, Fed. Sts.",FSM,2021,2573.177959
...,...,...,...,...
6489,Cyprus,CYP,2046,0.333543
6490,Cyprus,CYP,2047,0.360773
6491,Cyprus,CYP,2048,0.390227
6492,Cyprus,CYP,2049,0.422085
6493,Cyprus,CYP,2050,0.456544

In [14]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [15]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')