In [20]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_tj_per_tonne_production_metals'

In [21]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [22]:
IPPU_folder = 'prodinit_ippu_metals_tonne'
IPPU_var = 'prodinit_ippu_metals_tonne'
df_ippu_hist = pd.read_csv(ggpdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/historical/'+IPPU_var+'.csv')
df_ippu_proj = pd.read_csv(ggpdir+'/IPPU/'+IPPU_folder+'/input_to_sisepuede/projected/'+IPPU_var+'.csv')

code_ippu = list(set(df_ippu_proj['location_code'].values))

years_all = range(min(df_ippu_hist['year'].values),max(df_ippu_proj['year'].values)+1)
c_y_ippu = []
for c in code_ippu:
    for y in years_all:
    
        try:
            ippu = df_ippu_hist.loc[(df_ippu_hist['location_code']==c) & (df_ippu_hist['year']==y),][IPPU_var].values[0]
            
        except:
            ippu = df_ippu_proj.loc[(df_ippu_proj['location_code']==c) & (df_ippu_proj['year']==y)][IPPU_var].values[0]
            
        c_y_ippu.append([c,y,ippu])

df_ippu_all = pd.DataFrame(c_y_ippu,columns=['iso_code3', 'Year', IPPU_var])
df_ippu_all

     iso_code3  Year  prodinit_ippu_metals_tonne
0          BIH  2010                9.432306e+05
1          BIH  2011                1.016825e+06
2          BIH  2012                9.712133e+05
3          BIH  2013                1.044640e+06
4          BIH  2014                9.718005e+05
...        ...   ...                         ...
7826       VUT  2046                6.760209e+05
7827       VUT  2047                7.895322e+05
7828       VUT  2048                9.221034e+05
7829       VUT  2049                1.076935e+06
7830       VUT  2050                1.257764e+06

[7831 rows x 3 columns]

In [23]:
#df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

df_eei

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Manufacturing [ISIC 10-18; 20-32],Oil and oil products (PJ) ...,117.58,91.59,88.38,111.41,122.11,129.29,133.41,...,161.91,179.86,155.11,155.37,118.72,106.86,97.51,101.08,100.39,97.74
1,Australia,Manufacturing [ISIC 10-18; 20-32],Gas (PJ) ...,314.61,339.39,338.58,343.29,352.22,325.43,322.22,...,330.12,325.92,339.72,346.59,334.74,322.67,309.67,311.85,298.23,303.55
2,Australia,Manufacturing [ISIC 10-18; 20-32],Coal and coal products (PJ) ...,231.33,201.89,178.75,209.41,223.34,226.59,225.07,...,230.37,191.49,184.76,177.97,170.35,197.53,208.32,205.26,196.51,190.24
3,Australia,Manufacturing [ISIC 10-18; 20-32],Biofuels and waste (PJ) ...,96.47,94.43,99.89,101.47,104.3,109.06,110.25,...,104.6,104.29,112.36,105.27,115.61,115.49,124.1,112.09,103.36,98.69
4,Australia,Manufacturing [ISIC 10-18; 20-32],Heat (PJ) ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,Uzbekistan,Construction [ISIC 41-43],Biofuels and waste (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9756,Uzbekistan,Construction [ISIC 41-43],Heat (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9757,Uzbekistan,Construction [ISIC 41-43],Electricity (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0.51,0.42,0.28,0.46,..,..,..
9758,Uzbekistan,Construction [ISIC 41-43],Other sources (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0.01,0,..,..,..
9759,Uzbekistan,Construction [ISIC 41-43],Total final energy use (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,6.85,6.54,6.23,9.44,..,..,..

In [24]:
#Cross Walk with IEA data:
industries_correspondence = {
                'electronics' : (1.0, 'Machinery [ISIC 25-28]'), 
                'plastic' : (1.0, 'Rubber and plastic [ISIC 22]'), 
                'chemicals' : (1.0, 'Chemicals and chemical products [ISIC 20-21]'), 
                'cement' : (1.0, 'Of which: cement'),
                'glass' : (1.0, 'Non-metallic minerals [ISIC 23]'), 
                'other_product_manufacturing' : (1.0, 'Other manufacturing [ISIC 31-32]'), 
                'agriculture_and_livestock' : (1.0, 'Agriculture, forestry and fishing [ISIC 01-03]'), 
                'textiles' : (0.5, 'Textiles and leather [ISIC 13-15]'), 
                'rubber_and_leather' : (0.5, 'Textiles and leather [ISIC 13-15]'), 
                'metals' : (1.0, 'Basic metals [ISIC 24]'),  
                'lime_and_carbonite' : (1.0, 'Non-ferrous metals [ISIC 2420+2432]'), 
                'paper' : (1.0, 'Paper pulp and printing [ISIC 17-18]'),
                'recycled_wood' : (1.0, 'Wood and wood products [ISIC 16]') 
                }

In [25]:
fraction = 1.0
df_enduse = df_eei.loc[df_eei['ENDUSE']=='Basic metals [ISIC 24]']
df_enduse = df_enduse[df_enduse['PRODUCT/FLOW'].str.startswith('Total final energy use (PJ)')]
mask = (df_enduse == '..').any(axis=1)
df_enduse = df_enduse.drop(index=df_enduse[mask].index)
df_enduse

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
79,Australia,Basic metals [ISIC 24],Total final energy use (PJ) ...,517.56,521.79,497.51,487.03,506.6,495.15,498.31,...,517.22,492.13,478.81,469.17,413.95,436.06,433.21,436.09,423.98,420.33
239,Austria,Basic metals [ISIC 24],Total final energy use (PJ) ...,106.21,104.45,106.34,105.51,108.05,117,115.66,...,121.1,120.3,125.1,124.27,124.07,123.64,128.49,115.24,124.22,114.17
399,Belgium,Basic metals [ISIC 24],Total final energy use (PJ) ...,230.99,225.62,189.63,194.31,185.09,161.68,164.41,...,124.17,113.33,119.73,119.93,116.9,126.01,127.61,127.82,125.35,106.78
559,Canada,Basic metals [ISIC 24],Total final energy use (PJ) ...,470.98,458,478.82,478.97,478.95,482.36,496.39,...,457.49,443.21,423.23,443.36,437.17,467.13,478.27,483.23,486.11,431.71
719,Czech Republic,Basic metals [ISIC 24],Total final energy use (PJ) ...,160.76,163.9,152.33,149.48,156,144.92,146.86,...,101.41,98.56,98.36,96.79,93.43,94.07,94.28,97.27,83.78,90.32
879,Denmark,Basic metals [ISIC 24],Total final energy use (PJ) ...,6.55,6.77,4.59,4.38,4.37,4.42,4.4,...,2.57,3.28,3.32,3.54,3.43,3.58,3.76,3.99,3.8,3.86
1039,Estonia,Basic metals [ISIC 24],Total final energy use (PJ) ...,0.02,0.04,0.06,0.07,0.06,0.09,0.17,...,0.07,0.15,0.11,0.11,0.06,0.08,0.06,0.08,0.07,0.07
1199,Finland,Basic metals [ISIC 24],Total final energy use (PJ) ...,76.12,74.71,77.26,80.18,82.09,82.15,84.54,...,72.59,66.81,65.73,68.08,72.05,72.93,69.99,73.79,67.53,67.34
1359,France,Basic metals [ISIC 24],Total final energy use (PJ) ...,366.4,374.09,391.2,361.23,360.4,371.5,372.16,...,312.77,305.87,312.14,306.97,295.04,296.82,320.28,313.89,291.47,230.69
1519,Germany,Basic metals [ISIC 24],Total final energy use (PJ) ...,795.21,768.67,756.85,795.9,755.73,711.02,753.15,...,747.79,721,703.86,699.18,718.22,720.11,730.24,738.11,685.2,613.39
1679,Greece,Basic metals [ISIC 24],Total final energy use (PJ) ...,41.93,42.27,44.57,45.18,44.75,44.21,42.76,...,41.21,39.61,42.83,40.32,38.52,37.96,33.98,35.09,32.44,33.13
1839,Hungary,Basic metals [ISIC 24],Total final energy use (PJ) ...,49.57,43.35,43.5,43.52,41.61,42.31,45.75,...,38.15,35.56,27.77,29.05,34.19,28.58,35.85,37.55,34.59,30.82
1999,Ireland,Basic metals [ISIC 24],Total final energy use (PJ) ...,19.72,17.32,17.02,17.1,17.97,16.54,17.39,...,16.99,15.01,17.54,17.07,17.29,17.49,18.15,18.54,19.49,18.21
2159,Italy,Basic metals [ISIC 24],Total final energy use (PJ) ...,376.15,378.62,350.69,382.05,392.1,398.32,398.6,...,337.67,323.64,263.46,268.65,237.53,255.71,234.5,234.39,230.24,200.52
2319,Japan,Basic metals [ISIC 24],Total final energy use (PJ) ...,2059.07,2002.89,2058.12,2067.15,2080.84,2097.36,2148.45,...,2036.88,2059.69,2089.25,2058.65,1968.39,1968.12,1956.75,1935.2,1874.16,1608.86
2479,Korea,Basic metals [ISIC 24],Total final energy use (PJ) ...,661.01,659.1,694.13,708.86,718.37,733.33,740.86,...,1083.62,1091.65,1059.03,1157.36,1162.91,1131.13,1129.59,1153.59,1121.85,1065.16
2639,Lithuania,Basic metals [ISIC 24],Total final energy use (PJ) ...,0.24,0.23,0.15,0.13,0.17,0.21,0.2,...,0.16,0.15,0.14,0.1,0.1,0.1,0.09,0.08,0.06,0.04
2799,Luxembourg,Basic metals [ISIC 24],Total final energy use (PJ) ...,14.22,14.85,15.12,13.81,16.44,14.56,18.35,...,14.51,12.81,11.92,11.61,11.95,12.61,11.72,14.86,13.71,12.75
2999,Mexico,Basic metals [ISIC 24],Total final energy use (PJ) ...,229.21,190.27,174.74,188.66,201.81,202.44,212.98,...,209.56,213.75,213.42,216.18,227.01,231.61,239.41,245.67,257.43,217.41
3119,Netherlands,Basic metals [ISIC 24],Total final energy use (PJ) ...,132.19,136.21,136.8,141.86,147.36,146.03,135.93,...,140.8,127.97,122.85,121.19,127.83,127.72,128.06,124.68,126.63,112.21
3279,New Zealand,Basic metals [ISIC 24],Total final energy use (PJ) ...,32.33,32.1,32.54,33.75,35.34,35.24,34.36,...,37.29,35.68,37.55,37.05,35.98,35.45,35.35,34.95,37.16,35.51
3439,Norway,Basic metals [ISIC 24],Total final energy use (PJ) ...,128.63,121.45,113.32,118.37,131.83,128.2,120.7,...,104.67,104.57,105.63,108.59,109.01,111.79,114.46,116.54,116.67,116.61
3599,Poland,Basic metals [ISIC 24],Total final energy use (PJ) ...,298.4,265.6,248.92,270.52,272.18,214.77,230.35,...,182.3,186.17,190.8,199.89,201.47,197.78,214.81,216.78,200.63,171.16
3759,Portugal,Basic metals [ISIC 24],Total final energy use (PJ) ...,16.18,8.42,6.45,7.51,7.57,8.94,9.39,...,7.9,8.1,8.35,8.45,7.99,8.65,8.86,9.59,9.32,9.61
3919,Slovak Republic,Basic metals [ISIC 24],Total final energy use (PJ) ...,96.87,98.67,104.11,116.19,116.38,110.2,118.74,...,103.39,110.13,112.83,116.42,110.06,112.07,116.8,115.4,96.22,84.31
4079,Spain,Basic metals [ISIC 24],Total final energy use (PJ) ...,245.5,265.45,271.67,286.11,301.04,272.01,228.15,...,207.04,197.47,180.41,168.13,181.17,182.89,197.71,193.67,175.36,152.68
4239,Sweden,Basic metals [ISIC 24],Total final energy use (PJ) ...,104.64,109.93,112.71,109.9,111.14,111.18,123.39,...,97.33,88.22,87.33,86.14,87.97,86.4,88.98,88.27,92.5,82.98
4399,Switzerland,Basic metals [ISIC 24],Total final energy use (PJ) ...,12.51,12.31,12.77,13.73,14.3,13.4,12.52,...,12,11.93,11.49,12.56,12.54,12.29,12.87,12.88,12.22,11.96
4559,Republic of Türkiye,Basic metals [ISIC 24],Total final energy use (PJ) ...,216.4,198.42,192.79,217.82,231.11,238.4,255.06,...,320.28,333.11,327.33,325.6,353.48,365.31,397.75,397.8,393.63,399.95
4719,United Kingdom,Basic metals [ISIC 24],Total final energy use (PJ) ...,352.28,294.63,251.64,266.41,264.71,265.28,279.89,...,190.45,191.89,231.11,231.19,225.68,170.82,162.67,150.87,156.98,155.16
4879,United States,Basic metals [ISIC 24],Total final energy use (PJ) ...,2150.27,1889.68,1792.33,1813.73,1968.92,1710.73,1606.09,...,1641.85,1684.34,1642.96,1627.73,1608.02,1487.09,1383.92,1478.15,1579.54,1338.25
5199,Brazil,Basic metals [ISIC 24],Total final energy use (PJ) ...,868.22,822.29,888.26,961.19,1027.19,1015.63,1006.95,...,1105.62,1085.46,1055.64,1032.72,996.82,924.32,987.72,962.56,925.72,905.08
5839,Chile,Basic metals [ISIC 24],Total final energy use (PJ) ...,23.09,22,21.84,24.68,23.91,24.99,23.71,...,23.46,23.62,18.08,18.4,17.53,15.67,15.14,14.3,17.59,14
6159,Latvia,Basic metals [ISIC 24],Total final energy use (PJ) ...,5.91,6.07,5.84,5.83,5.94,5.86,5.92,...,2.14,3.61,1.28,0.14,0.64,0.13,0.11,0.1,0.09,0.08
6319,Albania,Basic metals [ISIC 24],Total final energy use (PJ) ...,1.94,2.06,1.78,1.85,1.91,1.65,1.45,...,1.09,1.14,1.18,2.6,1.09,1.15,1.11,1.38,1.44,1.43
6479,Armenia,Basic metals [ISIC 24],Total final energy use (PJ) ...,0.06,0.25,0.42,0.48,0.34,0.35,0.35,...,0.57,0.45,0.46,2.07,2.26,2.3,2.67,2.2,1.84,1.94
6959,Bosnia and Herzegovina,Basic metals [ISIC 24],Total final energy use (PJ) ...,4.05,5.44,6.83,7.78,11.41,14.05,14.4,...,37.54,35.94,37.72,35.24,35.55,33.91,34.97,38.58,37.4,30.7
7119,Bulgaria,Basic metals [ISIC 24],Total final energy use (PJ) ...,60.31,58.88,54,64.39,55.86,54.1,53.89,...,11.79,10.29,10.25,10.79,10.23,10.1,11.77,12.71,12.25,12
7279,Croatia,Basic metals [ISIC 24],Total final energy use (PJ) ...,2.66,2.27,1.86,1.87,2,2.19,2.56,...,1.96,1.21,1.68,1.61,1.31,0.56,0.97,1.85,1.6,1.4
8079,Kosovo,Basic metals [ISIC 24],Total final energy use (PJ) ...,1.79,2.26,2.26,2.39,2.41,2.49,2.56,...,5.32,5.22,4.4,4.04,4.42,4.1,4.13,3.35,3.61,3.89
8719,Republic of North Macedonia,Basic metals [ISIC 24],Total final energy use (PJ) ...,10.57,9.42,8.46,12.73,10.82,14.08,15.43,...,17.16,15.48,14.56,13.43,11.38,9.45,7,7.67,8.77,9.61
8879,Romania,Basic metals [ISIC 24],Total final energy use (PJ) ...,129.54,137.72,143.45,144.21,155.93,156.79,163.26,...,78.68,68.98,68.5,69.39,74.73,71.2,69.11,68.84,66.5,61.52
9039,Serbia,Basic metals [ISIC 24],Total final energy use (PJ) ...,9.04,5.68,4.25,10.99,20.34,30.59,40.85,...,22.07,10.68,9.93,12.53,20.32,24.92,27.65,38.95,39.94,29.33
9199,Slovenia,Basic metals [ISIC 24],Total final energy use (PJ) ...,12.03,11.31,11.83,12.77,12.97,14.3,14.46,...,11.8,12.53,12.48,12.39,12.62,12.97,13.73,13.26,12.49,11.29

In [26]:
years_hist=range(2010,2021)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 229.98204545454544,
 2011: 240.9188636363636,
 2012: 238.87954545454548,
 2013: 235.23977272727276,
 2014: 236.1063636363636,
 2015: 232.3252272727273,
 2016: 228.01772727272729,
 2017: 229.19431818181818,
 2018: 231.13204545454548,
 2019: 227.3086363636364,
 2020: 204.95954545454552}

In [27]:
sub_continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in sub_continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in sub_continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year     meanEEI
0    Australia and New Zealand  2010  275.080000
1    Australia and New Zealand  2011  277.255000
2    Australia and New Zealand  2012  263.905000
3    Australia and New Zealand  2013  258.180000
4    Australia and New Zealand  2014  253.110000
..                         ...   ...         ...
237             Western Europe  2016  202.742857
238             Western Europe  2017  208.467143
239             Western Europe  2018  206.782857
240             Western Europe  2019  196.971429
241             Western Europe  2020  171.707143

[110 rows x 3 columns]

In [28]:
#### HISTORICAL ######
iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_metals
0,Bosnia and Herzegovina,BIH,2010,0
1,Bosnia and Herzegovina,BIH,2011,0
2,Bosnia and Herzegovina,BIH,2012,0
3,Bosnia and Herzegovina,BIH,2013,0
4,Bosnia and Herzegovina,BIH,2014,0
...,...,...,...,...
2096,Vanuatu,VUT,2016,0
2097,Vanuatu,VUT,2017,0
2098,Vanuatu,VUT,2018,0
2099,Vanuatu,VUT,2019,0
2100,Vanuatu,VUT,2020,0

In [29]:
for c,y in zip(df_historical_out['iso_code3'].values,df_historical_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_historical_out.loc[(df_historical_out['iso_code3'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_metals
0,Bosnia and Herzegovina,BIH,2010,0.036354
1,Bosnia and Herzegovina,BIH,2011,0.036919
2,Bosnia and Herzegovina,BIH,2012,0.037005
3,Bosnia and Herzegovina,BIH,2013,0.036108
4,Bosnia and Herzegovina,BIH,2014,0.036263
...,...,...,...,...
2096,Vanuatu,VUT,2016,19.847368
2097,Vanuatu,VUT,2017,30.255461
2098,Vanuatu,VUT,2018,25.900125
2099,Vanuatu,VUT,2019,22.888251
2100,Vanuatu,VUT,2020,14.687625

In [30]:
#### Projected ######

years_proj=range(max(years_hist)+1,2051)

iso3 = set(df_ippu_all['iso_code3'].values)
coun_year=[]
for iso3 in iso3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        coun_year.append([count,iso3,year,0])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out[var_name]=0
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_metals
0,Bosnia and Herzegovina,BIH,2021,0
1,Bosnia and Herzegovina,BIH,2022,0
2,Bosnia and Herzegovina,BIH,2023,0
3,Bosnia and Herzegovina,BIH,2024,0
4,Bosnia and Herzegovina,BIH,2025,0
...,...,...,...,...
5725,Vanuatu,VUT,2046,0
5726,Vanuatu,VUT,2047,0
5727,Vanuatu,VUT,2048,0
5728,Vanuatu,VUT,2049,0
5729,Vanuatu,VUT,2050,0

In [31]:
y_hist_max = max(years_hist)
for c,y in zip(df_projected_out['iso_code3'].values,df_projected_out['Year'].values):
    
    tonne = df_ippu_all.loc[(df_ippu_all['iso_code3']==c)&(df_ippu_all['Year']==y)][IPPU_var].values[0]
    
    count = df_countries.loc[df_countries['ISO3']==c]['Country Name'].values[0]

    if count in df_enduse['COUNTRY'].values:
        
        tj= float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(y_hist_max)].values[0])*1e3

        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== count]['sub_region'].values[0]
            tj = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y_hist_max), 'meanEEI'].values[0]*1e3
            
        except:
            tj=golbal_mean[y_hist_max]*1e3
            
        if tonne!=0:
            dato=tj/tonne
        else:
            print(count,y,IPPU_var+f'={tonne}')
            dato=0
        
        df_projected_out.loc[(df_projected_out['iso_code3'] == c) & 
                        (df_projected_out['Year']== y), var_name] = dato
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_tj_per_tonne_production_metals
0,Bosnia and Herzegovina,BIH,2021,0.027862
1,Bosnia and Herzegovina,BIH,2022,0.027367
2,Bosnia and Herzegovina,BIH,2023,0.026881
3,Bosnia and Herzegovina,BIH,2024,0.026403
4,Bosnia and Herzegovina,BIH,2025,0.025934
...,...,...,...,...
5725,Vanuatu,VUT,2046,0.303185
5726,Vanuatu,VUT,2047,0.259596
5727,Vanuatu,VUT,2048,0.222274
5728,Vanuatu,VUT,2049,0.190318
5729,Vanuatu,VUT,2050,0.162956

In [32]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [33]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')

In [62]:
#Mexico
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Mexico')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='MEX')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Mexico')]['2015'].values[0]
print('Mexico')
print(hist_val*ippu_val/1000,iea_val)

#Brazil
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Brazil')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='BRA')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Brazil')]['2015'].values[0]

print('Brazil')
print(hist_val*ippu_val/1000,iea_val)

#Chile
hist_val=df_historical_out.loc[(df_historical_out['Nation']=='Chile')
                               &(df_historical_out['Year']==2015)][var_name].values[0]

ippu_val=df_ippu_all.loc[(df_ippu_all['iso_code3']=='CHL')&(df_ippu_all['Year']==2015)][IPPU_var].values[0]

iea_val =df_enduse.loc[(df_enduse['COUNTRY']=='Chile')]['2015'].values[0]

print('Chile')

print(hist_val*ippu_val/1000,iea_val)

Mexico
227.01000000000002 227.01
Brazil
996.82 996.82
Chile
17.53 17.53