In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'frac_scoe_heat_energy_residential_diesel'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [3]:
df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

In [4]:
df_WEBH2021.columns = df_WEBH2021.iloc[0]
df_WEBH2021

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
0,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
1,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1368.251838,1648.414248,1685.223676,1640.362098,...,9782.067241,10272.36221,11074.77871,11950.78794,12501.00154,12223.55369,12264.16248,12034.6322,12596.41582,12331.64135
2,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0,0,0,0,...,6.755636,3.635428,2.57749,5.287409,6.978797,6.829994,7.916741,12.735731,17.037944,19.629498
3,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-541.424001,-614.718001,-738.939398,-745.382946,...,-7720.391726,-8171.019358,-9101.059456,-10166.8869,-10634.4478,-10552.5051,-10248.0298,-10333.3662,-10629.0366,-10541.275
4,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),884.29747,923.250159,945.54188,928.32307,...,2013.814178,1968.848884,1831.204342,1736.61351,1797.035545,1863.051458,1872.030679,1797.650326,1744.105366,1648.774748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),..,..,..,..,...,17887289.48,18253458.88,18833000.52,19281187.98,19434697.21,19950693.71,20589646.76,21366327.3,21641349.85,21619592.25
6157,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3905413.008,4241816.367,4606277.139,4552612.92,...,15126682.35,15451913.86,15781936.88,16046172.63,16094265.01,16339136.28,16687929.51,17081705.24,17007627.45,..
6158,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),111087,152475,203196,272711,...,2582639.326,2460285.54,2479105.211,2535404.549,2570070.656,2608401.808,2636117.238,2709100.699,2789694.402,2678855.226
6159,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1240596.11,1304208.694,1321597.846,1460175.28,...,4410656.504,4729751.103,5060522.017,5302668.714,5511268.895,5891550.903,6250190.754,6679673.151,7014495.554,..
6160,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5257164.118,5698587.061,6131142.985,6287520.2,...,22213368.54,22736539.43,23420063.22,23984892.89,24274857.25,24947744.76,25688502.59,26595243.41,26935958.13,..

In [5]:
df_sector=df_WEBH2021[df_WEBH2021['Flow']=='Residential (PJ)']
df_sector

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
10,Australia,"Coal, peat and oil shale",Residential (PJ),01. Australia,"01. Coal, peat and oil shale",10. Residential (PJ),9.914581,9.851025,7.838452,14.835582,...,0.103502,0.066599,0.051301,0,0.020997,0.020997,0.020997,0.020997,0.020997,..
22,Australia,"Crude, NGL and feedstocks",Residential (PJ),01. Australia,"02. Crude, NGL and feedstocks",10. Residential (PJ),0,0,0,0,...,0,0,0,0,0,0,0,0,0,..
34,Australia,Oil products,Residential (PJ),01. Australia,03. Oil products,10. Residential (PJ),32.303699,32.775602,32.9901,42.169801,...,16.039212,15.7238,16.071304,15.827096,15.406813,16.884083,14.843525,14.942216,15.409676,..
46,Australia,Natural gas,Residential (PJ),01. Australia,04. Natural gas,10. Residential (PJ),10.5849,17.811899,19.522801,21.2337,...,133.246798,135.72,139.3245,143.0235,146.044799,149.199302,149.172301,149.077801,151.901098,..
58,Australia,Nuclear,Residential (PJ),01. Australia,05. Nuclear,10. Residential (PJ),0,0,0,0,...,0,0,0,0,0,0,0,0,0,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5890,World,Nuclear,Residential (PJ),55. World,05. Nuclear,10. Residential (PJ),0,0,0,0,...,0,0,0,0,0,0,0,0,0,..
5902,World,Renewables and waste,Residential (PJ),55. World,06. Renewables and waste,10. Residential (PJ),18272.86443,18652.85152,19033.04768,19356.45715,...,29331.14359,29273.91702,29599.39008,29569.35822,29270.43152,29068.41767,29380.23783,29319.70703,29558.52518,..
5914,World,Electricity,Residential (PJ),55. World,07. Electricity,10. Residential (PJ),3587.91721,3982.541741,4243.32306,4332.110384,...,17994.87957,18427.19406,19030.65892,19313.6658,19762.22955,20442.48236,20775.60218,21598.15567,21858.8491,..
5926,World,Heat,Residential (PJ),55. World,08. Heat,10. Residential (PJ),417.332001,465.811997,479.873997,499.158996,...,4559.189475,4632.78528,4509.196671,4404.722488,4296.095782,4149.552766,4241.743875,4647.482313,4612.669799,..
5938,World,Total,Residential (PJ),55. World,11. Total,10. Residential (PJ),42544.78404,44125.07055,44808.79334,44498.80647,...,81087.67469,80741.55306,82798.64156,82515.3414,82834.88729,83816.75966,85461.94685,87657.27847,87779.99592,..

In [22]:
nation_in_df=np.unique(df_sector['Country'].values)
nation_in_df

array(['Africa', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Canada',
       'Chile', 'Colombia', 'Czech Republic', 'Denmark', 'Estonia',
       'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'IEA Total',
       'IEA and Accession/Association countries', 'Iceland', 'India',
       'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Korea',
       'Latvia', 'Lithuania', 'Luxembourg', 'Mexico', 'Middle East',
       'Morocco', 'Netherlands', 'New Zealand', 'Non-OECD Americas',
       'Non-OECD Asia (including China)', 'Non-OECD Europe and Eurasia',
       'Non-OECD Total', 'Norway', 'OECD Total',
       "People's Republic of China", 'Poland', 'Portugal', 'Singapore',
       'Slovak Republic', 'Slovenia', 'South Africa', 'Spain', 'Sweden',
       'Switzerland', 'Thailand', 'Turkey', 'United Kingdom',
       'United States', 'World'], dtype=object)

In [93]:
df_fuel=df_sector[df_sector['Product']=='Coal, peat and oil shale']
df_fuel.replace(to_replace='..', value=0,inplace=True)
df_fuel

/var/folders/1d/nrx88sbx37qdy3x76g9yk83r0000gn/T/ipykernel_90915/2780761788.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fuel.replace(to_replace='..', value=0,inplace=True)

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
10,Australia,"Coal, peat and oil shale",Residential (PJ),01. Australia,"01. Coal, peat and oil shale",10. Residential (PJ),9.914581,9.851025,7.838452,14.835582,...,0.103502,0.066599,0.051301,0.000000,0.020997,0.020997,0.020997,0.020997,0.020997,0
118,Austria,"Coal, peat and oil shale",Residential (PJ),02. Austria,"01. Coal, peat and oil shale",10. Residential (PJ),60.739411,56.849513,59.379450,52.217569,...,1.674515,1.761395,1.334174,1.103645,0.899902,0.860145,0.941029,0.780591,0.805318,0
226,Belgium,"Coal, peat and oil shale",Residential (PJ),03. Belgium,"01. Coal, peat and oil shale",10. Residential (PJ),93.351719,87.928733,90.116306,88.320550,...,4.117454,4.024704,4.905761,3.340229,3.317491,3.211037,3.077934,2.518168,1.924802,0
334,Canada,"Coal, peat and oil shale",Residential (PJ),04. Canada,"01. Coal, peat and oil shale",10. Residential (PJ),27.433584,22.291377,16.720982,14.496171,...,0.771045,0.644876,0.588798,0.504685,0.266360,0.266360,0.322438,0.308416,0.252343,0
442,Chile,"Coal, peat and oil shale",Residential (PJ),05. Chile,"01. Coal, peat and oil shale",10. Residential (PJ),1.507499,1.606500,1.685702,1.709998,...,0.309601,0.356401,0.511200,0.101702,0.098101,0.064799,0.052900,0.028818,0.000000,0
550,Colombia,"Coal, peat and oil shale",Residential (PJ),06. Colombia,"01. Coal, peat and oil shale",10. Residential (PJ),6.422505,6.340863,6.313648,6.259220,...,2.993541,2.993541,2.639756,3.401750,2.666971,2.694185,2.673368,2.567802,2.713700,0
658,Czech Republic,"Coal, peat and oil shale",Residential (PJ),07. Czech Republic,"01. Coal, peat and oil shale",10. Residential (PJ),321.094970,302.581397,272.261943,242.245648,...,37.223759,39.264845,40.926154,34.754706,34.771567,34.331936,35.070299,32.921642,28.885809,0
766,Denmark,"Coal, peat and oil shale",Residential (PJ),08. Denmark,"01. Coal, peat and oil shale",10. Residential (PJ),12.013265,10.621120,9.156783,8.188962,...,0.018301,0.018301,0.018301,0.000000,0.000000,0.000825,0.000000,0.000000,0.000000,0
874,Estonia,"Coal, peat and oil shale",Residential (PJ),09. Estonia,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.448469,0.412425,0.411542,0.342078,0.215001,0.081450,0.087998,0.043999,0.049882,0
982,Finland,"Coal, peat and oil shale",Residential (PJ),10. Finland,"01. Coal, peat and oil shale",10. Residential (PJ),7.210415,11.358332,4.716606,4.497929,...,0.235294,0.235734,0.198362,0.184571,0.150750,0.159199,0.148799,0.152550,0.156599,0
1090,France,"Coal, peat and oil shale",Residential (PJ),11. France,"01. Coal, peat and oil shale",10. Residential (PJ),317.269424,283.819366,268.674149,252.558984,...,1.696508,1.889800,1.985728,1.471221,1.522898,1.581610,1.490287,1.103469,1.023786,0
1198,Germany,"Coal, peat and oil shale",Residential (PJ),12. Germany,"01. Coal, peat and oil shale",10. Residential (PJ),741.583743,694.849442,645.762993,617.604427,...,36.248603,31.101430,28.957228,23.980521,25.153658,21.753763,20.949763,20.618956,14.460181,0
1306,Greece,"Coal, peat and oil shale",Residential (PJ),13. Greece,"01. Coal, peat and oil shale",10. Residential (PJ),1.674490,1.679820,1.813018,1.500700,...,0.187460,0.016048,0.036568,0.120911,0.195243,0.081538,0.185241,0.150536,0.142699,0
1414,Hungary,"Coal, peat and oil shale",Residential (PJ),14. Hungary,"01. Coal, peat and oil shale",10. Residential (PJ),68.661284,62.676287,64.923230,60.099203,...,7.200454,6.368081,5.589269,4.288460,3.963928,5.047623,5.930435,3.984975,2.954583,0
1522,Iceland,"Coal, peat and oil shale",Residential (PJ),15. Iceland,"01. Coal, peat and oil shale",10. Residential (PJ),0.026377,0.026377,0.026377,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1630,Ireland,"Coal, peat and oil shale",Residential (PJ),16. Ireland,"01. Coal, peat and oil shale",10. Residential (PJ),50.057841,46.591368,40.299059,46.774925,...,18.892855,18.707472,20.094187,17.946103,17.861471,16.313046,15.934982,17.429820,14.162412,0
1738,Israel,"Coal, peat and oil shale",Residential (PJ),17. Israel,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1846,Italy,"Coal, peat and oil shale",Residential (PJ),18. Italy,"01. Coal, peat and oil shale",10. Residential (PJ),57.861697,49.921335,36.616677,39.962684,...,0.151558,0.101312,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1954,Japan,"Coal, peat and oil shale",Residential (PJ),19. Japan,"01. Coal, peat and oil shale",10. Residential (PJ),199.148994,183.418194,179.454898,177.085780,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2062,Korea,"Coal, peat and oil shale",Residential (PJ),20. Korea,"01. Coal, peat and oil shale",10. Residential (PJ),194.804787,202.508386,250.694401,263.020164,...,35.089897,34.150622,35.715627,30.349900,27.443465,23.381905,20.896905,19.229998,12.476517,0
2170,Latvia,"Coal, peat and oil shale",Residential (PJ),21. Latvia,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.974067,0.576841,0.529320,0.531565,0.502110,0.498120,0.409871,0.276011,0.194912,0
2278,Lithuania,"Coal, peat and oil shale",Residential (PJ),22. Lithuania,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2.763795,2.732226,2.838659,2.405283,1.944321,2.122088,2.401699,2.475027,1.928683,0
2386,Luxembourg,"Coal, peat and oil shale",Residential (PJ),23. Luxembourg,"01. Coal, peat and oil shale",10. Residential (PJ),2.478916,1.929868,1.425208,1.517443,...,0.022789,0.018744,0.026582,0.020842,0.025803,0.024556,0.015943,0.009944,0.010413,0
2494,Mexico,"Coal, peat and oil shale",Residential (PJ),24. Mexico,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2602,Netherlands,"Coal, peat and oil shale",Residential (PJ),25. Netherlands,"01. Coal, peat and oil shale",10. Residential (PJ),20.744979,15.802017,9.900915,6.274791,...,0.080001,0.080001,0.040001,0.026448,0.022584,0.045109,0.047160,0.042391,0.046921,0
2710,New Zealand,"Coal, peat and oil shale",Residential (PJ),26. New Zealand,"01. Coal, peat and oil shale",10. Residential (PJ),6.263440,6.086422,5.909890,5.566912,...,0.688825,0.450625,0.315387,0.328869,0.370925,0.326244,0.281445,0.298305,0.253867,0
2818,Norway,"Coal, peat and oil shale",Residential (PJ),27. Norway,"01. Coal, peat and oil shale",10. Residential (PJ),10.816481,8.211759,2.636558,2.899937,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2926,Poland,"Coal, peat and oil shale",Residential (PJ),28. Poland,"01. Coal, peat and oil shale",10. Residential (PJ),399.558876,392.254463,397.985410,413.913734,...,284.965088,300.920028,289.755893,265.455299,260.055801,275.730946,274.404450,257.671205,208.451837,0
3034,Portugal,"Coal, peat and oil shale",Residential (PJ),29. Portugal,"01. Coal, peat and oil shale",10. Residential (PJ),4.207948,1.861338,2.396587,1.424098,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3142,Slovak Republic,"Coal, peat and oil shale",Residential (PJ),30. Slovak Republic,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2.000943,1.866856,1.108250,0.820843,0.748516,1.239050,1.448428,1.260424,1.184387,0
3250,Slovenia,"Coal, peat and oil shale",Residential (PJ),31. Slovenia,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.037786,0.018903,0.019029,0.019058,0.000000,0.000000,0.004672,0.003165,0.002793,0
3358,Spain,"Coal, peat and oil shale",Residential (PJ),32. Spain,"01. Coal, peat and oil shale",10. Residential (PJ),52.601565,52.455119,20.849280,26.816069,...,5.112100,4.591902,3.968626,3.845500,3.709002,3.310197,3.321049,2.861799,2.718502,0
3466,Sweden,"Coal, peat and oil shale",Residential (PJ),33. Sweden,"01. Coal, peat and oil shale",10. Residential (PJ),9.695796,5.478269,5.996067,5.323282,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3574,Switzerland,"Coal, peat and oil shale",Residential (PJ),34. Switzerland,"01. Coal, peat and oil shale",10. Residential (PJ),15.955660,13.059601,12.696739,10.289685,...,0.306001,0.306001,0.306001,0.204002,0.204002,0.204002,0.100010,0.100010,0.100010,0
3682,Turkey,"Coal, peat and oil shale",Residential (PJ),35. Turkey,"01. Coal, peat and oil shale",10. Residential (PJ),46.947267,61.775677,54.379008,59.393505,...,126.999218,128.286679,90.859694,77.395862,82.408123,85.952103,82.116701,72.575134,54.337057,0
3790,United Kingdom,"Coal, peat and oil shale",Residential (PJ),36. United Kingdom,"01. Coal, peat and oil shale",10. Residential (PJ),809.513342,688.152358,612.271327,547.455836,...,28.922306,27.451512,28.036241,23.691167,23.223945,23.090960,22.843118,22.249451,20.341308,0
3898,United States,"Coal, peat and oil shale",Residential (PJ),37. United States,"01. Coal, peat and oil shale",10. Residential (PJ),163.539046,130.240090,132.942811,112.008770,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4006,OECD Total,"Coal, peat and oil shale",Residential (PJ),38. OECD Total,"01. Coal, peat and oil shale",10. Residential (PJ),3713.099900,3412.226417,3215.844475,3084.262558,...,600.235734,609.413907,561.767637,496.635218,491.762934,502.393789,495.177923,461.683603,369.600317,0
4114,Brazil,"Coal, peat and oil shale",Residential (PJ),39. Brazil,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4222,People's Republic of China,"Coal, peat and oil shale",Residential (PJ),40. People's Republic of China,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2101.430081,2100.070293,2081.220758,2079.075873,2118.785293,2069.029320,2013.047001,1672.126667,1423.038624,0
4330,India,"Coal, peat and oil shale",Residential (PJ),41. India,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,113.941463,115.932898,119.400624,112.714157,107.700364,112.609002,116.804682,114.036985,113.135400,0
4438,Indonesia,"Coal, peat and oil shale",Residential (PJ),42. Indonesia,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.399998,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4546,Morocco,"Coal, peat and oil shale",Residential (PJ),43. Morocco,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4654,Singapore,"Coal, peat and oil shale",Residential (PJ),44. Singapore,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4762,South Africa,"Coal, peat and oil shale",Residential (PJ),45. South Africa,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,97.023626,159.978298,168.212080,172.882384,151.204599,133.830727,224.019963,222.789295,224.717673,0
4870,Thailand,"Coal, peat and oil shale",Residential (PJ),46. Thailand,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4978,Non-OECD Total,"Coal, peat and oil shale",Residential (PJ),47. Non-OECD Total,"01. Coal, peat and oil shale",10. Residential (PJ),1831.671154,1915.351762,1954.066063,1953.435046,...,2607.542054,2637.348252,2605.363675,2663.775493,2706.603472,2646.419473,2762.432578,2417.834851,2160.869767,0
5086,Africa,"Coal, peat and oil shale",Residential (PJ),48. Africa,"01. Coal, peat and oil shale",10. Residential (PJ),104.793561,102.402446,99.254203,100.644697,...,97.524003,160.612899,168.426737,173.073440,151.294041,133.970625,224.222098,223.033335,224.954294,0
5194,Non-OECD Americas,"Coal, peat and oil shale",Residential (PJ),49. Non-OECD Americas,"01. Coal, peat and oil shale",10. Residential (PJ),0.406300,0.402699,0.408858,0.397160,...,0.126881,0.126881,0.107358,0.087839,0.078080,0.068320,0.048801,0.048801,0.048948,0
5302,Non-OECD Asia (including China),"Coal, peat and oil shale",Residential (PJ),50. Non-OECD Asia (including China),"01. Coal, peat and oil shale",10. Residential (PJ),1669.332522,1756.065433,1785.478411,1767.572083,...,2278.330290,2275.594811,2268.482112,2251.778530,2299.017956,2234.478991,2232.178156,1876.641970,1624.863025,0
5410,Non-OECD Europe and Eurasia,"Coal, peat and oil shale",Residential (PJ),51. Non-OECD Europe and Eurasia,"01. Coal, peat and oil shale",10. Residential (PJ),57.138771,56.481184,68.924592,84.821106,...,231.199680,200.652461,167.986269,238.474484,255.852195,277.540339,305.622324,317.749545,310.642301,0
5518,Middle East,"Coal, peat and oil shale",Residential (PJ),52. Middle East,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.361199,0.361199,0.361199,0.361199,0.361199,0.361199,0.361199,0.361199,0.361199,0
5626,IEA Total,"Coal, peat and oil shale",Residential (PJ),53. IEA Total,"01. Coal, peat and oil shale",10. Residential (PJ),3705.143519,3404.252677,3207.818748,3076.293340,...,593.156944,602.735994,555.229673,490.175861,486.551432,497.014597,489.635412,456.332780,364.760229,0
5734,IEA and Accession/Association countries,"Coal, peat and oil shale",Residential (PJ),54. IEA and Accession/Association countries,"01. Coal, peat and oil shale",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2911.619052,2984.799651,2930.452747,2860.757010,2868.951080,2817.364717,2848.635026,2470.357374,2130.294308,0
5842,World,"Coal, peat and oil shale",Residential (PJ),55. World,"01. Coal, peat and oil shale",10. Residential (PJ),5544.771054,5327.578179,5169.910538,5037.697603,...,3207.777788,3246.762159,3167.131312,3160.410711,3198.366406,3148.813263,3257.610501,2879.518454,2530.470084,0

In [92]:
df_total=df_sector[df_sector['Product']=='Total']
df_total.replace(to_replace='..', value=0,inplace=True)
df_total

/var/folders/1d/nrx88sbx37qdy3x76g9yk83r0000gn/T/ipykernel_90915/4275656317.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total.replace(to_replace='..', value=0,inplace=True)

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
106,Australia,Total,Residential (PJ),01. Australia,11. Total,10. Residential (PJ),196.399979,212.985129,211.313754,224.106886,...,438.581715,437.586601,438.944903,432.391196,439.140410,442.866783,441.313259,441.665616,443.395045,0.000000
214,Austria,Total,Residential (PJ),02. Austria,11. Total,10. Residential (PJ),212.298711,216.635415,239.341947,217.246964,...,270.683562,275.682011,285.731800,256.974844,272.049518,283.365375,285.150643,266.948836,273.234839,0.000000
322,Belgium,Total,Residential (PJ),03. Belgium,11. Total,10. Residential (PJ),390.712519,437.585236,462.558501,435.455147,...,334.193240,353.962962,379.763857,312.160301,344.509837,345.939165,340.029735,336.961812,327.153111,0.000000
430,Canada,Total,Residential (PJ),04. Canada,11. Total,10. Residential (PJ),1092.521985,1141.333579,1065.093081,1118.257277,...,1464.411643,1403.783572,1460.280905,1501.481688,1451.020360,1397.483263,1440.686534,1489.490140,1482.135038,0.000000
538,Chile,Total,Residential (PJ),05. Chile,11. Total,10. Residential (PJ),82.491097,86.939002,88.659501,86.386998,...,233.947105,249.712596,256.031792,170.419804,166.296313,183.409950,184.276752,192.729859,193.747059,0.000000
646,Colombia,Total,Residential (PJ),06. Colombia,11. Total,10. Residential (PJ),200.866566,175.051356,181.444436,176.924559,...,209.034560,208.365669,259.474770,261.625445,257.973798,257.364823,248.336383,257.614432,252.304904,0.000000
754,Czech Republic,Total,Residential (PJ),07. Czech Republic,11. Total,10. Residential (PJ),339.865768,323.210694,294.673545,267.272048,...,285.482799,295.658343,301.668134,271.339692,279.902891,292.740487,296.747723,289.181954,286.660809,0.000000
862,Denmark,Total,Residential (PJ),08. Denmark,11. Total,10. Residential (PJ),276.379067,273.715324,290.123787,251.799565,...,184.163423,181.686257,183.036471,168.648449,180.437795,185.775002,181.871125,178.787668,174.673208,0.000000
970,Estonia,Total,Residential (PJ),09. Estonia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,39.162473,40.649624,39.086738,37.187978,35.902802,38.965853,39.464496,39.403273,39.834099,0.000000
1078,Finland,Total,Residential (PJ),10. Finland,11. Total,10. Residential (PJ),146.005016,162.261335,179.625008,146.018527,...,213.128673,228.387834,216.385442,214.443094,207.146372,223.533017,220.204930,216.707160,213.260210,0.000000
1186,France,Total,Residential (PJ),11. France,11. Total,10. Residential (PJ),865.578023,852.415272,896.025153,870.860584,...,1624.496767,1783.345391,1864.758094,1532.689601,1612.284592,1681.324283,1646.368657,1583.696322,1564.583325,0.000000
1294,Germany,Total,Residential (PJ),12. Germany,11. Total,10. Residential (PJ),2357.073548,2427.241339,2545.415394,2322.654623,...,2319.185847,2448.423734,2584.221089,2203.862421,2263.907618,2343.329661,2324.112006,2293.238166,2368.031903,0.000000
1402,Greece,Total,Residential (PJ),13. Greece,11. Total,10. Residential (PJ),69.715487,74.477223,82.045018,76.889900,...,231.364364,213.360048,159.991666,160.977214,186.757544,182.070438,182.198722,160.982908,169.214575,0.000000
1510,Hungary,Total,Residential (PJ),14. Hungary,11. Total,10. Residential (PJ),132.601286,138.529682,158.746529,156.786604,...,274.962053,266.873980,259.914471,229.683464,249.878921,257.751922,263.311440,243.300173,237.280781,0.000000
1618,Iceland,Total,Residential (PJ),15. Iceland,11. Total,10. Residential (PJ),16.320774,17.006375,18.635376,18.470801,...,17.010282,17.423887,16.915057,17.591288,17.831242,18.177001,17.315077,19.431173,19.008675,0.000000
1726,Ireland,Total,Residential (PJ),16. Ireland,11. Total,10. Residential (PJ),75.427840,74.574767,75.601458,81.259922,...,129.982987,123.673906,120.979340,108.929290,114.807310,115.816116,115.194883,124.111850,118.042543,0.000000
1834,Israel,Total,Residential (PJ),17. Israel,11. Total,10. Residential (PJ),6.193198,11.188800,12.144596,12.296703,...,145.244702,116.213803,70.966201,73.479604,85.028352,87.261876,89.565851,88.040127,94.222527,0.000000
1942,Italy,Total,Residential (PJ),18. Italy,11. Total,10. Residential (PJ),994.460099,1081.926433,1121.276173,1143.869185,...,1355.604758,1438.096115,1433.167598,1237.031095,1360.478997,1347.525804,1373.141430,1331.649229,1299.675148,0.000000
2050,Japan,Total,Residential (PJ),19. Japan,11. Total,10. Residential (PJ),719.450995,764.216692,876.032697,887.450980,...,2013.123126,2033.093613,1979.025471,1897.918639,1845.976725,1847.932262,1923.516613,1772.191731,1753.015128,0.000000
2158,Korea,Total,Residential (PJ),20. Korea,11. Total,10. Residential (PJ),200.879185,209.321687,259.255503,272.051063,...,843.420297,849.581223,849.429025,798.679193,797.039768,868.267406,894.734647,898.942816,862.202403,0.000000
2266,Latvia,Total,Residential (PJ),21. Latvia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,55.587269,57.632537,53.069017,51.865367,46.299209,47.886320,50.068995,51.550477,49.749463,0.000000
2374,Lithuania,Total,Residential (PJ),22. Lithuania,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,64.129894,64.235623,61.409257,58.634283,56.909016,60.009790,60.935621,62.358342,59.616582,0.000000
2482,Luxembourg,Total,Residential (PJ),23. Luxembourg,11. Total,10. Residential (PJ),17.258320,19.901870,21.257606,19.704144,...,19.995227,20.516953,20.841078,19.569124,21.266365,21.926979,22.334259,20.885316,19.266163,0.000000
2590,Mexico,Total,Residential (PJ),24. Mexico,11. Total,10. Residential (PJ),334.483699,346.425399,359.763401,351.560099,...,750.961798,754.637499,734.562500,742.782805,744.104402,743.776303,740.356106,752.070601,740.666155,0.000000
2698,Netherlands,Total,Residential (PJ),25. Netherlands,11. Total,10. Residential (PJ),449.476179,522.539021,546.842918,483.608396,...,429.377747,453.747251,476.471485,380.201939,398.042677,409.933925,400.507617,400.550415,385.194355,0.000000
2806,New Zealand,Total,Residential (PJ),26. New Zealand,11. Total,10. Residential (PJ),34.873239,36.925524,37.012694,42.387812,...,62.365208,62.933265,61.785977,62.680784,62.421897,62.475275,62.952302,63.445369,64.804467,0.000000
2914,Norway,Total,Residential (PJ),27. Norway,11. Total,10. Residential (PJ),79.446284,80.422558,78.451756,75.004336,...,165.613802,173.718706,171.616300,159.824299,166.935399,169.105195,171.181802,171.993078,170.181174,0.000000
3022,Poland,Total,Residential (PJ),28. Poland,11. Total,10. Residential (PJ),563.710480,575.738566,577.626407,620.403231,...,840.668589,868.784228,854.629394,792.837100,791.832100,826.636743,832.959816,806.500043,751.916259,0.000000
3130,Portugal,Total,Residential (PJ),29. Portugal,11. Total,10. Residential (PJ),34.647152,33.139941,33.842788,31.392903,...,116.237706,112.806497,110.289393,107.386798,106.257337,109.040169,108.005448,110.757130,110.867213,0.000000
3238,Slovak Republic,Total,Residential (PJ),30. Slovak Republic,11. Total,10. Residential (PJ),27.211998,28.665203,30.321099,33.079802,...,88.807140,86.670352,89.889646,81.722643,83.219420,85.001150,88.284573,86.140982,109.490874,0.000000
3346,Slovenia,Total,Residential (PJ),31. Slovenia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,54.083584,51.906305,51.098228,43.537260,47.621999,48.249198,46.890887,43.809289,42.612706,0.000000
3454,Spain,Total,Residential (PJ),32. Spain,11. Total,10. Residential (PJ),190.634768,197.862821,151.904381,160.673667,...,653.632372,649.413677,622.620498,615.374562,622.409529,630.497581,605.133674,620.523740,608.814160,0.000000
3562,Sweden,Total,Residential (PJ),33. Sweden,11. Total,10. Residential (PJ),425.456595,435.301671,449.770063,372.107682,...,321.528254,337.098351,322.054605,302.594631,310.209608,320.601233,322.666284,313.603420,308.310204,0.000000
3670,Switzerland,Total,Residential (PJ),34. Switzerland,11. Total,10. Residential (PJ),50.970560,48.008901,53.100741,49.495282,...,216.226503,233.751405,247.385150,209.032048,220.916803,228.446156,223.465606,211.350129,213.260838,0.000000
3778,Turkey,Total,Residential (PJ),35. Turkey,11. Total,10. Residential (PJ),368.643268,411.302678,422.033610,430.442509,...,869.907024,844.394176,828.495992,801.329764,843.622322,866.989502,927.477056,860.454531,902.594518,0.000000
3886,United Kingdom,Total,Residential (PJ),36. United Kingdom,11. Total,10. Residential (PJ),1363.254343,1367.046856,1409.568424,1438.112536,...,1578.403411,1711.238115,1731.047939,1494.246768,1554.030642,1587.143130,1539.357373,1604.515955,1592.031684,0.000000
3994,United States,Total,Residential (PJ),37. United States,11. Total,10. Residential (PJ),9757.860947,10219.823590,9944.821806,9556.478865,...,10974.263580,10052.821620,11067.316290,11333.238170,10713.641620,10352.169920,10254.203500,11343.711960,11334.184690,0.000000
4102,OECD Total,Total,Residential (PJ),38. OECD Total,11. Total,10. Residential (PJ),22073.168970,23003.719940,23174.329150,22430.509600,...,29888.973480,29501.867730,30664.355570,29144.372650,28958.111510,28970.789060,28964.321820,29749.296020,29635.236840,0.000000
4210,Brazil,Total,Residential (PJ),39. Brazil,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,973.857484,994.525966,993.481682,1037.838558,1044.759569,1040.491800,1064.178060,1107.046722,1115.901670,1155.457992
4318,People's Republic of China,Total,Residential (PJ),40. People's Republic of China,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,11910.513820,12086.229300,12486.582470,12817.263820,13292.747790,13695.018860,14280.473110,14616.614860,14685.771800,0.000000
4426,India,Total,Residential (PJ),41. India,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,5991.175474,6021.646632,6099.773555,6238.077803,6346.786340,6435.927842,6508.293330,6601.284566,6702.186144,0.000000
4534,Indonesia,Total,Residential (PJ),42. Indonesia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2000.427006,1950.908203,1912.583597,1874.106297,1823.042004,1780.981101,1761.827534,1460.520289,1331.291379,0.000000
4642,Morocco,Total,Residential (PJ),43. Morocco,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,142.289202,148.168801,150.316696,156.025603,159.225503,164.205990,167.825420,169.552191,175.456956,0.000000
4750,Singapore,Total,Residential (PJ),44. Singapore,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,26.646704,27.241603,27.715904,28.280101,29.387999,30.701495,29.677022,29.455603,31.061564,0.000000
4858,South Africa,Total,Residential (PJ),45. South Africa,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,447.073697,490.334591,483.075207,475.528898,460.883601,470.604208,534.631182,521.328709,524.821543,0.000000
4966,Thailand,Total,Residential (PJ),46. Thailand,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,474.980494,498.762548,489.244373,493.839478,483.691337,406.630193,402.351886,389.570758,398.258992,0.000000
5074,Non-OECD Total,Total,Residential (PJ),47. Non-OECD Total,11. Total,10. Residential (PJ),20471.615070,21121.350610,21634.464200,22068.296870,...,51198.701210,51239.685320,52134.285980,53370.968750,53876.775770,54845.970610,56497.625020,57907.982450,58144.759080,0.000000
5182,Africa,Total,Residential (PJ),48. Africa,11. Total,10. Residential (PJ),4098.694961,4212.585207,4309.288049,4412.641929,...,11756.466970,12014.434920,12365.346120,12733.022260,12961.933550,13228.222390,13673.624550,13839.506190,14113.321760,0.000000
5290,Non-OECD Americas,Total,Residential (PJ),49. Non-OECD Americas,11. Total,10. Residential (PJ),1754.302087,1776.842851,1817.437336,1840.249769,...,2764.092983,2835.413007,2880.910540,2941.166940,2976.596802,3018.027595,2949.565008,3017.243985,2975.488870,0.000000
5398,Non-OECD Asia (including China),Total,Residential (PJ),50. Non-OECD Asia (including China),11. Total,10. Residential (PJ),13844.394910,14240.087710,14557.063120,14821.441890,...,25143.088340,25407.282890,25907.010540,26433.020550,26756.200050,27154.496210,27959.880250,28104.506390,28247.219420,0.000000
5506,Non-OECD Europe and Eurasia,Total,Residential (PJ),51. Non-OECD Europe and Eurasia,11. Total,10. Residential (PJ),588.153525,682.417070,718.004916,734.143004,...,8265.967672,7800.071851,7597.439913,7868.878643,7708.226861,7784.640102,8302.475994,9279.083846,9125.964866,0.000000
5614,Middle East,Total,Residential (PJ),52. Middle East,11. Total,10. Residential (PJ),186.069586,209.417770,232.670780,259.820281,...,3269.085247,3182.482654,3383.578866,3394.880354,3473.818515,3660.584315,3612.079224,3667.642042,3682.764173,0.000000
5722,IEA Total,Total,Residential (PJ),53. IEA Total,11. Total,10. Residential (PJ),21767.297340,22713.534400,22873.445240,22136.430540,...,29109.936090,28736.377310,29895.391250,28467.219600,28280.151580,28268.430100,28266.932260,29033.762320,28923.974920,0.000000
5830,IEA and Accession/Association countries,Total,Residential (PJ),54. IEA and Accession/Association countries,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,51729.256230,51592.722650,53186.046750,52152.339290,52486.883210,52881.038030,53599.304410,54529.878770,54488.616040,0.000000
5938,World,Total,Residential (PJ),55. World,11. Total,10. Residential (PJ),42544.784040,44125.070550,44808.793340,44498.806470,...,81087.674690,80741.553060,82798.641560,82515.341400,82834.887290,83816.759660,85461.946850,87657.278470,87779.995920,0.000000

In [40]:
#### HISTORICAL ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years=[y for y in df_total.columns if type(y)==int]

coun_year=[]
for count in zip(countries,ISO3):
    for year in years:
        coun_year.append([count[0],count[1],year])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
df_historical_out[var_name]=0
df_historical_out

         Nation iso_code3  Year  frac_scoe_heat_energy_residential_coal
0         Aruba       ABW  1971                                       0
1         Aruba       ABW  1972                                       0
2         Aruba       ABW  1973                                       0
3         Aruba       ABW  1974                                       0
4         Aruba       ABW  1975                                       0
...         ...       ...   ...                                     ...
13029  Zimbabwe       ZWE  2015                                       0
13030  Zimbabwe       ZWE  2016                                       0
13031  Zimbabwe       ZWE  2017                                       0
13032  Zimbabwe       ZWE  2018                                       0
13033  Zimbabwe       ZWE  2019                                       0

[13034 rows x 4 columns]

In [107]:
for count,year in zip(df_historical_out['Nation'].values,df_historical_out['Year'].values):
    if count in nation_in_df:
        Total=df_total.loc[df_total['Country']==count,[year]][year].values[0]
        fuel=df_fuel.loc[df_fuel['Country']==count,[year]][year].values[0]
        
        if Total!=0:
            dato=fuel/Total
            df_historical_out.loc[(df_historical_out['Nation'] == count) & 
                        (df_historical_out['Year']== year), var_name] = dato
        else:
            df_historical_out.loc[(df_historical_out['Nation'] == count) & 
                        (df_historical_out['Year']== year), var_name]=0
            
    else:
        Total=df_total.loc[df_total['Country']=='World',[year]][year].values[0]
        fuel=df_fuel.loc[df_fuel['Country']=='World',[year]][year].values[0]
        dato=fuel/Total
        df_historical_out.loc[(df_historical_out['Nation'] == count) & 
                        (df_historical_out['Year']== year), var_name] = dato
        
    
df_historical_out

         Nation iso_code3  Year  frac_scoe_heat_energy_residential_coal
0         Aruba       ABW  1971                                0.130328
1         Aruba       ABW  1972                                0.120738
2         Aruba       ABW  1973                                0.115377
3         Aruba       ABW  1974                                0.113210
4         Aruba       ABW  1975                                0.106406
...         ...       ...   ...                                     ...
13029  Zimbabwe       ZWE  2015                                0.038611
13030  Zimbabwe       ZWE  2016                                0.037568
13031  Zimbabwe       ZWE  2017                                0.038118
13032  Zimbabwe       ZWE  2018                                0.032850
13033  Zimbabwe       ZWE  2019                                0.028827

[13034 rows x 4 columns]

In [108]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [109]:
#### Projected ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years2=range(max(years)+1,2051)

coun_year=[]
for count in zip(countries,ISO3):
    for year in years2:
        coun_year.append([count[0],count[1],year])
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
df_projected_out[var_name]=0
df_projected_out

        Nation iso_code3  Year  frac_scoe_heat_energy_residential_coal
0        Aruba       ABW  2020                                       0
1        Aruba       ABW  2021                                       0
2        Aruba       ABW  2022                                       0
3        Aruba       ABW  2023                                       0
4        Aruba       ABW  2024                                       0
...        ...       ...   ...                                     ...
8241  Zimbabwe       ZWE  2046                                       0
8242  Zimbabwe       ZWE  2047                                       0
8243  Zimbabwe       ZWE  2048                                       0
8244  Zimbabwe       ZWE  2049                                       0
8245  Zimbabwe       ZWE  2050                                       0

[8246 rows x 4 columns]

In [129]:
for count,year in zip(df_projected_out['Nation'].values,df_projected_out['Year'].values):
    df_dato=df_historical_out[(df_historical_out['Nation']==count) & 
                               (df_historical_out['Year']==max(years))]
    dato=df_dato[var_name].values[0]
    df_projected_out.loc[(df_projected_out['Nation'] == count) & 
                        (df_projected_out['Year']== year), var_name] = dato
df_projected_out

        Nation iso_code3  Year  frac_scoe_heat_energy_residential_coal
0        Aruba       ABW  2020                                0.028827
1        Aruba       ABW  2021                                0.028827
2        Aruba       ABW  2022                                0.028827
3        Aruba       ABW  2023                                0.028827
4        Aruba       ABW  2024                                0.028827
...        ...       ...   ...                                     ...
8241  Zimbabwe       ZWE  2046                                0.028827
8242  Zimbabwe       ZWE  2047                                0.028827
8243  Zimbabwe       ZWE  2048                                0.028827
8244  Zimbabwe       ZWE  2049                                0.028827
8245  Zimbabwe       ZWE  2050                                0.028827

[8246 rows x 4 columns]

In [130]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')