In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

#var_name=os.path.basename(parentdir)

#var_name

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [3]:
df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

In [4]:
df_WEBH2021.columns = df_WEBH2021.iloc[0]
df_WEBH2021.replace(to_replace='..', value=0,inplace=True)
df_WEBH2021

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
0,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1.971000e+03,1.972000e+03,1.973000e+03,1.974000e+03,...,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2017,2018,2019,2020 Provisional
1,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1.368252e+03,1.648414e+03,1.685224e+03,1.640362e+03,...,9.782067e+03,1.027236e+04,1.107478e+04,1.195079e+04,1.250100e+04,1.222355e+04,12264.16248,12034.6322,12596.41582,12331.64135
2,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.755636e+00,3.635428e+00,2.577490e+00,5.287409e+00,6.978797e+00,6.829994e+00,7.916741,12.735731,17.037944,19.629498
3,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-5.414240e+02,-6.147180e+02,-7.389394e+02,-7.453829e+02,...,-7.720392e+03,-8.171019e+03,-9.101059e+03,-1.016689e+04,-1.063445e+04,-1.055251e+04,-10248.0298,-10333.3662,-10629.0366,-10541.275
4,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),8.842975e+02,9.232502e+02,9.455419e+02,9.283231e+02,...,2.013814e+03,1.968849e+03,1.831204e+03,1.736614e+03,1.797036e+03,1.863051e+03,1872.030679,1797.650326,1744.105366,1648.774748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.788729e+07,1.825346e+07,1.883300e+07,1.928119e+07,1.943470e+07,1.995069e+07,20589646.76,21366327.3,21641349.85,21619592.25
6157,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3.905413e+06,4.241816e+06,4.606277e+06,4.552613e+06,...,1.512668e+07,1.545191e+07,1.578194e+07,1.604617e+07,1.609427e+07,1.633914e+07,16687929.51,17081705.24,17007627.45,0
6158,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),1.110870e+05,1.524750e+05,2.031960e+05,2.727110e+05,...,2.582639e+06,2.460286e+06,2.479105e+06,2.535405e+06,2.570071e+06,2.608402e+06,2636117.238,2709100.699,2789694.402,2678855.226
6159,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1.240596e+06,1.304209e+06,1.321598e+06,1.460175e+06,...,4.410657e+06,4.729751e+06,5.060522e+06,5.302669e+06,5.511269e+06,5.891551e+06,6250190.754,6679673.151,7014495.554,0
6160,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5.257164e+06,5.698587e+06,6.131143e+06,6.287520e+06,...,2.221337e+07,2.273654e+07,2.342006e+07,2.398489e+07,2.427486e+07,2.494774e+07,25688502.59,26595243.41,26935958.13,0

In [15]:
np.unique(df_WEBH2021['Flow'].values)

array(['Commercial and public services (PJ)', 'Electricity output (GWh)',
       'Electricity, CHP and heat plants (PJ)', 'Exports (PJ)', 'Flow',
       'Imports (PJ)', 'Industry (PJ)',
       'Oil refineries, transformation (PJ)',
       'Other final consumption (PJ)', 'Production (PJ)',
       'Residential (PJ)', 'Total energy supply (PJ)',
       'Total final consumption (PJ)', 'Transport (PJ)'], dtype=object)

In [16]:
df_sector=df_WEBH2021[df_WEBH2021['Flow']=='Commercial and public services (PJ)']
df_sector

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
11,Australia,"Coal, peat and oil shale",Commercial and public services (PJ),01. Australia,"01. Coal, peat and oil shale",11. Commercial and public services (PJ),2.599999,3.900000,3.937652,10.945811,...,0.504798,0.306901,0.148698,0.278200,0.289500,0.324096,0.525498,0.137,0.034202,0
23,Australia,"Crude, NGL and feedstocks",Commercial and public services (PJ),01. Australia,"02. Crude, NGL and feedstocks",11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
35,Australia,Oil products,Commercial and public services (PJ),01. Australia,03. Oil products,11. Commercial and public services (PJ),5.111999,4.899000,4.686001,28.217701,...,27.966555,30.106421,31.185702,32.250041,32.663806,33.093623,34.238403,35.573381,29.091226,0
47,Australia,Natural gas,Commercial and public services (PJ),01. Australia,04. Natural gas,11. Commercial and public services (PJ),3.768300,5.652000,6.406202,5.102101,...,45.665101,45.626398,45.482402,49.212899,50.802300,52.524901,53.8713,54.533698,53.764202,0
59,Australia,Nuclear,Commercial and public services (PJ),01. Australia,05. Nuclear,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5891,World,Nuclear,Commercial and public services (PJ),55. World,05. Nuclear,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
5903,World,Renewables and waste,Commercial and public services (PJ),55. World,06. Renewables and waste,11. Commercial and public services (PJ),184.563016,195.304645,187.195098,194.875690,...,1063.109304,1153.746197,1199.814194,1282.560221,1323.421706,1340.474777,1399.54177,1457.853226,1485.429011,0
5915,World,Electricity,Commercial and public services (PJ),55. World,07. Electricity,11. Commercial and public services (PJ),2310.878444,2529.898564,2804.874618,2930.698797,...,15069.814830,15446.078540,15748.832400,15870.082570,16256.021070,16626.937880,16882.1924,17306.27419,17457.92597,0
5927,World,Heat,Commercial and public services (PJ),55. World,08. Heat,11. Commercial and public services (PJ),31.310000,34.367000,35.670996,41.686996,...,1375.711263,1408.997671,1465.923401,1472.012863,1439.333880,1538.109393,1629.813932,1667.594816,1722.476533,0
5939,World,Total,Commercial and public services (PJ),55. World,11. Total,11. Commercial and public services (PJ),13840.128990,14740.608420,15284.958120,15036.998090,...,29717.380930,30014.417850,31154.998270,31077.878070,31617.208860,32234.671810,32754.93312,33444.44712,33658.59355,0

In [17]:
df_total=df_sector[df_sector['Product']=='Total']
df_total

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
107,Australia,Total,Commercial and public services (PJ),01. Australia,11. Total,11. Commercial and public services (PJ),38.685496,42.790201,47.231856,81.678816,...,296.321256,297.161312,305.924205,312.095146,327.745208,331.154218,338.15852,343.932084,340.600237,0
215,Austria,Total,Commercial and public services (PJ),02. Austria,11. Total,11. Commercial and public services (PJ),15.381725,19.067198,20.759620,21.695947,...,103.543608,102.987727,101.832518,96.390306,99.097658,96.707435,103.791513,101.592731,104.088148,0
323,Belgium,Total,Commercial and public services (PJ),03. Belgium,11. Total,11. Commercial and public services (PJ),38.036404,43.108000,44.549403,30.695403,...,181.661722,189.780296,201.853160,174.959263,190.173139,191.616966,191.821642,192.029483,190.136727,0
431,Canada,Total,Commercial and public services (PJ),04. Canada,11. Total,11. Commercial and public services (PJ),695.727598,788.937033,707.226866,752.371092,...,992.381399,955.015997,985.731199,1036.537297,1017.174598,1015.810204,1092.383201,1169.699697,1192.683098,0
539,Chile,Total,Commercial and public services (PJ),05. Chile,11. Total,11. Commercial and public services (PJ),3.928500,4.350600,4.498202,4.924803,...,66.379696,59.917701,64.082198,65.449062,67.269282,75.252731,83.550537,79.917236,78.956491,0
647,Colombia,Total,Commercial and public services (PJ),06. Colombia,11. Total,11. Commercial and public services (PJ),11.567894,10.318787,8.707882,11.636825,...,64.032614,70.732988,61.692812,64.400282,63.836755,64.798379,73.896827,69.266461,78.233134,0
755,Czech Republic,Total,Commercial and public services (PJ),07. Czech Republic,11. Total,11. Commercial and public services (PJ),25.935978,26.133415,26.013581,26.879888,...,130.914466,126.979845,125.689453,121.979726,124.217780,128.919690,132.571367,130.245633,132.803856,0
863,Denmark,Total,Commercial and public services (PJ),08. Denmark,11. Total,11. Commercial and public services (PJ),0.469001,0.929202,13.434700,12.977502,...,81.549519,82.829474,82.242560,77.337062,79.377851,80.815171,83.033434,82.668739,81.180641,0
971,Estonia,Total,Commercial and public services (PJ),09. Estonia,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,16.852096,17.745693,17.508695,19.170411,19.496399,20.868987,19.631872,20.537175,19.563116,0
1079,Finland,Total,Commercial and public services (PJ),10. Finland,11. Total,11. Commercial and public services (PJ),10.098001,11.390399,12.675600,12.708001,...,119.939038,126.783899,121.601620,120.884819,114.484952,120.886109,122.297265,126.983509,124.188108,0
1187,France,Total,Commercial and public services (PJ),11. France,11. Total,11. Commercial and public services (PJ),1081.670398,1329.754501,1533.502297,1295.312004,...,871.739594,934.298136,964.051153,886.586485,918.786276,921.373786,936.515587,919.819294,902.611316,0
1295,Germany,Total,Commercial and public services (PJ),12. Germany,11. Total,11. Commercial and public services (PJ),1073.258032,1103.916089,1147.987095,1058.756464,...,1284.430691,1338.347221,1400.584606,1280.259776,1348.496598,1329.240098,1338.307911,1211.910831,1132.629084,0
1403,Greece,Total,Commercial and public services (PJ),13. Greece,11. Total,11. Commercial and public services (PJ),5.491800,6.550198,7.396200,7.209000,...,78.297996,81.254584,76.226505,71.762908,78.499800,85.307201,82.200462,76.993355,78.039825,0
1511,Hungary,Total,Commercial and public services (PJ),14. Hungary,11. Total,11. Commercial and public services (PJ),47.163988,47.277890,46.981762,48.575802,...,127.832625,98.539696,97.839399,88.534801,92.260723,91.408784,90.179029,87.781202,86.088115,0
1619,Iceland,Total,Commercial and public services (PJ),15. Iceland,11. Total,11. Commercial and public services (PJ),0.860199,0.910399,0.903800,0.971597,...,14.526588,15.037277,15.180273,15.918582,17.011454,18.247770,17.662736,20.49218,22.186531,0
1727,Ireland,Total,Commercial and public services (PJ),16. Ireland,11. Total,11. Commercial and public services (PJ),8.933999,9.499196,10.431596,7.979999,...,62.510883,64.643367,65.770567,62.101934,66.608865,67.925412,67.438362,71.236514,72.796168,0
1835,Israel,Total,Commercial and public services (PJ),17. Israel,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,61.441202,65.347202,63.910799,57.430800,68.276806,69.300479,69.543577,69.48734,71.121607,0
1943,Italy,Total,Commercial and public services (PJ),18. Italy,11. Total,11. Commercial and public services (PJ),53.397601,60.894000,65.091602,67.840797,...,659.478606,666.979602,663.462401,614.064495,644.409899,646.440501,657.055383,691.060719,661.094338,0
2051,Japan,Total,Commercial and public services (PJ),19. Japan,11. Total,11. Commercial and public services (PJ),685.592699,751.156296,845.857998,825.468697,...,2186.138315,2098.688975,2212.207681,2182.572560,2116.880579,2068.627701,2116.824191,2122.027974,2055.941144,0
2159,Korea,Total,Commercial and public services (PJ),20. Korea,11. Total,11. Commercial and public services (PJ),23.097211,31.528471,37.343556,36.688028,...,843.971409,848.261791,854.267400,842.249898,876.342616,903.420394,891.262249,898.173144,875.171477,0
2267,Latvia,Total,Commercial and public services (PJ),21. Latvia,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,23.311893,26.102856,25.144836,25.494317,24.554112,24.812116,25.38618,24.75932,23.791064,0
2375,Lithuania,Total,Commercial and public services (PJ),22. Lithuania,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,24.447232,25.540740,24.826841,24.518437,24.070361,25.227383,26.538601,27.206387,26.179667,0
2483,Luxembourg,Total,Commercial and public services (PJ),23. Luxembourg,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,14.765797,16.606331,17.197356,15.112422,16.624142,16.761251,19.073214,20.040231,22.244757,0
2591,Mexico,Total,Commercial and public services (PJ),24. Mexico,11. Total,11. Commercial and public services (PJ),23.966499,26.832900,29.422402,49.556501,...,151.390401,154.968298,163.412202,163.427405,166.918802,166.198802,164.817602,182.979438,180.270725,0
2699,Netherlands,Total,Commercial and public services (PJ),25. Netherlands,11. Total,11. Commercial and public services (PJ),80.414000,91.552802,80.168800,76.509202,...,290.470596,300.529806,301.388996,265.176634,279.504199,280.489416,285.569407,284.340665,281.799863,0
2807,New Zealand,Total,Commercial and public services (PJ),26. New Zealand,11. Total,11. Commercial and public services (PJ),17.975402,23.277000,21.504301,21.599697,...,47.150615,50.008705,49.560743,50.874833,51.708010,51.697882,52.096897,50.538118,52.514279,0
2915,Norway,Total,Commercial and public services (PJ),27. Norway,11. Total,11. Commercial and public services (PJ),20.789802,24.710201,24.173800,26.444499,...,110.438180,115.047737,117.133325,109.955977,110.805274,119.999328,117.699158,125.395146,125.78595,0
3023,Poland,Total,Commercial and public services (PJ),28. Poland,11. Total,11. Commercial and public services (PJ),218.539325,220.422397,231.514553,246.229032,...,352.246667,349.574676,337.656117,325.336734,327.625155,355.236281,335.996725,331.101832,326.006451,0
3131,Portugal,Total,Commercial and public services (PJ),29. Portugal,11. Total,11. Commercial and public services (PJ),8.103401,10.669298,10.518100,13.055703,...,77.681397,77.151805,74.783001,79.561409,82.410015,79.520512,79.475835,82.056448,80.319542,0
3239,Slovak Republic,Total,Commercial and public services (PJ),30. Slovak Republic,11. Total,11. Commercial and public services (PJ),19.779197,21.065399,22.685899,25.998500,...,67.060712,60.760726,71.618224,51.639995,54.412390,54.778881,59.736057,55.033857,50.676592,0
3347,Slovenia,Total,Commercial and public services (PJ),31. Slovenia,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,22.251594,18.977600,19.584699,17.886600,19.029203,20.617005,20.125089,19.519075,18.87301,0
3455,Spain,Total,Commercial and public services (PJ),32. Spain,11. Total,11. Commercial and public services (PJ),19.665898,25.254899,57.522998,59.979197,...,427.712016,422.835772,404.573432,369.006612,435.258794,458.801213,452.681635,450.787569,425.470918,0
3563,Sweden,Total,Commercial and public services (PJ),33. Sweden,11. Total,11. Commercial and public services (PJ),37.836798,38.215603,41.312801,41.821200,...,161.620336,169.288029,165.639203,165.703764,168.306329,176.458455,168.01239,172.571573,168.549603,0
3671,Switzerland,Total,Commercial and public services (PJ),34. Switzerland,11. Total,11. Commercial and public services (PJ),24.544801,27.381601,30.045599,31.279499,...,136.858420,144.826043,149.337881,130.684125,137.369637,140.872389,138.167984,132.720505,132.952764,0
3779,Turkey,Total,Commercial and public services (PJ),35. Turkey,11. Total,11. Commercial and public services (PJ),5.654399,9.262805,13.043100,14.416199,...,414.624607,460.762703,444.300093,461.444775,510.256838,519.461003,567.027213,524.368096,583.833086,0
3887,United Kingdom,Total,Commercial and public services (PJ),36. United Kingdom,11. Total,11. Commercial and public services (PJ),473.881493,547.636890,557.766966,515.626405,...,637.219463,678.206079,691.713014,647.035244,665.617380,717.484103,712.525228,723.947673,716.290983,0
3995,United States,Total,Commercial and public services (PJ),37. United States,11. Total,11. Commercial and public services (PJ),6072.494991,6214.459963,6226.970653,6062.386034,...,8609.009068,8206.276652,8641.863742,8852.956069,8713.012990,8750.178347,8684.654856,9110.242821,9068.187319,0
4103,OECD Total,Total,Commercial and public services (PJ),38. OECD Total,11. Total,11. Commercial and public services (PJ),10842.942530,11569.253630,11927.243590,11489.272330,...,19812.202320,19518.797340,20181.392910,19946.500960,20117.930870,20286.716380,20417.70974,20803.46405,20583.85973,0
4211,Brazil,Total,Commercial and public services (PJ),39. Brazil,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,455.431827,479.244051,499.695643,527.858422,526.008572,519.419901,522.617101,532.060876,550.29941,497.804495
4319,People's Republic of China,Total,Commercial and public services (PJ),40. People's Republic of China,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,2586.225414,2823.675807,3015.222196,3064.371163,3248.716942,3375.544886,3508.817341,3548.600135,3670.560128,0
4427,India,Total,Commercial and public services (PJ),41. India,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,562.525984,621.680289,635.254087,670.918895,728.532763,787.795753,838.412415,882.681516,943.018445,0
4535,Indonesia,Total,Commercial and public services (PJ),42. Indonesia,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,192.594299,216.578701,229.053301,235.175704,230.144000,242.493800,248.533757,248.28411,257.029335,0
4643,Morocco,Total,Commercial and public services (PJ),43. Morocco,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,48.342802,49.806499,50.239201,51.098998,51.211979,51.802079,53.89043,54.131083,55.781683,0
4751,Singapore,Total,Commercial and public services (PJ),44. Singapore,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,67.668196,69.537000,71.500399,72.437401,74.229799,75.791601,75.766853,78.783903,81.520831,0
4859,South Africa,Total,Commercial and public services (PJ),45. South Africa,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,162.940894,189.433156,195.649959,195.902369,184.807584,205.818332,223.624424,224.853476,222.594383,0
4967,Thailand,Total,Commercial and public services (PJ),46. Thailand,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,229.481703,252.501985,241.713493,179.768485,187.126497,195.328677,197.775221,204.039394,211.897092,0
5075,Non-OECD Total,Total,Commercial and public services (PJ),47. Non-OECD Total,11. Total,11. Commercial and public services (PJ),2997.186454,3171.354789,3357.714532,3547.725755,...,9905.178608,10495.620500,10973.605370,11131.377110,11499.277990,11947.955430,12337.22338,12640.98306,13074.73382,0
5183,Africa,Total,Commercial and public services (PJ),48. Africa,11. Total,11. Commercial and public services (PJ),126.825675,150.624849,155.894929,163.535512,...,793.329409,913.640812,941.162767,962.520936,959.379480,1009.641272,1030.736012,1045.290275,1066.66347,0
5291,Non-OECD Americas,Total,Commercial and public services (PJ),49. Non-OECD Americas,11. Total,11. Commercial and public services (PJ),142.932114,149.945281,171.800071,183.126856,...,956.916867,1006.079411,1054.439597,1080.922208,1107.480328,1084.764007,1097.476849,1116.877517,1104.92296,0
5399,Non-OECD Asia (including China),Total,Commercial and public services (PJ),50. Non-OECD Asia (including China),11. Total,11. Commercial and public services (PJ),430.823705,428.305759,445.900049,456.909390,...,4472.894674,4828.809861,5067.683687,5130.933339,5403.530466,5667.457148,5926.605204,6092.336948,6338.086232,0
5507,Non-OECD Europe and Eurasia,Total,Commercial and public services (PJ),51. Non-OECD Europe and Eurasia,11. Total,11. Commercial and public services (PJ),2241.957461,2383.751699,2517.741680,2666.604794,...,2665.857400,2590.893027,2716.324011,2664.841218,2639.183929,2754.576115,2863.230194,2854.913321,3041.937154,0
5615,Middle East,Total,Commercial and public services (PJ),52. Middle East,11. Total,11. Commercial and public services (PJ),54.647499,58.727201,66.377804,77.549203,...,1016.180259,1156.197393,1193.995304,1292.159406,1389.703783,1431.516885,1419.17512,1531.565001,1523.124002,0
5723,IEA Total,Total,Commercial and public services (PJ),53. IEA Total,11. Total,11. Commercial and public services (PJ),10826.585940,11553.673850,11913.133700,11471.739110,...,19535.811500,19237.140980,19906.970450,19675.402880,19833.882900,19988.460520,20101.00619,20492.81605,20264.51823,0
5831,IEA and Accession/Association countries,Total,Commercial and public services (PJ),54. IEA and Accession/Association countries,11. Total,11. Commercial and public services (PJ),0.000000,0.000000,0.000000,0.000000,...,24057.323360,24161.137100,25059.811380,24884.732900,25288.114240,25677.034520,26023.97327,26512.12797,26511.71044,0
5939,World,Total,Commercial and public services (PJ),55. World,11. Total,11. Commercial and public services (PJ),13840.128990,14740.608420,15284.958120,15036.998090,...,29717.380930,30014.417850,31154.998270,31077.878070,31617.208860,32234.671810,32754.93312,33444.44712,33658.59355,0

In [18]:
df_prop=pd.read_excel('../row_data/frac_scoe_heat_energy_proportion.xlsx')
df_prop

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_coal,0.90
1,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_sol...,0.10
2,Oil products,frac_scoe_heat_energy_commercial_municipal_diesel,0.25
3,Oil products,frac_scoe_heat_energy_commercial_municipal_gas...,0.40
4,Oil products,frac_scoe_heat_energy_commercial_municipal_ker...,0.10
5,Oil products,frac_scoe_heat_energy_commercial_municipal_gas...,0.25
6,Electricity,frac_scoe_heat_energy_commercial_municipal_ele...,1.00
7,Renewables and waste,frac_scoe_heat_energy_commercial_municipal_ele...,1.00
8,Nuclear,frac_scoe_heat_energy_commercial_municipal_ele...,1.00
9,Natural gas,frac_scoe_heat_energy_commercial_municipal_nat...,1.00
10,Heat,frac_scoe_heat_energy_commercial_municipal_nat...,1.00

In [19]:
df_prop_=df_prop[df_prop['SISEPUEDE_var']=='frac_scoe_heat_energy_commercial_municipal_coal']
df_prop_

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_commercial_municipal_coal,0.9

In [20]:
sisepuede_vars=[var for var in np.unique(df_prop['SISEPUEDE_var'].values)]
sisepuede_vars.append('frac_scoe_heat_energy_commercial_municipal_hydrogen')
sisepuede_vars

['frac_scoe_heat_energy_commercial_municipal_coal',
 'frac_scoe_heat_energy_commercial_municipal_diesel',
 'frac_scoe_heat_energy_commercial_municipal_electricity',
 'frac_scoe_heat_energy_commercial_municipal_gas_petroleum_liquid',
 'frac_scoe_heat_energy_commercial_municipal_gasoline',
 'frac_scoe_heat_energy_commercial_municipal_kerosene',
 'frac_scoe_heat_energy_commercial_municipal_natural_gas',
 'frac_scoe_heat_energy_commercial_municipal_solid_biomass',
 'frac_scoe_heat_energy_commercial_municipal_hydrogen']

In [21]:
#### HISTORICAL ######

nation_in_df=np.unique(df_WEBH2021['Country'].values)

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years=range(2000,2020)

for s_var in sisepuede_vars:
    coun_year=[]
    df_historical_out=0
    for count in zip(countries,ISO3):
        for year in years:
            coun_year.append([count[0],count[1],year])
            
    df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_historical_out[s_var]=0

    df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    for country in countries:
        for year in years:
        
        
            if country in nation_in_df:

                dato_fuel=[]

                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):

                    Total=df_total.loc[df_total['Country']==country,[year]][year].values[0]

                    df_fuel=df_sector[df_sector['Product']==fuel]

                    f=df_fuel.loc[df_fuel['Country']==country,[year]][year].values[0]

                    dato_fuel.append(p*f/Total)

                    #print(dato_fuel)


                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                            (df_historical_out['Year']== year), s_var]=sum(dato_fuel)
            
            else:
                
                dato_fuel=[]
                
                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):
                    
                    Total=df_total.loc[df_total['Country']=='World',[year]][year].values[0]
                    
                    df_fuel=df_sector[df_sector['Product']==fuel]
                    
                    f=df_fuel.loc[df_fuel['Country']=='World',[year]][year].values[0]
                    
                    dato_fuel.append(p*f/Total)
                    
                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                                (df_historical_out['Year']== year), s_var] = sum(dato_fuel)
                
    
    df_historical_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')

In [22]:
#### Projected ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years2=range(max(years)+1,2051)

for s_var in sisepuede_vars:
    coun_year=[]
    for count in zip(countries,ISO3):
        for year in years2:
            coun_year.append([count[0],count[1],year])
            
    df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_projected_out[s_var]=0

    #df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    df_historical=pd.read_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')
    
    for count,year in zip(df_projected_out['Nation'].values,df_projected_out['Year'].values):
        
        df_dato=df_historical[(df_historical['Nation']==count) & 
                                   (df_historical['Year']==max(years))]
        dato=df_dato[s_var].values[0]
        
        df_projected_out.loc[(df_projected_out['Nation'] == count) & 
                            (df_projected_out['Year']== year), s_var] = dato
    
    
    df_projected_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/projected/{s_var}.csv')