In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_inen_energy_total_pj_agriculture_and_livestock'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries
df_country_continent = pd.read_csv("../row_data/countryContinent.csv",encoding="ISO-8859-1")
df_country_continent.dropna(how='any')
df_country_continent

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,150.0,39.0
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,2.0,15.0
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,9.0,61.0
...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,9.0,61.0
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,2.0,15.0
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,142.0,145.0
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Eastern Africa,2.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Eastern Africa,2.0,14.0

In [3]:
#df_eei=pd.read_csv("../row_data/eei industry.csv")
df_eei=pd.read_csv("../row_data/IEA_Energy_Industry.csv")

df_eei

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Manufacturing [ISIC 10-18; 20-32],Oil and oil products (PJ) ...,117.58,91.59,88.38,111.41,122.11,129.29,133.41,...,161.91,179.86,155.11,155.37,118.72,106.86,97.51,101.08,100.39,97.74
1,Australia,Manufacturing [ISIC 10-18; 20-32],Gas (PJ) ...,314.61,339.39,338.58,343.29,352.22,325.43,322.22,...,330.12,325.92,339.72,346.59,334.74,322.67,309.67,311.85,298.23,303.55
2,Australia,Manufacturing [ISIC 10-18; 20-32],Coal and coal products (PJ) ...,231.33,201.89,178.75,209.41,223.34,226.59,225.07,...,230.37,191.49,184.76,177.97,170.35,197.53,208.32,205.26,196.51,190.24
3,Australia,Manufacturing [ISIC 10-18; 20-32],Biofuels and waste (PJ) ...,96.47,94.43,99.89,101.47,104.3,109.06,110.25,...,104.6,104.29,112.36,105.27,115.61,115.49,124.1,112.09,103.36,98.69
4,Australia,Manufacturing [ISIC 10-18; 20-32],Heat (PJ) ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,Uzbekistan,Construction [ISIC 41-43],Biofuels and waste (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9756,Uzbekistan,Construction [ISIC 41-43],Heat (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0,0,..,..,..
9757,Uzbekistan,Construction [ISIC 41-43],Electricity (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0.51,0.42,0.28,0.46,..,..,..
9758,Uzbekistan,Construction [ISIC 41-43],Other sources (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,0,0,0.01,0,..,..,..
9759,Uzbekistan,Construction [ISIC 41-43],Total final energy use (PJ) ...,..,..,..,..,..,..,..,...,..,..,..,6.85,6.54,6.23,9.44,..,..,..

In [4]:
df_enduse = df_eei.loc[df_eei['ENDUSE']=='Agriculture forestry and fishing [ISIC 01-03]']
df_enduse = df_enduse[df_enduse['PRODUCT/FLOW'].str.startswith('Total final energy use (PJ)')]
mask = (df_enduse == '..').any(axis=1)
df_enduse = df_enduse.drop(index=df_enduse[mask].index)
df_enduse

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
143,Australia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),67.38,81.71,82.25,93.33,93.15,96.86,92.5,...,91.62,93.66,94.69,94.99,99.62,104.46,110.79,112.04,94.09,83.91
303,Austria,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),22.39,23.01,22.34,22.93,23.15,22.24,22.11,...,21.83,22.16,23.16,22.32,22.62,23.15,23.4,22.44,22.09,21.67
463,Belgium,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),33.2,31.83,26.61,34.55,43.6,42.14,36.31,...,31.13,31.91,34.3,29.62,30.43,32.75,33.31,33.44,37.75,33.62
623,Canada,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),239.51,231.38,223.17,233.84,239.12,244.69,249.18,...,271.92,266.62,277.82,285.05,297.09,300.6,308.23,320.29,310.21,296.03
783,Czech Republic,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),27.63,25.65,24.11,23.78,23.61,23.19,23.44,...,22.79,23.46,25.45,25.61,25.28,26.79,26.84,25.99,26.67,26.59
943,Denmark,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),40.34,39.48,38.72,37.91,36.26,36.05,37.41,...,34.62,32.66,32.93,31.02,31.7,31.49,30.1,29.54,29.04,28.31
1103,Estonia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),2.44,4.19,4.58,4.76,4.4,4.38,4.15,...,4.59,4.66,4.64,5.52,5.58,5.48,5.6,5.25,4.77,4.62
1263,Finland,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),31.99,32.78,33.68,32.51,32.44,31.43,32.04,...,31.18,33.3,33.09,32.01,31.01,31.83,30.94,29.96,29.95,29.08
1423,France,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),190.85,193.52,189.75,190.01,198.32,195.09,190.59,...,188.19,183.23,191.26,188.94,189.21,183.66,181.91,184.25,182.38,188.33
1583,Germany,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),165.13,150.98,168.38,154.87,150.54,136.52,146.09,...,154.57,150.31,147.36,167.17,158.43,162.02,152.85,147.93,150.06,152.87
1743,Greece,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),46.42,46.47,48.44,52.2,46.47,48.03,49.17,...,28.01,13.23,13.56,11.75,11.36,11.86,12.71,11.65,12.22,12.12
1903,Hungary,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),27.92,26.38,27.25,25.68,24.45,23.37,22.94,...,20.37,16.83,21.57,25.07,24.39,27.1,25.56,27.12,28.2,29.47
2063,Ireland,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),14.8,15.08,14.9,15.53,15.33,16.03,15.23,...,11.76,11.43,10.41,9.6,9.24,9.48,9.87,10.5,10.29,10.07
2223,Italy,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),133.33,138.21,136.19,137.82,137.1,139.06,137.64,...,122.43,118.22,116.6,116.22,119.39,120.2,122.16,126.97,122.62,123.98
2383,Japan,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),251.19,258.01,247.19,249.36,254.34,247.99,231.25,...,205.88,201.18,183.75,180.95,200.7,210.25,212.34,176.82,189.42,195.58
2543,Korea,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),151.71,161.28,157.06,141.3,132.3,126.85,122.08,...,120.09,124.82,131.49,111.49,110.45,112.68,109.13,109.49,114.47,119.07
2703,Lithuania,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),4.16,4.14,4.21,4.26,4.41,4.42,4.76,...,4.63,4.62,4.44,4.43,4.19,4.42,4.62,4.56,4.68,4.78
2863,Luxembourg,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),0.74,0.84,0.82,0.89,0.91,0.94,0.97,...,1.03,1.03,1.08,1.03,1.01,1.16,1.07,1.01,0.96,0.91
2983,Mexico,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),115.44,103.64,101.65,104.83,108.77,111.91,127.07,...,155.11,158.63,158.61,159.47,179.07,180.26,181.91,189.27,191.9,186.01
3183,Netherlands,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),188.31,184.17,170.4,169.01,170.12,174.37,154.98,...,157.97,159.92,161.21,148.64,158.72,159.99,159.29,170.61,170.56,166.55
3343,New Zealand,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),25.31,26.06,27.96,29.36,26.88,29.21,30.13,...,28.14,31.09,30.82,32.84,32.22,29.36,29.5,27.37,27.67,32.43
3503,Norway,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),32.17,33.96,33.84,33.34,33.69,33.41,31.96,...,20.39,21.13,20.61,20.12,21.2,21.96,23.94,24.85,24.25,25.22
3663,Poland,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),193.34,191.86,182.27,174.69,179.16,184.79,159.23,...,152.86,152.3,148.63,142.41,138.78,148.11,162.1,165.47,161.09,162.04
3823,Portugal,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),29.91,21.18,19.82,19.04,24.61,23.97,18.65,...,17.81,17.26,17.54,17.77,18.34,18.11,19.11,19.43,20.04,21.12
3983,Slovak Republic,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),8.64,7.55,6.23,6.64,6.75,6.89,5.92,...,6.57,6.03,5.53,5.8,6.32,6.46,6,5.58,5.45,5.55
4143,Spain,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),107.14,99.88,98.35,122.48,139.04,129.4,116.99,...,99.92,112.98,118.68,115.29,111.48,112.89,114.12,114.37,120.63,124.63
4303,Sweden,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),31.9,31.59,33.28,33.8,33.12,31.81,30.59,...,28.12,27.2,29.88,28.79,27.5,28.33,27.4,26.26,27.06,25.27
4463,Switzerland,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),11.48,12.07,12.09,12.2,12.07,12.37,12.21,...,10.18,10.72,10.81,9.55,9.93,10.06,9.93,9.61,9.68,9.38
4623,Republic of Türkiye,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),122.11,122.21,133.42,122.18,136.62,138.48,148.17,...,225.61,190.96,178.91,189.18,162.51,158.53,178.39,191.75,197.27,208.4
4783,United Kingdom,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),48.05,51,47.22,37.45,35.85,39.06,36.21,...,36.02,38.44,42.15,49.4,40.81,60.76,62.7,58.43,57.53,58.07
4943,United States,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),797.17,875.99,866.33,797.46,932.81,927.74,951.89,...,867.34,830.7,884.94,866.48,868.26,856.24,868.54,885.65,902.07,843.54
5263,Brazil,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),306.58,323.6,326.96,341.22,346.42,350.07,358.12,...,417.84,432.99,444.37,467.82,479.46,470.78,514.64,517.01,531.39,544.8
5423,Morocco,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),20.07,23.53,23.78,25.1,26.95,29.29,29.93,...,39.41,41.4,43.34,44.97,47.2,49.75,51.45,51.59,53.09,49.91
5903,Chile,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),8.22,7.15,8.81,6.95,9.83,7.31,5.06,...,16.3,10.49,9.57,8.51,9.46,11.41,26.88,30.99,28.84,27.44
6223,Latvia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),5.43,5.7,5.39,6.14,6.54,6.39,6.49,...,6.43,6.3,6.54,6.46,6.78,7.41,8.13,7.9,8.74,8.86
6383,Albania,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),8.24,8.29,9.2,7.44,5.26,3.93,6.52,...,4.3,4.34,4.4,4.85,4.3,4.4,4.82,4.95,4.94,4.97
6543,Armenia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),1.71,1.41,0.83,0.8,0.94,0.98,0.82,...,0.44,0.5,0.54,0.62,1.65,1.47,2.74,2.95,3.81,3.96
7183,Bulgaria,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),13.03,11.44,11.62,11.77,11.49,12.64,12.36,...,8.57,8.38,8.12,7.98,7.78,7.76,7.44,7.78,7.88,7.91
7343,Croatia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),12.32,11.63,10.84,10.92,10.16,10.39,10.48,...,10.71,9.9,9.78,10.08,9.94,10.06,9.94,10.14,10.24,10.78
7503,Cyprus,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),0.34,0.33,0.36,0.41,0.42,1.6,1.72,...,1.74,1.68,1.68,1.58,1.73,1.85,1.91,1.86,1.9,1.97
7663,Georgia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),2.46,1.03,1.11,0.86,1.28,5.04,5.37,...,6.12,6.5,0.56,0.43,0.76,1.15,1.24,1.08,1.12,1.04
8143,Kosovo,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),1.37,1.52,1.53,1.54,1.44,1.53,1.51,...,0.77,0.84,1.24,0.94,1.16,1.23,1.24,1.31,1.52,1.41
8303,Kyrgyzstan,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),11.35,11.46,11.57,11.69,11.83,3.86,3.3,...,4.43,3.97,5.57,5.1,5.1,5.1,0.9,1.09,0.78,0.81
8463,Malta,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),0,0,0,0,0,0.35,0.22,...,0.25,0.3,0.21,0.22,0.17,0.22,0.27,0.32,0.37,0.39
8623,Republic of Moldova,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),3.61,3.46,4.12,4.01,3.62,2.86,2.83,...,2.86,2.51,2.72,2.7,2.98,3.37,4.51,4.57,5.16,5.17
8783,Republic of North Macedonia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),2.34,2.37,1.31,1.16,2.52,1.47,1.26,...,0.87,1.07,1,0.95,0.98,0.92,0.89,0.88,0.9,0.86
8943,Romania,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),16.57,12.01,11.6,10.09,9.61,8.95,10.9,...,18.06,20.85,19.66,17.63,19.21,18.99,20.67,23.65,23.29,22.18
9103,Serbia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),5.39,5.4,5.56,5.7,6.08,1,1.15,...,4.95,7.71,7.66,6.68,6.38,8.05,7.98,7.13,6.37,6.3
9263,Slovenia,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),3.24,3.2,3.16,3.29,3.07,3.12,3.16,...,2.83,2.97,2.93,3.15,3.11,3.07,3.05,3.12,3.07,3.01

In [5]:
df_enduse.columns

Index(['COUNTRY', 'ENDUSE', 'PRODUCT/FLOW', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

In [6]:
y='2005'
df_enduse[str(y)].values

array(['96.86', '22.24', '42.14', '244.69', '23.19', '36.05', '4.38',
       '31.43', '195.09', '136.52', '48.03', '23.37', '16.03', '139.06',
       '247.99', '126.85', '4.42', '0.94', '111.91', '174.37', '29.21',
       '33.41', '184.79', '23.97', '6.89', '129.4', '31.81', '12.37',
       '138.48', '39.06', '927.74', '350.07', '29.29', '7.31', '6.39',
       '3.93', '0.98', '12.64', '10.39', '1.6', '5.04', '1.53', '3.86',
       '0.35', '2.86', '1.47', '8.95', '1', '3.12'], dtype=object)

In [7]:
years_hist=range(2010,2021)
golbal_mean={}
for y in years_hist:
    m=[float(val) for val in df_enduse[str(y)].values]
    golbal_mean[y]=np.mean(m)
golbal_mean

{2010: 76.62877551020406,
 2011: 75.90938775510205,
 2012: 74.55897959183673,
 2013: 76.03693877551021,
 2014: 75.90204081632653,
 2015: 76.63244897959184,
 2016: 77.49857142857144,
 2017: 79.85836734693878,
 2018: 80.53510204081633,
 2019: 81.1934693877551,
 2020: 80.22428571428573}

In [8]:
continents = ['Australia and New Zealand',
 'Caribbean',
 'Central America',
 'Central Asia',
 'Eastern Africa',
 'Eastern Asia',
 'Eastern Europe',
 'Melanesia',
 'Micronesia',
 'Middle Africa',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South America',
 'South-Eastern Asia',
 'Southern Africa',
 'Southern Asia',
 'Southern Europe',
 'Western Africa',
 'Western Asia',
 'Western Europe']
coun_year=[]
for cont in continents:
    for year in years_hist:
        coun_year.append([cont,year,0])
        
df_meanEEI = pd.DataFrame(coun_year, columns=['sub_region', 'Year','meanEEI'])

for year in years_hist:
    for cont in continents:
        set1 = set(df_country_continent.loc[df_country_continent['sub_region']== cont]['country'].values)
        set2 = set(df_enduse['COUNTRY'].values)

        common_countries = set1.intersection(set2)
        #print(cont,common_countries)
        mean_array=[]
        for count in common_countries:
            mean_array.append(float(df_enduse.loc[(df_enduse['COUNTRY']==count)][str(year)].values[0]))
        if mean_array == []:
            mean_array = [0]
        #print(mean_array)
        df_meanEEI.loc[(df_meanEEI['sub_region']==cont) & (df_meanEEI['Year']==year),'meanEEI']=np.mean(mean_array)
    
df_meanEEI.dropna(how='any')
df_meanEEI = df_meanEEI.drop(df_meanEEI.index[(df_meanEEI == 0).any(axis=1)])

df_meanEEI

                    sub_region  Year    meanEEI
0    Australia and New Zealand  2010  59.395000
1    Australia and New Zealand  2011  59.880000
2    Australia and New Zealand  2012  62.375000
3    Australia and New Zealand  2013  62.755000
4    Australia and New Zealand  2014  63.915000
..                         ...   ...        ...
237             Western Europe  2016  81.827143
238             Western Europe  2017  80.251429
239             Western Europe  2018  81.327143
240             Western Europe  2019  81.925714
241             Western Europe  2020  81.904286

[132 rows x 3 columns]

In [9]:
#### HISTORICAL ######
countries = df_countries['Country Name'].values
coun_year=[]
for count in countries:
    iso3 = df_countries.loc[df_countries['Country Name']==count]['ISO3'].values[0]
    for year in years_hist:
        coun_year.append([count,iso3,year,0])
df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_total_pj_agriculture_and_livestock
0,Aruba,ABW,2010,0
1,Aruba,ABW,2011,0
2,Aruba,ABW,2012,0
3,Aruba,ABW,2013,0
4,Aruba,ABW,2014,0
...,...,...,...,...
2921,Zimbabwe,ZWE,2016,0
2922,Zimbabwe,ZWE,2017,0
2923,Zimbabwe,ZWE,2018,0
2924,Zimbabwe,ZWE,2019,0
2925,Zimbabwe,ZWE,2020,0

In [10]:
for c,y in zip(df_historical_out['Nation'].values,df_historical_out['Year'].values):
    
    if c in df_enduse['COUNTRY'].values:
        
        dato=df_enduse.loc[(df_enduse['COUNTRY'] == c)][str(y)].values[0]
        
        df_historical_out.loc[(df_historical_out['Nation'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
        
    else:
        try:
            cont = df_country_continent.loc[df_country_continent['country']== c]['sub_region'].values[0]
            
            dato = df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== y), 'meanEEI'].values[0]
        except:
            dato=golbal_mean[y]        
        df_historical_out.loc[(df_historical_out['Nation'] == c) & 
                        (df_historical_out['Year']== y), var_name] = dato
df_historical_out

,Nation,iso_code3,Year,consumpinit_inen_energy_total_pj_agriculture_and_livestock
0,Aruba,ABW,2010,76.628776
1,Aruba,ABW,2011,75.909388
2,Aruba,ABW,2012,74.55898
3,Aruba,ABW,2013,76.036939
4,Aruba,ABW,2014,75.902041
...,...,...,...,...
2921,Zimbabwe,ZWE,2016,77.498571
2922,Zimbabwe,ZWE,2017,79.858367
2923,Zimbabwe,ZWE,2018,80.535102
2924,Zimbabwe,ZWE,2019,81.193469
2925,Zimbabwe,ZWE,2020,80.224286

In [11]:
cont = df_country_continent.loc[df_country_continent['country']== 'El Salvador']['sub_region'].values[0]

cont,y,df_meanEEI.loc[(df_meanEEI['sub_region'] == cont) & 
                            (df_meanEEI['Year']== 2016), 'meanEEI'].values[0]

('Central America', 2020, 180.26)

In [12]:
df_enduse.loc[(df_enduse['COUNTRY'] == 'Mexico')]

,COUNTRY,ENDUSE,PRODUCT/FLOW,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2983,Mexico,Agriculture forestry and fishing [ISIC 01-03],Total final energy use (PJ),115.44,103.64,101.65,104.83,108.77,111.91,127.07,...,155.11,158.63,158.61,159.47,179.07,180.26,181.91,189.27,191.9,186.01

In [13]:
df_historical_out.to_csv('../input_to_sisepuede/historical/'+var_name+'.csv')

In [14]:
#### Projected ######

years2=range(max(years_hist)+1,2051)

coun_year=[]
for count in countries:
    iso3 = df_countries.loc[df_countries['Country Name']==count]['ISO3'].values[0]
    for year in years2:
        
        dato=df_historical_out.loc[(df_historical_out['Nation'] == count) & 
                        (df_historical_out['Year']== 2016)][var_name].values[0]
        
        coun_year.append([count,iso3,year,dato])
        
df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year',var_name])
df_projected_out

,Nation,iso_code3,Year,consumpinit_inen_energy_total_pj_agriculture_and_livestock
0,Aruba,ABW,2021,77.498571
1,Aruba,ABW,2022,77.498571
2,Aruba,ABW,2023,77.498571
3,Aruba,ABW,2024,77.498571
4,Aruba,ABW,2025,77.498571
...,...,...,...,...
7975,Zimbabwe,ZWE,2046,77.498571
7976,Zimbabwe,ZWE,2047,77.498571
7977,Zimbabwe,ZWE,2048,77.498571
7978,Zimbabwe,ZWE,2049,77.498571
7979,Zimbabwe,ZWE,2050,77.498571

In [15]:
df_projected_out.to_csv('../input_to_sisepuede/projected/'+var_name+'.csv')

In [16]:
df_historical_out.loc[(df_historical_out['Nation'] == 'Mexico') & 
                        (df_historical_out['Year']== 2016)]

,Nation,iso_code3,Year,consumpinit_inen_energy_total_pj_agriculture_and_livestock
1700,Mexico,MEX,2016,180.26