In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

var_name=os.path.basename(parentdir)

var_name

'frac_scoe_heat_energy_residential_coal'

In [2]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [3]:
df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

In [4]:
df_WEBH2021.columns = df_WEBH2021.iloc[0]
df_WEBH2021.replace(to_replace='..', value=0,inplace=True)
df_WEBH2021

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
0,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1.971000e+03,1.972000e+03,1.973000e+03,1.974000e+03,...,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2017,2018,2019,2020 Provisional
1,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1.368252e+03,1.648414e+03,1.685224e+03,1.640362e+03,...,9.782067e+03,1.027236e+04,1.107478e+04,1.195079e+04,1.250100e+04,1.222355e+04,12264.16248,12034.6322,12596.41582,12331.64135
2,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.755636e+00,3.635428e+00,2.577490e+00,5.287409e+00,6.978797e+00,6.829994e+00,7.916741,12.735731,17.037944,19.629498
3,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-5.414240e+02,-6.147180e+02,-7.389394e+02,-7.453829e+02,...,-7.720392e+03,-8.171019e+03,-9.101059e+03,-1.016689e+04,-1.063445e+04,-1.055251e+04,-10248.0298,-10333.3662,-10629.0366,-10541.275
4,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),8.842975e+02,9.232502e+02,9.455419e+02,9.283231e+02,...,2.013814e+03,1.968849e+03,1.831204e+03,1.736614e+03,1.797036e+03,1.863051e+03,1872.030679,1797.650326,1744.105366,1648.774748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.788729e+07,1.825346e+07,1.883300e+07,1.928119e+07,1.943470e+07,1.995069e+07,20589646.76,21366327.3,21641349.85,21619592.25
6157,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3.905413e+06,4.241816e+06,4.606277e+06,4.552613e+06,...,1.512668e+07,1.545191e+07,1.578194e+07,1.604617e+07,1.609427e+07,1.633914e+07,16687929.51,17081705.24,17007627.45,0
6158,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),1.110870e+05,1.524750e+05,2.031960e+05,2.727110e+05,...,2.582639e+06,2.460286e+06,2.479105e+06,2.535405e+06,2.570071e+06,2.608402e+06,2636117.238,2709100.699,2789694.402,2678855.226
6159,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1.240596e+06,1.304209e+06,1.321598e+06,1.460175e+06,...,4.410657e+06,4.729751e+06,5.060522e+06,5.302669e+06,5.511269e+06,5.891551e+06,6250190.754,6679673.151,7014495.554,0
6160,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5.257164e+06,5.698587e+06,6.131143e+06,6.287520e+06,...,2.221337e+07,2.273654e+07,2.342006e+07,2.398489e+07,2.427486e+07,2.494774e+07,25688502.59,26595243.41,26935958.13,0

In [5]:
df_sector=df_WEBH2021[df_WEBH2021['Flow']=='Residential (PJ)']
df_sector

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
10,Australia,"Coal, peat and oil shale",Residential (PJ),01. Australia,"01. Coal, peat and oil shale",10. Residential (PJ),9.914581,9.851025,7.838452,14.835582,...,0.103502,0.066599,0.051301,0.000000,0.020997,0.020997,0.020997,0.020997,0.020997,0
22,Australia,"Crude, NGL and feedstocks",Residential (PJ),01. Australia,"02. Crude, NGL and feedstocks",10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
34,Australia,Oil products,Residential (PJ),01. Australia,03. Oil products,10. Residential (PJ),32.303699,32.775602,32.990100,42.169801,...,16.039212,15.723800,16.071304,15.827096,15.406813,16.884083,14.843525,14.942216,15.409676,0
46,Australia,Natural gas,Residential (PJ),01. Australia,04. Natural gas,10. Residential (PJ),10.584900,17.811899,19.522801,21.233700,...,133.246798,135.720000,139.324500,143.023500,146.044799,149.199302,149.172301,149.077801,151.901098,0
58,Australia,Nuclear,Residential (PJ),01. Australia,05. Nuclear,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5890,World,Nuclear,Residential (PJ),55. World,05. Nuclear,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
5902,World,Renewables and waste,Residential (PJ),55. World,06. Renewables and waste,10. Residential (PJ),18272.864430,18652.851520,19033.047680,19356.457150,...,29331.143590,29273.917020,29599.390080,29569.358220,29270.431520,29068.417670,29380.23783,29319.70703,29558.52518,0
5914,World,Electricity,Residential (PJ),55. World,07. Electricity,10. Residential (PJ),3587.917210,3982.541741,4243.323060,4332.110384,...,17994.879570,18427.194060,19030.658920,19313.665800,19762.229550,20442.482360,20775.60218,21598.15567,21858.8491,0
5926,World,Heat,Residential (PJ),55. World,08. Heat,10. Residential (PJ),417.332001,465.811997,479.873997,499.158996,...,4559.189475,4632.785280,4509.196671,4404.722488,4296.095782,4149.552766,4241.743875,4647.482313,4612.669799,0
5938,World,Total,Residential (PJ),55. World,11. Total,10. Residential (PJ),42544.784040,44125.070550,44808.793340,44498.806470,...,81087.674690,80741.553060,82798.641560,82515.341400,82834.887290,83816.759660,85461.94685,87657.27847,87779.99592,0

In [6]:
df_total=df_sector[df_sector['Product']=='Total']
df_total

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
106,Australia,Total,Residential (PJ),01. Australia,11. Total,10. Residential (PJ),196.399979,212.985129,211.313754,224.106886,...,438.581715,437.586601,438.944903,432.391196,439.140410,442.866783,441.313259,441.665616,443.395045,0
214,Austria,Total,Residential (PJ),02. Austria,11. Total,10. Residential (PJ),212.298711,216.635415,239.341947,217.246964,...,270.683562,275.682011,285.731800,256.974844,272.049518,283.365375,285.150643,266.948836,273.234839,0
322,Belgium,Total,Residential (PJ),03. Belgium,11. Total,10. Residential (PJ),390.712519,437.585236,462.558501,435.455147,...,334.193240,353.962962,379.763857,312.160301,344.509837,345.939165,340.029735,336.961812,327.153111,0
430,Canada,Total,Residential (PJ),04. Canada,11. Total,10. Residential (PJ),1092.521985,1141.333579,1065.093081,1118.257277,...,1464.411643,1403.783572,1460.280905,1501.481688,1451.020360,1397.483263,1440.686534,1489.49014,1482.135038,0
538,Chile,Total,Residential (PJ),05. Chile,11. Total,10. Residential (PJ),82.491097,86.939002,88.659501,86.386998,...,233.947105,249.712596,256.031792,170.419804,166.296313,183.409950,184.276752,192.729859,193.747059,0
646,Colombia,Total,Residential (PJ),06. Colombia,11. Total,10. Residential (PJ),200.866566,175.051356,181.444436,176.924559,...,209.034560,208.365669,259.474770,261.625445,257.973798,257.364823,248.336383,257.614432,252.304904,0
754,Czech Republic,Total,Residential (PJ),07. Czech Republic,11. Total,10. Residential (PJ),339.865768,323.210694,294.673545,267.272048,...,285.482799,295.658343,301.668134,271.339692,279.902891,292.740487,296.747723,289.181954,286.660809,0
862,Denmark,Total,Residential (PJ),08. Denmark,11. Total,10. Residential (PJ),276.379067,273.715324,290.123787,251.799565,...,184.163423,181.686257,183.036471,168.648449,180.437795,185.775002,181.871125,178.787668,174.673208,0
970,Estonia,Total,Residential (PJ),09. Estonia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,39.162473,40.649624,39.086738,37.187978,35.902802,38.965853,39.464496,39.403273,39.834099,0
1078,Finland,Total,Residential (PJ),10. Finland,11. Total,10. Residential (PJ),146.005016,162.261335,179.625008,146.018527,...,213.128673,228.387834,216.385442,214.443094,207.146372,223.533017,220.20493,216.70716,213.26021,0
1186,France,Total,Residential (PJ),11. France,11. Total,10. Residential (PJ),865.578023,852.415272,896.025153,870.860584,...,1624.496767,1783.345391,1864.758094,1532.689601,1612.284592,1681.324283,1646.368657,1583.696322,1564.583325,0
1294,Germany,Total,Residential (PJ),12. Germany,11. Total,10. Residential (PJ),2357.073548,2427.241339,2545.415394,2322.654623,...,2319.185847,2448.423734,2584.221089,2203.862421,2263.907618,2343.329661,2324.112006,2293.238166,2368.031903,0
1402,Greece,Total,Residential (PJ),13. Greece,11. Total,10. Residential (PJ),69.715487,74.477223,82.045018,76.889900,...,231.364364,213.360048,159.991666,160.977214,186.757544,182.070438,182.198722,160.982908,169.214575,0
1510,Hungary,Total,Residential (PJ),14. Hungary,11. Total,10. Residential (PJ),132.601286,138.529682,158.746529,156.786604,...,274.962053,266.873980,259.914471,229.683464,249.878921,257.751922,263.31144,243.300173,237.280781,0
1618,Iceland,Total,Residential (PJ),15. Iceland,11. Total,10. Residential (PJ),16.320774,17.006375,18.635376,18.470801,...,17.010282,17.423887,16.915057,17.591288,17.831242,18.177001,17.315077,19.431173,19.008675,0
1726,Ireland,Total,Residential (PJ),16. Ireland,11. Total,10. Residential (PJ),75.427840,74.574767,75.601458,81.259922,...,129.982987,123.673906,120.979340,108.929290,114.807310,115.816116,115.194883,124.11185,118.042543,0
1834,Israel,Total,Residential (PJ),17. Israel,11. Total,10. Residential (PJ),6.193198,11.188800,12.144596,12.296703,...,145.244702,116.213803,70.966201,73.479604,85.028352,87.261876,89.565851,88.040127,94.222527,0
1942,Italy,Total,Residential (PJ),18. Italy,11. Total,10. Residential (PJ),994.460099,1081.926433,1121.276173,1143.869185,...,1355.604758,1438.096115,1433.167598,1237.031095,1360.478997,1347.525804,1373.14143,1331.649229,1299.675148,0
2050,Japan,Total,Residential (PJ),19. Japan,11. Total,10. Residential (PJ),719.450995,764.216692,876.032697,887.450980,...,2013.123126,2033.093613,1979.025471,1897.918639,1845.976725,1847.932262,1923.516613,1772.191731,1753.015128,0
2158,Korea,Total,Residential (PJ),20. Korea,11. Total,10. Residential (PJ),200.879185,209.321687,259.255503,272.051063,...,843.420297,849.581223,849.429025,798.679193,797.039768,868.267406,894.734647,898.942816,862.202403,0
2266,Latvia,Total,Residential (PJ),21. Latvia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,55.587269,57.632537,53.069017,51.865367,46.299209,47.886320,50.068995,51.550477,49.749463,0
2374,Lithuania,Total,Residential (PJ),22. Lithuania,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,64.129894,64.235623,61.409257,58.634283,56.909016,60.009790,60.935621,62.358342,59.616582,0
2482,Luxembourg,Total,Residential (PJ),23. Luxembourg,11. Total,10. Residential (PJ),17.258320,19.901870,21.257606,19.704144,...,19.995227,20.516953,20.841078,19.569124,21.266365,21.926979,22.334259,20.885316,19.266163,0
2590,Mexico,Total,Residential (PJ),24. Mexico,11. Total,10. Residential (PJ),334.483699,346.425399,359.763401,351.560099,...,750.961798,754.637499,734.562500,742.782805,744.104402,743.776303,740.356106,752.070601,740.666155,0
2698,Netherlands,Total,Residential (PJ),25. Netherlands,11. Total,10. Residential (PJ),449.476179,522.539021,546.842918,483.608396,...,429.377747,453.747251,476.471485,380.201939,398.042677,409.933925,400.507617,400.550415,385.194355,0
2806,New Zealand,Total,Residential (PJ),26. New Zealand,11. Total,10. Residential (PJ),34.873239,36.925524,37.012694,42.387812,...,62.365208,62.933265,61.785977,62.680784,62.421897,62.475275,62.952302,63.445369,64.804467,0
2914,Norway,Total,Residential (PJ),27. Norway,11. Total,10. Residential (PJ),79.446284,80.422558,78.451756,75.004336,...,165.613802,173.718706,171.616300,159.824299,166.935399,169.105195,171.181802,171.993078,170.181174,0
3022,Poland,Total,Residential (PJ),28. Poland,11. Total,10. Residential (PJ),563.710480,575.738566,577.626407,620.403231,...,840.668589,868.784228,854.629394,792.837100,791.832100,826.636743,832.959816,806.500043,751.916259,0
3130,Portugal,Total,Residential (PJ),29. Portugal,11. Total,10. Residential (PJ),34.647152,33.139941,33.842788,31.392903,...,116.237706,112.806497,110.289393,107.386798,106.257337,109.040169,108.005448,110.75713,110.867213,0
3238,Slovak Republic,Total,Residential (PJ),30. Slovak Republic,11. Total,10. Residential (PJ),27.211998,28.665203,30.321099,33.079802,...,88.807140,86.670352,89.889646,81.722643,83.219420,85.001150,88.284573,86.140982,109.490874,0
3346,Slovenia,Total,Residential (PJ),31. Slovenia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,54.083584,51.906305,51.098228,43.537260,47.621999,48.249198,46.890887,43.809289,42.612706,0
3454,Spain,Total,Residential (PJ),32. Spain,11. Total,10. Residential (PJ),190.634768,197.862821,151.904381,160.673667,...,653.632372,649.413677,622.620498,615.374562,622.409529,630.497581,605.133674,620.52374,608.81416,0
3562,Sweden,Total,Residential (PJ),33. Sweden,11. Total,10. Residential (PJ),425.456595,435.301671,449.770063,372.107682,...,321.528254,337.098351,322.054605,302.594631,310.209608,320.601233,322.666284,313.60342,308.310204,0
3670,Switzerland,Total,Residential (PJ),34. Switzerland,11. Total,10. Residential (PJ),50.970560,48.008901,53.100741,49.495282,...,216.226503,233.751405,247.385150,209.032048,220.916803,228.446156,223.465606,211.350129,213.260838,0
3778,Turkey,Total,Residential (PJ),35. Turkey,11. Total,10. Residential (PJ),368.643268,411.302678,422.033610,430.442509,...,869.907024,844.394176,828.495992,801.329764,843.622322,866.989502,927.477056,860.454531,902.594518,0
3886,United Kingdom,Total,Residential (PJ),36. United Kingdom,11. Total,10. Residential (PJ),1363.254343,1367.046856,1409.568424,1438.112536,...,1578.403411,1711.238115,1731.047939,1494.246768,1554.030642,1587.143130,1539.357373,1604.515955,1592.031684,0
3994,United States,Total,Residential (PJ),37. United States,11. Total,10. Residential (PJ),9757.860947,10219.823590,9944.821806,9556.478865,...,10974.263580,10052.821620,11067.316290,11333.238170,10713.641620,10352.169920,10254.2035,11343.71196,11334.18469,0
4102,OECD Total,Total,Residential (PJ),38. OECD Total,11. Total,10. Residential (PJ),22073.168970,23003.719940,23174.329150,22430.509600,...,29888.973480,29501.867730,30664.355570,29144.372650,28958.111510,28970.789060,28964.32182,29749.29602,29635.23684,0
4210,Brazil,Total,Residential (PJ),39. Brazil,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,973.857484,994.525966,993.481682,1037.838558,1044.759569,1040.491800,1064.17806,1107.046722,1115.90167,1155.457992
4318,People's Republic of China,Total,Residential (PJ),40. People's Republic of China,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,11910.513820,12086.229300,12486.582470,12817.263820,13292.747790,13695.018860,14280.47311,14616.61486,14685.7718,0
4426,India,Total,Residential (PJ),41. India,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,5991.175474,6021.646632,6099.773555,6238.077803,6346.786340,6435.927842,6508.29333,6601.284566,6702.186144,0
4534,Indonesia,Total,Residential (PJ),42. Indonesia,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,2000.427006,1950.908203,1912.583597,1874.106297,1823.042004,1780.981101,1761.827534,1460.520289,1331.291379,0
4642,Morocco,Total,Residential (PJ),43. Morocco,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,142.289202,148.168801,150.316696,156.025603,159.225503,164.205990,167.82542,169.552191,175.456956,0
4750,Singapore,Total,Residential (PJ),44. Singapore,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,26.646704,27.241603,27.715904,28.280101,29.387999,30.701495,29.677022,29.455603,31.061564,0
4858,South Africa,Total,Residential (PJ),45. South Africa,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,447.073697,490.334591,483.075207,475.528898,460.883601,470.604208,534.631182,521.328709,524.821543,0
4966,Thailand,Total,Residential (PJ),46. Thailand,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,474.980494,498.762548,489.244373,493.839478,483.691337,406.630193,402.351886,389.570758,398.258992,0
5074,Non-OECD Total,Total,Residential (PJ),47. Non-OECD Total,11. Total,10. Residential (PJ),20471.615070,21121.350610,21634.464200,22068.296870,...,51198.701210,51239.685320,52134.285980,53370.968750,53876.775770,54845.970610,56497.62502,57907.98245,58144.75908,0
5182,Africa,Total,Residential (PJ),48. Africa,11. Total,10. Residential (PJ),4098.694961,4212.585207,4309.288049,4412.641929,...,11756.466970,12014.434920,12365.346120,12733.022260,12961.933550,13228.222390,13673.62455,13839.50619,14113.32176,0
5290,Non-OECD Americas,Total,Residential (PJ),49. Non-OECD Americas,11. Total,10. Residential (PJ),1754.302087,1776.842851,1817.437336,1840.249769,...,2764.092983,2835.413007,2880.910540,2941.166940,2976.596802,3018.027595,2949.565008,3017.243985,2975.48887,0
5398,Non-OECD Asia (including China),Total,Residential (PJ),50. Non-OECD Asia (including China),11. Total,10. Residential (PJ),13844.394910,14240.087710,14557.063120,14821.441890,...,25143.088340,25407.282890,25907.010540,26433.020550,26756.200050,27154.496210,27959.88025,28104.50639,28247.21942,0
5506,Non-OECD Europe and Eurasia,Total,Residential (PJ),51. Non-OECD Europe and Eurasia,11. Total,10. Residential (PJ),588.153525,682.417070,718.004916,734.143004,...,8265.967672,7800.071851,7597.439913,7868.878643,7708.226861,7784.640102,8302.475994,9279.083846,9125.964866,0
5614,Middle East,Total,Residential (PJ),52. Middle East,11. Total,10. Residential (PJ),186.069586,209.417770,232.670780,259.820281,...,3269.085247,3182.482654,3383.578866,3394.880354,3473.818515,3660.584315,3612.079224,3667.642042,3682.764173,0
5722,IEA Total,Total,Residential (PJ),53. IEA Total,11. Total,10. Residential (PJ),21767.297340,22713.534400,22873.445240,22136.430540,...,29109.936090,28736.377310,29895.391250,28467.219600,28280.151580,28268.430100,28266.93226,29033.76232,28923.97492,0
5830,IEA and Accession/Association countries,Total,Residential (PJ),54. IEA and Accession/Association countries,11. Total,10. Residential (PJ),0.000000,0.000000,0.000000,0.000000,...,51729.256230,51592.722650,53186.046750,52152.339290,52486.883210,52881.038030,53599.30441,54529.87877,54488.61604,0
5938,World,Total,Residential (PJ),55. World,11. Total,10. Residential (PJ),42544.784040,44125.070550,44808.793340,44498.806470,...,81087.674690,80741.553060,82798.641560,82515.341400,82834.887290,83816.759660,85461.94685,87657.27847,87779.99592,0

In [7]:
df_prop=pd.read_excel('../row_data/frac_scoe_heat_energy_proportion.xlsx')
df_prop

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_residential_coal,0.90
1,"Coal, peat and oil shale",frac_scoe_heat_energy_residential_solid_biomass,0.10
2,Oil products,frac_scoe_heat_energy_residential_diesel,0.25
3,Oil products,frac_scoe_heat_energy_residential_gasoline,0.40
4,Oil products,frac_scoe_heat_energy_residential_kerosene,0.10
5,Oil products,frac_scoe_heat_energy_residential_hydrocarbon_...,0.25
6,Electricity,frac_scoe_heat_energy_residential_electricity,1.00
7,Renewables and waste,frac_scoe_heat_energy_residential_electricity,1.00
8,Nuclear,frac_scoe_heat_energy_residential_electricity,1.00
9,Natural gas,frac_scoe_heat_energy_residential_natural_gas,1.00
10,Heat,frac_scoe_heat_energy_residential_natural_gas,1.00

In [8]:
df_prop_=df_prop[df_prop['SISEPUEDE_var']=='frac_scoe_heat_energy_residential_natural_gas']
df_prop_

   WEBH2021_var                                  SISEPUEDE_var  Proportion
9   Natural gas  frac_scoe_heat_energy_residential_natural_gas         1.0
10         Heat  frac_scoe_heat_energy_residential_natural_gas         1.0

In [9]:
sisepuede_vars=[var for var in np.unique(df_prop['SISEPUEDE_var'].values)]
sisepuede_vars.append('frac_scoe_heat_energy_residential_hydrogen')
sisepuede_vars

['frac_scoe_heat_energy_residential_coal',
 'frac_scoe_heat_energy_residential_diesel',
 'frac_scoe_heat_energy_residential_electricity',
 'frac_scoe_heat_energy_residential_gasoline',
 'frac_scoe_heat_energy_residential_hydrocarbon_gas_liquids',
 'frac_scoe_heat_energy_residential_kerosene',
 'frac_scoe_heat_energy_residential_natural_gas',
 'frac_scoe_heat_energy_residential_solid_biomass',
 'frac_scoe_heat_energy_residential_hydrogen']

In [ ]:
#### HISTORICAL ######

nation_in_df=np.unique(df_WEBH2021['Country'].values)

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years=range(2000,2020)

for s_var in sisepuede_vars:
    coun_year=[]
    df_historical_out=0
    for count in zip(countries,ISO3):
        for year in years:
            coun_year.append([count[0],count[1],year])
            
    df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_historical_out[s_var]=0

    df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    for country in countries:
        for year in years:
        
        
            if country in nation_in_df:

                dato_fuel=[]

                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):

                    Total=df_total.loc[df_total['Country']==country,[year]][year].values[0]

                    df_fuel=df_sector[df_sector['Product']==fuel]

                    f=df_fuel.loc[df_fuel['Country']==country,[year]][year].values[0]

                    dato_fuel.append(p*f/Total)

                    #print(dato_fuel)


                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                            (df_historical_out['Year']== year), s_var]=sum(dato_fuel)
            
            else:
                
                dato_fuel=[]
                
                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):
                    
                    Total=df_total.loc[df_total['Country']=='World',[year]][year].values[0]
                    
                    df_fuel=df_sector[df_sector['Product']==fuel]
                    
                    f=df_fuel.loc[df_fuel['Country']=='World',[year]][year].values[0]
                    
                    dato_fuel.append(p*f/Total)
                    
                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                                (df_historical_out['Year']== year), s_var] = sum(dato_fuel)
                
    
    df_historical_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')

In [ ]:
#### Projected ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years2=range(max(years)+1,2051)

for s_var in sisepuede_vars:
    coun_year=[]
    for count in zip(countries,ISO3):
        for year in years2:
            coun_year.append([count[0],count[1],year])
            
    df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_projected_out[s_var]=0

    #df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    df_historical=pd.read_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')
    
    for count,year in zip(df_projected_out['Nation'].values,df_projected_out['Year'].values):
        
        df_dato=df_historical[(df_historical['Nation']==count) & 
                                   (df_historical['Year']==max(years))]
        dato=df_dato[s_var].values[0]
        
        df_projected_out.loc[(df_projected_out['Nation'] == count) & 
                            (df_projected_out['Year']== year), s_var] = dato
    
    
    df_projected_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/projected/{s_var}.csv')