In [27]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

var_name=os.path.basename(parentdir)

var_name

'consumpinit_scoe_gj_per_hh_residential_elec_appliances'

In [28]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [29]:
df_popur_hist = pd.read_csv(ggpdir+
        "/SocioEconomic/population_gnrl_urban/input_to_sisepuede/historical/population_gnrl_urban.csv") 
df_popur_proj = pd.read_csv(ggpdir+
        "/SocioEconomic/population_gnrl_urban/input_to_sisepuede/projected/population_gnrl_urban.csv")

df_popru_hist = pd.read_csv(ggpdir+
        "/SocioEconomic/population_gnrl_rural/input_to_sisepuede/historical/population_gnrl_rural.csv") 
df_popru_proj = pd.read_csv(ggpdir+
        "/SocioEconomic/population_gnrl_rural/input_to_sisepuede/projected/population_gnrl_rural.csv")

df_occ_hist = pd.read_csv(ggpdir+
        "/SocioEconomic/occrateinit_gnrl_occupancy/input_to_sisepuede/historical/occrateinit_gnrl_occupancy.csv")
df_occ_proj = pd.read_csv(ggpdir+
        "/SocioEconomic/occrateinit_gnrl_occupancy/input_to_sisepuede/projected/occrateinit_gnrl_occupancy.csv")

# hh = round((population_rurual + population_urban)/occ_rate)

#countries=df_countries['Country Name'].values
set1 = set(df_popur_hist['iso_code3'].values)
set2 = set(df_popru_hist['iso_code3'].values)
set3 = set(df_occ_hist['iso_code3'].values)

common_set = set1.intersection(set2, set3)
common_elements = sorted(list(common_set))
ISO3=common_elements

#countries=np.unique(df_countries['Nation'].values)
years_hist=range(max(min(zip(df_popur_hist['Year'].values,
                             df_popru_hist['Year'].values,
                             df_occ_hist['Year'].values))),
                min(max(zip(df_popur_hist['Year'].values,
                            df_popru_hist['Year'].values,
                            df_occ_hist['Year'].values)))
                )
coun_year=[]
for iso3 in ISO3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_hist:
        pop_ru = df_popru_hist.loc[(df_popru_hist['iso_code3'] == iso3) & 
                        (df_popru_hist['Year']== year), 'population_gnrl_rural'].values[0]
        
        pop_ur = df_popur_hist.loc[(df_popur_hist['iso_code3'] == iso3) & 
                        (df_popur_hist['Year']== year), 'population_gnrl_urban'].values[0]
        
        occ_rate = df_occ_hist.loc[(df_occ_hist['iso_code3'] == iso3) & 
                        (df_occ_hist['Year']== year), 'occrateinit_gnrl_occupancy'].values[0]
        
        hh = round((pop_ru+pop_ur)/occ_rate)
        coun_year.append([count,iso3,year,hh])
        
df_hh_hist = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year','hh'])
df_hh_hist

        Nation iso_code3  Year       hh
0        Aruba       ABW  2011    35311
1        Aruba       ABW  2012    35490
2        Aruba       ABW  2013    35697
3        Aruba       ABW  2014    35909
4        Aruba       ABW  2015    36103
...        ...       ...   ...      ...
1633  Zimbabwe       ZWE  2015  3282501
1634  Zimbabwe       ZWE  2016  3333753
1635  Zimbabwe       ZWE  2017  3382763
1636  Zimbabwe       ZWE  2018  3430811
1637  Zimbabwe       ZWE  2019  3479916

[1638 rows x 4 columns]

In [30]:
years_proj=range(max(min(zip(df_popur_proj['Year'].values,
                             df_popru_proj['Year'].values,
                             df_occ_proj['Year'].values))),
                min(max(zip(df_popur_proj['Year'].values,
                            df_popru_proj['Year'].values,
                            df_occ_proj['Year'].values)))+1
                )

years_proj=range(2020,
                min(max(zip(df_popur_proj['Year'].values,
                            df_popru_proj['Year'].values,
                            df_occ_proj['Year'].values)))+1
                )
coun_year=[]
for iso3 in ISO3:
    count = df_countries.loc[df_countries['ISO3']==iso3]['Country Name'].values[0]
    for year in years_proj:
        try:
            pop_ru = df_popru_proj.loc[(df_popru_proj['iso_code3'] == iso3) & 
                            (df_popru_proj['Year']== year), 'population_gnrl_rural'].values[0]
        except:
            pop_ru = df_popru_hist.loc[(df_popru_hist['iso_code3'] == iso3) & 
                            (df_popru_hist['Year']== year), 'population_gnrl_rural'].values[0]
        try:
            pop_ur = df_popur_proj.loc[(df_popur_proj['iso_code3'] == iso3) & 
                            (df_popur_proj['Year']== year), 'population_gnrl_urban'].values[0]
        except:
            pop_ur = df_popur_hist.loc[(df_popur_hist['iso_code3'] == iso3) & 
                        (df_popur_hist['Year']== year), 'population_gnrl_urban'].values[0]
        try:
            occ_rate = df_occ_proj.loc[(df_occ_proj['iso_code3'] == iso3) & 
                            (df_occ_proj['Year']== year), 'occrateinit_gnrl_occupancy'].values[0]
        except:
            occ_rate = df_occ_hist.loc[(df_occ_hist['iso_code3'] == iso3) & 
                        (df_occ_hist['Year']== year), 'occrateinit_gnrl_occupancy'].values[0]
        hh = round((pop_ru+pop_ur)/occ_rate)
        coun_year.append([count,iso3,year,hh])
        
df_hh_proj = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year','hh'])
df_hh_proj

        Nation iso_code3  Year       hh
0        Aruba       ABW  2020    43340
1        Aruba       ABW  2021    43804
2        Aruba       ABW  2022    44268
3        Aruba       ABW  2023    44732
4        Aruba       ABW  2024    45196
...        ...       ...   ...      ...
5637  Zimbabwe       ZWE  2046  3140103
5638  Zimbabwe       ZWE  2047  3134648
5639  Zimbabwe       ZWE  2048  3129192
5640  Zimbabwe       ZWE  2049  3123737
5641  Zimbabwe       ZWE  2050  3118282

[5642 rows x 4 columns]

In [31]:
df_hh_proj[df_hh_proj['Nation'].str.startswith('Tur')]

            Nation iso_code3  Year        hh
4991  Turkmenistan       TKM  2020   1093411
4992  Turkmenistan       TKM  2021   1102406
4993  Turkmenistan       TKM  2022   1111400
4994  Turkmenistan       TKM  2023   1120394
4995  Turkmenistan       TKM  2024   1129388
...            ...       ...   ...       ...
5172        Turkey       TUR  2046  22677181
5173        Turkey       TUR  2047  22740658
5174        Turkey       TUR  2048  22804135
5175        Turkey       TUR  2049  22867612
5176        Turkey       TUR  2050  22931089

[62 rows x 4 columns]

In [165]:
# df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

df_energy=pd.read_excel('../row_data/IEA - Energy Efficiency Indicators database - Extended (December 2022).xlsb',
                        engine='pyxlsb',sheet_name='Residential - Energy',skiprows=[0])
df_energy=df_energy.replace('..',0)
df_energy

,Country,End use,Product,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,Total Residential,Oil and oil products (PJ) ...,14.63,14.35,14.44,14.97,13.57,12.07,14.46,...,15.87,15.58,15.87,15.68,15.30,16.70,14.65,14.74,15.20,14.73
1,Australia,Total Residential,Gas (PJ) ...,104.84,107.69,110.50,110.61,110.85,113.71,117.22,...,131.16,133.55,136.95,140.58,143.29,146.38,146.15,145.92,148.58,154.10
2,Australia,Total Residential,Coal and coal products (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,Australia,Total Residential,Biofuels and waste (PJ) ...,80.60,79.50,76.34,73.20,70.60,67.80,65.58,...,52.80,52.80,52.80,51.77,49.80,49.22,48.80,48.20,47.60,47.10
4,Australia,Total Residential,Heat (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4408,Uruguay,Non-specified,Biofuels and waste (PJ) ...,12.69,12.69,12.66,12.66,12.66,12.66,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.31,0.00
4409,Uruguay,Non-specified,Heat (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4410,Uruguay,Non-specified,Electricity (PJ) ...,10.42,10.41,10.07,9.40,9.45,9.70,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,16.65,0.00
4411,Uruguay,Non-specified,Other sources (PJ) ...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4412,Uruguay,Non-specified,Total final energy use (PJ) ...,30.30,29.79,29.19,28.00,27.73,27.92,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.22,0.00

In [200]:
df_energy_totalproduct=df_energy[df_energy['Product'].str.startswith('Total final energy use (PJ)')]
df_energy_totalproduct[df_energy_totalproduct['Country']=='Uruguay']

,Country,End use,Product,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
4343,Uruguay,Total Residential,Total final energy use (PJ) ...,30.3,29.79,29.19,28.0,27.73,27.92,29.45,...,31.48,31.88,32.27,32.60,33.09,34.18,33.39,33.86,35.22,0.0
4351,Uruguay,Residential space heating,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,9.89,...,10.90,12.02,11.98,12.16,12.44,12.47,12.57,12.63,0.00,0.0
4355,Uruguay,Residential space cooling,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.25,...,0.58,0.72,0.85,1.08,1.22,1.27,1.39,1.42,0.00,0.0
4363,Uruguay,Residential water heating,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,5.14,...,5.40,5.19,5.52,5.74,5.85,5.91,5.98,6.08,0.00,0.0
4371,Uruguay,Residential cooking,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,8.28,...,6.89,5.80,5.86,5.76,5.56,5.56,5.40,5.39,0.00,0.0
4374,Uruguay,Residential lighting,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4377,Uruguay,Residential appliances,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,5.89,...,7.71,8.15,8.06,7.85,8.02,8.96,8.06,8.34,0.00,0.0
4380,Uruguay,Refrigerators,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4383,Uruguay,Freezers,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4386,Uruguay,Refrigerator/Freezer combinations,Total final energy use (PJ),0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4389,Uruguay,Dish washers,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4392,Uruguay,Clothes washers,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4395,Uruguay,Clothes dryers,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4398,Uruguay,Televisions,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4401,Uruguay,Personal computers,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4404,Uruguay,Other appliances,Total final energy use (PJ) ...,0.0,0.00,0.00,0.0,0.00,0.00,5.89,...,7.71,8.15,8.06,7.85,8.02,8.96,8.06,8.34,0.00,0.0
4412,Uruguay,Non-specified,Total final energy use (PJ) ...,30.3,29.79,29.19,28.0,27.73,27.92,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.22,0.0

In [201]:
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False
Nations = df_energy_totalproduct['Country'].unique()
coun_year=[]
for count in Nations:
        for year in years_hist:
            coun_year.append([count,year])
            
merged_df=pd.DataFrame(coun_year, columns=['Nation', 'Year'])

for end_use in [eu for eu in df_energy_totalproduct['End use'].unique() if eu !='Total Residential']:
    df_enduse=df_energy_totalproduct[df_energy_totalproduct['End use']==end_use]
    nation_enduse = df_enduse['Country'].values
#     years_hist = range(min(df_energy_totalproduct.columns),2020+1)

    c_y_enduse = []
    for c in Nations:
        for y in years_hist:

            end_use_num = df_enduse.loc[(df_enduse['Country']==c)][y].values[0]
            
            total=df_energy_totalproduct.loc[(df_energy_totalproduct['Country']==c)][y].values[0]
            
#             total=df_enduse_complete[(df_enduse_complete['Nation']==c)&
#                             (df_enduse_complete['Year']==y)]['Total Residential Total (PJ)'].values[0]
            if total!=0:
                end_use_frac= end_use_num/total
            else:
                end_use_frac=0

            if is_number(end_use_num):
                end_use_num=float(end_use_num)

#                 c_y_enduse.append([c,y,end_use_num,end_use_frac])

#     df_enduse = pd.DataFrame(c_y_enduse,columns=['Nation', 'Year',end_use+'Total (PJ)',end_use+'_Fraction'])
                c_y_enduse.append([c,y,end_use_num])

    df_enduse = pd.DataFrame(c_y_enduse,columns=['Nation', 'Year',end_use])

#     nation_mean=[]
#     for nation in df_enduse['Nation'].unique():
#         values=df_enduse.loc[df_enduse['Nation']==nation][end_use+'Total (PJ)'].values
#         nation_mean.append([nation,np.mean(values)])
#     mean_df=pd.DataFrame(nation_mean,columns=['Nation','end_use_mean'])

#     # Fill holes in present nations with the mean value
    
#     for count in Nations:
#         for year in years_hist:
#             PJ=df_enduse.loc[(df_enduse['Nation'] ==count) & 
#                             (df_enduse['Year']== year), end_use+'Total (PJ)'].values[0]
#             if PJ==0:
#                 PJ=mean_df.loc[mean_df['Nation'] ==count,'end_use_mean'].values[0]
#                 df_enduse.loc[(df_enduse['Nation'] ==count) & 
#                             (df_enduse['Year']== year), end_use+'Total (PJ)']=PJ
#    consumpinit_scoe_gj_per_hh_residential_elec_appliances : [all but (residential space heating +residential cooking+ clothes dryers)]
#    consumpinit_scoe_gj_per_hh_residential_heat_energy : [residential space heating +residential cooking+ clothes dryers]

    merged_df=pd.merge(merged_df, df_enduse, on=['Nation', 'Year'])
merged_df

,Nation,Year,Residential space heating,Residential space cooling,Residential water heating,Residential cooking,Residential lighting,Residential appliances,Refrigerators,Freezers,Refrigerator/Freezer combinations,Dish washers,Clothes washers,Clothes dryers,Televisions,Personal computers,Other appliances,Non-specified
0,Australia,2011,159.30,19.13,104.59,21.07,30.39,103.98,0.0,6.28,26.52,3.35,2.97,1.19,22.17,8.73,32.76,0.00
1,Australia,2012,159.83,19.47,105.69,21.00,29.21,102.30,0.0,6.17,26.18,3.39,3.08,1.20,20.96,8.21,33.12,0.00
2,Australia,2013,162.49,19.83,105.25,21.51,28.55,101.17,0.0,6.12,26.13,3.47,3.20,1.22,19.48,7.61,33.93,0.00
3,Australia,2014,163.35,19.32,103.05,21.67,26.82,97.15,0.0,5.88,25.30,3.43,3.24,1.21,17.32,6.86,33.90,0.00
4,Australia,2015,162.72,20.29,107.39,22.29,26.48,99.76,0.0,6.04,26.24,3.63,3.50,1.26,16.44,6.68,35.96,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,Uruguay,2015,12.44,1.22,5.85,5.56,0.00,8.02,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.02,0.00
509,Uruguay,2016,12.47,1.27,5.91,5.56,0.00,8.96,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.96,0.00
510,Uruguay,2017,12.57,1.39,5.98,5.40,0.00,8.06,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.06,0.00
511,Uruguay,2018,12.63,1.42,6.08,5.39,0.00,8.34,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.34,0.00
512,Uruguay,2019,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.22

In [202]:
df_energy_totalproduct['End use'].unique()

array(['Total Residential', 'Residential space heating',
       'Residential space cooling', 'Residential water heating',
       'Residential cooking', 'Residential lighting',
       'Residential appliances', 'Refrigerators', 'Freezers',
       'Refrigerator/Freezer combinations', 'Dish washers',
       'Clothes washers', 'Clothes dryers', 'Televisions',
       'Personal computers', 'Other appliances', 'Non-specified'],
      dtype=object)

In [421]:
heat_enduse=['Residential space heating','Residential cooking','Clothes dryers']
merged_df['Heat_Total_PJ']=0
merged_df['Elect_Total_PJ']=0
for c in Nations:
    for y in years_hist:
        heat_vect=[]
        electric_vect=[]
        df_c_y=merged_df.loc[(merged_df['Nation']==c)&(merged_df['Year']==y)]
        for enduse in [eu for eu in df_energy_totalproduct['End use'].unique() if eu !='Total Residential']:
            if enduse in heat_enduse:
                heat_val=df_c_y[enduse].values[0]
                heat_vect.append(heat_val)
            else:
                elect_val=df_c_y[enduse].values[0]
                electric_vect.append(elect_val)
                
        merged_df.loc[(merged_df['Nation']==c)&(merged_df['Year']==y),'Elect_Total_PJ']=sum(electric_vect)
        merged_df.loc[(merged_df['Nation']==c)&(merged_df['Year']==y),'Heat_Total_PJ']=sum(heat_vect)
merged_df

,Nation,Year,Residential space heating,Residential space cooling,Residential water heating,Residential cooking,Residential lighting,Residential appliances,Refrigerators,Freezers,Refrigerator/Freezer combinations,Dish washers,Clothes washers,Clothes dryers,Televisions,Personal computers,Other appliances,Non-specified,Heat_Total_PJ,Elect_Total_PJ
0,Australia,2011,159.30,19.13,104.59,21.07,30.39,103.98,0.0,6.28,26.52,3.35,2.97,1.19,22.17,8.73,32.76,0.00,181.56,360.87
1,Australia,2012,159.83,19.47,105.69,21.00,29.21,102.30,0.0,6.17,26.18,3.39,3.08,1.20,20.96,8.21,33.12,0.00,182.03,357.78
2,Australia,2013,162.49,19.83,105.25,21.51,28.55,101.17,0.0,6.12,26.13,3.47,3.20,1.22,19.48,7.61,33.93,0.00,185.22,354.74
3,Australia,2014,163.35,19.32,103.05,21.67,26.82,97.15,0.0,5.88,25.30,3.43,3.24,1.21,17.32,6.86,33.90,0.00,186.23,342.27
4,Australia,2015,162.72,20.29,107.39,22.29,26.48,99.76,0.0,6.04,26.24,3.63,3.50,1.26,16.44,6.68,35.96,0.00,186.27,352.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,Uruguay,2015,12.44,1.22,5.85,5.56,0.00,8.02,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.02,0.00,18.00,23.11
509,Uruguay,2016,12.47,1.27,5.91,5.56,0.00,8.96,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.96,0.00,18.03,25.10
510,Uruguay,2017,12.57,1.39,5.98,5.40,0.00,8.06,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.06,0.00,17.97,23.49
511,Uruguay,2018,12.63,1.42,6.08,5.39,0.00,8.34,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.34,0.00,18.02,24.18
512,Uruguay,2019,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.22,0.00,35.22

In [440]:
for c in merged_df['Nation'].unique():
    for y in merged_df['Year'].unique():
        heat_val=merged_df.loc[(merged_df['Nation']==c) &
                        (merged_df['Year']==y)]['Heat_Total_PJ'].values[0]
        elect_val=merged_df.loc[(merged_df['Nation']==c) &
                        (merged_df['Year']==y)]['Elect_Total_PJ'].values[0]
        
        if heat_val==0:
            heat_vals=merged_df.loc[(merged_df['Nation']==c)]['Heat_Total_PJ'].values
            if sum(heat_vals)!=0:
                heat_mean=np.mean(heat_vals[heat_vals.nonzero()])
            else:
                heat_mean=0
            merged_df.loc[(merged_df['Nation']==c) &
                        (merged_df['Year']==y),'Heat_Total_PJ']=heat_mean
            
        if elect_val==0:
            elect_vals=merged_df.loc[(merged_df['Nation']==c)]['Elect_Total_PJ'].values
            if sum(elect_vals)!=0:
                elect_mean=np.mean(heat_vals[elect_vals.nonzero()])
            else:
                elect_mean=0
            merged_df.loc[(merged_df['Nation']==c) &
                        (merged_df['Year']==y),'Elect_Total_PJ']=elect_mean
merged_df

,Nation,Year,Residential space heating,Residential space cooling,Residential water heating,Residential cooking,Residential lighting,Residential appliances,Refrigerators,Freezers,Refrigerator/Freezer combinations,Dish washers,Clothes washers,Clothes dryers,Televisions,Personal computers,Other appliances,Non-specified,Heat_Total_PJ,Elect_Total_PJ
0,Australia,2011,159.30,19.13,104.59,21.07,30.39,103.98,0.0,6.28,26.52,3.35,2.97,1.19,22.17,8.73,32.76,0.00,181.56000,360.87
1,Australia,2012,159.83,19.47,105.69,21.00,29.21,102.30,0.0,6.17,26.18,3.39,3.08,1.20,20.96,8.21,33.12,0.00,182.03000,357.78
2,Australia,2013,162.49,19.83,105.25,21.51,28.55,101.17,0.0,6.12,26.13,3.47,3.20,1.22,19.48,7.61,33.93,0.00,185.22000,354.74
3,Australia,2014,163.35,19.32,103.05,21.67,26.82,97.15,0.0,5.88,25.30,3.43,3.24,1.21,17.32,6.86,33.90,0.00,186.23000,342.27
4,Australia,2015,162.72,20.29,107.39,22.29,26.48,99.76,0.0,6.04,26.24,3.63,3.50,1.26,16.44,6.68,35.96,0.00,186.27000,352.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,Uruguay,2015,12.44,1.22,5.85,5.56,0.00,8.02,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.02,0.00,18.00000,23.11
509,Uruguay,2016,12.47,1.27,5.91,5.56,0.00,8.96,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.96,0.00,18.03000,25.10
510,Uruguay,2017,12.57,1.39,5.98,5.40,0.00,8.06,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.06,0.00,17.97000,23.49
511,Uruguay,2018,12.63,1.42,6.08,5.39,0.00,8.34,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8.34,0.00,18.02000,24.18
512,Uruguay,2019,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.22,17.92375,35.22

In [441]:
heat_vals=merged_df.loc[(merged_df['Nation']=='Mexico')]['Heat_Total_PJ'].values
if sum(heat_vals)!=0:
    heat_mean=np.mean(heat_vals[heat_vals.nonzero()])
else:
    heat_mean=0
heat_mean

0

In [442]:
merged_df[merged_df['Nation']=='Chile']

,Nation,Year,Residential space heating,Residential space cooling,Residential water heating,Residential cooking,Residential lighting,Residential appliances,Refrigerators,Freezers,Refrigerator/Freezer combinations,Dish washers,Clothes washers,Clothes dryers,Televisions,Personal computers,Other appliances,Non-specified,Heat_Total_PJ,Elect_Total_PJ
324,Chile,2011,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,233.95,103.51,233.95
325,Chile,2012,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,249.71,103.51,249.71
326,Chile,2013,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,256.03,103.51,256.03
327,Chile,2014,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,170.42,103.51,170.42
328,Chile,2015,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,166.30,103.51,166.30
329,Chile,2016,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,183.41,103.51,183.41
330,Chile,2017,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,184.28,103.51,184.28
331,Chile,2018,90.51,0.41,33.69,10.11,7.9,32.43,9.09,0.93,0.0,0.13,0.87,2.89,7.72,1.04,9.75,17.68,103.51,121.64
332,Chile,2019,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,193.75,103.51,193.75

In [443]:
merged_df[merged_df['Nation']=='Mexico']

,Nation,Year,Residential space heating,Residential space cooling,Residential water heating,Residential cooking,Residential lighting,Residential appliances,Refrigerators,Freezers,Refrigerator/Freezer combinations,Dish washers,Clothes washers,Clothes dryers,Televisions,Personal computers,Other appliances,Non-specified,Heat_Total_PJ,Elect_Total_PJ
162,Mexico,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,750.96,0.0,750.96
163,Mexico,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,754.64,0.0,754.64
164,Mexico,2013,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,734.56,0.0,734.56
165,Mexico,2014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,742.78,0.0,742.78
166,Mexico,2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,744.10,0.0,744.10
167,Mexico,2016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,743.78,0.0,743.78
168,Mexico,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,740.36,0.0,740.36
169,Mexico,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,757.58,0.0,757.58
170,Mexico,2019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,745.94,0.0,745.94

In [444]:
#Socioeconomic varibles

#GDP
df_gdp_hist = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/historical/gdp_mmm_usd.csv')
df_gdp_proj = pd.read_csv(ggpdir+'/Socioeconomic/gdp_mmm_usd/input_to_sisepuede/projected/gdp_mmm_usd.csv')

nation_gdp = sorted(set(df_gdp_proj['Nation'].values))

years_all = range(min(df_gdp_hist['Year'].values),max(df_gdp_proj['Year'].values)+1)
c_y_gdp = []
for c in nation_gdp:
    for y in years_all:
    
        try:
            gdp = df_gdp_hist.loc[(df_gdp_hist['Nation']==c) & (df_gdp_hist['Year']==y),]['gdp_mmm_usd'].values[0]
            
        except:
            gdp = df_gdp_proj.loc[(df_gdp_proj['Nation']==c) & (df_gdp_proj['Year']==y)]['gdp_mmm_usd'].values[0]
            
        c_y_gdp.append([c,y,gdp])

df_gdp_all = pd.DataFrame(c_y_gdp,columns=['Nation', 'Year', 'gdp_mmm_usd'])



#Rural population
df_popru_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/historical/population_gnrl_rural.csv')
df_popru_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_rural/input_to_sisepuede/projected/population_gnrl_rural.csv')

#Urban population
df_popur_hist = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/historical/population_gnrl_urban.csv')
df_popur_proj = pd.read_csv(ggpdir+
        '/Socioeconomic/population_gnrl_urban/input_to_sisepuede/projected/population_gnrl_urban.csv')

nation_pop = sorted(set(df_popur_proj['Nation'].values))

years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop = []
for c in nation_pop:
    for y in years_all:
    
        try:
            pop_ur = df_popur_hist.loc[(df_popur_hist['Nation']==c) &
                                       (df_popur_hist['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_hist.loc[(df_popru_hist['Nation']==c) &
                                       (df_popru_hist['Year']==y),]['population_gnrl_rural'].values[0]
            
        except:
            pop_ur = df_popur_proj.loc[(df_popur_proj['Nation']==c) &
                                       (df_popur_proj['Year']==y),]['population_gnrl_urban'].values[0]
            pop_ru = df_popru_proj.loc[(df_popru_proj['Nation']==c) &
                                       (df_popru_proj['Year']==y),]['population_gnrl_rural'].values[0]
            
        c_y_pop.append([c,y,pop_ur,pop_ru])

df_pop_all = pd.DataFrame(c_y_pop,columns=['Nation', 'Year', 'population_gnrl_urban','population_gnrl_rural'])

#All Together
nation_pop_gdp = sorted(set(nation_pop).intersection(set(nation_gdp)))
years_all = range(min(df_popur_hist['Year'].values),max(df_popur_proj['Year'].values)+1)
c_y_pop_gdp = []
for c in nation_pop_gdp:
    iso3 = df_gdp_hist.loc[df_gdp_hist['Nation']==c]['iso_code3'].values[0]
    for y in years_all:
        pop_ur = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_urban'].values[0]
        
        pop_ru = df_pop_all.loc[(df_pop_all['Nation']==c) &
                                       (df_pop_all['Year']==y),]['population_gnrl_rural'].values[0]
        
        gdp = df_gdp_all.loc[(df_gdp_all['Nation']==c) & (df_gdp_all['Year']==y)]['gdp_mmm_usd'].values[0]
        
        c_y_pop_gdp.append([c,iso3,y,pop_ur,pop_ru,gdp])
df_pop_gdp_all = pd.DataFrame(c_y_pop_gdp,columns=['Nation','iso_code3', 'Year',
                                                   'population_gnrl_urban',
                                                   'population_gnrl_rural',
                                                   'gdp_mmm_usd'])

df_pop_gdp_all['population_gnrl_urban(millions)']=df_pop_gdp_all.apply(lambda x: x['population_gnrl_urban']*1e-6, axis=1)
df_pop_gdp_all['population_gnrl_rural(millions)']=df_pop_gdp_all.apply(lambda x: x['population_gnrl_rural']*1e-6, axis=1)
df_pop_gdp_all

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions)
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997
...,...,...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637

In [445]:
joined_df = df_pop_gdp_all.merge(merged_df[['Nation','Year','Heat_Total_PJ', 'Elect_Total_PJ']], on=['Nation','Year'])

# joined_df=joined_df.merge(df_hh_hist)

joined_df['population_gnrl_urban(millions)']=joined_df.apply(lambda x: x['population_gnrl_urban']*1e-6, axis=1)
joined_df['population_gnrl_rural(millions)']=joined_df.apply(lambda x: x['population_gnrl_rural']*1e-6, axis=1)

joined_df

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),Heat_Total_PJ,Elect_Total_PJ
0,Albania,ALB,2011,1.546929e+06,1.358266e+06,21.159910,1.546929,1.358266,12.88000,9.76
1,Albania,ALB,2012,1.575788e+06,1.324613e+06,21.865577,1.575788,1.324613,13.45000,10.17
2,Albania,ALB,2013,1.603505e+06,1.291587e+06,22.571244,1.603505,1.291587,14.51000,12.99
3,Albania,ALB,2014,1.630119e+06,1.258985e+06,23.276911,1.630119,1.258985,14.33000,11.76
4,Albania,ALB,2015,1.654503e+06,1.226200e+06,23.982578,1.654503,1.226200,13.49000,11.24
...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,URY,2015,3.242948e+06,1.690652e+05,51.626567,3.242948,0.169065,18.00000,23.11
446,Uruguay,URY,2016,3.257863e+06,1.662762e+05,52.159029,3.257863,0.166276,18.03000,25.10
447,Uruguay,URY,2017,3.273061e+06,1.635843e+05,52.691490,3.273061,0.163584,17.97000,23.49
448,Uruguay,URY,2018,3.288346e+06,1.609439e+05,53.223952,3.288346,0.160944,18.02000,24.18
449,Uruguay,URY,2019,3.303391e+06,1.583396e+05,53.756413,3.303391,0.158340,17.92375,35.22

In [485]:
# sum(joined_df[joined_df['Nation']=='Mexico']['Heat_Total_PJ'].values)
sum(joined_df[(joined_df['Nation']==c)]['Heat_Total_PJ'].values)
joined_df['Nation'].unique()

array(['Albania', 'Argentina', 'Australia', 'Austria', 'Azerbaijan',
       'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Brazil',
       'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Georgia', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy',
       'Japan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Mexico',
       'Morocco', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Serbia', 'Slovak Republic', 'Slovenia',
       'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Ukraine',
       'United Kingdom', 'United States', 'Uruguay'], dtype=object)

In [486]:
from sklearn.linear_model import Lasso 
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import normalize

X=joined_df[['population_gnrl_urban(millions)','population_gnrl_rural(millions)','gdp_mmm_usd']]
Y_elect=joined_df['Elect_Total_PJ']
Y_heat=joined_df['Heat_Total_PJ']


linear_model_heat = LinearRegression()
linear_model_elect = LinearRegression()

linear_model_heat.fit(X,Y_heat)
linear_model_elect.fit(X,Y_elect)

c_y_iso3_h_e=[]
years_all=range(2011,2051)

for c in sorted(set(df_hh_hist['Nation'].unique()).intersection(df_pop_gdp_all['Nation'].unique())):
    iso3 = df_countries.loc[df_countries['Country Name']==c]['ISO3'].values[0]
    for y in years_all:
        if (c,y) in zip(joined_df['Nation'],joined_df['Year']):
            
            h=joined_df[(joined_df['Nation']==c)&(joined_df['Year']==y)]['Heat_Total_PJ'].values[0]*1e6
            E=joined_df[(joined_df['Nation']==c)&(joined_df['Year']==y)]['Elect_Total_PJ'].values[0]*1e6
            
        else:
            
            X_test = df_pop_gdp_all.loc[(df_pop_gdp_all['Nation'] == c) & 
                                (df_pop_gdp_all['Year']== y)][['population_gnrl_urban(millions)',
                                                                  'population_gnrl_rural(millions)',
                                                                  'gdp_mmm_usd']]
            
            if sum(joined_df[(joined_df['Nation']==c)]['Heat_Total_PJ'].values)==0 and c in joined_df['Nation'].unique():
                h=0
            else:
                h =linear_model_heat.predict(X_test)[0]*1e6
                if h<0:
                    h=0
                    
            if sum(joined_df[(joined_df['Nation']==c)]['Elect_Total_PJ'].values)==0 and c in joined_df['Nation'].unique():
                E=0
            else:
                E =linear_model_elect.predict(X_test)[0]*1e6
                if E<0:
                    E=0
        
        c_y_iso3_h_e.append([c,iso3,y,h,E])

total_heat_elect_df=pd.DataFrame(c_y_iso3_h_e,columns=['Nation','iso_code3','Year','Heat_Total_GJ','Elect_Total_GJ'])
total_heat_elect_df

           Nation iso_code3  Year  Heat_Total_GJ  Elect_Total_GJ
0     Afghanistan       AFG  2011   5.292452e+08    1.371512e+08
1     Afghanistan       AFG  2012   5.450645e+08    1.436363e+08
2     Afghanistan       AFG  2013   5.617517e+08    1.504121e+08
3     Afghanistan       AFG  2014   5.781630e+08    1.570840e+08
4     Afghanistan       AFG  2015   5.934765e+08    1.633688e+08
...           ...       ...   ...            ...             ...
7235     Zimbabwe       ZWE  2046   1.816076e+08    8.833231e+06
7236     Zimbabwe       ZWE  2047   1.807230e+08    9.143963e+06
7237     Zimbabwe       ZWE  2048   1.798384e+08    9.454694e+06
7238     Zimbabwe       ZWE  2049   1.789539e+08    9.765425e+06
7239     Zimbabwe       ZWE  2050   1.780693e+08    1.007616e+07

[7240 rows x 5 columns]

In [487]:
total_heat_elect_df[total_heat_elect_df['Nation']=='Mexico']

      Nation iso_code3  Year  Heat_Total_GJ  Elect_Total_GJ
4200  Mexico       MEX  2011            0.0    7.509600e+08
4201  Mexico       MEX  2012            0.0    7.546400e+08
4202  Mexico       MEX  2013            0.0    7.345600e+08
4203  Mexico       MEX  2014            0.0    7.427800e+08
4204  Mexico       MEX  2015            0.0    7.441000e+08
4205  Mexico       MEX  2016            0.0    7.437800e+08
4206  Mexico       MEX  2017            0.0    7.403600e+08
4207  Mexico       MEX  2018            0.0    7.575800e+08
4208  Mexico       MEX  2019            0.0    7.459400e+08
4209  Mexico       MEX  2020            0.0    8.155275e+08
4210  Mexico       MEX  2021            0.0    8.278224e+08
4211  Mexico       MEX  2022            0.0    8.350877e+08
4212  Mexico       MEX  2023            0.0    8.423529e+08
4213  Mexico       MEX  2024            0.0    8.496181e+08
4214  Mexico       MEX  2025            0.0    8.568834e+08
4215  Mexico       MEX  2026            0.0    8.823470e+08
4216  Mexico       MEX  2027            0.0    9.078107e+08
4217  Mexico       MEX  2028            0.0    9.332743e+08
4218  Mexico       MEX  2029            0.0    9.587380e+08
4219  Mexico       MEX  2030            0.0    9.842016e+08
4220  Mexico       MEX  2031            0.0    1.012236e+09
4221  Mexico       MEX  2032            0.0    1.040271e+09
4222  Mexico       MEX  2033            0.0    1.068305e+09
4223  Mexico       MEX  2034            0.0    1.096340e+09
4224  Mexico       MEX  2035            0.0    1.124374e+09
4225  Mexico       MEX  2036            0.0    1.154766e+09
4226  Mexico       MEX  2037            0.0    1.185157e+09
4227  Mexico       MEX  2038            0.0    1.215548e+09
4228  Mexico       MEX  2039            0.0    1.245939e+09
4229  Mexico       MEX  2040            0.0    1.276331e+09
4230  Mexico       MEX  2041            0.0    1.310245e+09
4231  Mexico       MEX  2042            0.0    1.344159e+09
4232  Mexico       MEX  2043            0.0    1.378074e+09
4233  Mexico       MEX  2044            0.0    1.411988e+09
4234  Mexico       MEX  2045            0.0    1.445902e+09
4235  Mexico       MEX  2046            0.0    1.484283e+09
4236  Mexico       MEX  2047            0.0    1.522664e+09
4237  Mexico       MEX  2048            0.0    1.561044e+09
4238  Mexico       MEX  2049            0.0    1.599425e+09
4239  Mexico       MEX  2050            0.0    1.637805e+09

In [488]:
df_hh_heat_elect_hist=df_hh_hist.merge(total_heat_elect_df,on=['Nation','iso_code3','Year'])
df_hh_heat_elect_hist

        Nation iso_code3  Year       hh  Heat_Total_GJ  Elect_Total_GJ
0        Aruba       ABW  2011    35311   3.238857e+07    0.000000e+00
1        Aruba       ABW  2012    35490   3.248540e+07    0.000000e+00
2        Aruba       ABW  2013    35697   3.258253e+07    0.000000e+00
3        Aruba       ABW  2014    35909   3.267915e+07    0.000000e+00
4        Aruba       ABW  2015    36103   3.277473e+07    0.000000e+00
...        ...       ...   ...      ...            ...             ...
1624  Zimbabwe       ZWE  2015  3282501   2.167056e+08    1.530004e+07
1625  Zimbabwe       ZWE  2016  3333753   2.199770e+08    1.641311e+07
1626  Zimbabwe       ZWE  2017  3382763   2.229955e+08    1.743358e+07
1627  Zimbabwe       ZWE  2018  3430811   2.258219e+08    1.838103e+07
1628  Zimbabwe       ZWE  2019  3479916   2.285729e+08    1.929472e+07

[1629 rows x 6 columns]

In [489]:
df_hh_heat_elect_proj=df_hh_proj.merge(total_heat_elect_df,on=['Nation','iso_code3','Year'])
df_hh_heat_elect_proj

        Nation iso_code3  Year       hh  Heat_Total_GJ  Elect_Total_GJ
0        Aruba       ABW  2020    43340   3.268916e+07    0.000000e+00
1        Aruba       ABW  2021    43804   3.288878e+07    0.000000e+00
2        Aruba       ABW  2022    44268   3.291062e+07    0.000000e+00
3        Aruba       ABW  2023    44732   3.293245e+07    0.000000e+00
4        Aruba       ABW  2024    45196   3.295429e+07    0.000000e+00
...        ...       ...   ...      ...            ...             ...
5606  Zimbabwe       ZWE  2046  3140103   1.816076e+08    8.833231e+06
5607  Zimbabwe       ZWE  2047  3134648   1.807230e+08    9.143963e+06
5608  Zimbabwe       ZWE  2048  3129192   1.798384e+08    9.454694e+06
5609  Zimbabwe       ZWE  2049  3123737   1.789539e+08    9.765425e+06
5610  Zimbabwe       ZWE  2050  3118282   1.780693e+08    1.007616e+07

[5611 rows x 6 columns]

In [490]:
df_hh_heat_elect_hist['consumpinit_scoe_gj_per_hh_residential_elec_appliances'] = df_hh_heat_elect_hist.apply(lambda row: row['Elect_Total_GJ'] / (row['hh'] ), axis=1)
df_hh_heat_elect_hist['consumpinit_scoe_gj_per_hh_residential_heat_energy'] = df_hh_heat_elect_hist.apply(lambda row: row['Heat_Total_GJ'] / (row['hh'] ), axis=1)
df_hh_heat_elect_hist

,Nation,iso_code3,Year,hh,Heat_Total_GJ,Elect_Total_GJ,consumpinit_scoe_gj_per_hh_residential_elec_appliances,consumpinit_scoe_gj_per_hh_residential_heat_energy
0,Aruba,ABW,2011,35311,3.238857e+07,0.000000e+00,0.000000,917.237310
1,Aruba,ABW,2012,35490,3.248540e+07,0.000000e+00,0.000000,915.339602
2,Aruba,ABW,2013,35697,3.258253e+07,0.000000e+00,0.000000,912.752661
3,Aruba,ABW,2014,35909,3.267915e+07,0.000000e+00,0.000000,910.054500
4,Aruba,ABW,2015,36103,3.277473e+07,0.000000e+00,0.000000,907.811719
...,...,...,...,...,...,...,...,...
1624,Zimbabwe,ZWE,2015,3282501,2.167056e+08,1.530004e+07,4.661093,66.018443
1625,Zimbabwe,ZWE,2016,3333753,2.199770e+08,1.641311e+07,4.923313,65.984790
1626,Zimbabwe,ZWE,2017,3382763,2.229955e+08,1.743358e+07,5.153652,65.921117
1627,Zimbabwe,ZWE,2018,3430811,2.258219e+08,1.838103e+07,5.357634,65.821713
1628,Zimbabwe,ZWE,2019,3479916,2.285729e+08,1.929472e+07,5.544594,65.683442

In [491]:
df_hist_heat=df_hh_heat_elect_hist[['Nation','iso_code3','Year','consumpinit_scoe_gj_per_hh_residential_heat_energy']]
df_hist_heat

,Nation,iso_code3,Year,consumpinit_scoe_gj_per_hh_residential_heat_energy
0,Aruba,ABW,2011,917.237310
1,Aruba,ABW,2012,915.339602
2,Aruba,ABW,2013,912.752661
3,Aruba,ABW,2014,910.054500
4,Aruba,ABW,2015,907.811719
...,...,...,...,...
1624,Zimbabwe,ZWE,2015,66.018443
1625,Zimbabwe,ZWE,2016,65.984790
1626,Zimbabwe,ZWE,2017,65.921117
1627,Zimbabwe,ZWE,2018,65.821713
1628,Zimbabwe,ZWE,2019,65.683442

In [492]:
df_hist_elec=df_hh_heat_elect_hist[['Nation','iso_code3','Year','consumpinit_scoe_gj_per_hh_residential_elec_appliances']]
df_hist_elec

,Nation,iso_code3,Year,consumpinit_scoe_gj_per_hh_residential_elec_appliances
0,Aruba,ABW,2011,0.000000
1,Aruba,ABW,2012,0.000000
2,Aruba,ABW,2013,0.000000
3,Aruba,ABW,2014,0.000000
4,Aruba,ABW,2015,0.000000
...,...,...,...,...
1624,Zimbabwe,ZWE,2015,4.661093
1625,Zimbabwe,ZWE,2016,4.923313
1626,Zimbabwe,ZWE,2017,5.153652
1627,Zimbabwe,ZWE,2018,5.357634
1628,Zimbabwe,ZWE,2019,5.544594

In [493]:
df_hh_heat_elect_proj['consumpinit_scoe_gj_per_hh_residential_elec_appliances'] = df_hh_heat_elect_proj.apply(lambda row: row['Elect_Total_GJ'] / (row['hh'] ), axis=1)
df_hh_heat_elect_proj['consumpinit_scoe_gj_per_hh_residential_heat_energy'] = df_hh_heat_elect_proj.apply(lambda row: row['Heat_Total_GJ'] / (row['hh'] ), axis=1)
df_hh_heat_elect_proj

,Nation,iso_code3,Year,hh,Heat_Total_GJ,Elect_Total_GJ,consumpinit_scoe_gj_per_hh_residential_elec_appliances,consumpinit_scoe_gj_per_hh_residential_heat_energy
0,Aruba,ABW,2020,43340,3.268916e+07,0.000000e+00,0.000000,754.249166
1,Aruba,ABW,2021,43804,3.288878e+07,0.000000e+00,0.000000,750.816910
2,Aruba,ABW,2022,44268,3.291062e+07,0.000000e+00,0.000000,743.440360
3,Aruba,ABW,2023,44732,3.293245e+07,0.000000e+00,0.000000,736.216843
4,Aruba,ABW,2024,45196,3.295429e+07,0.000000e+00,0.000000,729.141645
...,...,...,...,...,...,...,...,...
5606,Zimbabwe,ZWE,2046,3140103,1.816076e+08,8.833231e+06,2.813039,57.834919
5607,Zimbabwe,ZWE,2047,3134648,1.807230e+08,9.143963e+06,2.917062,57.653370
5608,Zimbabwe,ZWE,2048,3129192,1.798384e+08,9.454694e+06,3.021449,57.471207
5609,Zimbabwe,ZWE,2049,3123737,1.789539e+08,9.765425e+06,3.126200,57.288389
5610,Zimbabwe,ZWE,2050,3118282,1.780693e+08,1.007616e+07,3.231317,57.104931

In [494]:
df_proj_elec=df_hh_heat_elect_proj[['Nation','iso_code3','Year','consumpinit_scoe_gj_per_hh_residential_elec_appliances']]
df_proj_elec

,Nation,iso_code3,Year,consumpinit_scoe_gj_per_hh_residential_elec_appliances
0,Aruba,ABW,2020,0.000000
1,Aruba,ABW,2021,0.000000
2,Aruba,ABW,2022,0.000000
3,Aruba,ABW,2023,0.000000
4,Aruba,ABW,2024,0.000000
...,...,...,...,...
5606,Zimbabwe,ZWE,2046,2.813039
5607,Zimbabwe,ZWE,2047,2.917062
5608,Zimbabwe,ZWE,2048,3.021449
5609,Zimbabwe,ZWE,2049,3.126200
5610,Zimbabwe,ZWE,2050,3.231317

In [495]:
df_proj_heat=df_hh_heat_elect_proj[['Nation','iso_code3','Year','consumpinit_scoe_gj_per_hh_residential_heat_energy']]
df_proj_heat

,Nation,iso_code3,Year,consumpinit_scoe_gj_per_hh_residential_heat_energy
0,Aruba,ABW,2020,754.249166
1,Aruba,ABW,2021,750.816910
2,Aruba,ABW,2022,743.440360
3,Aruba,ABW,2023,736.216843
4,Aruba,ABW,2024,729.141645
...,...,...,...,...
5606,Zimbabwe,ZWE,2046,57.834919
5607,Zimbabwe,ZWE,2047,57.653370
5608,Zimbabwe,ZWE,2048,57.471207
5609,Zimbabwe,ZWE,2049,57.288389
5610,Zimbabwe,ZWE,2050,57.104931

In [496]:
df_hist_heat.to_csv(grandparentdir+'/consumpinit_scoe_gj_per_hh_residential_heat_energy/'+
                   '/input_to_sisepuede/historical/consumpinit_scoe_gj_per_hh_residential_heat_energy.csv')
df_hist_elec.to_csv(grandparentdir+'/consumpinit_scoe_gj_per_hh_residential_elec_appliances/'+
                   '/input_to_sisepuede/historical/consumpinit_scoe_gj_per_hh_residential_elec_appliances.csv')
df_proj_heat.to_csv(grandparentdir+'/consumpinit_scoe_gj_per_hh_residential_heat_energy/'+
                   '/input_to_sisepuede/projected/consumpinit_scoe_gj_per_hh_residential_heat_energy.csv')
df_proj_elec.to_csv(grandparentdir+'/consumpinit_scoe_gj_per_hh_residential_elec_appliances/'+
                   '/input_to_sisepuede/projected/consumpinit_scoe_gj_per_hh_residential_elec_appliances.csv')

In [497]:
df_hh_heat_elect_all=pd.concat([df_hh_heat_elect_hist,df_hh_heat_elect_proj])
df_hh_heat_elect_all.to_csv('../row_data/hh_heat_elec_gj_all.csv')
df_hh_heat_elect_all

,Nation,iso_code3,Year,hh,Heat_Total_GJ,Elect_Total_GJ,consumpinit_scoe_gj_per_hh_residential_elec_appliances,consumpinit_scoe_gj_per_hh_residential_heat_energy
0,Aruba,ABW,2011,35311,3.238857e+07,0.000000e+00,0.000000,917.237310
1,Aruba,ABW,2012,35490,3.248540e+07,0.000000e+00,0.000000,915.339602
2,Aruba,ABW,2013,35697,3.258253e+07,0.000000e+00,0.000000,912.752661
3,Aruba,ABW,2014,35909,3.267915e+07,0.000000e+00,0.000000,910.054500
4,Aruba,ABW,2015,36103,3.277473e+07,0.000000e+00,0.000000,907.811719
...,...,...,...,...,...,...,...,...
5606,Zimbabwe,ZWE,2046,3140103,1.816076e+08,8.833231e+06,2.813039,57.834919
5607,Zimbabwe,ZWE,2047,3134648,1.807230e+08,9.143963e+06,2.917062,57.653370
5608,Zimbabwe,ZWE,2048,3129192,1.798384e+08,9.454694e+06,3.021449,57.471207
5609,Zimbabwe,ZWE,2049,3123737,1.789539e+08,9.765425e+06,3.126200,57.288389
5610,Zimbabwe,ZWE,2050,3118282,1.780693e+08,1.007616e+07,3.231317,57.104931

In [498]:
df_hh_heat_elect_all[df_hh_heat_elect_all['Nation']=='Chile']

,Nation,iso_code3,Year,hh,Heat_Total_GJ,Elect_Total_GJ,consumpinit_scoe_gj_per_hh_residential_elec_appliances,consumpinit_scoe_gj_per_hh_residential_heat_energy
270,Chile,CHL,2011,5073675,1.035100e+08,2.339500e+08,46.110561,20.401386
271,Chile,CHL,2012,5122775,1.035100e+08,2.497100e+08,48.745065,20.205845
272,Chile,CHL,2013,5173163,1.035100e+08,2.560300e+08,49.491965,20.009035
273,Chile,CHL,2014,5228352,1.035100e+08,1.704200e+08,32.595357,19.797825
274,Chile,CHL,2015,5290291,1.035100e+08,1.663000e+08,31.434944,19.566031
275,Chile,CHL,2016,5360865,1.035100e+08,1.834100e+08,34.212762,19.308451
276,Chile,CHL,2017,5437812,1.035100e+08,1.842800e+08,33.888630,19.035230
277,Chile,CHL,2018,5513984,1.035100e+08,1.216400e+08,22.060274,18.772271
278,Chile,CHL,2019,5579598,1.035100e+08,1.937500e+08,34.724724,18.551516
930,Chile,CHL,2020,5466209,7.167550e+07,6.840374e+07,12.513926,13.112470
931,Chile,CHL,2021,5502390,7.632612e+07,7.333909e+07,13.328588,13.871448
932,Chile,CHL,2022,5538572,7.837132e+07,7.677107e+07,13.861167,14.150094
933,Chile,CHL,2023,5574753,8.041651e+07,8.020305e+07,14.386835,14.425126
934,Chile,CHL,2024,5610935,8.246171e+07,8.363503e+07,14.905721,14.696608
935,Chile,CHL,2025,5647116,8.450691e+07,8.706701e+07,15.417961,14.964614
936,Chile,CHL,2026,5676807,8.863697e+07,9.313125e+07,16.405570,15.613878
937,Chile,CHL,2027,5706498,9.276704e+07,9.919549e+07,17.382902,16.256386
938,Chile,CHL,2028,5736188,9.689710e+07,1.052597e+08,18.350119,16.892246
939,Chile,CHL,2029,5765879,1.010272e+08,1.113240e+08,19.307373,17.521554
940,Chile,CHL,2030,5795570,1.051572e+08,1.173882e+08,20.254818,18.144415
941,Chile,CHL,2031,5818268,1.093387e+08,1.234516e+08,21.217926,18.792318
942,Chile,CHL,2032,5840967,1.135203e+08,1.295149e+08,22.173544,19.435182
943,Chile,CHL,2033,5863665,1.177018e+08,1.355783e+08,23.121768,20.073072
944,Chile,CHL,2034,5886364,1.218833e+08,1.416417e+08,24.062675,20.706039
945,Chile,CHL,2035,5909062,1.260648e+08,1.477050e+08,24.996357,21.334147
946,Chile,CHL,2036,5924750,1.306250e+08,1.541818e+08,26.023343,22.047336
947,Chile,CHL,2037,5940437,1.351851e+08,1.606586e+08,27.044908,22.756761
948,Chile,CHL,2038,5956125,1.397453e+08,1.671353e+08,28.061088,23.462445
949,Chile,CHL,2039,5971813,1.443054e+08,1.736121e+08,29.071929,24.164422
950,Chile,CHL,2040,5987500,1.488656e+08,1.800889e+08,30.077477,24.862724
951,Chile,CHL,2041,5996783,1.538002e+08,1.869747e+08,31.179159,25.647125
952,Chile,CHL,2042,6006066,1.587349e+08,1.938604e+08,32.277435,26.429101
953,Chile,CHL,2043,6015348,1.636696e+08,2.007462e+08,33.372328,27.208668
954,Chile,CHL,2044,6024631,1.686043e+08,2.076319e+08,34.463840,27.985829
955,Chile,CHL,2045,6033914,1.735390e+08,2.145177e+08,35.551994,28.760598
956,Chile,CHL,2046,6036217,1.785741e+08,2.214450e+08,36.686057,29.583781
957,Chile,CHL,2047,6038520,1.836093e+08,2.283723e+08,37.819255,30.406336
958,Chile,CHL,2048,6040824,1.886444e+08,2.352997e+08,38.951582,31.228259
959,Chile,CHL,2049,6043127,1.936796e+08,2.422270e+08,40.083052,32.049561
960,Chile,CHL,2050,6045430,1.987147e+08,2.491543e+08,41.213661,32.870236

In [499]:
df_hh_heat_elect_all[(df_hh_heat_elect_all['Nation']=='Brazil')&
                    (df_hh_heat_elect_all['Year']==2015)].to_csv('../row_data/hh_heat_elec_gj_BRA_2015.csv')
df_hh_heat_elect_all[(df_hh_heat_elect_all['Nation']=='Brazil')&
                    (df_hh_heat_elect_all['Year']==2015)]

,Nation,iso_code3,Year,hh,Heat_Total_GJ,Elect_Total_GJ,consumpinit_scoe_gj_per_hh_residential_elec_appliances,consumpinit_scoe_gj_per_hh_residential_heat_energy
202,Brazil,BRA,2015,56640376,550420000.0,750190000.0,13.244792,9.717803

In [500]:
# #scoe crowss walk 
# scoe_energy_demands = {
#    consumpinit_scoe_gj_per_hh_residential_elec_appliances : [all but (residential space heating +residential cooking+ clothes dryers)]
#    consumpinit_scoe_gj_per_hh_residential_heat_energy : [residential space heating +residential cooking+ clothes dryers]
#    consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances : (share of electric in residential [0-1.0])*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy  (1- share of electri in residential)*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances :  (share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy (1-share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]
total_heat_elect_df['Share_of_electricity']=total_heat_elect_df.apply(lambda row:
                    row['Elect_Total_GJ'] / (row['Heat_Total_GJ']+ row['Elect_Total_GJ']) 
                    if (row['Heat_Total_GJ']+ row['Elect_Total_GJ'] )!=0 else 0, axis=1)
total_heat_elect_df['Share_of_heat']=total_heat_elect_df.apply(lambda row: 1-row['Share_of_electricity'], axis=1)
total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145
...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445

In [501]:
df_energy_services=pd.read_excel('../row_data/IEA - Energy Efficiency Indicators database - Extended (December 2022).xlsb',
                        engine='pyxlsb',sheet_name='Services - Energy',skiprows=[0])
df_energy_services=df_energy_services.replace('..',0)
df_energy_bilding=df_energy_services[(df_energy_services['End use']=='Other building energy use')&
                                    (df_energy_services['Product'].str.startswith('Total final energy use (PJ)'))]
df_energy_bilding

,Country,End use,Product,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
33,Australia,Other building energy use,Total final energy use (PJ) ...,212.02,217.68,224.95,254.08,259.77,260.31,263.75,...,297.01,294.91,303.08,310.23,327.90,327.11,334.32,338.31,338.78,333.04
75,Austria,Other building energy use,Total final energy use (PJ) ...,40.00,42.50,41.06,43.16,41.84,43.23,44.11,...,39.08,39.67,40.23,39.84,40.53,38.41,40.53,40.96,41.14,38.31
117,Belgium,Other building energy use,Total final energy use (PJ) ...,145.54,152.85,158.65,167.36,195.08,195.97,190.24,...,184.38,193.25,205.30,177.43,193.01,194.07,194.07,194.50,192.07,185.86
192,Canada,Other building energy use,Total final energy use (PJ) ...,195.00,196.66,205.02,219.90,222.06,213.27,218.24,...,251.58,246.71,259.69,265.83,263.50,265.38,287.93,293.65,300.10,286.62
234,Czech Republic,Other building energy use,Total final energy use (PJ) ...,124.41,134.61,126.82,143.56,144.63,129.94,128.04,...,130.91,126.98,125.69,121.98,124.22,128.92,132.57,130.29,132.94,124.12
309,Denmark,Other building energy use,Total final energy use (PJ) ...,38.92,39.29,40.14,40.00,40.49,40.82,42.05,...,40.23,39.41,39.14,38.74,38.20,38.44,39.89,39.78,39.71,76.29
351,Estonia,Other building energy use,Total final energy use (PJ) ...,12.08,12.42,12.41,14.19,15.94,16.29,16.47,...,16.85,17.75,17.51,19.17,19.50,20.87,19.63,20.54,19.57,19.75
393,Finland,Other building energy use,Total final energy use (PJ) ...,53.20,56.54,58.48,58.72,60.28,61.40,62.99,...,67.68,69.84,68.41,68.02,67.31,65.24,68.21,68.18,66.69,63.14
435,France,Other building energy use,Total final energy use (PJ) ...,160.86,163.94,160.34,164.79,167.78,165.53,165.53,...,165.10,168.47,169.01,174.42,172.50,165.66,170.28,170.52,169.56,175.77
510,Germany,Other building energy use,Total final energy use (PJ) ...,1227.57,385.84,385.99,376.51,375.79,375.34,440.20,...,446.20,446.38,436.91,447.05,480.66,496.04,485.78,463.60,474.70,480.90
552,Greece,Other building energy use,Total final energy use (PJ) ...,55.05,61.76,64.73,69.96,74.87,81.56,87.28,...,78.30,81.25,76.23,71.76,78.50,85.31,82.20,76.99,78.04,67.00
594,Hungary,Other building energy use,Total final energy use (PJ) ...,126.64,133.90,124.17,129.12,148.44,146.54,133.24,...,127.83,98.54,97.84,88.53,92.26,91.41,90.18,87.78,85.74,83.53
669,Ireland,Other building energy use,Total final energy use (PJ) ...,49.10,50.34,51.87,55.41,55.04,59.19,62.68,...,62.91,65.15,66.47,62.67,66.96,68.46,68.22,73.29,75.51,75.95
744,Italy,Other building energy use,Total final energy use (PJ) ...,146.98,153.57,159.89,176.56,183.99,204.34,215.15,...,230.27,239.58,241.49,236.77,250.64,254.44,258.67,276.22,259.64,230.30
819,Japan,Other building energy use,Total final energy use (PJ) ...,1328.39,1359.37,1364.13,1407.41,1436.78,1352.39,1380.94,...,1265.72,1279.16,1276.87,1254.43,1266.61,1284.70,1289.67,1311.48,1306.99,1253.51
861,Korea,Other building energy use,Total final energy use (PJ) ...,241.69,230.54,232.93,256.89,281.02,309.01,293.44,...,277.95,273.36,268.19,264.07,271.00,291.18,290.76,289.67,269.09,243.35
903,Lithuania,Other building energy use,Total final energy use (PJ) ...,19.45,19.66,20.35,21.67,22.70,23.55,25.41,...,24.43,25.62,24.86,24.52,24.08,25.21,26.54,27.21,26.18,24.07
945,Luxembourg,Other building energy use,Total final energy use (PJ) ...,15.21,15.40,14.57,16.47,15.54,15.38,15.40,...,14.24,16.10,16.78,14.84,16.69,16.79,18.83,19.35,21.79,20.69
1020,Mexico,Other building energy use,Total final energy use (PJ) ...,114.69,115.65,120.97,119.49,118.26,118.04,122.72,...,128.84,131.86,132.31,132.93,137.27,139.19,135.45,135.28,136.65,128.23
1062,Netherlands,Other building energy use,Total final energy use (PJ) ...,47.52,50.08,48.51,49.40,52.29,51.16,52.01,...,56.49,54.63,55.18,53.35,53.77,52.77,53.93,53.52,56.88,263.90
1104,New Zealand,Other building energy use,Total final energy use (PJ) ...,9.11,9.06,9.28,9.69,10.60,10.97,11.31,...,11.22,11.98,11.95,12.22,12.50,12.39,12.43,12.81,12.90,12.35
1146,Norway,Other building energy use,Total final energy use (PJ) ...,88.90,106.26,110.98,95.27,95.75,95.73,94.43,...,113.08,117.06,119.26,112.95,114.22,122.87,119.95,122.29,123.09,115.38
1188,Poland,Other building energy use,Total final energy use (PJ) ...,219.88,239.43,272.61,280.47,281.46,281.52,312.05,...,352.24,349.57,337.65,326.08,327.18,354.81,335.56,332.00,326.96,316.24
1230,Portugal,Other building energy use,Total final energy use (PJ) ...,54.50,73.64,76.37,72.42,73.40,23.00,25.35,...,26.35,28.88,28.53,34.34,37.39,36.24,37.33,40.28,38.87,35.39
1305,Slovak Republic,Other building energy use,Total final energy use (PJ) ...,92.09,96.04,95.46,80.14,88.24,73.30,78.60,...,67.06,60.76,71.62,51.64,54.41,54.78,59.74,55.05,50.75,45.86
1347,Spain,Other building energy use,Total final energy use (PJ) ...,21.98,25.12,28.46,33.64,28.26,22.06,48.30,...,59.12,60.94,56.24,52.54,56.83,57.89,61.19,58.02,58.74,54.06
1422,Sweden,Other building energy use,Total final energy use (PJ) ...,63.15,70.02,69.94,68.21,67.93,66.51,63.10,...,60.35,62.02,59.53,58.73,61.13,62.52,63.01,63.72,62.83,61.32
1464,Switzerland,Other building energy use,Total final energy use (PJ) ...,33.67,34.57,34.69,34.77,35.32,35.51,36.14,...,37.24,37.08,37.22,37.00,36.80,36.47,36.35,36.72,36.06,34.07
1506,Republic of Türkiye,Other building energy use,Total final energy use (PJ) ...,104.36,115.36,126.60,158.23,182.42,206.95,252.45,...,414.62,460.76,444.30,461.44,510.26,519.46,588.18,538.62,605.80,594.04
1548,United Kingdom,Other building energy use,Total final energy use (PJ) ...,851.73,184.04,158.53,140.81,135.06,184.51,159.79,...,127.92,139.89,141.58,162.81,240.04,253.81,253.87,242.65,237.55,221.01
1590,United States,Other building energy use,Total final energy use (PJ) ...,8082.59,8092.40,8212.02,8341.00,8411.21,8389.97,8266.48,...,4858.81,4920.03,5085.10,5308.20,5601.46,5609.47,5531.86,5638.07,5554.49,5094.08
1665,Argentina,Other building energy use,Total final energy use (PJ) ...,133.09,136.53,132.15,140.37,147.82,154.85,154.97,...,183.68,187.93,195.41,190.70,205.70,193.05,196.01,194.09,183.87,0.00
1707,Brazil,Other building energy use,Total final energy use (PJ) ...,343.85,329.51,340.18,343.73,317.01,334.09,340.78,...,410.64,432.84,451.12,478.20,476.16,465.35,467.10,475.65,492.31,441.27
1782,Morocco,Other building energy use,Total final energy use (PJ) ...,0.00,0.00,0.00,0.00,33.05,33.66,34.32,...,36.75,37.38,37.58,37.87,38.18,38.59,39.53,39.70,40.65,39.56
1824,South Africa,Other building energy use,Total final energy use (PJ) ...,92.37,108.28,117.66,132.96,154.20,166.95,184.58,...,162.94,189.43,195.65,195.90,184.81,205.82,223.62,224.85,222.59,0.00
1866,Ukraine,Other building energy use,Total final energy use (PJ) ...,67.03,93.00,93.55,96.05,115.37,91.36,112.26,...,214.76,209.62,241.48,195.31,162.80,195.60,181.58,198.80,201.81,0.00
1908,Chile,Other building energy use,Total final energy use (PJ) ...,26.08,26.92,29.23,34.08,39.27,38.86,40.69,...,66.38,59.92,64.08,65.45,67.27,75.25,83.55,79.92,78.96,67.80
1950,Colombia,Other building energy use,Total final energy use (PJ) ...,49.68,37.53,46.89,49.23,43.41,44.23,48.09,...,64.03,70.73,61.69,64.40,63.84,64.80,73.90,69.27,78.23,0.00
2025,Latvia,Other building energy use,Total final energy use (PJ) ...,19.78,21.01,22.39,23.65,24.98,24.91,26.62,...,23.31,26.10,25.14,25.49,24.55,24.81,25.39,24.76,23.79,23.01
2067,Albania,Other building energy use,Total final energy use (PJ) ...,5.61,5.49,4.36,9.32,8.10,8.59,5.94,...,6.84,6.58,7.96,7.47,8.20,7.47,8.91,8.98,9.53,8.24
2109,Azerbaijan,Other building energy use,Total final energy use (PJ) ...,27.81,20.80,17.75,16.26,10.00,11.26,8.73,...,20.78,23.99,25.93,27.08,28.46,24.92,28.73,27.39,49.25,0.00
2151,Belarus,Other building energy use,Total final energy use (PJ) ...,91.07,86.39,78.83,86.08,85.88,87.43,87.41,...,82.44,89.36,89.29,89.59,84.48,86.35,86.07,88.88,85.09,0.00
2193,Bosnia and Herzegovina,Other building energy use,Total final energy use (PJ) ...,3.78,3.86,3.90,4.24,4.37,4.85,4.83,...,0.00,0.00,0.00,14.92,14.99,18.23,14.89,14.59,17.04,15.81
2235,Bulgaria,Other building energy use,Total final energy use (PJ) ...,27.53,32.30,31.25,31.92,29.39,34.49,39.38,...,43.84,42.82,40.42,38.81,42.03,45.04,45.21,47.68,48.67,40.54
2277,Croatia,Other building energy use,Total final energy use (PJ) ...,21.79,24.87,26.21,27.89,28.88,30.16,29.95,...,32.92,31.73,31.01,29.02,31.95,32.67,34.23,34.86,34.98,31.71
2319,Cyprus,Other building energy use,Total final energy use (PJ) ...,4.50,5.24,5.70,5.99,6.16,6.73,8.62,...,9.90,9.32,8.50,8.39,8.65,9.26,9.59,9.80,10.19,8.49
2361,Georgia,Other building energy use,Total final energy use (PJ) ...,11.11,8.02,8.36,8.82,9.14,11.00,9.64,...,6.74,8.29,14.73,17.94,16.86,18.16,18.96,21.56,22.42,17.29
2403,Hong Kong (China),Other building energy use,Total final energy use (PJ) ...,49.76,52.61,60.73,63.34,64.48,64.24,68.34,...,76.27,78.54,79.11,80.26,81.72,83.12,83.47,83.78,85.66,73.75
2478,Kosovo,Other building energy use,Total final energy use (PJ) ...,4.69,5.40,5.40,5.49,5.45,5.73,5.93,...,4.93,4.92,5.01,5.82,6.21,7.41,8.02,6.47,6.86,6.63
2520,Malta,Other building energy use,Total final energy use (PJ) ...,1.81,1.97,2.08,2.24,2.25,2.66,3.03,...,3.68,4.20,4.33,4.63,5.06,4.95,5.22,4.89,5.11,4.85
2562,Republic of Moldova,Other building energy use,Total final energy use (PJ) ...,8.21,7.49,7.28,8.58,11.14,10.46,10.82,...,11.27,11.28,10.82,9.95,10.33,10.84,10.75,11.00,10.96,10.25
2604,Republic of North Macedonia,Other building energy use,Total final energy use (PJ) ...,5.96,4.95,8.02,10.63,9.71,9.99,9.38,...,8.63,9.57,8.45,8.21,8.87,8.91,8.99,8.80,8.86,7.52
2646,Romania,Other building energy use,Total final energy use (PJ) ...,28.14,46.96,23.25,48.08,52.79,69.99,100.89,...,74.29,73.83,74.75,74.05,73.78,75.65,77.09,82.42,81.83,76.49
2688,Serbia,Other building energy use,Total final energy use (PJ) ...,1.07,1.18,1.21,1.13,16.52,24.52,26.64,...,43.75,34.92,33.62,32.34,36.62,37.11,39.35,37.32,36.15,35.86
2730,Slovenia,Other building energy use,Total final energy use (PJ) ...,21.98,30.00,29.83,21.03,22.66,19.84,18.37,...,22.25,18.98,19.58,17.89,19.03,20.62,20.13,19.87,18.87,17.39
2772,Chinese Taipei,Other building energy use,Total final energy use (PJ) ...,113.25,122.57,125.40,136.75,144.00,149.47,153.40,...,105.08,101.01,104.37,70.40,70.52,67.78,67.52,117.03,114.88,0.00
2814,Uruguay,Other building energy use,Total final energy use (PJ) ...,4.96,4.87,4.78,4.74,5.00,5.10,6.02,...,7.41,7.73,7.80,7.64,7.50,7.86,7.66,8.06,12.85,0.00

In [502]:
#fill present data with mean value
#input all countries with linear regression
#apply shear of elec fraction
def is_number(s):
    try:
        float(s)
        return True
#     except ValueError:
    except:
        return False
nation_mean=[]
for nation in df_energy_bilding['Country'].unique():
    values=[val for val in df_energy_bilding.loc[df_energy_bilding['Country']==nation].values[0] if is_number(val)]
    nation_mean.append([nation,np.mean(values)])
mean_building=pd.DataFrame(nation_mean,columns=['Nation','building_energy_mean'])
mean_building

                         Nation  building_energy_mean
0                     Australia            287.163333
1                       Austria             40.919524
2                       Belgium            186.136190
3                        Canada            244.880476
4                Czech Republic            129.657143
5                       Denmark             41.780000
6                       Estonia             17.199524
7                       Finland             64.332381
8                        France            168.476667
9                       Germany            477.399048
10                       Greece             77.418571
11                      Hungary            112.700000
12                      Ireland             63.239048
13                        Italy            221.179524
14                        Japan           1316.650476
15                        Korea            272.943810
16                    Lithuania             24.148571
17                   Luxembourg             16.628095
18                       Mexico            126.950952
19                  Netherlands             63.239048
20                  New Zealand             11.349048
21                       Norway            110.101429
22                       Poland            313.437619
23                     Portugal             39.979048
24              Slovak Republic             71.650476
25                        Spain             48.542857
26                       Sweden             63.411429
27                  Switzerland             36.061905
28          Republic of Türkiye            371.306190
29               United Kingdom            217.986190
30                United States           6747.479524
31                    Argentina            163.275238
32                       Brazil            401.574286
33                      Morocco             29.974286
34                 South Africa            169.307143
35                      Ukraine            154.998095
36                        Chile             54.297619
37                     Colombia             54.461905
38                       Latvia             24.422381
39                      Albania              7.243810
40                   Azerbaijan             21.036667
41                      Belarus             81.981905
42       Bosnia and Herzegovina              6.925714
43                     Bulgaria             39.018095
44                      Croatia             30.522381
45                       Cyprus              8.284762
46                      Georgia             12.623333
47            Hong Kong (China)             72.600952
48                       Kosovo              5.706190
49                        Malta              3.624762
50          Republic of Moldova             10.142857
51  Republic of North Macedonia              8.691429
52                      Romania             68.685714
53                       Serbia             27.495238
54                     Slovenia             20.831429
55               Chinese Taipei            111.212857
56                      Uruguay              6.562381

In [503]:
coun_year_building=[]
for c in df_energy_bilding['Country'].unique():
    for y in years_hist:
        building_data=df_energy_bilding[df_energy_bilding['Country']==c][y].values[0]
        if building_data==0:
            building_data=mean_building[mean_building['Nation']==c]['building_energy_mean'].values[0]
        coun_year_building.append([c,y,building_data])

building_complete_hist=pd.DataFrame(coun_year_building,columns=['Nation','Year','Other building energy use'])
        
building_complete_hist

        Nation  Year  Other building energy use
0    Australia  2011                     297.01
1    Australia  2012                     294.91
2    Australia  2013                     303.08
3    Australia  2014                     310.23
4    Australia  2015                     327.90
..         ...   ...                        ...
508    Uruguay  2015                       7.50
509    Uruguay  2016                       7.86
510    Uruguay  2017                       7.66
511    Uruguay  2018                       8.06
512    Uruguay  2019                      12.85

[513 rows x 3 columns]

In [504]:
building_pop_gdp=building_complete_hist.merge(df_pop_gdp_all,on=['Nation','Year'])
building_pop_gdp['bias']=1
building_pop_gdp

,Nation,Year,Other building energy use,iso_code3,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias
0,Australia,2011,297.01,AUS,1.905604e+07,3.283984e+06,861.792237,19.056040,3.283984,1
1,Australia,2012,294.91,AUS,1.941483e+07,3.318631e+06,895.123477,19.414834,3.318631,1
2,Australia,2013,303.08,AUS,1.977501e+07,3.353116e+06,928.454717,19.775013,3.353116,1
3,Australia,2014,310.23,AUS,2.009566e+07,3.380029e+06,961.785957,20.095657,3.380029,1
4,Australia,2015,327.90,AUS,2.041055e+07,3.405449e+06,995.117197,20.410546,3.405449,1
...,...,...,...,...,...,...,...,...,...,...
445,Uruguay,2015,7.50,URY,3.242948e+06,1.690652e+05,51.626567,3.242948,0.169065,1
446,Uruguay,2016,7.86,URY,3.257863e+06,1.662762e+05,52.159029,3.257863,0.166276,1
447,Uruguay,2017,7.66,URY,3.273061e+06,1.635843e+05,52.691490,3.273061,0.163584,1
448,Uruguay,2018,8.06,URY,3.288346e+06,1.609439e+05,53.223952,3.288346,0.160944,1
449,Uruguay,2019,12.85,URY,3.303391e+06,1.583396e+05,53.756413,3.303391,0.158340,1

In [505]:
df_pop_gdp_all['bias']=1
df_pop_gdp_all

,Nation,iso_code3,Year,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias
0,Afghanistan,AFG,2011,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1
1,Afghanistan,AFG,2012,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1
2,Afghanistan,AFG,2013,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1
3,Afghanistan,AFG,2014,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1
4,Afghanistan,AFG,2015,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1
...,...,...,...,...,...,...,...,...,...
7275,Zimbabwe,ZWE,2046,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1
7276,Zimbabwe,ZWE,2047,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1
7277,Zimbabwe,ZWE,2048,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1
7278,Zimbabwe,ZWE,2049,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1
7279,Zimbabwe,ZWE,2050,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1

In [506]:
building_pop_gdp=building_pop_gdp.merge(
total_heat_elect_df[total_heat_elect_df['Nation'].isin( building_pop_gdp['Nation'].unique())],on=['Nation','iso_code3','Year'])
building_pop_gdp

,Nation,Year,Other building energy use,iso_code3,population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat
0,Australia,2011,297.01,AUS,1.905604e+07,3.283984e+06,861.792237,19.056040,3.283984,1,181560000.0,360870000.0,0.665284,0.334716
1,Australia,2012,294.91,AUS,1.941483e+07,3.318631e+06,895.123477,19.414834,3.318631,1,182030000.0,357780000.0,0.662789,0.337211
2,Australia,2013,303.08,AUS,1.977501e+07,3.353116e+06,928.454717,19.775013,3.353116,1,185220000.0,354740000.0,0.656975,0.343025
3,Australia,2014,310.23,AUS,2.009566e+07,3.380029e+06,961.785957,20.095657,3.380029,1,186230000.0,342270000.0,0.647625,0.352375
4,Australia,2015,327.90,AUS,2.041055e+07,3.405449e+06,995.117197,20.410546,3.405449,1,186270000.0,352410000.0,0.654210,0.345790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,Uruguay,2015,7.50,URY,3.242948e+06,1.690652e+05,51.626567,3.242948,0.169065,1,18000000.0,23110000.0,0.562150,0.437850
437,Uruguay,2016,7.86,URY,3.257863e+06,1.662762e+05,52.159029,3.257863,0.166276,1,18030000.0,25100000.0,0.581962,0.418038
438,Uruguay,2017,7.66,URY,3.273061e+06,1.635843e+05,52.691490,3.273061,0.163584,1,17970000.0,23490000.0,0.566570,0.433430
439,Uruguay,2018,8.06,URY,3.288346e+06,1.609439e+05,53.223952,3.288346,0.160944,1,18020000.0,24180000.0,0.572986,0.427014
440,Uruguay,2019,12.85,URY,3.303391e+06,1.583396e+05,53.756413,3.303391,0.158340,1,17923750.0,35220000.0,0.662731,0.337269

In [507]:
build_mean_TJ=np.mean(building_pop_gdp['Other building energy use'].values)*1e3
heat_mean_TJ=np.mean(building_pop_gdp['Heat_Total_GJ'].values)*1e-3
elect_mean_TJ=np.mean(building_pop_gdp['Elect_Total_GJ'].values)*1e-3
residential_commercial_share_mean=build_mean_TJ/(heat_mean_TJ+elect_mean_TJ)
residential_commercial_share_mean

0.3009723478329948

In [508]:
#input all countries with linear regression
X=building_pop_gdp[['bias','population_gnrl_urban(millions)','population_gnrl_rural(millions)','gdp_mmm_usd']]
#X=building_pop_gdp[['bias','gdp_mmm_usd']]

Y=building_pop_gdp['Other building energy use']

linear_model_building = LinearRegression()

linear_model_building.fit(X,Y)

df_building_all=df_pop_gdp_all.copy()

for c in df_pop_gdp_all['Nation'].unique():
    for y in years_all:
        if (c,y) in zip(building_pop_gdp['Nation'],building_pop_gdp['Year']):
            
            row=building_pop_gdp[(building_pop_gdp['Nation']==c)&(building_pop_gdp['Year']==y)]
            build_data=row['Other building energy use'].values[0]*1e3

        else:
            
            X_test = df_pop_gdp_all.loc[(df_pop_gdp_all['Nation'] == c) & 
                                (df_pop_gdp_all['Year']== y)][['bias','population_gnrl_urban(millions)',
                                                                  'population_gnrl_rural(millions)',
                                                                  'gdp_mmm_usd']]
#             X_test = df_pop_gdp_all.loc[(df_pop_gdp_all['Nation'] == c) & 
#                                 (df_pop_gdp_all['Year']== y)][['bias','gdp_mmm_usd']]
            
            build_data=linear_model_building.predict(X_test)[0]*1e3
            
            if build_data<0:
                build_data=residential_commercial_share_mean*total_heat_elect_df.loc[(total_heat_elect_df['Nation']==c)&
                       (total_heat_elect_df['Year']==y)
                       ].apply(lambda row: row['Heat_Total_GJ']+row['Elect_Total_GJ'],axis=1).values[0]*1e-3
                
        total_heat_elect_df.loc[(total_heat_elect_df['Nation']==c)&
                            (total_heat_elect_df['Year']==y),'Other building energy use(TJ)']=build_data

total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ)
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136
...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038

In [509]:
# consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances : (share of electric in residential [0-1.0])*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy  (1- share of electri in residential)*0.9*[sheet: services, End use =="other building energy use" & PRoduct= "total final energy"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances :  (share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]
#    consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy (1-share of electric in residential [0-1.0])*0.1*[sheet: services, End use =="other building energy use"]
total_heat_elect_df=total_heat_elect_df.merge(df_pop_gdp_all, on=['Nation','iso_code3','Year'])

total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1

In [510]:

total_heat_elect_df['consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances']=total_heat_elect_df.apply(
    lambda row: row['Share_of_electricity'] *0.9 * row['Other building energy use(TJ)']/row['gdp_mmm_usd'], axis=1) 

total_heat_elect_df['consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy']=total_heat_elect_df.apply(
    lambda row: row['Share_of_heat'] *0.9 * row['Other building energy use(TJ)']/row['gdp_mmm_usd'], axis=1) 

total_heat_elect_df['consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances']=total_heat_elect_df.apply(
    lambda row: row['Share_of_electricity'] *0.1 * row['Other building energy use(TJ)']/row['gdp_mmm_usd'], axis=1) 

total_heat_elect_df['consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy']=total_heat_elect_df.apply(
    lambda row: row['Share_of_heat'] *0.1 * row['Other building energy use(TJ)']/row['gdp_mmm_usd'], axis=1) 


total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1,1050.373626,4053.228277,116.708181,450.358697
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1,1021.585861,3876.668179,113.509540,430.740909
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1,998.561085,3729.377484,110.951232,414.375276
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1,977.764441,3598.756476,108.640493,399.861831
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1,957.142833,3477.050887,106.349204,386.338987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1,98.133965,2017.594010,10.903774,224.177112
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1,95.253855,1882.615375,10.583762,209.179486
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1,92.711731,1763.476773,10.301303,195.941864
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1,90.451398,1657.544451,10.050155,184.171606
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1,88.428460,1562.737884,9.825384,173.637543

In [511]:
total_heat_elect_df_hist=total_heat_elect_df[total_heat_elect_df['Year'] < 2020]
total_heat_elect_df_proj=total_heat_elect_df[total_heat_elect_df['Year'] >= 2020]

total_heat_elect_df_hist

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1,1050.373626,4053.228277,116.708181,450.358697
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1,1021.585861,3876.668179,113.509540,430.740909
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1,998.561085,3729.377484,110.951232,414.375276
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1,977.764441,3598.756476,108.640493,399.861831
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1,957.142833,3477.050887,106.349204,386.338987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7204,Zimbabwe,ZWE,2015,2.167056e+08,1.530004e+07,0.065947,0.934053,69827.284635,4.473872e+06,9.340770e+06,6.769741,4.473872,9.340770,1,612.194825,8670.959876,68.021647,963.439986
7205,Zimbabwe,ZWE,2016,2.199770e+08,1.641311e+07,0.069432,0.930568,71146.883411,4.531238e+06,9.499100e+06,6.756399,4.531238,9.499100,1,658.028432,8819.238109,73.114270,979.915345
7206,Zimbabwe,ZWE,2017,2.229955e+08,1.743358e+07,0.072510,0.927490,72362.509687,4.589452e+06,9.647147e+06,6.743057,4.589452,9.647147,1,700.323868,8957.945405,77.813763,995.327267
7207,Zimbabwe,ZWE,2018,2.258219e+08,1.838103e+07,0.075270,0.924730,73498.316767,4.650597e+06,9.788215e+06,6.729715,4.650597,9.788215,1,739.847700,9089.467371,82.205300,1009.940819
7208,Zimbabwe,ZWE,2019,2.285729e+08,1.929472e+07,0.077843,0.922157,74601.288177,4.717307e+06,9.928166e+06,6.716372,4.717307,9.928166,1,778.167143,9218.473291,86.463016,1024.274810

In [512]:
total_heat_elect_df_proj

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
9,Afghanistan,AFG,2020,6.508870e+08,1.838898e+08,0.220286,0.779714,251244.726176,1.013149e+07,2.879685e+07,50.050108,10.131490,28.796851,1,995.226178,3522.651290,110.580686,391.405699
10,Afghanistan,AFG,2021,6.903290e+08,1.979817e+08,0.222874,0.777126,267356.956213,1.095378e+07,3.071641e+07,51.885013,10.953783,30.716406,1,1033.599134,3603.987809,114.844348,400.443090
11,Afghanistan,AFG,2022,7.040280e+08,2.032529e+08,0.224024,0.775976,273066.457319,1.134045e+07,3.139778e+07,53.719919,11.340453,31.397784,1,1024.874048,3549.961796,113.874894,394.440200
12,Afghanistan,AFG,2023,7.177269e+08,2.085241e+08,0.225127,0.774873,278775.958424,1.172712e+07,3.207916e+07,55.554825,11.727123,32.079162,1,1016.725320,3499.504604,112.969480,388.833845
13,Afghanistan,AFG,2024,7.314259e+08,2.137954e+08,0.226186,0.773814,284485.459529,1.211379e+07,3.276054e+07,57.389731,12.113792,32.760540,1,1009.097666,3452.273920,112.121963,383.585991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1,98.133965,2017.594010,10.903774,224.177112
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1,95.253855,1882.615375,10.583762,209.179486
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1,92.711731,1763.476773,10.301303,195.941864
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1,90.451398,1657.544451,10.050155,184.171606
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1,88.428460,1562.737884,9.825384,173.637543

In [513]:
for ssp_var in ['consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances',
               'consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy',
                'consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances',
                'consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy']:
    

    total_heat_elect_df_hist[['Nation','iso_code3','Year',
    ssp_var]].to_csv(grandparentdir+'/'+ssp_var+
    '/input_to_sisepuede/historical/'+ssp_var+'.csv')

    total_heat_elect_df_proj[['Nation','iso_code3','Year',
    ssp_var]].to_csv(grandparentdir+'/'+ssp_var+
    '/input_to_sisepuede/projected/'+ssp_var+'.csv')
    
    total_heat_elect_df_hist[['Nation','iso_code3','Year',
    ssp_var]].loc[(total_heat_elect_df_hist['Nation']=='Brazil')&
                 (total_heat_elect_df_hist['Year']==2015)].to_csv(grandparentdir+'/'+ssp_var+
    '/row_data/'+ssp_var+'_Bra_2015.csv')
    total_heat_elect_df.to_csv(grandparentdir+'/'+ssp_var+
    '/row_data/'+ssp_var[0:30]+'_all.csv')

In [514]:
total_heat_elect_df_hist[['Nation','iso_code3','Year',
    ssp_var]].loc[(total_heat_elect_df_hist['Nation']=='Brazil')&
                 (total_heat_elect_df_hist['Year']==2015)]

,Nation,iso_code3,Year,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
884,Brazil,BRA,2015,8.286033

In [515]:
total_heat_elect_df_hist.loc[(total_heat_elect_df_hist['Nation']=='Brazil')&
(total_heat_elect_df_hist['Year']==2015)]['Other building energy use(TJ)'].values[0]/(544210+640870)

0.40179565936476863

In [516]:
total_heat_elect_df_hist.loc[(total_heat_elect_df_hist['Nation']=='Brazil')]

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
880,Brazil,BRA,2011,544210000.0,640870000.0,0.540782,0.459218,410640.0,1.671585e+08,3.035601e+07,2064.430164,167.158531,30.356010,1,96.811252,82.209577,10.756806,9.134397
881,Brazil,BRA,2012,545120000.0,675800000.0,0.553517,0.446483,432840.0,1.692407e+08,3.004655e+07,2156.308348,169.240747,30.046545,1,99.997700,80.661063,11.110856,8.962340
882,Brazil,BRA,2013,518190000.0,721540000.0,0.582014,0.417986,451120.0,1.713007e+08,2.973522e+07,2248.186533,171.300683,29.735221,1,105.107946,75.485610,11.678661,8.387290
883,Brazil,BRA,2014,538940000.0,766750000.0,0.587237,0.412763,478200.0,1.733468e+08,2.941696e+07,2340.064717,173.346780,29.416964,1,108.003522,75.914468,12.000391,8.434941
884,Brazil,BRA,2015,550420000.0,750190000.0,0.576799,0.423201,476160.0,1.753754e+08,2.909633e+07,2431.942902,175.375428,29.096331,1,101.640367,74.574296,11.293374,8.286033
885,Brazil,BRA,2016,541590000.0,755080000.0,0.582322,0.417678,465350.0,1.773868e+08,2.877624e+07,2421.772225,177.386817,28.776239,1,100.705326,72.232078,11.189481,8.025786
886,Brazil,BRA,2017,561250000.0,758950000.0,0.574875,0.425125,467100.0,1.793793e+08,2.845453e+07,2411.601547,179.379296,28.454529,1,100.212122,74.107719,11.134680,8.234191
887,Brazil,BRA,2018,593920000.0,776370000.0,0.566573,0.433427,475650.0,1.813355e+08,2.813382e+07,2401.430870,181.335496,28.133824,1,100.998792,77.263679,11.222088,8.584853
888,Brazil,BRA,2019,587770000.0,807050000.0,0.578605,0.421395,492310.0,1.832416e+08,2.780788e+07,2391.260192,183.241634,27.807885,1,107.210324,78.080679,11.912258,8.675631

In [517]:
total_heat_elect_df_hist[['Nation','iso_code3','Year',
    'Other building energy use(TJ)','consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances']].loc[(total_heat_elect_df_hist['Nation']=='Ecuador')]

,Nation,iso_code3,Year,Other building energy use(TJ),consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances
1880,Ecuador,ECU,2011,44598.544115,48.252606
1881,Ecuador,ECU,2012,45303.484284,50.172703
1882,Ecuador,ECU,2013,46003.322693,51.995183
1883,Ecuador,ECU,2014,46708.722305,53.738728
1884,Ecuador,ECU,2015,47419.988971,55.401991
1885,Ecuador,ECU,2016,47304.945796,54.687879
1886,Ecuador,ECU,2017,47195.385707,53.959951
1887,Ecuador,ECU,2018,47044.591787,53.129454
1888,Ecuador,ECU,2019,46838.247201,52.184287

In [518]:
total_heat_elect_df_hist[['Nation','iso_code3','Year',
'Other building energy use(TJ)',
'consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances']].loc[
    (total_heat_elect_df_hist['Nation']=='Brazil')]

,Nation,iso_code3,Year,Other building energy use(TJ),consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances
880,Brazil,BRA,2011,410640.0,96.811252
881,Brazil,BRA,2012,432840.0,99.997700
882,Brazil,BRA,2013,451120.0,105.107946
883,Brazil,BRA,2014,478200.0,108.003522
884,Brazil,BRA,2015,476160.0,101.640367
885,Brazil,BRA,2016,465350.0,100.705326
886,Brazil,BRA,2017,467100.0,100.212122
887,Brazil,BRA,2018,475650.0,100.998792
888,Brazil,BRA,2019,492310.0,107.210324

In [519]:
total_heat_elect_df.loc[(total_heat_elect_df['Nation']=='Brazil')&
                       (total_heat_elect_df['Year']==2015)
                       ].apply(lambda row: row['Heat_Total_GJ']+row['Elect_Total_GJ'],axis=1).values[0]

1300610000.0

In [520]:
total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1,1050.373626,4053.228277,116.708181,450.358697
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1,1021.585861,3876.668179,113.509540,430.740909
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1,998.561085,3729.377484,110.951232,414.375276
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1,977.764441,3598.756476,108.640493,399.861831
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1,957.142833,3477.050887,106.349204,386.338987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1,98.133965,2017.594010,10.903774,224.177112
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1,95.253855,1882.615375,10.583762,209.179486
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1,92.711731,1763.476773,10.301303,195.941864
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1,90.451398,1657.544451,10.050155,184.171606
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1,88.428460,1562.737884,9.825384,173.637543

In [521]:
total_heat_elect_df

,Nation,iso_code3,Year,Heat_Total_GJ,Elect_Total_GJ,Share_of_electricity,Share_of_heat,Other building energy use(TJ),population_gnrl_urban,population_gnrl_rural,gdp_mmm_usd,population_gnrl_urban(millions),population_gnrl_rural(millions),bias,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy,consumpinit_scoe_tj_per_mmmgdp_other_se_elec_appliances,consumpinit_scoe_tj_per_mmmgdp_other_se_heat_energy
0,Afghanistan,AFG,2011,5.292452e+08,1.371512e+08,0.205810,0.794190,200566.890673,7.212518e+06,2.290489e+07,35.369178,7.212518,22.904893,1,1050.373626,4053.228277,116.708181,450.358697
1,Afghanistan,AFG,2012,5.450645e+08,1.436363e+08,0.208561,0.791439,207279.881574,7.528589e+06,2.363279e+07,38.085386,7.528589,23.632789,1,1021.585861,3876.668179,113.509540,430.740909
2,Afghanistan,AFG,2013,5.617517e+08,1.504121e+08,0.211204,0.788796,214341.586239,7.865068e+06,2.440452e+07,40.801594,7.865068,24.404524,1,998.561085,3729.377484,110.951232,414.375276
3,Afghanistan,AFG,2014,5.781630e+08,1.570840e+08,0.213648,0.786352,221289.032137,8.204880e+06,2.516592e+07,43.517802,8.204880,25.165924,1,977.764441,3598.756476,108.640493,399.861831
4,Afghanistan,AFG,2015,5.934765e+08,1.633688e+08,0.215855,0.784145,227789.505136,8.535606e+06,2.587800e+07,46.234010,8.535606,25.877997,1,957.142833,3477.050887,106.349204,386.338987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,Zimbabwe,ZWE,2046,1.816076e+08,8.833231e+06,0.046383,0.953617,57317.425304,5.352032e+06,7.863317e+06,24.382002,5.352032,7.863317,1,98.133965,2017.594010,10.903774,224.177112
7236,Zimbabwe,ZWE,2047,1.807230e+08,9.143963e+06,0.048160,0.951840,57144.712237,5.384492e+06,7.807897e+06,26.002852,5.384492,7.807897,1,95.253855,1882.615375,10.583762,209.179486
7237,Zimbabwe,ZWE,2048,1.798384e+08,9.454694e+06,0.049947,0.950053,56971.999171,5.416953e+06,7.752477e+06,27.623703,5.416953,7.752477,1,92.711731,1763.476773,10.301303,195.941864
7238,Zimbabwe,ZWE,2049,1.789539e+08,9.765425e+06,0.051746,0.948254,56799.286104,5.449414e+06,7.697057e+06,29.244553,5.449414,7.697057,1,90.451398,1657.544451,10.050155,184.171606
7239,Zimbabwe,ZWE,2050,1.780693e+08,1.007616e+07,0.053555,0.946445,56626.573038,5.481874e+06,7.641637e+06,30.865404,5.481874,7.641637,1,88.428460,1562.737884,9.825384,173.637543

In [523]:
total_heat_elect_df['Total_residential TJ']=total_heat_elect_df.apply(lambda row:
                    row['Heat_Total_GJ']*1e-3+row['Elect_Total_GJ']*1e-3,axis=1)

In [529]:
total_heat_elect_df[['Nation','iso_code3','Year',
'Other building energy use(TJ)','Total_residential TJ','gdp_mmm_usd']].loc[
    (total_heat_elect_df['Nation']=='Brazil')]

,Nation,iso_code3,Year,Other building energy use(TJ),Total_residential TJ,gdp_mmm_usd
880,Brazil,BRA,2011,410640.000000,1.185080e+06,2064.430164
881,Brazil,BRA,2012,432840.000000,1.220920e+06,2156.308348
882,Brazil,BRA,2013,451120.000000,1.239730e+06,2248.186533
883,Brazil,BRA,2014,478200.000000,1.305690e+06,2340.064717
884,Brazil,BRA,2015,476160.000000,1.300610e+06,2431.942902
885,Brazil,BRA,2016,465350.000000,1.296670e+06,2421.772225
886,Brazil,BRA,2017,467100.000000,1.320200e+06,2411.601547
887,Brazil,BRA,2018,475650.000000,1.370290e+06,2401.430870
888,Brazil,BRA,2019,492310.000000,1.394820e+06,2391.260192
889,Brazil,BRA,2020,301946.681957,8.810358e+05,2381.089515
890,Brazil,BRA,2021,318174.061126,8.976251e+05,2420.084159
891,Brazil,BRA,2022,329037.830647,9.011671e+05,2459.078803
892,Brazil,BRA,2023,339901.600168,9.047091e+05,2498.073447
893,Brazil,BRA,2024,350765.369689,9.082510e+05,2537.068091
894,Brazil,BRA,2025,361629.139210,9.117930e+05,2576.062735
895,Brazil,BRA,2026,385198.039433,9.459302e+05,2644.560657
896,Brazil,BRA,2027,408766.939655,9.800674e+05,2713.058580
897,Brazil,BRA,2028,432335.839878,1.014205e+06,2781.556502
898,Brazil,BRA,2029,455904.740101,1.048342e+06,2850.054425
899,Brazil,BRA,2030,479473.640324,1.082479e+06,2918.552347
900,Brazil,BRA,2031,502606.024839,1.114698e+06,2984.207436
901,Brazil,BRA,2032,525738.409354,1.146918e+06,3049.862524
902,Brazil,BRA,2033,548870.793869,1.179137e+06,3115.517613
903,Brazil,BRA,2034,572003.178384,1.211356e+06,3181.172701
904,Brazil,BRA,2035,595135.562899,1.243576e+06,3246.827790
905,Brazil,BRA,2036,619786.582261,1.279178e+06,3314.481563
906,Brazil,BRA,2037,644437.601622,1.314781e+06,3382.135336
907,Brazil,BRA,2038,669088.620984,1.350383e+06,3449.789110
908,Brazil,BRA,2039,693739.640345,1.385985e+06,3517.442883
909,Brazil,BRA,2040,718390.659706,1.421588e+06,3585.096656
910,Brazil,BRA,2041,743965.644636,1.459480e+06,3653.264451
911,Brazil,BRA,2042,769540.629565,1.497373e+06,3721.432246
912,Brazil,BRA,2043,795115.614494,1.535265e+06,3789.600040
913,Brazil,BRA,2044,820690.599423,1.573158e+06,3857.767835
914,Brazil,BRA,2045,846265.584352,1.611050e+06,3925.935630
915,Brazil,BRA,2046,872260.138153,1.650458e+06,3993.112738
916,Brazil,BRA,2047,898254.691954,1.689866e+06,4060.289846
917,Brazil,BRA,2048,924249.245756,1.729274e+06,4127.466953
918,Brazil,BRA,2049,950243.799557,1.768682e+06,4194.644061
919,Brazil,BRA,2050,976238.353358,1.808090e+06,4261.821169

In [530]:
total_heat_elect_df[['Nation','iso_code3','Year','Total_residential TJ','gdp_mmm_usd']].loc[
    (total_heat_elect_df['Nation']=='Ecuador')]

       Nation iso_code3  Year  Total_residential TJ  gdp_mmm_usd
1880  Ecuador       ECU  2011         148181.533739   107.338178
1881  Ecuador       ECU  2012         150523.742828   109.711532
1882  Ecuador       ECU  2013         152849.000994   112.084885
1883  Ecuador       ECU  2014         155192.736611   114.458239
1884  Ecuador       ECU  2015         157555.965897   116.831593
1885  Ecuador       ECU  2016         157173.727542   116.470857
1886  Ecuador       ECU  2017         156809.707095   116.110122
1887  Ecuador       ECU  2018         156308.684589   115.749386
1888  Ecuador       ECU  2019         155623.091418   115.388651
1889  Ecuador       ECU  2020         154708.293085   115.027915
1890  Ecuador       ECU  2021         151065.679074   116.214234
1891  Ecuador       ECU  2022         151649.502934   117.400553
1892  Ecuador       ECU  2023         152233.326795   118.586873
1893  Ecuador       ECU  2024         152817.150655   119.773192
1894  Ecuador       ECU  2025         153400.974515   120.959511
1895  Ecuador       ECU  2026         157726.609878   125.974948
1896  Ecuador       ECU  2027         162052.245240   130.990386
1897  Ecuador       ECU  2028         166377.880603   136.005823
1898  Ecuador       ECU  2029         170703.515965   141.021260
1899  Ecuador       ECU  2030         175029.151328   146.036698
1900  Ecuador       ECU  2031         179763.281390   151.596765
1901  Ecuador       ECU  2032         184497.411452   157.156833
1902  Ecuador       ECU  2033         189231.541514   162.716901
1903  Ecuador       ECU  2034         193965.671576   168.276968
1904  Ecuador       ECU  2035         198699.801638   173.837036
1905  Ecuador       ECU  2036         204222.456806   180.296078
1906  Ecuador       ECU  2037         209745.111973   186.755121
1907  Ecuador       ECU  2038         215267.767140   193.214163
1908  Ecuador       ECU  2039         220790.422308   199.673205
1909  Ecuador       ECU  2040         226313.077475   206.132248
1910  Ecuador       ECU  2041         232640.310277   213.492915
1911  Ecuador       ECU  2042         238967.543078   220.853583
1912  Ecuador       ECU  2043         245294.775880   228.214251
1913  Ecuador       ECU  2044         251622.008681   235.574918
1914  Ecuador       ECU  2045         257949.241483   242.935586
1915  Ecuador       ECU  2046         265086.881329   251.180162
1916  Ecuador       ECU  2047         272224.521175   259.424738
1917  Ecuador       ECU  2048         279362.161022   267.669314
1918  Ecuador       ECU  2049         286499.800868   275.913890
1919  Ecuador       ECU  2050         293637.440714   284.158465