In [12]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

#var_name=os.path.basename(parentdir)

#var_name

In [13]:
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [14]:
df_WEBH2021=pd.read_excel('../row_data/WorldEnergyBalancesHighlights2021.xlsx',sheet_name=3)

In [15]:
df_WEBH2021.columns = df_WEBH2021.iloc[0]
df_WEBH2021.replace(to_replace='..', value=0,inplace=True)
df_WEBH2021

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
0,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1.971000e+03,1.972000e+03,1.973000e+03,1.974000e+03,...,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2017,2018,2019,2020 Provisional
1,Australia,"Coal, peat and oil shale",Production (PJ),01. Australia,"01. Coal, peat and oil shale",01. Production (PJ),1.368252e+03,1.648414e+03,1.685224e+03,1.640362e+03,...,9.782067e+03,1.027236e+04,1.107478e+04,1.195079e+04,1.250100e+04,1.222355e+04,12264.16248,12034.6322,12596.41582,12331.64135
2,Australia,"Coal, peat and oil shale",Imports (PJ),01. Australia,"01. Coal, peat and oil shale",02. Imports (PJ),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.755636e+00,3.635428e+00,2.577490e+00,5.287409e+00,6.978797e+00,6.829994e+00,7.916741,12.735731,17.037944,19.629498
3,Australia,"Coal, peat and oil shale",Exports (PJ),01. Australia,"01. Coal, peat and oil shale",03. Exports (PJ),-5.414240e+02,-6.147180e+02,-7.389394e+02,-7.453829e+02,...,-7.720392e+03,-8.171019e+03,-9.101059e+03,-1.016689e+04,-1.063445e+04,-1.055251e+04,-10248.0298,-10333.3662,-10629.0366,-10541.275
4,Australia,"Coal, peat and oil shale",Total energy supply (PJ),01. Australia,"01. Coal, peat and oil shale",04. Total energy supply (PJ),8.842975e+02,9.232502e+02,9.455419e+02,9.283231e+02,...,2.013814e+03,1.968849e+03,1.831204e+03,1.736614e+03,1.797036e+03,1.863051e+03,1872.030679,1797.650326,1744.105366,1648.774748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6156,IEA and Accession/Association countries,Total,Electricity output (GWh),54. IEA and Accession/Association countries,11. Total,13. Electricity output (GWh),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.788729e+07,1.825346e+07,1.883300e+07,1.928119e+07,1.943470e+07,1.995069e+07,20589646.76,21366327.3,21641349.85,21619592.25
6157,World,Fossil fuels,Electricity output (GWh),55. World,09. Fossil fuels,13. Electricity output (GWh),3.905413e+06,4.241816e+06,4.606277e+06,4.552613e+06,...,1.512668e+07,1.545191e+07,1.578194e+07,1.604617e+07,1.609427e+07,1.633914e+07,16687929.51,17081705.24,17007627.45,0
6158,World,Nuclear,Electricity output (GWh),55. World,05. Nuclear,13. Electricity output (GWh),1.110870e+05,1.524750e+05,2.031960e+05,2.727110e+05,...,2.582639e+06,2.460286e+06,2.479105e+06,2.535405e+06,2.570071e+06,2.608402e+06,2636117.238,2709100.699,2789694.402,2678855.226
6159,World,Renewable sources,Electricity output (GWh),55. World,10. Renewable sources,13. Electricity output (GWh),1.240596e+06,1.304209e+06,1.321598e+06,1.460175e+06,...,4.410657e+06,4.729751e+06,5.060522e+06,5.302669e+06,5.511269e+06,5.891551e+06,6250190.754,6679673.151,7014495.554,0
6160,World,Total,Electricity output (GWh),55. World,11. Total,13. Electricity output (GWh),5.257164e+06,5.698587e+06,6.131143e+06,6.287520e+06,...,2.221337e+07,2.273654e+07,2.342006e+07,2.398489e+07,2.427486e+07,2.494774e+07,25688502.59,26595243.41,26935958.13,0

In [16]:
np.unique(df_WEBH2021['Flow'].values)

array(['Commercial and public services (PJ)', 'Electricity output (GWh)',
       'Electricity, CHP and heat plants (PJ)', 'Exports (PJ)', 'Flow',
       'Imports (PJ)', 'Industry (PJ)',
       'Oil refineries, transformation (PJ)',
       'Other final consumption (PJ)', 'Production (PJ)',
       'Residential (PJ)', 'Total energy supply (PJ)',
       'Total final consumption (PJ)', 'Transport (PJ)'], dtype=object)

In [17]:
df_sector=df_WEBH2021[df_WEBH2021['Flow']=='Other final consumption (PJ)']
df_sector

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
12,Australia,"Coal, peat and oil shale",Other final consumption (PJ),01. Australia,"01. Coal, peat and oil shale",12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
24,Australia,"Crude, NGL and feedstocks",Other final consumption (PJ),01. Australia,"02. Crude, NGL and feedstocks",12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
36,Australia,Oil products,Other final consumption (PJ),01. Australia,03. Oil products,12. Other final consumption (PJ),177.023502,170.663305,206.726302,121.889701,...,266.736460,291.274470,280.087462,284.649244,258.598418,273.347870,273.448571,275.128884,262.445811,0
48,Australia,Natural gas,Other final consumption (PJ),01. Australia,04. Natural gas,12. Other final consumption (PJ),3.768300,4.521602,7.517701,6.616802,...,29.512799,27.735302,52.295401,59.920200,60.586203,60.453900,54.791998,57.3363,48.526201,0
60,Australia,Nuclear,Other final consumption (PJ),01. Australia,05. Nuclear,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5892,World,Nuclear,Other final consumption (PJ),55. World,05. Nuclear,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
5904,World,Renewables and waste,Other final consumption (PJ),55. World,06. Renewables and waste,12. Other final consumption (PJ),1762.057875,1716.221651,1656.579935,1676.297021,...,580.265950,594.149215,615.737955,626.586892,659.814848,679.729011,706.383971,728.582435,771.709632,0
5916,World,Electricity,Other final consumption (PJ),55. World,07. Electricity,12. Other final consumption (PJ),929.558415,1007.418982,1063.489868,1102.449637,...,3874.982778,4093.671216,4362.007611,4651.553385,4952.388145,5476.439602,5896.659096,6567.539335,6985.452916,0
5928,World,Heat,Other final consumption (PJ),55. World,08. Heat,12. Other final consumption (PJ),481.125004,495.722010,518.410983,576.368989,...,493.326277,486.975739,358.361861,411.921387,410.087531,455.276857,462.159633,459.303938,421.397112,0
5940,World,Total,Other final consumption (PJ),55. World,11. Total,12. Other final consumption (PJ),21405.837740,22787.190230,24504.908300,24653.156580,...,44805.682520,46416.030240,46666.992850,48526.403780,49154.602010,50401.443540,52207.03874,53455.23678,54583.09472,0

In [18]:
df_total=df_sector[df_sector['Product']=='Total']
df_total

,Country,Product,Flow,NoCountry,NoProduct,NoFlow,1971,1972,1973,1974,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020 Provisional
108,Australia,Total,Other final consumption (PJ),01. Australia,11. Total,12. Other final consumption (PJ),183.815806,178.334900,217.822402,132.041699,...,306.725257,331.202977,340.389264,353.429044,328.375417,340.123365,335.339778,340.100785,318.798414,0
216,Austria,Total,Other final consumption (PJ),02. Austria,11. Total,12. Other final consumption (PJ),47.241661,50.719046,54.732751,54.504692,...,88.653455,96.190143,96.084703,97.589217,94.644603,97.665295,90.687516,96.837741,107.156963,0
324,Belgium,Total,Other final consumption (PJ),03. Belgium,11. Total,12. Other final consumption (PJ),130.181642,135.122652,151.353201,149.025901,...,321.992310,326.620813,350.576276,367.736927,353.579530,353.029536,349.236019,362.559212,342.685824,0
432,Canada,Total,Other final consumption (PJ),04. Canada,11. Total,12. Other final consumption (PJ),308.427003,331.201001,410.263900,439.897702,...,1255.557614,1313.102701,1223.903517,1185.333610,1243.929421,1283.842533,1194.643086,1206.158808,1114.874962,0
540,Chile,Total,Other final consumption (PJ),05. Chile,11. Total,12. Other final consumption (PJ),7.817015,6.815918,6.197678,6.075373,...,45.793707,43.531491,36.673391,38.276513,20.226142,36.541951,51.711975,64.413487,67.009001,0
648,Colombia,Total,Other final consumption (PJ),06. Colombia,11. Total,12. Other final consumption (PJ),37.226802,51.854138,42.989150,42.014417,...,109.832320,113.266271,165.193648,174.420945,167.561397,206.025428,147.994182,126.881623,165.876917,0
756,Czech Republic,Total,Other final consumption (PJ),07. Czech Republic,11. Total,12. Other final consumption (PJ),153.630276,159.886536,162.944650,164.108815,...,136.229684,141.210883,138.473934,149.116009,130.903517,102.664029,151.178992,149.800844,151.548888,0
864,Denmark,Total,Other final consumption (PJ),08. Denmark,11. Total,12. Other final consumption (PJ),88.196994,93.532199,84.040602,75.567193,...,47.258836,44.421257,44.834122,41.782690,42.355913,42.038306,40.537862,39.84699,37.61455,0
972,Estonia,Total,Other final consumption (PJ),09. Estonia,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,7.484299,8.420199,11.722797,10.013921,9.682134,9.715139,10.577657,10.325997,10.310347,0
1080,Finland,Total,Other final consumption (PJ),10. Finland,11. Total,12. Other final consumption (PJ),232.369008,232.847304,237.241099,243.172095,...,86.180664,86.585369,103.837434,108.104034,99.195742,105.690859,101.62775,97.819549,98.125433,0
1188,France,Total,Other final consumption (PJ),11. France,11. Total,12. Other final consumption (PJ),589.685605,654.733496,745.470199,702.472893,...,820.836572,804.092650,798.723100,822.122196,801.010035,764.100500,792.431227,763.097577,772.090233,0
1296,Germany,Total,Other final consumption (PJ),12. Germany,11. Total,12. Other final consumption (PJ),981.598019,1124.393589,1219.699497,1268.565361,...,998.800010,975.058870,968.914628,994.933810,956.225479,967.573667,1025.013841,1071.180437,1069.339451,0
1404,Greece,Total,Other final consumption (PJ),13. Greece,11. Total,12. Other final consumption (PJ),44.549093,53.319660,58.177022,51.116135,...,68.814710,61.986344,51.600221,51.354858,51.223899,46.705713,58.898868,59.227444,60.302773,0
1512,Hungary,Total,Other final consumption (PJ),14. Hungary,11. Total,12. Other final consumption (PJ),114.822232,119.633916,134.171277,139.975970,...,92.459520,87.357239,87.029542,103.692014,107.411894,108.725439,121.105773,124.242055,121.21942,0
1620,Iceland,Total,Other final consumption (PJ),15. Iceland,11. Total,12. Other final consumption (PJ),5.353603,5.954199,6.723009,7.304601,...,11.884010,11.715006,13.077487,13.046642,13.604517,16.572334,16.815298,18.853412,17.0115,0
1728,Ireland,Total,Other final consumption (PJ),16. Ireland,11. Total,12. Other final consumption (PJ),9.680401,8.434397,9.638596,9.554399,...,24.808109,23.397928,22.935445,18.436436,18.396175,20.860522,20.224668,20.477513,20.499502,0
1836,Israel,Total,Other final consumption (PJ),17. Israel,11. Total,12. Other final consumption (PJ),48.532393,49.872500,45.071601,47.371800,...,108.194243,99.146468,106.937207,104.501046,111.151292,111.549226,119.645334,120.080949,120.795573,0
1944,Italy,Total,Other final consumption (PJ),18. Italy,11. Total,12. Other final consumption (PJ),386.159157,400.510456,427.197902,415.928904,...,513.249873,454.815651,387.743404,421.809495,401.928249,388.009496,455.209474,429.14718,418.591998,0
2052,Japan,Total,Other final consumption (PJ),19. Japan,11. Total,12. Other final consumption (PJ),1632.951085,1802.893301,1976.868306,1877.404399,...,1618.224112,1649.493529,1671.653253,1597.154899,1714.765607,1670.252651,1713.524774,1577.95503,1565.937591,0
2160,Korea,Total,Other final consumption (PJ),20. Korea,11. Total,12. Other final consumption (PJ),32.960801,35.854600,62.250795,68.567500,...,1847.011111,1991.374508,2013.168707,2093.242597,2148.129310,2246.757493,2364.866167,2292.846947,2369.262487,0
2268,Latvia,Total,Other final consumption (PJ),21. Latvia,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,10.334919,10.258740,10.849962,10.237161,11.322309,11.403097,11.851424,12.366677,12.795413,0
2376,Lithuania,Total,Other final consumption (PJ),22. Lithuania,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,53.029121,53.276121,44.427341,47.073561,51.355858,48.409276,55.416983,51.874063,55.03361,0
2484,Luxembourg,Total,Other final consumption (PJ),23. Luxembourg,11. Total,12. Other final consumption (PJ),3.110998,2.962797,3.123395,3.451003,...,2.546655,2.728387,2.645375,2.523606,2.411848,2.693938,2.453369,2.630571,2.54521,0
2592,Mexico,Total,Other final consumption (PJ),24. Mexico,11. Total,12. Other final consumption (PJ),141.088897,154.577996,164.247105,170.685093,...,496.327221,448.197907,458.054145,501.621211,485.494905,503.509990,500.30893,454.453359,422.237398,0
2700,Netherlands,Total,Other final consumption (PJ),25. Netherlands,11. Total,12. Other final consumption (PJ),333.215057,450.947609,528.896601,547.943611,...,722.434329,740.311500,701.181307,678.988768,672.616692,697.363004,730.387695,707.908381,677.496873,0
2808,New Zealand,Total,Other final consumption (PJ),26. New Zealand,11. Total,12. Other final consumption (PJ),22.109289,20.435612,23.080233,21.756128,...,70.215776,77.627216,83.970708,105.536408,95.472007,101.292374,93.547644,84.688049,94.85393,0
2916,Norway,Total,Other final consumption (PJ),27. Norway,11. Total,12. Other final consumption (PJ),103.381395,107.836602,116.041994,99.212799,...,131.740601,134.373399,132.014401,131.214994,123.358506,117.887104,125.914397,127.292545,126.876352,0
3024,Poland,Total,Other final consumption (PJ),28. Poland,11. Total,12. Other final consumption (PJ),209.918612,222.098331,251.971961,267.180923,...,367.314441,361.278390,361.594590,363.806974,381.528773,387.191173,415.703047,401.803382,395.035591,0
3132,Portugal,Total,Other final consumption (PJ),29. Portugal,11. Total,12. Other final consumption (PJ),28.382501,31.373999,31.642796,31.887699,...,92.275787,73.216493,75.618394,79.010903,75.548784,67.616079,70.443354,50.611709,69.247256,0
3240,Slovak Republic,Total,Other final consumption (PJ),30. Slovak Republic,11. Total,12. Other final consumption (PJ),88.603172,93.464394,95.093193,95.198403,...,58.687481,46.808972,49.843825,44.278274,49.674460,47.109472,51.596829,57.740506,46.98993,0
3348,Slovenia,Total,Other final consumption (PJ),31. Slovenia,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,8.649866,9.005300,8.503952,10.088559,9.310263,9.252748,9.745422,10.725711,11.336125,0
3456,Spain,Total,Other final consumption (PJ),32. Spain,11. Total,12. Other final consumption (PJ),187.218205,199.138397,229.620600,212.091205,...,426.809242,394.765911,364.184486,325.578472,304.044487,326.775662,327.257349,344.576927,355.043994,0
3564,Sweden,Total,Other final consumption (PJ),33. Sweden,11. Total,12. Other final consumption (PJ),186.277820,194.541521,191.000124,217.579045,...,108.931484,103.485575,116.364030,111.239370,101.775447,119.511276,131.924653,118.222768,124.127123,0
3672,Switzerland,Total,Other final consumption (PJ),34. Switzerland,11. Total,12. Other final consumption (PJ),266.616810,268.372205,299.352197,263.002597,...,35.691507,33.253672,33.775506,31.078323,31.869185,31.082217,32.546165,32.07322,29.908502,0
3780,Turkey,Total,Other final consumption (PJ),35. Turkey,11. Total,12. Other final consumption (PJ),46.947204,51.123399,57.762600,59.994399,...,485.026897,488.090198,473.749755,417.146698,449.492311,489.614193,381.046722,383.956942,414.964542,0
3888,United Kingdom,Total,Other final consumption (PJ),36. United Kingdom,11. Total,12. Other final consumption (PJ),657.583363,620.638621,672.756364,684.115864,...,401.831312,369.816146,374.974162,368.751648,389.372337,440.496381,449.664686,428.208931,407.099906,0
3996,United States,Total,Other final consumption (PJ),37. United States,11. Total,12. Other final consumption (PJ),4536.254264,4729.077882,5069.474256,4992.457366,...,6783.928285,7077.227233,6872.228953,7316.106605,7096.034485,7267.256388,7655.850123,7993.1808,8201.016223,0
4104,OECD Total,Total,Other final consumption (PJ),38. OECD Total,11. Total,12. Other final consumption (PJ),11845.906180,12642.503170,13786.917060,13561.225980,...,18765.765340,19086.711460,18797.452970,19290.378440,19144.982930,19586.907860,20206.92903,20234.16812,20395.65981,0
4212,Brazil,Total,Other final consumption (PJ),39. Brazil,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,1116.673427,1133.587316,1122.812013,1139.753196,1125.751092,1102.381174,1158.562943,1122.509571,1143.882938,1079.410752
4320,People's Republic of China,Total,Other final consumption (PJ),40. People's Republic of China,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,8696.636456,9066.235257,9796.948924,10766.175210,11128.413990,11546.797940,11806.82026,12115.40565,12842.13338,0
4428,India,Total,Other final consumption (PJ),41. India,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,2928.906382,3247.973589,3245.996284,3354.837036,3640.258507,3749.747212,3855.636345,4086.514329,4170.072323,0
4536,Indonesia,Total,Other final consumption (PJ),42. Indonesia,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,497.950757,598.181815,504.640631,464.687142,399.698707,411.394039,391.786701,402.752425,411.376157,0
4644,Morocco,Total,Other final consumption (PJ),43. Morocco,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,62.651903,58.063803,62.390798,61.962099,69.436998,71.066199,71.741274,69.95066,75.600868,0
4752,Singapore,Total,Other final consumption (PJ),44. Singapore,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,256.756900,244.190203,263.450597,280.194301,304.332099,275.310101,279.787503,284.111241,290.713627,0
4860,South Africa,Total,Other final consumption (PJ),45. South Africa,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,317.643929,308.934874,299.199752,319.631562,303.249777,298.741996,355.138238,347.315785,339.594563,0
4968,Thailand,Total,Other final consumption (PJ),46. Thailand,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,951.091483,977.453803,1143.479012,1153.416529,1135.517272,1109.683251,1095.66996,1178.710344,1141.094885,0
5076,Non-OECD Total,Total,Other final consumption (PJ),47. Non-OECD Total,11. Total,12. Other final consumption (PJ),9559.931564,10144.687050,10717.991250,11091.930600,...,26039.917180,27329.318780,27869.539880,29236.025340,30009.619080,30814.535690,32000.1097,33221.06866,34187.43491,0
5184,Africa,Total,Other final consumption (PJ),48. Africa,11. Total,12. Other final consumption (PJ),320.465472,329.923985,347.014322,357.732681,...,1375.865906,1467.492450,1379.729406,1413.490999,1445.267739,1490.179999,1549.894619,1613.372482,1618.389855,0
5292,Non-OECD Americas,Total,Other final consumption (PJ),49. Non-OECD Americas,11. Total,12. Other final consumption (PJ),597.717876,647.498455,671.232386,709.415830,...,2218.704531,2271.951014,2245.937940,2240.229221,2212.447073,2147.498237,2189.300484,2073.530762,2129.549895,0
5400,Non-OECD Asia (including China),Total,Other final consumption (PJ),50. Non-OECD Asia (including China),11. Total,12. Other final consumption (PJ),1598.705146,1699.112443,1846.780314,1884.654433,...,15203.566780,16100.922140,17081.736370,18110.534480,18656.698840,19417.328260,19892.77932,20587.98817,21334.71286,0
5508,Non-OECD Europe and Eurasia,Total,Other final consumption (PJ),51. Non-OECD Europe and Eurasia,11. Total,12. Other final consumption (PJ),6828.346009,7233.825062,7585.002424,7850.650857,...,4195.389434,4223.002405,3976.221059,4053.491241,4039.204988,4099.249105,4425.975932,4896.625286,4960.196364,0
5616,Middle East,Total,Other final consumption (PJ),52. Middle East,11. Total,12. Other final consumption (PJ),214.697061,234.327107,267.961798,289.476801,...,3046.390532,3265.950774,3185.915106,3418.279399,3656.000435,3660.280082,3942.159352,4049.551952,4144.585932,0
5724,IEA Total,Total,Other final consumption (PJ),53. IEA Total,11. Total,12. Other final consumption (PJ),11746.976370,12528.006420,13685.935620,13458.459790,...,18418.047150,18746.512060,18411.789980,18892.734010,18760.451150,19147.153790,19793.74842,19828.9722,19945.80167,0
5832,IEA and Accession/Association countries,Total,Other final consumption (PJ),54. IEA and Accession/Association countries,11. Total,12. Other final consumption (PJ),0.000000,0.000000,0.000000,0.000000,...,33563.207780,34690.353070,35203.939580,36797.663150,37217.404280,38114.801590,39183.66012,39799.49232,40768.98551,0
5940,World,Total,Other final consumption (PJ),55. World,11. Total,12. Other final consumption (PJ),21405.837740,22787.190230,24504.908300,24653.156580,...,44805.682520,46416.030240,46666.992850,48526.403780,49154.602010,50401.443540,52207.03874,53455.23678,54583.09472,0

In [19]:
df_prop=pd.read_excel('../row_data/frac_scoe_heat_energy_proportion.xlsx')
df_prop

,WEBH2021_var,SISEPUEDE_var,Proportion
0,"Coal, peat and oil shale",frac_scoe_heat_energy_other_se_coal,0.90
1,"Coal, peat and oil shale",frac_scoe_heat_energy_other_se_solid_biomass,0.10
2,Oil products,frac_scoe_heat_energy_other_se_diesel,0.25
3,Oil products,frac_scoe_heat_energy_other_se_gasoline,0.40
4,Oil products,frac_scoe_heat_energy_other_se_kerosene,0.10
5,Oil products,frac_scoe_heat_energy_other_se_hydrocarbon_gas...,0.25
6,Electricity,frac_scoe_heat_energy_other_se_electricity,1.00
7,Renewables and waste,frac_scoe_heat_energy_other_se_electricity,1.00
8,Nuclear,frac_scoe_heat_energy_other_se_electricity,1.00
9,Natural gas,frac_scoe_heat_energy_other_se_natural_gas,1.00
10,Heat,frac_scoe_heat_energy_other_se_natural_gas,1.00

In [20]:
df_prop_=df_prop[df_prop['SISEPUEDE_var']=='frac_scoe_heat_energy_other_se_natural_gas']
df_prop_

   WEBH2021_var                               SISEPUEDE_var  Proportion
9   Natural gas  frac_scoe_heat_energy_other_se_natural_gas         1.0
10         Heat  frac_scoe_heat_energy_other_se_natural_gas         1.0

In [21]:
sisepuede_vars=[var for var in np.unique(df_prop['SISEPUEDE_var'].values)]
sisepuede_vars.append('frac_scoe_heat_energy_other_se_hydrogen')
sisepuede_vars

['frac_scoe_heat_energy_other_se_coal',
 'frac_scoe_heat_energy_other_se_diesel',
 'frac_scoe_heat_energy_other_se_electricity',
 'frac_scoe_heat_energy_other_se_gasoline',
 'frac_scoe_heat_energy_other_se_hydrocarbon_gas_liquids',
 'frac_scoe_heat_energy_other_se_kerosene',
 'frac_scoe_heat_energy_other_se_natural_gas',
 'frac_scoe_heat_energy_other_se_solid_biomass',
 'frac_scoe_heat_energy_other_se_hydrogen']

In [22]:
#### HISTORICAL ######

nation_in_df=np.unique(df_WEBH2021['Country'].values)

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years=range(2000,2020)

for s_var in sisepuede_vars:
    coun_year=[]
    df_historical_out=0
    for count in zip(countries,ISO3):
        for year in years:
            coun_year.append([count[0],count[1],year])
            
    df_historical_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_historical_out[s_var]=0

    df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    for country in countries:
        for year in years:
        
        
            if country in nation_in_df:

                dato_fuel=[]

                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):

                    Total=df_total.loc[df_total['Country']==country,[year]][year].values[0]

                    df_fuel=df_sector[df_sector['Product']==fuel]

                    f=df_fuel.loc[df_fuel['Country']==country,[year]][year].values[0]

                    try:
                        dato_fuel.append(p*f/Total)
                    except:
                        dato_fuel.append(0)

                    #print(dato_fuel)


                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                            (df_historical_out['Year']== year), s_var]=sum(dato_fuel)
            
            else:
                
                dato_fuel=[]
                
                for fuel,p in zip(df_prop_var['WEBH2021_var'].values,df_prop_var['Proportion'].values):
                    
                    Total=df_total.loc[df_total['Country']=='World',[year]][year].values[0]
                    
                    df_fuel=df_sector[df_sector['Product']==fuel]
                    
                    f=df_fuel.loc[df_fuel['Country']=='World',[year]][year].values[0]
                    
                    dato_fuel.append(p*f/Total)
                    
                df_historical_out.loc[(df_historical_out['Nation'] == country) & 
                                (df_historical_out['Year']== year), s_var] = sum(dato_fuel)
                
    
    df_historical_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')

In [23]:
#### Projected ######

countries=df_countries['Country Name'].values
ISO3=np.unique(df_countries['ISO3'].values)
years2=range(max(years)+1,2051)

for s_var in sisepuede_vars:
    coun_year=[]
    for count in zip(countries,ISO3):
        for year in years2:
            coun_year.append([count[0],count[1],year])
            
    df_projected_out = pd.DataFrame(coun_year, columns=['Nation','iso_code3', 'Year'])
    
    df_projected_out[s_var]=0

    #df_prop_var=df_prop[df_prop['SISEPUEDE_var']==s_var]
    
    df_historical=pd.read_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/historical/{s_var}.csv')
    
    for count,year in zip(df_projected_out['Nation'].values,df_projected_out['Year'].values):
        
        df_dato=df_historical[(df_historical['Nation']==count) & 
                                   (df_historical['Year']==max(years))]
        dato=df_dato[s_var].values[0]
        
        df_projected_out.loc[(df_projected_out['Nation'] == count) & 
                            (df_projected_out['Year']== year), s_var] = dato
    
    
    df_projected_out.to_csv(grandparentdir+f'/{s_var}/input_to_sisepuede/projected/{s_var}.csv')